RustboroCity_Flat1_2F_Text_H0::
	.string "Oh, it's so hard every day…\p"
	.string "What's hard?\n"
	.string "You need to ask?\p"
	.string "It's trying to figure out what to\n"
	.string "make for meals every day.\p"
	.string "It really isn't easy coming up with\n"
	.string "meals every day.$"

RustboroCity_Flat1_2F_Text_H1::
	.string "It's a POKéMON plush DOLL!$"

RustboroCity_Flat1_2F_Text_H2::
	.string "It's a POKéMON plush DOLL!$"

RustboroCity_Flat1_2F_Text_H3::
	.string "It's a POKéMON plush DOLL!$"

RustboroCity_Flat1_2F_Text_H4::
	.string "It's a POKéMON plush DOLL!$"

RustboroCity_Flat1_2F_Text_H5::
	.string "It's a POKéMON plush DOLL!$"

