#!/usr/bin/env python3
"""Import the Hoenn heal locations (where the player wakes up after a whiteout).

Appends Emerald's heal locations to src/data/heal_locations.json (FR/LG
generates the table and the constants from it) and gives every imported
Pokemon Center an OnTransition script that sets the respawn point, the way
FR/LG's own centers do.

The save keeps the respawn as a map and position, not as a table index, so
adding entries is safe for old saves.
"""
import json, os, re

FR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../..'))
EM = '/root/src/pokeemerald'

GEN = ' (generated by tools/hoenn_import/import_heal_locations.py)'
BEGIN, END = '@ BEGIN HOENN HEAL LOCATION' + GEN, '@ END HOENN HEAL LOCATION'


def read(p):
    return open(p).read()


def main():
    em = json.load(open(f'{EM}/src/data/heal_locations.json'))['heal_locations']
    fr_path = f'{FR}/src/data/heal_locations.json'
    fr = json.load(open(fr_path))
    kept = [h for h in fr['heal_locations'] if not h['id'].startswith('HEAL_LOCATION_HOENN_')]

    # only keep the ones whose map we imported
    have_maps = set(re.findall(r'#define (MAP_\w+)\s', read(f'{FR}/include/constants/map_groups.h')))
    # the nurse who heals the player after a whiteout: her map and local id
    def center_of(town_map):
        name = ''.join(w.capitalize() for w in town_map[len('MAP_'):].split('_'))
        d = f'{FR}/data/maps/{name}_PokemonCenter_1F'
        if not os.path.exists(f'{d}/map.json'):
            return None, None
        objs = json.load(open(f'{d}/map.json'))['object_events']
        for i, o in enumerate(objs):
            if o['script'] == 'EventScript_PkmnCenterNurse':
                return town_map + '_POKEMON_CENTER_1F', i + 1
        return None, None

    added, by_map = [], {}
    for h in em:
        if h['map'] not in have_maps:
            continue
        respawn_map, npc = center_of(h['map'])
        if respawn_map is None:              # a house or a map we did not import
            respawn_map, npc = h['map'], 1
        new = {'id': 'HEAL_LOCATION_HOENN_' + h['id'][len('HEAL_LOCATION_'):], 'map': h['map'],
               'x': h['x'], 'y': h['y'], 'respawn_map': respawn_map, 'respawn_npc': npc}
        added.append(new)
        by_map[h['map']] = new['id']
    fr['heal_locations'] = kept + added
    open(fr_path, 'w').write(json.dumps(fr, indent=2) + '\n')

    # every Pokemon Center whose town has a heal location sets the respawn there
    centers = 0
    for d in sorted(os.listdir(f'{FR}/data/maps')):
        p = f'{FR}/data/maps/{d}'
        if not os.path.exists(f'{p}/.hoenn') or not d.endswith('_PokemonCenter_1F'):
            continue
        town = 'MAP_' + re.sub(r'(?<!^)(?=[A-Z])', '_', d[:-len('_PokemonCenter_1F')]).upper()
        town = town.replace('__', '_')
        heal = by_map.get(town)
        if heal is None:
            continue
        s = read(f'{p}/scripts.inc')
        block = (f'{BEGIN}\n{d}_OnTransition::\n\tsetrespawn {heal}\n\tend\n{END}\n')
        if BEGIN in s:
            s = s[:s.index(BEGIN)] + block + s[s.index(END) + len(END) + 1:]
        else:
            s = s.replace(f'{d}_MapScripts::\n\t.byte 0\n',
                          f'{d}_MapScripts::\n'
                          f'\tmap_script MAP_SCRIPT_ON_TRANSITION, {d}_OnTransition\n\t.byte 0\n\n' + block, 1)
        open(f'{p}/scripts.inc', 'w').write(s)
        centers += 1
    print(f'{len(added)} heal locations, {centers} Pokemon Centers set a respawn')


if __name__ == '__main__':
    main()
