#!/usr/bin/env python3
"""Import the Hoenn region map from pokeemerald.

Emerald draws its map with an 8bpp tileset and a byte per tile; FR/LG's region
map is a 4bpp 30x20 tilemap with four palettes. This converts the tiles into
4bpp with as many palettes as the colours need, rebuilds the tilemap, copies
FR/LG's CANCEL button into a corner of the sea, and writes the mapsec layout,
the fly destinations and the "visited" flags that go with them.

Everything it writes is generated, so rerunning replaces the previous import.
"""
import os, re, struct
from PIL import Image

FR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../..'))
EM = '/root/src/pokeemerald'

GEN = ' (generated by tools/hoenn_import/import_region_map.py)'

# Emerald's cursor grid sits at these tiles of its tilemap, and so does ours
MAP_X, MAP_Y = 1, 2
MAP_W, MAP_H = 28, 15
# the CANCEL button goes over the open sea in the south east
CANCEL_TILE_X, CANCEL_TILE_Y = 26, 13


def read(p):
    return open(p).read()


def load_pal(path):
    lines = read(path).split('\n')
    n = int(lines[2])
    return [tuple(int(v) for v in lines[3 + i].split()) for i in range(n)]


def main():
    # --- Emerald's map: an 8bpp tileset and a tilemap of one byte per tile
    tiles_img = Image.open(f'{EM}/graphics/pokenav/region_map/map.png')
    em_pal = [tuple(c) for c in zip(*[iter(tiles_img.getpalette())] * 3)]
    raw = open(f'{EM}/graphics/pokenav/region_map/map.bin', 'rb').read()
    em_map = [[raw[y * 64 + x] for x in range(30)] for y in range(20)]

    px = tiles_img.load()
    def em_tile(n):
        tx, ty = (n % 16) * 8, (n // 16) * 8
        return [[px[tx + x, ty + y] for x in range(8)] for y in range(8)]

    # --- FR/LG's CANCEL button, so the map has something to press
    fr_tiles = Image.open(f'{FR}/graphics/region_map/region_map.png')
    fr_pal = [tuple(c) for c in zip(*[iter(fr_tiles.getpalette())] * 3)]
    fr_px = fr_tiles.load()
    fr_map = struct.unpack('<600H', open(f'{FR}/graphics/region_map/kanto.bin', 'rb').read())
    cancel = []          # 3x3 block of (rgb grid) taken from the Kanto map
    for dy in range(3):
        row = []
        for dx in range(3):
            v = fr_map[(16 + dy) * 30 + 24 + dx]
            n, pal = v & 0x3FF, v >> 12
            tx, ty = (n % 16) * 8, (n // 16) * 8
            row.append([[fr_pal[fr_px[tx + x, ty + y]] for x in range(8)] for y in range(8)])
        cancel.append(row)

    # --- every tile as RGB, then packed into 16 colour palettes
    used = sorted({n for row in em_map for n in row})
    tiles = {n: [[em_pal[c] for c in line] for line in em_tile(n)] for n in used}
    place = {}           # (tile source, palette) -> index in the new tileset
    palettes = []        # list of colour lists, 16 each

    # The region map code writes its own colour into index 0 of the first four
    # palettes and into index 15 of the third, so the map's colours live in
    # 1..14 and those two slots are left alone.
    SLOTS = 14

    def add_tile(grid, key):
        colours = {c for line in grid for c in line}
        for pi, pal in enumerate(palettes):
            if len(set(pal) | colours) <= SLOTS:
                for c in colours:
                    if c not in pal:
                        pal.append(c)
                place[key] = (len(place), pi)
                return place[key]
        if len(palettes) == 5:
            raise SystemExit('the Hoenn map needs more than five palettes')
        palettes.append(sorted(colours))
        place[key] = (len(place), len(palettes) - 1)
        return place[key]

    order = []
    for n in used:
        add_tile(tiles[n], ('em', n))
        order.append(('em', n))
    for dy in range(3):
        for dx in range(3):
            add_tile(cancel[dy][dx], ('cancel', dx, dy))
            order.append(('cancel', dx, dy))

    # --- write the tileset as an indexed PNG, 16 tiles a row
    count = len(order)
    rows = (count + 15) // 16
    out = Image.new('P', (128, rows * 8))
    flat = []
    for pal in palettes:
        flat += [(0, 0, 0)] + pal + [(0, 0, 0)] * (15 - len(pal))
    flat += [(0, 0, 0)] * (256 - len(flat))
    out.putpalette([v for c in flat for v in c])
    op = out.load()
    for i, key in enumerate(order):
        grid = tiles[key[1]] if key[0] == 'em' else cancel[key[2]][key[1]]
        idx, pi = place[key]
        tx, ty = (i % 16) * 8, (i // 16) * 8
        for y in range(8):
            for x in range(8):
                op[tx + x, ty + y] = pi * 16 + 1 + palettes[pi].index(grid[y][x])
    out.save(f'{FR}/graphics/region_map/hoenn.png')
    with open(f'{FR}/graphics/region_map/hoenn.pal', 'w') as fh:
        fh.write('JASC-PAL\n0100\n80\n' + ''.join(f'{r} {g} {b}\n' for r, g, b in flat[:80]))

    # --- the tilemap, with the CANCEL button dropped into the sea
    tilemap = [[0] * 30 for _ in range(20)]
    for y in range(20):
        for x in range(30):
            idx, pi = place[('em', em_map[y][x])]
            tilemap[y][x] = idx | (pi << 12)
    for dy in range(3):
        for dx in range(3):
            idx, pi = place[('cancel', dx, dy)]
            tilemap[CANCEL_TILE_Y + MAP_Y - 1 + dy][CANCEL_TILE_X + MAP_X - 1 + dx] = idx | (pi << 12)
    open(f'{FR}/graphics/region_map/hoenn_tilemap.bin', 'wb').write(
        struct.pack('<600H', *[v for row in tilemap for v in row]))

    # --- the mapsec layout, as FR/LG writes its own
    layout = re.findall(r'\{([^{}]*)\}', read(f'{EM}/src/data/region_map/region_map_layout.h'))
    grid = [[c.strip() for c in r.split(',') if c.strip()] for r in layout if 'MAPSEC' in r]
    assert len(grid) == MAP_H and len(grid[0]) == MAP_W, (len(grid), len(grid[0]))
    body = ['static const u8 sRegionMapSections_Hoenn[LAYER_COUNT][MAP_HEIGHT][HOENN_MAP_WIDTH] = {',
            '    [LAYER_MAP] =', '    {']
    for row in grid:
        body.append('        {' + ', '.join(row) + '},')
    body += ['    },', '    [LAYER_DUNGEON] =', '    {']
    for _ in range(MAP_H):
        body.append('        {' + ', '.join(['MAPSEC_NONE'] * MAP_W) + '},')
    body += ['    }', '};']
    open(f'{FR}/src/data/region_map/region_map_layout_hoenn.h', 'w').write(
        '//' + GEN + '\n\n' + '\n'.join(body) + '\n')

    # --- fly destinations: every town whose Pokemon Center we imported
    heals = {h['map']: h['id'] for h in __import__('json').load(
        open(f'{FR}/src/data/heal_locations.json'))['heal_locations'] if h['id'].startswith('HEAL_LOCATION_HOENN_')}
    mapsec_of = {}
    for d in os.listdir(f'{FR}/data/maps'):
        p = f'{FR}/data/maps/{d}/map.json'
        if os.path.exists(f'{FR}/data/maps/{d}/.hoenn') and os.path.exists(p):
            j = __import__('json').load(open(p))
            mapsec_of.setdefault(j['region_map_section'], []).append((j['id'], d))
    rows_out, flags = [], []
    for town_map, heal in sorted(heals.items(), key=lambda kv: kv[1]):
        sec = None
        for s, maps in mapsec_of.items():
            if any(mid == town_map for mid, _ in maps):
                sec = s
                break
        if sec is None or sec == 'MAPSEC_NONE':
            continue
        flag = f'FLAG_HOENN_WORLD_MAP_{sec[len("MAPSEC_"):]}'
        if any(f[0] == flag for f in flags):
            continue
        flags.append((flag, town_map))
        rows_out.append(f'    [{sec}] = {{MAP({town_map}), {heal}, {flag}}},')
    open(f'{FR}/src/data/region_map/fly_destinations_hoenn.h', 'w').write(
        '//' + GEN + '\n\nstatic const struct HoennFlyDestination sHoennFlyDestinations[KANTO_MAPSEC_START] = {\n'
        + '\n'.join(rows_out) + '\n};\n')

    # --- the "visited" flags, and the town scripts that set them
    # They sit high in the Hoenn flag range so they cannot collide with the item
    # flags import_maps.py hands out from the bottom of it.
    open(f'{FR}/include/constants/flags_hoenn_map.h', 'w').write(
        '#ifndef GUARD_CONSTANTS_FLAGS_HOENN_MAP_H\n#define GUARD_CONSTANTS_FLAGS_HOENN_MAP_H\n\n'
        '//' + GEN + '\n// A town is a fly destination once the player has stood in it.\n\n'
        '#define HOENN_WORLD_MAP_FLAGS_START (HOENN_FLAGS_START + 0x400)\n\n'
        + ''.join(f'#define {f:<44} (HOENN_WORLD_MAP_FLAGS_START + {i})\n' for i, (f, _) in enumerate(flags))
        + '\n#endif  // GUARD_CONSTANTS_FLAGS_HOENN_MAP_H\n')

    towns = 0
    for flag, town_map in flags:
        name = ''.join(w.capitalize() for w in town_map[len('MAP_'):].split('_'))
        p = f'{FR}/data/maps/{name}/scripts.inc'
        if not os.path.exists(p):
            print('  no script file for', town_map)
            continue
        begin, end = '@ BEGIN HOENN WORLD MAP FLAG' + GEN, '@ END HOENN WORLD MAP FLAG'
        block = f'{begin}\n{name}_OnTransition::\n\tsetflag {flag}\n\tend\n{end}\n'
        t = read(p)
        if begin in t:
            t = t[:t.index(begin)] + block + t[t.index(end) + len(end) + 1:]
        elif f'{name}_OnTransition' in t:
            t = t.replace(f'{name}_OnTransition::\n', f'{name}_OnTransition::\n\tsetflag {flag}\n', 1)
        else:
            t = t.replace(f'{name}_MapScripts::\n\t.byte 0\n',
                          f'{name}_MapScripts::\n\tmap_script MAP_SCRIPT_ON_TRANSITION, {name}_OnTransition\n\t.byte 0\n\n' + block, 1)
        open(p, 'w').write(t)
        towns += 1
    print(f'{count} tiles, {len(palettes)} palettes, {len(rows_out)} fly destinations, {towns} towns flag a visit')


if __name__ == '__main__':
    main()
