#!/usr/bin/env python3
"""Import the Hoenn music from pokeemerald.

Copies the songs the imported Hoenn maps ask for, together with everything
they need to play: voicegroups, keysplit tables, direct sound samples and
programmable wave samples. Emerald names its voicegroups (voicegroup_littleroot)
while FR/LG numbers them (voicegroup132), so the two sets never collide.

Everything generated sits between markers, so rerunning replaces the import.
New songs are appended to the song table, which keeps the existing song ids.
"""
import json, glob, os, re, shutil, collections

FR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../..'))
EM = '/root/src/pokeemerald'

GEN = ' (generated by tools/hoenn_import/import_music.py)'
MARKERS = {
    'asm': ('@ BEGIN HOENN MUSIC' + GEN, '@ END HOENN MUSIC'),
    'c': ('// BEGIN HOENN MUSIC' + GEN, '// END HOENN MUSIC'),
    'ld': ('        /* BEGIN HOENN MUSIC' + GEN + ' */', '        /* END HOENN MUSIC */'),
}


def read(p):
    return open(p).read()


def put_block(path, kind, body, before=None):
    begin, end = MARKERS[kind]
    s = read(path)
    block = f'{begin}\n{body}{end}\n'
    if begin in s:
        s = s[:s.index(begin)] + block + s[s.index(end) + len(end) + 1:]
    elif before is None:
        s = s.rstrip('\n') + '\n\n' + block
    else:
        assert before in s, (path, before)
        s = s.replace(before, block + before, 1)
    open(path, 'w').write(s)


def songs_h_without_our_block(path):
    s = read(path)
    begin, end = MARKERS['c']
    if begin in s:
        s = s[:s.index(begin)] + s[s.index(end) + len(end):]
    return s


def wanted_songs():
    """The songs the imported Hoenn maps use that FR/LG does not have."""
    ours = {os.path.basename(os.path.dirname(f)) for f in glob.glob(f'{FR}/data/maps/*/.hoenn')}
    have = set(re.findall(r'#define (MUS_\w+)',
                          songs_h_without_our_block(f'{FR}/include/constants/songs.h')))
    used = collections.Counter()
    for m in ours:
        p = f'{EM}/data/maps/{m}/map.json'
        if os.path.exists(p):
            used[json.load(open(p))['music']] += 1
    return [s for s in used if s not in have and s != 'MUS_NONE']


def main():
    songs = sorted(wanted_songs())
    cfg = {}
    for line in read(f'{EM}/sound/songs/midi/midi.cfg').splitlines():
        if ':' in line:
            name, opts = line.split(':', 1)
            cfg[name.strip()[:-4]] = opts.strip()

    # voicegroup name -> file, and what each file needs
    vg_file, vg_text = {}, {}
    for p in glob.glob(f'{EM}/sound/voicegroups/**/*.inc', recursive=True):
        t = read(p)
        for name in re.findall(r'voice_group (\w+)', t):
            vg_file[name] = os.path.relpath(p, EM)
        vg_text[os.path.relpath(p, EM)] = t

    fr_samples = set(re.findall(r'(DirectSoundWaveData_\w+)::', read(f'{FR}/sound/direct_sound_data.inc')))
    fr_waves = set(re.findall(r'(ProgrammableWaveData_\w+)::', read(f'{FR}/sound/programmable_wave_data.inc')))
    fr_keysplits = set(re.findall(r'(\w+)::', read(f'{FR}/sound/keysplit_tables.inc')))
    em_samples = dict(re.findall(r'(DirectSoundWaveData_\w+)::\s*\n\s*\.incbin "([^"]+)"', read(f'{EM}/sound/direct_sound_data.inc')))
    em_waves = dict(re.findall(r'(ProgrammableWaveData_\w+)::\s*\n\s*\.incbin "([^"]+)"', read(f'{EM}/sound/programmable_wave_data.inc')))
    em_keysplit_src = read(f'{EM}/sound/keysplit_tables.inc')

    need_files, need_samples, need_waves, need_keysplits = [], set(), set(), set()
    seen_vg = set()

    def want_voicegroup(name):
        if name in seen_vg:
            return
        seen_vg.add(name)
        f = vg_file[name]
        if f not in need_files:
            need_files.append(f)
        t = vg_text[f]
        for ref in re.findall(r'voicegroup_(\w+)', t):
            if ref in vg_file:
                want_voicegroup(ref)
        for s in re.findall(r'(DirectSoundWaveData_\w+)', t):
            need_samples.add(s)
        for w in re.findall(r'(ProgrammableWaveData_\w+)', t):
            need_waves.add(w)
        for k in re.findall(r'voice_keysplit \w+, (\w+)', t):
            need_keysplits.add(k)

    song_files = []
    for mus in songs:
        song = 'mus_' + mus[len('MUS_'):].lower()
        if song not in cfg:
            print('  no midi.cfg entry, skipped:', song)
            continue
        vg = re.search(r'-G(\S+)', cfg[song]).group(1)
        name = vg[1:] if vg.startswith('_') else vg
        if name not in vg_file:
            print('  unknown voicegroup, skipped:', song, vg)
            continue
        want_voicegroup(name)
        shutil.copy(f'{EM}/sound/songs/midi/{song}.mid', f'{FR}/sound/songs/midi/{song}.mid')
        song_files.append((mus, song, cfg[song]))

    # assets
    os.makedirs(f'{FR}/sound/voicegroups', exist_ok=True)
    for f in need_files:
        dst = f'{FR}/{f}'
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy(f'{EM}/{f}', dst)

    sample_lines = []
    for s in sorted(need_samples - fr_samples):
        binp = em_samples[s]
        wav = f'{EM}/{binp[:-4]}.wav'
        if not os.path.exists(wav):
            print('  missing sample wav:', wav)
            continue
        os.makedirs(os.path.dirname(f'{FR}/{binp}'), exist_ok=True)
        shutil.copy(wav, f'{FR}/{binp[:-4]}.wav')
        sample_lines.append(f'\t.align 2\n{s}::\n\t.incbin "{binp}"\n')

    wave_lines = []
    for w in sorted(need_waves - fr_waves):
        binp = em_waves[w]
        shutil.copy(f'{EM}/{binp}', f'{FR}/{binp}')
        wave_lines.append(f'\t.align 2\n{w}::\n\t.incbin "{binp}"\n')

    # Emerald's keysplit tables are written with the `keysplit <name>` macro and
    # carry their own symbols (keysplit_piano), so the whole file comes across.
    shutil.copy(f'{EM}/sound/keysplit_tables.inc', f'{FR}/sound/hoenn_keysplit_tables.inc')
    ks_lines = ['\t.include "sound/hoenn_keysplit_tables.inc"\n']

    # song ids: they index the song table, so they continue after FR/LG's own songs
    songs_h = songs_h_without_our_block(f'{FR}/include/constants/songs.h')
    next_id = max(int(n) for _, n in re.findall(r'#define ((?:MUS|SE)_\w+)\s+(\d+)', songs_h)) + 1
    consts, table = [], []
    for mus, song, _ in song_files:
        consts.append(f'#define {mus:<25} {next_id} // Hoenn')
        table.append(f'\tsong {song}, 0, 0')
        next_id += 1

    put_block(f'{FR}/include/constants/songs.h', 'c', '\n'.join(consts) + '\n', before='#define MUS_NONE')
    put_block(f'{FR}/sound/song_table.inc', 'asm', '\n'.join(table) + '\n', before='\ndummy_song_header:')
    # midi.cfg is read line by line by audio_rules.mk, so it takes no comment markers:
    # drop any line for a song we import, then append the current set.
    mine = {song for _, song, _ in song_files}
    lines = [l for l in read(f'{FR}/sound/songs/midi/midi.cfg').splitlines()
             if l.split('.mid:')[0].strip() not in mine]
    lines += [f'{song}.mid:{" " * max(1, 30 - len(song))}{opts}' for _, song, opts in song_files]
    open(f'{FR}/sound/songs/midi/midi.cfg', 'w').write('\n'.join(l for l in lines if l.strip()) + '\n')
    put_block(f'{FR}/sound/voice_groups.inc', 'asm',
              ''.join(f'\t.include "{f}"\n' for f in need_files))
    if sample_lines:
        put_block(f'{FR}/sound/direct_sound_data.inc', 'asm', ''.join(sample_lines))
    if wave_lines:
        put_block(f'{FR}/sound/programmable_wave_data.inc', 'asm', ''.join(wave_lines))
    put_block(f'{FR}/data/sound_data.s', 'asm', ''.join(ks_lines),
              before='\t.include "sound/voice_groups.inc"')
    # the linker script lists every song object, so the new ones go in too
    put_block(f'{FR}/ld_script.ld', 'ld',
              ''.join(f'        sound/songs/midi/{song}.o(.rodata);\n' for _, song, _ in song_files),
              before='        sound/songs/midi/mus_teachy_tv_menu.o(.rodata);')
    print(f'imported {len(song_files)} songs, {len(need_files)} voicegroup files, '
          f'{len(sample_lines)} samples, {len(wave_lines)} waves')


if __name__ == '__main__':
    main()
