#!/usr/bin/env python3
"""Import Hoenn object event sprites from pokeemerald.

Copies the pictures and palettes of the Hoenn-only characters (team members,
gym leaders, Hoenn trainer classes, Hoenn Pokemon and the vehicles) and
generates the tables FR/LG needs for them. Everything it writes sits between
generated markers, so rerunning it replaces the previous import.

Generic townsfolk keep their FR/LG art: the graphics id is a u8 and only a few
dozen slots are free, so only characters that FR/LG has no stand-in for come
across.
"""
import os, re, shutil, sys

FR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../..'))
EM = '/root/src/pokeemerald'

WANT = """
AQUA_MEMBER_M AQUA_MEMBER_F MAGMA_MEMBER_M MAGMA_MEMBER_F ARCHIE MAXIE STEVEN SCOTT WALLY
PROF_BIRCH RIVAL_BRENDAN_NORMAL RIVAL_MAY_NORMAL
ROXANNE BRAWLY WATTSON FLANNERY NORMAN WINONA TATE LIZA JUAN WALLACE SIDNEY PHOEBE GLACIA DRAKE
NINJA_BOY HEX_MANIAC RICH_BOY SCHOOL_KID_M CYCLING_TRIATHLETE_M CYCLING_TRIATHLETE_F
RUNNING_TRIATHLETE_M RUNNING_TRIATHLETE_F DEVON_EMPLOYEE CONTEST_JUDGE
KECLEON WINGULL POOCHYENA ZIGZAGOON_1 ZIGZAGOON_2 AZURILL AZUMARILL SKITTY SUDOWOODO KIRLIA DUSCLOPS
VIGOROTH_CARRYING_BOX VIGOROTH_FACING_AWAY
SS_TIDAL MR_BRINEYS_BOAT CABLE_CAR SUBMARINE_SHADOW MOVING_BOX TRICK_HOUSE_STATUE BIRCHS_BAG
REGIROCK REGICE REGISTEEL
""".split()

# Emerald symbol -> FR/LG symbol for the shared tables
ANIMS = {'sAnimTable_BrendanMayNormal': 'sAnimTable_Standard'}
GEN = ' (generated by tools/hoenn_import/import_objevent_gfx.py)'
BEGIN = '// BEGIN HOENN OBJECT EVENTS' + GEN
END = '// END HOENN OBJECT EVENTS'
BEGIN_DECLS = '// BEGIN HOENN OBJECT EVENT DECLARATIONS' + GEN
END_DECLS = '// END HOENN OBJECT EVENT DECLARATIONS'
BEGIN_PALS = '// BEGIN HOENN OBJECT EVENT PALETTES' + GEN
END_PALS = '// END HOENN OBJECT EVENT PALETTES'
MK_BEGIN = '# BEGIN HOENN OBJECT EVENTS (generated by tools/hoenn_import/import_objevent_gfx.py)'
MK_END = '# END HOENN OBJECT EVENTS'


def snake(name):
    return re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower().replace('__', '_')


def read(p):
    return open(p).read()


def replace_block(path, begin, end, body, before=None):
    """Put body between the markers, adding the block if it isn't there yet."""
    s = read(path)
    block = begin + '\n' + body + end + '\n'
    if begin in s:
        s = s[:s.index(begin)] + block + s[s.index(end) + len(end) + 1:]
    elif before is None:
        s = s.rstrip('\n') + '\n\n' + block
    else:
        assert before in s, (path, before)
        s = s.replace(before, block + before, 1)
    open(path, 'w').write(s)


def main():
    ptr = read(f'{EM}/src/data/object_events/object_event_graphics_info_pointers.h')
    info_of = dict(re.findall(r'\[(OBJ_EVENT_GFX_\w+)\]\s*=\s*&gObjectEventGraphicsInfo_(\w+)', ptr))
    infos = dict(re.findall(r'const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_(\w+) = \{(.*?)\};',
                            read(f'{EM}/src/data/object_events/object_event_graphics_info.h'), re.S))
    pics = dict(re.findall(r'static const struct SpriteFrameImage sPicTable_(\w+)\[\] = \{(.*?)\};',
                           read(f'{EM}/src/data/object_events/object_event_pic_tables.h'), re.S))
    gfx = read(f'{EM}/src/data/object_events/object_event_graphics.h')
    pic_src = {m[0]: (m[1], m[2] or None, m[3] or None) for m in re.findall(
        r'const u32 gObjectEventPic_(\w+)\[\] = INCGFX_U32\("([^"]+)", "\.4bpp"(?:, "-mwidth (\d+) -mheight (\d+)")?\);', gfx)}
    pal_src = dict(re.findall(r'const u16 gObjectEventPal_(\w+)\[\] = INC(?:BIN|GFX)_U16\("([^"]+)"(?:, "\.gbapal")?\);', gfx))
    em_mov = read(f'{EM}/src/event_object_movement.c')
    pal_of_tag = {tag: sym for sym, tag in re.findall(r'\{gObjectEventPal_(\w+),\s*(OBJ_EVENT_PAL_TAG_\w+)\}', em_mov)}

    ev = read(f'{FR}/include/constants/event_objects.h')
    if BEGIN in ev:   # ignore a previous import of ours
        ev_clean = ev[:ev.index(BEGIN)] + ev[ev.index(END) + len(END):]
    else:
        ev_clean = ev
    fr_gfx_consts = set(re.findall(r'#define (OBJ_EVENT_GFX_\w+)', ev_clean))
    fr_mov = read(f'{FR}/src/event_object_movement.c')
    if BEGIN in fr_mov:
        fr_mov_clean = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), '', fr_mov, flags=re.S)
    else:
        fr_mov_clean = fr_mov
    fr_tags = dict(re.findall(r'#define (OBJ_EVENT_PAL_TAG_\w+)\s+(0x[0-9A-Fa-f]+)', fr_mov_clean))
    next_tag = max(int(v, 16) for k, v in fr_tags.items() if k != 'OBJ_EVENT_PAL_TAG_NONE') + 1

    os.makedirs(f'{FR}/graphics/object_events/pics/hoenn', exist_ok=True)
    os.makedirs(f'{FR}/graphics/object_events/palettes/hoenn', exist_ok=True)

    graphics, pic_tables, info_out, rules, pointers, consts, decls = [], [], [], [], [], [], []
    pal_rows, pal_defs, new_pals, done_pics, done_gfx = [], [], {}, set(), set()
    gfx_id = max(int(n) for _, n in re.findall(r'#define (OBJ_EVENT_GFX_\w+)\s+(\d+)\b', ev_clean) if int(n) < 240) + 1
    first_id = gfx_id

    for want in WANT:
        const = 'OBJ_EVENT_GFX_' + want
        assert const not in fr_gfx_consts, f'{const} already exists in FR/LG'
        name = info_of[const]
        body = infos[name]
        pic_name = re.search(r'\.images = sPicTable_(\w+)', body).group(1)
        pic_syms = re.findall(r'(?:overworld_frame|obj_frame_tiles)\(gObjectEventPic_(\w+)[,)]', pics[pic_name])
        for sym in dict.fromkeys(pic_syms):
            png, mw, mh = pic_src[sym]
            if sym in done_gfx:
                continue
            done_gfx.add(sym)
            base = snake(sym)
            dst = f'graphics/object_events/pics/hoenn/{base}.png'
            shutil.copy(f'{EM}/{png}', f'{FR}/{dst}')
            graphics.append(f'const u32 gObjectEventPic_Hoenn{sym}[] = INCBIN_U32("{dst[:-4]}.4bpp");')
            if mw:
                rules.append(f'$(OBJEVENTGFXDIR)/hoenn/{base}.4bpp: %.4bpp: %.png\n\t$(GFX) $< $@ -mwidth {mw} -mheight {mh}')

        tag = re.search(r'\.paletteTag = (\w+)', body).group(1)
        if tag != 'OBJ_EVENT_PAL_TAG_NONE' and tag not in new_pals:
            sym = pal_of_tag[tag]
            src = pal_src[sym]
            dst = f'graphics/object_events/palettes/hoenn/{snake(sym)}.pal'
            shutil.copy(f'{EM}/{src}', f'{FR}/{dst}')
            new_tag = f'OBJ_EVENT_PAL_TAG_HOENN_{tag[len("OBJ_EVENT_PAL_TAG_"):]}'
            new_pals[tag] = new_tag
            graphics.append(f'const u16 gObjectEventPal_Hoenn{sym}[] = INCBIN_U16("{dst[:-4]}.gbapal");')
            pal_defs.append(f'#define {new_tag:<45} 0x{next_tag:04X}')
            pal_rows.append(f'    {{gObjectEventPal_Hoenn{sym}, {new_tag}}},')
            next_tag += 1

        table = pics[pic_name]
        for sym in dict.fromkeys(pic_syms):
            table = table.replace(f'gObjectEventPic_{sym}', f'gObjectEventPic_Hoenn{sym}')
        if pic_name not in done_pics:
            pic_tables.append(f'static const struct SpriteFrameImage sPicTable_Hoenn{pic_name}[] = {{{table}}};')
            done_pics.add(pic_name)

        out = body
        out = out.replace(f'.paletteTag = {tag}', f'.paletteTag = {new_pals.get(tag, tag)}')
        out = re.sub(r'\.reflectionPaletteTag = OBJ_EVENT_PAL_TAG_\w+', '.reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE', out)
        out = out.replace('.subspriteTables = sOamTables_', '.subspriteTables = gObjectEventSpriteOamTables_')
        out = re.sub(r'\.anims = (\w+)', lambda m: '.anims = ' + ANIMS.get(m.group(1), m.group(1)), out)
        out = out.replace(f'.images = sPicTable_{pic_name}', f'.images = sPicTable_Hoenn{pic_name}')
        info_out.append(f'const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_Hoenn{name} = {{{out}}};')

        decls.append(f'const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_Hoenn{name};')
        consts.append(f'#define {const:<43} {gfx_id}')
        pointers.append(f'    [{const}] = &gObjectEventGraphicsInfo_Hoenn{name},')
        gfx_id += 1

    # constants
    replace_block(f'{FR}/include/constants/event_objects.h', BEGIN, END,
                  '\n'.join(consts) + '\n', before='#define NUM_OBJ_EVENT_GFX')
    s = read(f'{FR}/include/constants/event_objects.h')
    s = re.sub(r'#define NUM_OBJ_EVENT_GFX\s+\d+', f'#define NUM_OBJ_EVENT_GFX     {gfx_id}', s)
    open(f'{FR}/include/constants/event_objects.h', 'w').write(s)

    replace_block(f'{FR}/src/data/object_events/object_event_graphics.h', BEGIN, END, '\n'.join(graphics) + '\n', before=None)
    replace_block(f'{FR}/src/data/object_events/object_event_pic_tables.h', BEGIN, END, '\n\n'.join(pic_tables) + '\n', before=None)
    replace_block(f'{FR}/src/data/object_events/object_event_graphics_info.h', BEGIN, END, '\n\n'.join(info_out) + '\n', before=None)
    replace_block(f'{FR}/src/data/object_events/object_event_graphics_info_pointers.h', BEGIN_DECLS, END_DECLS,
                  '\n'.join(decls) + '\n', before='const struct ObjectEventGraphicsInfo *const gObjectEventGraphicsInfoPointers[')
    replace_block(f'{FR}/src/data/object_events/object_event_graphics_info_pointers.h', BEGIN, END,
                  '\n'.join(pointers) + '\n', before='};')
    replace_block(f'{FR}/src/event_object_movement.c', BEGIN, END, '\n'.join(pal_defs) + '\n',
                  before='#define OBJ_EVENT_PAL_TAG_NONE')
    replace_block(f'{FR}/src/event_object_movement.c', BEGIN_PALS, END_PALS, '\n'.join(pal_rows) + '\n',
                  before='    {},\n};')
    replace_block(f'{FR}/spritesheet_rules.mk', MK_BEGIN, MK_END, '\n'.join(rules) + '\n', before=None)
    print(f'imported {len(WANT)} sprites, gfx ids {first_id}..{gfx_id - 1}, {len(new_pals)} palettes')


if __name__ == '__main__':
    main()
