#!/usr/bin/env python3
"""Import the Hoenn tileset animations from pokeemerald.

Copies the animation frames of the imported tilesets (water, flowers, flags,
fountains, the balloons over Slateport...) and generates the callbacks that
drive them. FR/LG keeps the animation framework (the DMA queue, the counters
and AppendTilesetAnimToBuffer) in src/tileset_anims.c, so the generated code
is included at the end of that file and uses those statics.

Run it after import_tilesets.py, which writes the tileset headers this patches.
"""
import os, re, shutil

FR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../..'))
EM = '/root/src/pokeemerald'

GEN = ' (generated by tools/hoenn_import/import_tileset_anims.py)'
BEGIN, END = '// BEGIN HOENN TILESET ANIMS' + GEN, '// END HOENN TILESET ANIMS'
PREFIXES = ('TilesetAnim_', 'QueueAnimTiles_', 'BlendAnimPalette_', 'InitTilesetAnim_')
# The BATTLE DOME's floor lights animate a palette through the battle transition
# task, which FR/LG has no counterpart for; that tileset keeps a still floor.
SKIP = ('BattleDome',)


def read(p):
    return open(p).read()


def put_block(path, body, before=None, comment='//'):
    begin, end = BEGIN.replace('//', comment), END.replace('//', comment)
    s = read(path)
    block = f'{begin}\n{body}{end}\n'
    if begin in s:
        s = s[:s.index(begin)] + block + s[s.index(end) + len(end) + 1:]
    elif before is None:
        s = s.rstrip('\n') + '\n\n' + block
    else:
        s = s.replace(before, block + before, 1)
    open(path, 'w').write(s)


def functions(src):
    """name -> source text, for every top level function in a C file."""
    out = {}
    for m in re.finditer(r'^((?:static\s+)?[A-Za-z_][\w \*]*?\b(\w+)\([^;{]*\)\s*\n?\{)', src, re.M):
        name = m.group(2)
        i = src.index('{', m.start())
        depth, j = 0, i
        while j < len(src):
            if src[j] == '{':
                depth += 1
            elif src[j] == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        out[name] = src[m.start():j + 1]
    return out


def main():
    em_anims = read(f'{EM}/src/tileset_anims.c')
    em_headers = read(f'{EM}/src/data/tilesets/headers.h')
    fr_headers_path = f'{FR}/src/data/tilesets/hoenn_headers.h'
    fr_headers = read(fr_headers_path)

    # which imported tilesets have an animation callback in Emerald
    callback_of = {}
    for name, body in re.findall(r'const struct Tileset gTileset_(\w+) =\s*\{(.*?)\};', em_headers, re.S):
        m = re.search(r'\.callback = (\w+)', body)
        if m and m.group(1) != 'NULL':
            callback_of[name] = m.group(1)
    mine = set(re.findall(r'const struct Tileset gTileset_Em(\w+) =', fr_headers))
    used = {n: c for n, c in callback_of.items() if n in mine and not n.startswith(SKIP)}

    funcs = functions(em_anims)
    wanted, queue = [], [c for c in used.values()]
    while queue:
        fn = queue.pop(0)
        if fn in wanted or fn not in funcs:
            continue
        wanted.append(fn)
        for ref in re.findall(r'\b(\w+)\b', funcs[fn]):
            if ref.startswith(PREFIXES) and ref in funcs:
                queue.append(ref)

    # rename everything so it cannot clash with FR/LG's own animations
    def rename(text):
        text = re.sub(r'\bgTilesetAnims_(\w+)', r'sTilesetAnims_Em\1', text)
        # Emerald tilesets keep Emerald's split: 512 tiles in the primary tileset
        text = text.replace('NUM_TILES_IN_PRIMARY', '512')
        for p in PREFIXES:
            text = re.sub(r'\b' + p + r'(\w+)', p + r'Em\1', text)
        return text

    # frame data the wanted functions use
    body = '\n'.join(funcs[f] for f in wanted)
    frame_tables = [t for t in re.findall(r'\bgTilesetAnims_\w+', body)]
    data_lines, copied, done_frames, done_tables = [], set(), set(), set()
    src_lines = em_anims.splitlines()
    for table in dict.fromkeys(frame_tables):
        if table in done_tables:
            continue
        done_tables.add(table)
        # VRAM destination tables (u16 *const ...[]) come across as they are
        dests = re.search(r'u16 \*const ' + table + r'\[\] = \{(.*?)\};', em_anims, re.S)
        if dests and 'const u16 *const ' + table not in em_anims:
            data_lines.append('static u16 *const ' + table.replace('gTilesetAnims_', 'sTilesetAnims_Em')
                              + '[] = {' + dests.group(1) + '};\n')
            continue
        m = re.search(r'(?:static )?const u16 \*const ' + table + r'\[\] = \{(.*?)\};', em_anims, re.S)
        if not m:
            continue
        frames = re.findall(r'\b(gTilesetAnims_\w+)', m.group(1))
        for fr_sym in dict.fromkeys(frames):
            inc = re.search(r'const u16 ' + fr_sym + r'\[\] = INC(?:GFX|BIN)_U16\(([^;]+)\);', em_anims)
            if not inc:
                print('  no frame data for', fr_sym)
                continue
            # a frame can be several files (Sootopolis' water has a KYOGRE and a GROUDON half)
            paths = [p for p in re.findall(r'"([^"]+)"', inc.group(1)) if not p.startswith('.')]
            dsts = []
            for path in paths:
                dst = re.sub(r'^data/tilesets/(primary|secondary)/([^/]+)/', r'data/tilesets/\1/em_\2/', path)
                if dst.endswith('.4bpp'):
                    src_png, dst = path[:-5] + '.png', dst[:-5] + '.png'
                else:
                    src_png = path
                if dst not in copied:
                    os.makedirs(os.path.dirname(f'{FR}/{dst}'), exist_ok=True)
                    shutil.copy(f'{EM}/{src_png}', f'{FR}/{dst}')
                    copied.add(dst)
                dsts.append(dst[:-4] + '.4bpp')
            args = ', '.join(f'"{d}"' for d in dsts)
            if fr_sym in done_frames:
                continue
            done_frames.add(fr_sym)
            data_lines.append(f'static const u16 {fr_sym.replace("gTilesetAnims_", "sTilesetAnims_Em")}[] = '
                              f'INCBIN_U16({args});')
        data_lines.append(f'\nstatic const u16 *const {table.replace("gTilesetAnims_", "sTilesetAnims_Em")}[] = {{'
                          + ''.join(f'\n    {f.replace("gTilesetAnims_", "sTilesetAnims_Em")},' for f in frames)
                          + '\n};\n')

    decls = '\n'.join(f'static void {rename(f)}(u16);' if 'u16 timer' in funcs[f] or '(u16' in funcs[f].split(')')[0]
                      else f'static void {rename(f)}(void);'
                      for f in wanted if not f.startswith('InitTilesetAnim_'))
    out = ['// Hoenn tileset animations' + GEN, '']
    out.append(rename('\n'.join(data_lines)))
    out.append('')
    for f in wanted:
        text = rename(funcs[f])
        if f.startswith('InitTilesetAnim_'):
            text = text.replace('static void', 'void')
        else:
            text = 'static ' + text if not text.startswith('static') else text
        out.append(text + '\n')
    open(f'{FR}/src/data/tilesets/hoenn_anims.h', 'w').write('\n'.join(out))

    # forward declarations, so the order inside the generated file does not matter
    fwd = []
    for f in wanted:
        sig = funcs[f].split('\n')[0]
        sig = rename(sig[:sig.index('{')].strip() if '{' in sig else sig.strip())
        if f.startswith('InitTilesetAnim_'):
            sig = sig.replace('static void', 'void')
        fwd.append(sig.rstrip() + ';')
    put_block(f'{FR}/src/tileset_anims.c',
              '\n'.join(fwd) + '\n#include "data/tilesets/hoenn_anims.h"\n')

    # declare the init callbacks and hook them up in the tileset headers
    put_block(f'{FR}/include/tileset_anims.h',
              ''.join(f'void InitTilesetAnim_Em{n}(void);\n' for n in sorted(used)),
              before='#endif')
    # start from a clean slate so a rerun can also remove a callback
    fr_headers = re.sub(r'\.callback = InitTilesetAnim_Em\w+', '.callback = NULL', fr_headers)
    for name, cb in used.items():
        fr_headers = re.sub(
            r'(const struct Tileset gTileset_Em' + name + r' =\s*\{.*?)\.callback = NULL',
            lambda m: m.group(1) + '.callback = ' + cb.replace('InitTilesetAnim_', 'InitTilesetAnim_Em'),
            fr_headers, flags=re.S)
    open(fr_headers_path, 'w').write(fr_headers)
    print(f'{len(used)} animated tilesets, {len(wanted)} functions, {len(copied)} frames')


if __name__ == '__main__':
    main()
