#!/usr/bin/env python3
"""Import the Hoenn trainers from pokeemerald.

Brings across the trainers the imported maps battle: their party, class,
battle sprite, name, items and AI. FR/LG already carries the Hoenn trainer
classes and front pics (under RS_ names where they clash), so only the
trainer entries and parties are new.

Their ids start at HOENN_TRAINERS_START, past the save's trainer flag block,
and battle_setup.c keeps their "defeated" bits in unused SaveBlock2 space, so
the save layout is untouched.
"""
import glob, json, os, re

FR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../..'))
EM = '/root/src/pokeemerald'

GEN = ' (generated by tools/hoenn_import/import_trainers.py)'
BEGIN, END = '// BEGIN HOENN TRAINERS' + GEN, '// END HOENN TRAINERS'


# Emerald names that FR/LG spells differently
CLASS_ALIAS = {
    'TRAINER_CLASS_RIVAL': 'TRAINER_CLASS_RIVAL_EARLY',
    'TRAINER_CLASS_COOLTRAINER_2': 'TRAINER_CLASS_COOLTRAINER',
    'TRAINER_CLASS_WINSTRATE': 'TRAINER_CLASS_HOENN_WINSTRATE',   # added below
}
PIC_ALIAS = {
    'TRAINER_PIC_BRENDAN': 'TRAINER_PIC_RS_BRENDAN_1',
    'TRAINER_PIC_MAY': 'TRAINER_PIC_RS_MAY_1',
    'TRAINER_PIC_STEVEN': 'TRAINER_PIC_CHAMPION_STEVEN',
    'TRAINER_PIC_CHAMPION_WALLACE': 'TRAINER_PIC_LEADER_WALLACE',
    'TRAINER_PIC_MAGMA_ADMIN': 'TRAINER_PIC_MAGMA_ADMIN_M',
    'TRAINER_PIC_LEADER_JUAN': 'TRAINER_PIC_HOENN_LEADER_JUAN',   # added below
}
# JUAN is Emerald's own gym leader, so his battle sprite comes across too
NEW_PIC = ('HOENN_LEADER_JUAN', 'graphics/trainers/front_pics/leader_juan.png',
           'graphics/trainers/palettes/leader_juan.gbapal', 'HoennLeaderJuan')
NEW_CLASS = ('HOENN_WINSTRATE', 'WINSTRATE', 15)   # name and money multiplier


def read(p):
    return open(p).read()


def put_block(path, body, before=None):
    s = read(path)
    block = f'{BEGIN}\n{body}{END}\n'
    if BEGIN in s:
        s = s[:s.index(BEGIN)] + block + s[s.index(END) + len(END) + 1:]
    elif before is None:
        s = s.rstrip('\n') + '\n\n' + block
    else:
        assert before in s, (path, before)
        s = s.replace(before, block + before, 1)
    open(path, 'w').write(s)


def imported_maps():
    return {os.path.basename(os.path.dirname(f)) for f in glob.glob(f'{FR}/data/maps/*/.hoenn')}


def trainers_used():
    """Trainers the scripts of the imported maps battle."""
    used = set()
    for m in imported_maps():
        p = f'{EM}/data/maps/{m}/scripts.inc'
        if os.path.exists(p):
            used |= set(re.findall(r'trainerbattle\w*\s+(TRAINER_\w+)', read(p)))
    return used - {'TRAINER_NONE'}


def add_new_graphics():
    """JUAN's battle sprite and the WINSTRATE class, which FR/LG has neither of."""
    import shutil
    from PIL import Image

    pic_const, png, _unused, sym = NEW_PIC
    dst_png = f'graphics/trainers/front_pics/{pic_const.lower()}_front_pic.png'
    shutil.copy(f'{EM}/{png}', f'{FR}/{dst_png}')
    im = Image.open(f'{FR}/{dst_png}')
    pal = im.getpalette()[:48]
    dst_pal = f'graphics/trainers/palettes/{pic_const.lower()}.pal'
    with open(f'{FR}/{dst_pal}', 'w') as fh:
        fh.write('JASC-PAL\n0100\n16\n' + ''.join(f'{pal[i*3]} {pal[i*3+1]} {pal[i*3+2]}\n' for i in range(16)))

    trainers_h = f'{FR}/include/constants/trainers.h'
    t = read(trainers_h)
    if BEGIN in t:      # ignore a previous import of ours
        t = t[:t.index(BEGIN)] + t[t.index(END) + len(END):]
    pic_id = max(int(n) for _, n in re.findall(r'#define (TRAINER_PIC_\w+)\s+(\d+)', t)) + 1
    class_id = max(int(n) for _, n in re.findall(r'#define (TRAINER_CLASS_\w+)\s+(\d+)', t)) + 1
    put_block(trainers_h,
              f'#define TRAINER_PIC_{pic_const:<25} {pic_id}\n'
              f'#define TRAINER_CLASS_{NEW_CLASS[0]:<23} {class_id}\n',
              before='#define F_TRAINER_PARTY_CUSTOM_MOVESET')

    put_block(f'{FR}/src/data/graphics/trainers.h',
              f'const u32 gTrainerFrontPic_{sym}[] = INCBIN_U32("{dst_png[:-4]}.4bpp.lz");\n'
              f'const u32 gTrainerPalette_{sym}[] = INCBIN_U32("{dst_pal[:-4]}.gbapal.lz");\n')

    put_block(f'{FR}/include/graphics.h',
              f'extern const u32 gTrainerFrontPic_{sym}[];\n'
              f'extern const u32 gTrainerPalette_{sym}[];\n',
              before='#endif //GUARD_GRAPHICS_H' if '#endif //GUARD_GRAPHICS_H' in read(f'{FR}/include/graphics.h')
              else '#endif')

    tables = f'{FR}/src/data/trainer_graphics/front_pic_tables.h'
    t = read(tables)
    if BEGIN not in t:
        t = t.replace('    {.size = 8, .y_offset = 1}, // TRAINER_PIC_JESSIE_JAMES\n',
                      '    {.size = 8, .y_offset = 1}, // TRAINER_PIC_JESSIE_JAMES\n'
                      f'    {BEGIN}\n    {{.size = 8, .y_offset = 1}}, // TRAINER_PIC_{pic_const}\n    {END}\n')
        t = t.replace('    TRAINER_SPRITE(JESSIE_JAMES, gTrainerFrontPic_JessieJames, 0x800),\n',
                      '    TRAINER_SPRITE(JESSIE_JAMES, gTrainerFrontPic_JessieJames, 0x800),\n'
                      f'    TRAINER_SPRITE({pic_const}, gTrainerFrontPic_{sym}, 0x800),\n')
        t = t.replace('    TRAINER_PAL(JESSIE_JAMES, gTrainerPalette_JessieJames),\n',
                      '    TRAINER_PAL(JESSIE_JAMES, gTrainerPalette_JessieJames),\n'
                      f'    TRAINER_PAL({pic_const}, gTrainerPalette_{sym}),\n')
        open(tables, 'w').write(t)

    anims = f'{FR}/src/data/trainer_graphics/front_pic_anims.h'
    a = read(anims)
    put_block(anims, f'    [TRAINER_PIC_{pic_const}] = sAnims_LeaderWallace,\n',
              before=a[a.index('gTrainerFrontAnimsPtrTable'):].split('};')[0].splitlines()[-1] + '\n')

    names = f'{FR}/src/data/text/trainer_class_names.h'
    put_block(names, f'    [TRAINER_CLASS_{NEW_CLASS[0]}] = _("{NEW_CLASS[1]}"),\n', before='};')
    money = f'{FR}/src/battle_main.c'
    put_block(money, f'    {{TRAINER_CLASS_{NEW_CLASS[0]}, {NEW_CLASS[2]}}},\n',
              before='    { 0xFF, 5},')


def main():
    add_new_graphics()
    em_trainers = read(f'{EM}/src/data/trainers.h')
    em_parties = read(f'{EM}/src/data/trainer_parties.h')
    entries = dict(re.findall(r'\[(TRAINER_\w+)\] =\s*\n?\s*\{(.*?)\n    \},', em_trainers, re.S))
    parties = dict(re.findall(r'static const struct (\w+) (sParty_\w+)\[\] = \{(.*?)\n\};'.replace('(\\w+) (sParty', '(\\w+)\\s+(sParty'),
                              em_parties, re.S) and
                   [(m[1], (m[0], m[2])) for m in re.findall(
                       r'static const struct (\w+)\s+(sParty_\w+)\[\] = \{(.*?)\n\};', em_parties, re.S)])

    fr_classes = set(re.findall(r'#define (TRAINER_CLASS_\w+)', read(f'{FR}/include/constants/trainers.h')))
    fr_pics = set(re.findall(r'#define (TRAINER_PIC_\w+)', read(f'{FR}/include/constants/trainers.h')))
    fr_music = set(re.findall(r'#define (TRAINER_ENCOUNTER_MUSIC_\w+)', read(f'{FR}/include/constants/trainers.h')))

    def map_const(name, have, prefix):
        """Emerald's name, FR/LG's RS_ variant of it, or an explicit alias."""
        alias = (CLASS_ALIAS if prefix == 'TRAINER_CLASS_' else PIC_ALIAS).get(name)
        if alias:
            return alias
        if name in have:
            return name
        rs = name.replace(prefix, prefix + 'RS_')
        if rs in have:
            return rs
        return None

    wanted = sorted(t for t in trainers_used() if t in entries)
    out_parties, out_entries, consts, skipped = [], [], [], []
    next_id = 0
    for t in wanted:
        body = entries[t]
        cls = re.search(r'\.trainerClass = (\w+)', body)
        pic = re.search(r'\.trainerPic = (\w+)', body)
        mus = re.search(r'\.encounterMusic_gender = ([^,\n]+)', body)
        party = re.search(r'\.party = (\w+)\((sParty_\w+)\)', body)
        if not (cls and pic and party) or party.group(2) not in parties:
            skipped.append(t)
            continue
        new_cls = map_const(cls.group(1), fr_classes, 'TRAINER_CLASS_')
        new_pic = map_const(pic.group(1), fr_pics, 'TRAINER_PIC_')
        if new_cls is None or new_pic is None:
            skipped.append(t)
            continue
        music = mus.group(1).strip() if mus else 'TRAINER_ENCOUNTER_MUSIC_MALE'
        for name in re.findall(r'TRAINER_ENCOUNTER_MUSIC_\w+', music):
            if name not in fr_music:
                music = music.replace(name, 'TRAINER_ENCOUNTER_MUSIC_MALE')

        struct_name, party_body = parties[party.group(2)]
        new_party = 'sHoennParty_' + party.group(2)[len('sParty_'):]
        if f'static const struct {struct_name} {new_party}[]' not in ''.join(out_parties):
            out_parties.append(f'static const struct {struct_name} {new_party}[] = {{{party_body}\n}};\n')

        new_t = 'TRAINER_HOENN_' + t[len('TRAINER_'):]
        consts.append(f'#define {new_t:<45} (HOENN_TRAINERS_START + {next_id})')
        next_id += 1
        new_body = body
        new_body = new_body.replace(f'.trainerClass = {cls.group(1)}', f'.trainerClass = {new_cls}')
        new_body = new_body.replace(f'.trainerPic = {pic.group(1)}', f'.trainerPic = {new_pic}')
        if mus:
            new_body = new_body.replace(mus.group(0), f'.encounterMusic_gender = {music}')
        new_body = new_body.replace(f'{party.group(1)}({party.group(2)})', f'{party.group(1)}({new_party})')
        out_entries.append(f'    [{new_t}] =\n    {{{new_body}\n    }},\n')

    # gSaveBlock2Ptr->hoennTrainerFlags is 0x80 bytes, one bit per trainer
    assert next_id <= 0x80 * 8, f'{next_id} Hoenn trainers do not fit in the flag space'
    open(f'{FR}/src/data/trainer_parties_hoenn.h', 'w').write(
        '// Trainer parties imported from pokeemerald (Hoenn)' + GEN + '\n\n' + '\n'.join(out_parties))
    open(f'{FR}/src/data/trainers_hoenn.h', 'w').write(
        '// Trainers imported from pokeemerald (Hoenn)' + GEN + '\n\n' + ''.join(out_entries))
    put_block(f'{FR}/include/constants/opponents.h', '\n'.join(consts) + '\n', before='#endif  // GUARD_CONSTANTS_OPPONENTS_H')
    # both includers sit in src/data, so the paths are relative to that directory
    put_block(f'{FR}/src/data/trainer_parties.h', '#include "trainer_parties_hoenn.h"\n')
    put_block(f'{FR}/src/data/trainers.h', '#include "trainers_hoenn.h"\n', before='};')
    print(f'imported {next_id} trainers, {len(out_parties)} parties'
          + (f', skipped {len(skipped)}: {skipped[:6]}' if skipped else ''))


if __name__ == '__main__':
    main()
