Route110_TrickHousePuzzle3_Text_H0_0::
	.string "I keep coming back to this same\n"
	.string "place!$"

Route110_TrickHousePuzzle3_Text_H0_1::
	.string "I'm already having trouble, and then\n"
	.string "you have to beat me? It's not fair!$"

Route110_TrickHousePuzzle3_Text_H0_2::
	.string "It's full of doors here! It's too\n"
	.string "small and dark in here! Help!$"

Route110_TrickHousePuzzle3_Text_H1_0::
	.string "I don't know what's going on here.\n"
	.string "I'm starting to feel sad…$"

Route110_TrickHousePuzzle3_Text_H1_1::
	.string "You… You're awful!$"

Route110_TrickHousePuzzle3_Text_H1_2::
	.string "I know I'm weak!\n"
	.string "And, I have no sense of direction!$"

Route110_TrickHousePuzzle3_Text_H2_0::
	.string "I don't get it. What would anyone\n"
	.string "want with a house this bizarre?$"

Route110_TrickHousePuzzle3_Text_H2_1::
	.string "I don't get it.\n"
	.string "How did I lose?$"

Route110_TrickHousePuzzle3_Text_H2_2::
	.string "I don't get it.\n"
	.string "How many traps are in this house?\p"
	.string "You may be the one to solve that.$"

