Route110_TrickHousePuzzle7_Text_H0_0::
	.string "The TRICK MASTER always vanishes\n"
	.string "like smoke. How does he do it?$"

Route110_TrickHousePuzzle7_Text_H0_1::
	.string "Aiyeeeh! You're much too strong!\n"
	.string "How do you do it?$"

Route110_TrickHousePuzzle7_Text_H0_2::
	.string "I wish I could appear and disappear as\n"
	.string "if I were smoke, too.$"

Route110_TrickHousePuzzle7_Text_H1_0::
	.string "Whoever wins will get through here\n"
	.string "first. That's the feeling I get.$"

Route110_TrickHousePuzzle7_Text_H1_1::
	.string "Oh!\n"
	.string "Well, go ahead, then!$"

Route110_TrickHousePuzzle7_Text_H1_2::
	.string "You're solving all the puzzles in the\n"
	.string "TRICK HOUSE. That's the feeling I get.$"

Route110_TrickHousePuzzle7_Text_H2_0::
	.string "Going around the same spot…\n"
	.string "It begets ill fortune…$"

Route110_TrickHousePuzzle7_Text_H2_1::
	.string "Defeated!\n"
	.string "It's a bad sign…$"

Route110_TrickHousePuzzle7_Text_H2_2::
	.string "I've circled the same spot over ten\n"
	.string "times now… It's ill fortune…$"

Route110_TrickHousePuzzle7_Text_H3_0::
	.string "I ever so closely watched you coming!$"

Route110_TrickHousePuzzle7_Text_H3_1::
	.string "This outcome I didn't see coming…$"

Route110_TrickHousePuzzle7_Text_H3_2::
	.string "Well, anyway, we both picked a weird\n"
	.string "place to get acquainted.\p"
	.string "As one weirdo to another,\n"
	.string "let's do our best!$"

Route110_TrickHousePuzzle7_Text_H4_0::
	.string "Nufufufu, here at last!\n"
	.string "Let's get right with it!$"

Route110_TrickHousePuzzle7_Text_H4_1::
	.string "You're so casual about winning!$"

Route110_TrickHousePuzzle7_Text_H4_2::
	.string "Humph! I'm not upset!\n"
	.string "Not me!$"

Route110_TrickHousePuzzle7_Text_H5_0::
	.string "It's awfully cramped in here…$"

Route110_TrickHousePuzzle7_Text_H5_1::
	.string "Oh, yes, strong you are.$"

Route110_TrickHousePuzzle7_Text_H5_2::
	.string "I was hoping to switch places with you\n"
	.string "when I beat you, but…$"

