Route120_MapScripts::
	.byte 0

Route120_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_COLIN, Route120_Text_H0_0, Route120_Text_H0_1
	msgbox Route120_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_ROBERT_1, Route120_Text_H1_0, Route120_Text_H1_1
	msgbox Route120_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_LORENZO, Route120_Text_H2_0, Route120_Text_H2_1
	msgbox Route120_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_JENNA, Route120_Text_H3_0, Route120_Text_H3_1
	msgbox Route120_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_JEFFREY_1, Route120_Text_H4_0, Route120_Text_H4_1
	msgbox Route120_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_HItem55::
	finditem ITEM_NUGGET
	end

Route120_EventScript_HItem56::
	finditem ITEM_FULL_HEAL
	end

Route120_EventScript_H5::
	msgbox Route120_Text_H5, MSGBOX_NPC
	end

Route120_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_JENNIFER, Route120_Text_H6_0, Route120_Text_H6_1
	msgbox Route120_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_CHIP, Route120_Text_H7_0, Route120_Text_H7_1
	msgbox Route120_Text_H7_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_H8::
	trainerbattle_single TRAINER_HOENN_CLARISSA, Route120_Text_H8_0, Route120_Text_H8_1
	msgbox Route120_Text_H8_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_H9::
	trainerbattle_single TRAINER_HOENN_ANGELICA, Route120_Text_H9_0, Route120_Text_H9_1
	msgbox Route120_Text_H9_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_HItem57::
	finditem ITEM_NEST_BALL
	end

Route120_EventScript_HItem58::
	finditem ITEM_HYPER_POTION
	end

Route120_EventScript_H10::
	trainerbattle_single TRAINER_HOENN_KEIGO, Route120_Text_H10_0, Route120_Text_H10_1
	msgbox Route120_Text_H10_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_H11::
	trainerbattle_single TRAINER_HOENN_RILEY, Route120_Text_H11_0, Route120_Text_H11_1
	msgbox Route120_Text_H11_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_H12::
	trainerbattle_single TRAINER_HOENN_CALLIE, Route120_Text_H12_0, Route120_Text_H12_1
	msgbox Route120_Text_H12_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_H13::
	trainerbattle_single TRAINER_HOENN_LEONEL, Route120_Text_H13_0, Route120_Text_H13_1
	msgbox Route120_Text_H13_2, MSGBOX_AUTOCLOSE
	end

Route120_EventScript_HItem59::
	finditem ITEM_REVIVE
	end

Route120_EventScript_H14::
	msgbox Route120_Text_H14, MSGBOX_SIGN
	end

Route120_EventScript_H15::
	msgbox Route120_Text_H15, MSGBOX_SIGN
	end

