Route120_Text_H0_0::
	.string "Do you have any moves that can strike\n"
	.string "a flying POKéMON?$"

Route120_Text_H0_1::
	.string "You soared above me!$"

Route120_Text_H0_2::
	.string "The move FLY is convenient,\n"
	.string "don't you think?\p"
	.string "While the POKéMON is flying,\n"
	.string "almost no moves can strike it.$"

Route120_Text_H1_0::
	.string "My POKéMON is strong!\n"
	.string "How about yours?$"

Route120_Text_H1_1::
	.string "Your POKéMON were stronger…$"

Route120_Text_H1_2::
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_H2_0::
	.string "I'll check your POKéMON and see if\n"
	.string "they're fit for the outdoors.$"

Route120_Text_H2_1::
	.string "With POKéMON that strong, you're in\n"
	.string "no danger of needing rescue!$"

Route120_Text_H2_2::
	.string "To travel wherever your heart desires\n"
	.string "with POKéMON…\l"
	.string "That's the joy of being a TRAINER.$"

Route120_Text_H3_0::
	.string "How's your physical fitness?\n"
	.string "If you're not fit, you could have a\l"
	.string "rough time in critical situations.$"

Route120_Text_H3_1::
	.string "I'm totally fit, but…$"

Route120_Text_H3_2::
	.string "Fitness training is in my routine.\n"
	.string "I always run with my POKéMON.$"

Route120_Text_H4_0::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle?$"

Route120_Text_H4_1::
	.string "Lost it…$"

Route120_Text_H4_2::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…$"

Route120_Text_H5::
	.string "BERRIES grow by soaking up sunlight.\p"
	.string "We help the BERRIES grow by watering\n"
	.string "them regularly.\p"
	.string "It's an expression of love, isn't it?$"

Route120_Text_H6_0::
	.string "POKéMON have many special abilities.\n"
	.string "If you want to become a first-class\l"
	.string "TRAINER, learn about them.$"

Route120_Text_H6_1::
	.string "You're obviously thinking.$"

Route120_Text_H6_2::
	.string "The special abilities of POKéMON\n"
	.string "will make battle styles change.$"

Route120_Text_H7_0::
	.string "Who might you be?\p"
	.string "Are you perhaps searching for ancient\n"
	.string "ruins that are rumored to possibly\l"
	.string "exist according to legend?$"

Route120_Text_H7_1::
	.string "What a disgraceful setback…$"

Route120_Text_H7_2::
	.string "That giant rock… I would like to\n"
	.string "believe it may indeed contain ancient\l"
	.string "ruins. But I see no entrance.$"

Route120_Text_H8_0::
	.string "Why am I carrying this parasol?\p"
	.string "I'll tell you if you can win against me.$"

Route120_Text_H8_1::
	.string "A parasol can't ward off POKéMON\n"
	.string "attacks…$"

Route120_Text_H8_2::
	.string "I don't think strong sunlight is good\n"
	.string "for my POKéMON.\l"
	.string "So I shield them with my parasol.$"

Route120_Text_H9_0::
	.string "Me, POKéMON, and my parasol…\p"
	.string "If any one of them is missing,\n"
	.string "the picture of beauty will be ruined.$"

Route120_Text_H9_1::
	.string "You've completely ruined my beauty…$"

Route120_Text_H9_2::
	.string "A parasol wouldn't suit you at all.\p"
	.string "Why, something like this would only\n"
	.string "get in your way.$"

Route120_Text_H10_0::
	.string "I will adopt the movements of POKéMON\n"
	.string "and create new ninja techniques.$"

Route120_Text_H10_1::
	.string "The creation of new ninja techniques\n"
	.string "is but a distant dream…$"

Route120_Text_H10_2::
	.string "Perhaps I ought to apprentice under\n"
	.string "a ninja sensei.$"

Route120_Text_H11_0::
	.string "We ninja conceal ourselves under our\n"
	.string "camouflage cloaks.\l"
	.string "I bet you didn't know where I was!$"

Route120_Text_H11_1::
	.string "I lost!\n"
	.string "I should camouflage my shame!$"

Route120_Text_H11_2::
	.string "Our camouflage cloaks are all\n"
	.string "handmade.$"

Route120_Text_H12_0::
	.string "If you don't pay attention,\n"
	.string "you could get hurt!$"

Route120_Text_H12_1::
	.string "Ouch!\n"
	.string "I was the one to get hurt.$"

Route120_Text_H12_2::
	.string "I wonder… Should I evolve my POKéMON?\n"
	.string "They're cute the way they are, though.$"

Route120_Text_H13_0::
	.string "Your party POKéMON…\n"
	.string "Do you have different types?$"

Route120_Text_H13_1::
	.string "I've seen your policy in action!$"

Route120_Text_H13_2::
	.string "I think it's awesome you're so strong\n"
	.string "battling with your favorite POKéMON.$"

Route120_Text_H14::
	.string "ROUTE 120\n"
	.string "{LEFT_ARROW} FORTREE CITY$"

Route120_Text_H15::
	.string "{RIGHT_ARROW} ROUTE 121\n"
	.string "{LEFT_ARROW} ROUTE 120$"

