Route120_Text_H0::
	.string "The move FLY is convenient,\n"
	.string "don't you think?\p"
	.string "While the POKéMON is flying,\n"
	.string "almost no moves can strike it.$"

Route120_Text_H1::
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_H2::
	.string "To travel wherever your heart desires\n"
	.string "with POKéMON…\l"
	.string "That's the joy of being a TRAINER.$"

Route120_Text_H3::
	.string "Fitness training is in my routine.\n"
	.string "I always run with my POKéMON.$"

Route120_Text_H4::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…$"

Route120_Text_H5::
	.string "BERRIES grow by soaking up sunlight.\p"
	.string "We help the BERRIES grow by watering\n"
	.string "them regularly.\p"
	.string "It's an expression of love, isn't it?$"

Route120_Text_H6::
	.string "The special abilities of POKéMON\n"
	.string "will make battle styles change.$"

Route120_Text_H7::
	.string "That giant rock… I would like to\n"
	.string "believe it may indeed contain ancient\l"
	.string "ruins. But I see no entrance.$"

Route120_Text_H8::
	.string "I don't think strong sunlight is good\n"
	.string "for my POKéMON.\l"
	.string "So I shield them with my parasol.$"

Route120_Text_H9::
	.string "A parasol wouldn't suit you at all.\p"
	.string "Why, something like this would only\n"
	.string "get in your way.$"

Route120_Text_H10::
	.string "Perhaps I ought to apprentice under\n"
	.string "a ninja sensei.$"

Route120_Text_H11::
	.string "Our camouflage cloaks are all\n"
	.string "handmade.$"

Route120_Text_H12::
	.string "I wonder… Should I evolve my POKéMON?\n"
	.string "They're cute the way they are, though.$"

Route120_Text_H13::
	.string "I think it's awesome you're so strong\n"
	.string "battling with your favorite POKéMON.$"

Route120_Text_H14::
	.string "ROUTE 120\n"
	.string "{LEFT_ARROW} FORTREE CITY$"

Route120_Text_H15::
	.string "{RIGHT_ARROW} ROUTE 121\n"
	.string "{LEFT_ARROW} ROUTE 120$"

