FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "WARDEN: Hif fuff hefifoo!\p"
    .string "Ha lof ha feef ee hafahi ho.\n"
    .string "Heff hee fwee!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "Ah howhee ho hoo!\n"
    .string "Eef ee hafahi ho!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "Ha?\n"
    .string "He ohay heh ha hoo ee haheh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "{PLAYER} gave the GOLD TEETH\n"
    .string "to the WARDEN.$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "The WARDEN popped in his teeth!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "WARDEN: Thanks, son!\n"
    .string "You're a real lifesaver!\p"
    .string "No one could understand a word\n"
    .string "that I said, not a one!\p"
    .string "I was too ashamed to show my face\n"
    .string "around the OFFICE, even.\p"
    .string "Let me give you something for your\n"
    .string "trouble.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "WARDEN: Thank you, lassie!\n"
    .string "You're a real lifesaver!\p"
    .string "No one could understand a word\n"
    .string "that I said, not a one!\p"
    .string "I was too ashamed to show my face\n"
    .string "around the OFFICE, even.\p"
    .string "Let me give you something for your\n"
    .string "trouble.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "{PLAYER} received HM04\n"
    .string "from the WARDEN.$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "WARDEN: Inside HM04 you'll find\n"
    .string "STRENGTH.\p"
    .string "It lets POKéMON move boulders when\n"
    .string "you're outside of battle.\p"
    .string "Oh yes, did you find the SECRET\n"
    .string "HOUSE in the SAFARI ZONE?$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "POKéMON photos and fossils are on\n"
    .string "display.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string "Old POKéMON merchandise is on\n"
    .string "display.$"


FuchsiaCity_WardensHouse_Text_ElderVisitingPupil::
    .string "I am an elder of a clan of DRAGON\n"
    .string "masters from a faraway land.\p"
    .string "The WARDEN here was once my pupil.\n"
    .string "I came to see how he is faring…\p"
    .string "It seems he has lost his teeth\n"
    .string "along with his voice. Hohoho.$"

FuchsiaCity_WardensHouse_Text_ElderMustTestYou::
    .string "Hm… Good to see you here.\p"
    .string "You found my pupil's teeth and\n"
    .string "bested the GYM of this town.\p"
    .string "I am sorry, but I must test you.\p"
    .string "Not to worry, you are to answer\n"
    .string "only a few questions.\p"
    .string "Ready?$"

FuchsiaCity_WardensHouse_Text_ElderQuestion1::
    .string "What are POKéMON to you?$"

FuchsiaCity_WardensHouse_Text_ElderQuestion2::
    .string "What helps you to win battles?$"

FuchsiaCity_WardensHouse_Text_ElderQuestion3::
    .string "What kind of TRAINER do you wish\n"
    .string "to battle?$"

FuchsiaCity_WardensHouse_Text_ElderQuestion4::
    .string "What is most important for\n"
    .string "raising POKéMON?$"

FuchsiaCity_WardensHouse_Text_ElderQuestion5::
    .string "Strong POKéMON. Weak POKéMON.\n"
    .string "Which is more important?$"

FuchsiaCity_WardensHouse_Text_ElderIUnderstand::
    .string "Oh, I understand…$"

FuchsiaCity_WardensHouse_Text_ElderDidntCatchThat::
    .string "Hah? I didn't quite catch that…$"

FuchsiaCity_WardensHouse_Text_ElderWhatDidYouSay::
    .string "What was it you said?$"

FuchsiaCity_WardensHouse_Text_ElderYouCareDeeply::
    .string "Hm… I see…\p"
    .string "You care deeply for POKéMON.\n"
    .string "Very commendable.\p"
    .string "That conviction is what is\n"
    .string "important!\p"
    .string "{PLAYER}, don't lose that belief.\p"
    .string "It will see you through at the\n"
    .string "POKéMON LEAGUE.$"

FuchsiaCity_WardensHouse_Text_ElderTakeThisDratini::
    .string "I have something for you.\p"
    .string "Take this DRATINI as proof that\n"
    .string "I have recognized your worth.$"

FuchsiaCity_WardensHouse_Text_ElderPartyFull::
    .string "Hm? Your POKéMON party is full.\p"
    .string "Come back when you have room.$"

FuchsiaCity_WardensHouse_Text_ReceivedDratini::
    .string "{PLAYER} received DRATINI!$"

FuchsiaCity_WardensHouse_Text_ElderDragonsSymbolicOfClan::
    .string "DRAGON POKéMON are symbolic of\n"
    .string "our clan.\p"
    .string "You have shown that you can be\n"
    .string "entrusted with one.$"
