Route119_MapScripts::
	.byte 0

Route119_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_GREG, Route119_Text_H0_0, Route119_Text_H0_1
	msgbox Route119_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_TAYLOR, Route119_Text_H1_0, Route119_Text_H1_1
	msgbox Route119_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_DONALD, Route119_Text_H2_0, Route119_Text_H2_1
	msgbox Route119_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_JACKSON_1, Route119_Text_H3_0, Route119_Text_H3_1
	msgbox Route119_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_BRENT, Route119_Text_H4_0, Route119_Text_H4_1
	msgbox Route119_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_CATHERINE_1, Route119_Text_H5_0, Route119_Text_H5_1
	msgbox Route119_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_DOUG, Route119_Text_H6_0, Route119_Text_H6_1
	msgbox Route119_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_KENT, Route119_Text_H7_0, Route119_Text_H7_1
	msgbox Route119_Text_H7_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H8::
	trainerbattle_single TRAINER_HOENN_YASU, Route119_Text_H8_0, Route119_Text_H8_1
	msgbox Route119_Text_H8_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H9::
	trainerbattle_single TRAINER_HOENN_TAKASHI, Route119_Text_H9_0, Route119_Text_H9_1
	msgbox Route119_Text_H9_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H10::
	trainerbattle_single TRAINER_HOENN_HUGH, Route119_Text_H10_0, Route119_Text_H10_1
	msgbox Route119_Text_H10_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H11::
	trainerbattle_single TRAINER_HOENN_PHIL, Route119_Text_H11_0, Route119_Text_H11_1
	msgbox Route119_Text_H11_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_HItem46::
	finditem ITEM_SUPER_REPEL
	end

Route119_EventScript_HItem47::
	finditem ITEM_ZINC
	end

Route119_EventScript_HItem48::
	finditem ITEM_ELIXIR
	end

Route119_EventScript_HItem49::
	finditem ITEM_LEAF_STONE
	end

Route119_EventScript_HItem50::
	finditem ITEM_RARE_CANDY
	end

Route119_EventScript_HItem51::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_H12::
	msgbox Route119_Text_H12, MSGBOX_NPC
	end

Route119_EventScript_H13::
	msgbox Route119_Text_H13, MSGBOX_NPC
	end

Route119_EventScript_HItem52::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_H14::
	msgbox Route119_Text_H14, MSGBOX_NPC
	end

Route119_EventScript_H15::
	trainerbattle_single TRAINER_HOENN_HIDEO, Route119_Text_H15_0, Route119_Text_H15_1
	msgbox Route119_Text_H15_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H16::
	trainerbattle_single TRAINER_HOENN_CHRIS, Route119_Text_H16_0, Route119_Text_H16_1
	msgbox Route119_Text_H16_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H17::
	trainerbattle_single TRAINER_HOENN_RACHEL, Route119_Text_H17_0, Route119_Text_H17_1
	msgbox Route119_Text_H17_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H18::
	trainerbattle_single TRAINER_HOENN_DAYTON, Route119_Text_H18_0, Route119_Text_H18_1
	msgbox Route119_Text_H18_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_H19::
	trainerbattle_single TRAINER_HOENN_FABIAN, Route119_Text_H19_0, Route119_Text_H19_1
	msgbox Route119_Text_H19_2, MSGBOX_AUTOCLOSE
	end

Route119_EventScript_HItem53::
	finditem ITEM_NUGGET
	end

Route119_EventScript_HItem54::
	finditem ITEM_ELIXIR
	end

Route119_EventScript_H20::
	msgbox Route119_Text_H20, MSGBOX_SIGN
	end

Route119_EventScript_H21::
	msgbox Route119_Text_H21, MSGBOX_SIGN
	end

Route119_EventScript_H22::
	msgbox Route119_Text_H22, MSGBOX_SIGN
	end

