Route119_Text_H0_0::
	.string "You don't know who I am, do you?\p"
	.string "But, I also don't know you.\n"
	.string "So, we'll battle!$"

Route119_Text_H0_1::
	.string "You're pretty strong!$"

Route119_Text_H0_2::
	.string "Until you go away somewhere, we'll\n"
	.string "keep on mimicking your every move.$"

Route119_Text_H1_0::
	.string "If you step forward, we step forward.\p"
	.string "If you turn right, we turn, too…$"

Route119_Text_H1_1::
	.string "But if you win, I lose…$"

Route119_Text_H1_2::
	.string "I can't MIMIC you winning the match.\n"
	.string "That's just impossible…\l"
	.string "It's burning me up…$"

Route119_Text_H2_0::
	.string "So, we finally meet!\n"
	.string "My BUG POKéMON will keep you company!$"

Route119_Text_H2_1::
	.string "I wish we'd never met…$"

Route119_Text_H2_2::
	.string "I want to MIMIC you some more.\n"
	.string "Can you hurry up and move?$"

Route119_Text_H3_0::
	.string "Who has the knowledge and\n"
	.string "the technique for survival?\p"
	.string "POKéMON RANGERS, that's who!$"

Route119_Text_H3_1::
	.string "I didn't have enough POKéMON\n"
	.string "know-how…$"

Route119_Text_H3_2::
	.string "To break away from civilization and\n"
	.string "awaken the wild spirit within!\p"
	.string "That's our vision.$"

Route119_Text_H4_0::
	.string "We're the MIMIC CIRCLE!\n"
	.string "We MIMIC what you do!$"

Route119_Text_H4_1::
	.string "Whoopsie!\n"
	.string "I lost!$"

Route119_Text_H4_2::
	.string "What's so good about mimicry?\p"
	.string "Fufufu…\n"
	.string "You'll never understand…$"

Route119_Text_H5_0::
	.string "Oh? Look at you.\p"
	.string "For someone on an adventure,\n"
	.string "you're traveling awfully light.$"

Route119_Text_H5_1::
	.string "Accidents happen when you're not\n"
	.string "prepared!$"

Route119_Text_H5_2::
	.string "You're traveling light but you have\n"
	.string "everything you need.\p"
	.string "You're on top of things mentally and\n"
	.string "physically, too.$"

Route119_Text_H6_0::
	.string "Yep, you've finally caught me!\n"
	.string "Or were you trying to avoid me?$"

Route119_Text_H6_1::
	.string "Whoop, that was a great match!$"

Route119_Text_H6_2::
	.string "We're the MIMIC CIRCLE!\n"
	.string "I hope you enjoyed our performance.$"

Route119_Text_H7_0::
	.string "The MIMIC CIRCLE was formed by people\n"
	.string "who like to MIMIC.\p"
	.string "A battle starts the instant we meet!$"

Route119_Text_H7_1::
	.string "I give up!$"

Route119_Text_H7_2::
	.string "Won't you join our MIMIC CIRCLE?$"

Route119_Text_H8_0::
	.string "To lurk in shadows, and live in\n"
	.string "darkness… That is my destiny.\p"
	.string "I emerge to challenge you!$"

Route119_Text_H8_1::
	.string "I admit defeat!$"

Route119_Text_H8_2::
	.string "Those defeated in battle withdraw\n"
	.string "quietly back into the shadows.\l"
	.string "That, too, is destiny…$"

Route119_Text_H9_0::
	.string "If you're not on your guard,\n"
	.string "you're in for some pain!$"

Route119_Text_H9_1::
	.string "You're surprisingly good!$"

Route119_Text_H9_2::
	.string "My surprise attack ended in\n"
	.string "failure…$"

Route119_Text_H10_0::
	.string "The vast sky holds untold promise!\p"
	.string "Nothing can compare to the sheer\n"
	.string "exhilaration of flight!$"

Route119_Text_H10_1::
	.string "Down and out!$"

Route119_Text_H10_2::
	.string "My BIRD POKéMON made my dreams of\n"
	.string "flying come true!$"

Route119_Text_H11_0::
	.string "I'll show you the true potential of me\n"
	.string "and my BIRD POKéMON!$"

Route119_Text_H11_1::
	.string "We lacked potential…$"

Route119_Text_H11_2::
	.string "Ever since I was a little kid, I always\n"
	.string "admired BIRD POKéMON…$"

Route119_Text_H12::
	.string "I thought you FLY by catching a whole\n"
	.string "flock of BIRD POKéMON, and then\l"
	.string "hanging on to them somehow.\p"
	.string "But it turns out there's an HM move\n"
	.string "called FLY!\p"
	.string "I wish I'd known about that a long\n"
	.string "time ago…$"

Route119_Text_H13::
	.string "Tch…\n"
	.string "It's a no-go…\p"
	.string "The tall grass snares BIKE tires.\n"
	.string "There's no way you can cycle here.$"

Route119_Text_H14::
	.string "Can your POKéMON use its SECRET POWER\n"
	.string "on a big pile of grass and make a\l"
	.string "SECRET BASE?$"

Route119_Text_H15_0::
	.string "To hide a tree, use a forest!$"

Route119_Text_H15_1::
	.string "I bow to your superiority.$"

Route119_Text_H15_2::
	.string "To hide a tree, use a forest!\n"
	.string "To hide a POKéMON, use a POKéMON!\p"
	.string "There is no deep, hidden meaning\n"
	.string "to that.$"

Route119_Text_H16_0::
	.string "You spoke to me…\n"
	.string "So you want to challenge me!\p"
	.string "Sure! I'll try out the POKéMON I caught\n"
	.string "while SURFING!$"

Route119_Text_H16_1::
	.string "I don't have a clue about what it\n"
	.string "takes to win.$"

Route119_Text_H16_2::
	.string "Go for a SURF on my POKéMON…\p"
	.string "Then fish off its back…\p"
	.string "It's an indescribably luxuriant moment!$"

Route119_Text_H17_0::
	.string "Wherever and whenever I may be,\n"
	.string "I always have my parasol in hand.$"

Route119_Text_H17_1::
	.string "Oh, but…\n"
	.string "That's not fair.$"

Route119_Text_H17_2::
	.string "You're asking if my parasol is heavy?\n"
	.string "Your BAG is filled with more junk than\l"
	.string "I ever carry around.$"

Route119_Text_H18_0::
	.string "Hohoho!\n"
	.string "I like kid TRAINERS!\l"
	.string "Let's have a good one!$"

Route119_Text_H18_1::
	.string "You're pretty amazing!\n"
	.string "Hohoho!$"

Route119_Text_H18_2::
	.string "Hohoho!\n"
	.string "I'll try emulating the pep of kid\l"
	.string "TRAINERS like you!$"

Route119_Text_H19_0::
	.string "Hit me with a power chord!\n"
	.string "Victory is mine!\l"
	.string "It's our time to shine, whoa, yeah!$"

Route119_Text_H19_1::
	.string "You showed me who's the boss!\n"
	.string "We'll have to take the loss, oh, no!$"

Route119_Text_H19_2::
	.string "Hit me with another power chord!\n"
	.string "Leave me alone!\l"
	.string "Your win you have to atone!$"

Route119_Text_H20::
	.string "WEATHER INSTITUTE$"

Route119_Text_H21::
	.string "ROUTE 119\n"
	.string "{RIGHT_ARROW} FORTREE CITY$"

Route119_Text_H22::
	.string "TRAINER TIPS\p"
	.string "Up to sixteen decorations and\n"
	.string "furniture items can be placed in\l"
	.string "a SECRET BASE.\p"
	.string "Pick your favorite items and create\n"
	.string "your very own SECRET BASE exactly the\l"
	.string "way you want.$"

