Route112_MapScripts::
	.byte 0

Route112_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_BRICE, Route112_Text_H0_0, Route112_Text_H0_1
	msgbox Route112_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route112_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_LARRY, Route112_Text_H1_0, Route112_Text_H1_1
	msgbox Route112_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route112_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_CAROL, Route112_Text_H2_0, Route112_Text_H2_1
	msgbox Route112_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route112_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_TRENT_1, Route112_Text_H3_0, Route112_Text_H3_1
	msgbox Route112_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route112_EventScript_H4::
	msgbox Route112_Text_H4, MSGBOX_NPC
	end

Route112_EventScript_HItem25::
	finditem ITEM_NUGGET
	end

Route112_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_BRYANT, Route112_Text_H5_0, Route112_Text_H5_1
	msgbox Route112_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route112_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_SHAYLA, Route112_Text_H6_0, Route112_Text_H6_1
	msgbox Route112_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route112_EventScript_H7::
	msgbox Route112_Text_H7, MSGBOX_SIGN
	end

Route112_EventScript_H8::
	msgbox Route112_Text_H8, MSGBOX_SIGN
	end

Route112_EventScript_H9::
	msgbox Route112_Text_H9, MSGBOX_SIGN
	end

