Route112_Text_H0_0::
	.string "Hahahaha!\n"
	.string "How about we have a battle?\l"
	.string "You and me!\l"
	.string "Hahahaha!$"

Route112_Text_H0_1::
	.string "I lost!\n"
	.string "Hahahaha!$"

Route112_Text_H0_2::
	.string "Hahahahaha! Something flew up my\n"
	.string "nose! Hahahaha-hatchoo!$"

Route112_Text_H1_0::
	.string "I'm strong.\n"
	.string "I won't cry if I lose.$"

Route112_Text_H1_1::
	.string "Waaaah!$"

Route112_Text_H1_2::
	.string "I'm not crying because I miss my\n"
	.string "mommy! Snivel…$"

Route112_Text_H2_0::
	.string "When you're out on a picnic, why,\n"
	.string "you simply have to sing!\l"
	.string "Come on, sing with me!$"

Route112_Text_H2_1::
	.string "Oh, you're so strong!$"

Route112_Text_H2_2::
	.string "It doesn't matter if you're good or\n"
	.string "bad at singing or POKéMON.\p"
	.string "If you have the most fun, you win!$"

Route112_Text_H3_0::
	.string "My legs are solid from pounding up\n"
	.string "and down the mountains.\p"
	.string "They're not going to buckle easily,\n"
	.string "friend!$"

Route112_Text_H3_1::
	.string "Ouch! My legs cramped up!$"

Route112_Text_H3_2::
	.string "Try hiking, and I mean really\n"
	.string "pounding, on these mountain trails\l"
	.string "with a heavy pack weighing dozens of\l"
	.string "pounds.\p"
	.string "That, my friend, will get your body\n"
	.string "into serious shape.$"

Route112_Text_H4::
	.string "Eh, I'd like to get to MAUVILLE, but\n"
	.string "if I went down these ledges, it'd be\l"
	.string "no easy matter to get back to\l"
	.string "LAVARIDGE.$"

Route112_Text_H5_0::
	.string "I caught hot POKéMON in FIERY\n"
	.string "PATH! Take a look!$"

Route112_Text_H5_1::
	.string "What a bumpy ride that was!$"

Route112_Text_H5_2::
	.string "I like the way you battle.\n"
	.string "It has a certain flair to it.$"

Route112_Text_H6_0::
	.string "Oh, aren't you an adorable TRAINER!\n"
	.string "Please, I need a romantic battle!\l"
	.string "I'm somewhat decent!$"

Route112_Text_H6_1::
	.string "Oh, how strong you are!\n"
	.string "You've given me quite a shock!$"

Route112_Text_H6_2::
	.string "Are you busy right now? I was\n"
	.string "thinking that maybe we can have a\l"
	.string "rematch right now… But it's all right\l"
	.string "if you're busy.$"

Route112_Text_H7::
	.string "MT. CHIMNEY\p"
	.string "“For LAVARIDGE TOWN or the summit,\n"
	.string "please take the CABLE CAR.”$"

Route112_Text_H8::
	.string "MT. CHIMNEY CABLE CAR\n"
	.string "“A short walk {UP_ARROW} way!”$"

Route112_Text_H9::
	.string "ROUTE 112\n"
	.string "{LEFT_ARROW} LAVARIDGE TOWN$"

