PetalburgWoods_MapScripts::
	.byte 0

PetalburgWoods_EventScript_H0::
	msgbox PetalburgWoods_Text_H0, MSGBOX_NPC
	end

PetalburgWoods_EventScript_H1::
	msgbox PetalburgWoods_Text_H1, MSGBOX_NPC
	end

PetalburgWoods_EventScript_H2::
	msgbox PetalburgWoods_Text_H2, MSGBOX_NPC
	end

PetalburgWoods_EventScript_H3::
	msgbox PetalburgWoods_Text_H3, MSGBOX_NPC
	end

PetalburgWoods_EventScript_H4::
	msgbox PetalburgWoods_Text_H4, MSGBOX_NPC
	end

PetalburgWoods_EventScript_H5::
	msgbox PetalburgWoods_Text_H5, MSGBOX_SIGN
	end

PetalburgWoods_EventScript_H6::
	msgbox PetalburgWoods_Text_H6, MSGBOX_SIGN
	end

