PetalburgWoods_Text_H0::
	.string "Yo, there!\n"
	.string "Your POKéMON doing okay?\p"
	.string "If your POKéMON are weak and you\n"
	.string "want to avoid battles, you should\l"
	.string "stay out of tall grass.$"

PetalburgWoods_Text_H1_0::
	.string "I caught a whole bunch of POKéMON!\p"
	.string "Go, go, go!\n"
	.string "My BUG POKéMON team!$"

PetalburgWoods_Text_H1_1::
	.string "I have all these POKéMON,\n"
	.string "but I couldn't win…$"

PetalburgWoods_Text_H1_2::
	.string "I caught a bunch of POKéMON.\n"
	.string "Now I'm out of POKé BALLS.$"

PetalburgWoods_Text_H2_0::
	.string "If you take BUG POKéMON to school,\n"
	.string "you get to be instantly popular!$"

PetalburgWoods_Text_H2_1::
	.string "I can't be popular if I lose.$"

PetalburgWoods_Text_H2_2::
	.string "If you have a big BUG POKéMON,\n"
	.string "people respect you for it.$"

PetalburgWoods_Text_H3::
	.string "Sometimes, there are things on the\n"
	.string "ground even if you can't see them.\p"
	.string "That's why I always check where I'm\n"
	.string "walking.$"

PetalburgWoods_Text_H4::
	.string "Oh, neat!\n"
	.string "That's the BADGE from RUSTBORO GYM!\p"
	.string "You must be a TRAINER.\n"
	.string "You should try using this item.$"

PetalburgWoods_Text_H5::
	.string "TRAINER TIPS\p"
	.string "Any POKéMON that appears even once\n"
	.string "in a battle is awarded EXP Points.\p"
	.string "To raise a weak POKéMON, put it at\n"
	.string "the left of the team list.\p"
	.string "As soon as a battle starts, switch it\n"
	.string "out. It will earn EXP Points without\l"
	.string "being exposed to any harm.$"

PetalburgWoods_Text_H6::
	.string "TRAINER TIPS\p"
	.string "In addition to Hit Points (HP),\n"
	.string "POKéMON have Power Points (PP) that\l"
	.string "are used to make moves during\l"
	.string "battle.\p"
	.string "If a POKéMON runs out of PP, it must\n"
	.string "be taken to a POKéMON CENTER.$"

