FortreeCity_DecorationShop_MapScripts::
	.byte 0

FortreeCity_DecorationShop_EventScript_H0::
	msgbox FortreeCity_DecorationShop_Text_H0, MSGBOX_NPC
	end

FortreeCity_DecorationShop_EventScript_H1::
	msgbox FortreeCity_DecorationShop_Text_H1, MSGBOX_NPC
	end

FortreeCity_DecorationShop_EventScript_H2::
	msgbox FortreeCity_DecorationShop_Text_H2, MSGBOX_NPC
	end

FortreeCity_DecorationShop_EventScript_H3::
	msgbox FortreeCity_DecorationShop_Text_H3, MSGBOX_NPC
	end

