RustboroCity_PokemonCenter_1F_Text_H0::
	.string "My POKéMON has a NAIVE nature, and\n"
	.string "my friend's has a JOLLY nature.\p"
	.string "It's fascinating how POKéMON have\n"
	.string "personalities!$"

RustboroCity_PokemonCenter_1F_Text_H1::
	.string "Just like people, there are male and\n"
	.string "female POKéMON.\p"
	.string "But no one seems to have any idea\n"
	.string "how they're different.$"

RustboroCity_PokemonCenter_1F_Text_H2::
	.string "The man next door gave me an HM!\p"
	.string "I used it to teach my POKéMON how\n"
	.string "to CUT down skinny trees.$"

