Route126_MapScripts::
	.byte 0

Route126_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_BARRY, Route126_Text_H0_0, Route126_Text_H0_1
	msgbox Route126_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route126_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_DEAN, Route126_Text_H1_0, Route126_Text_H1_1
	msgbox Route126_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route126_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_NIKKI, Route126_Text_H2_0, Route126_Text_H2_1
	msgbox Route126_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route126_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_BRENDA, Route126_Text_H3_0, Route126_Text_H3_1
	msgbox Route126_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route126_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_SIENNA, Route126_Text_H4_0, Route126_Text_H4_1
	msgbox Route126_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route126_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_PABLO_1, Route126_Text_H5_0, Route126_Text_H5_1
	msgbox Route126_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route126_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_ISOBEL, Route126_Text_H6_0, Route126_Text_H6_1
	msgbox Route126_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route126_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_LEONARDO, Route126_Text_H7_0, Route126_Text_H7_1
	msgbox Route126_Text_H7_2, MSGBOX_AUTOCLOSE
	end

