Route126_Text_H0::
	.string "Thanks to my daily swimming routine…\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_H1::
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_H2::
	.string "You thrashed me… I want to\n"
	.string "disappear in a wave of despair…$"

Route126_Text_H3::
	.string "I love frolicking with POKéMON in\n"
	.string "the sea like this!$"

Route126_Text_H4::
	.string "I need to cool down now…\n"
	.string "I think I'll go for a dive.$"

Route126_Text_H5::
	.string "Losing to you stimulated my senses!\n"
	.string "I'll train myself and POKéMON harder!$"

Route126_Text_H6::
	.string "Ooh, I choked on some water!\n"
	.string "It's bitter! It's salty!!$"

Route126_Text_H7::
	.string "If you practice at something,\n"
	.string "you will get better at it.\p"
	.string "You're young--don't be afraid to\n"
	.string "try all sorts of things!$"

