Route126_Text_H0_0::
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_H0_1::
	.string "I admit it!\n"
	.string "You win!$"

Route126_Text_H0_2::
	.string "Thanks to my daily swimming routine…\n"
	.string "Look! Feast your eyes on this\l"
	.string "physique!$"

Route126_Text_H1_0::
	.string "This towering white mountain of rock\n"
	.string "is SOOTOPOLIS CITY.$"

Route126_Text_H1_1::
	.string "I was done in?$"

Route126_Text_H1_2::
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_H2_0::
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_H2_1::
	.string "My fantasy burst as if it were a\n"
	.string "bubble! Blub, blub, blub…$"

Route126_Text_H2_2::
	.string "You thrashed me… I want to\n"
	.string "disappear in a wave of despair…$"

Route126_Text_H3_0::
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_H3_1::
	.string "Oh, noooooh!$"

Route126_Text_H3_2::
	.string "I love frolicking with POKéMON in\n"
	.string "the sea like this!$"

Route126_Text_H4_0::
	.string "I'm throwing my whole heart\n"
	.string "into this!$"

Route126_Text_H4_1::
	.string "You had more heart!$"

Route126_Text_H4_2::
	.string "I need to cool down now…\n"
	.string "I think I'll go for a dive.$"

Route126_Text_H5_0::
	.string "Check out this sculpted body!\n"
	.string "I'm more cut than a BLACK BELT!$"

Route126_Text_H5_1::
	.string "Whoops! Too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_H5_2::
	.string "Losing to you stimulated my senses!\n"
	.string "I'll train myself and POKéMON\l"
	.string "harder!$"

Route126_Text_H6_0::
	.string "If seawater gets up your nose,\n"
	.string "doesn't it feel terrible?$"

Route126_Text_H6_1::
	.string "Ack! Why, you…\n"
	.string "Glub!$"

Route126_Text_H6_2::
	.string "Ooh, I choked on some water!\n"
	.string "It's bitter! It's salty!!$"

Route126_Text_H7_0::
	.string "I couldn't even swim last year,\n"
	.string "but now I'm a decent SWIMMER.\p"
	.string "I think I'm capable of anything now.$"

Route126_Text_H7_1::
	.string "Sheesh, getting greedy didn't do\n"
	.string "a thing for me.$"

Route126_Text_H7_2::
	.string "If you practice at something,\n"
	.string "you will get better at it.\p"
	.string "You're young--don't be afraid to\n"
	.string "try all sorts of things!$"

