MeteorFalls_StevensCave_Text_H0::
	.string "STEVEN: Oh, wow, {PLAYER}{KUN}. I'm\n"
	.string "amazed you knew where to find me.\p"
	.string "Do you, uh…maybe think of me as\n"
	.string "just a rock maniac?\p"
	.string "No, that can't be right.\p"
	.string "We battled alongside each other at\n"
	.string "the SOOTOPOLIS SPACE CENTER.\p"
	.string "You should have a very good idea\n"
	.string "about how good I am.\p"
	.string "Okay, {PLAYER}{KUN}, if you're going to\n"
	.string "mount a serious challenge, expect\l"
	.string "the worst!$"

