SlateportCity_PokemonFanClub_MapScripts::
	.byte 0

SlateportCity_PokemonFanClub_EventScript_H0::
	msgbox SlateportCity_PokemonFanClub_Text_H0, MSGBOX_NPC
	end

SlateportCity_PokemonFanClub_EventScript_H1::
	msgbox SlateportCity_PokemonFanClub_Text_H1, MSGBOX_NPC
	end

SlateportCity_PokemonFanClub_EventScript_H2::
	msgbox SlateportCity_PokemonFanClub_Text_H2, MSGBOX_NPC
	end

SlateportCity_PokemonFanClub_EventScript_H3::
	msgbox SlateportCity_PokemonFanClub_Text_H3, MSGBOX_NPC
	end

SlateportCity_PokemonFanClub_EventScript_H4::
	msgbox SlateportCity_PokemonFanClub_Text_H4, MSGBOX_NPC
	end

SlateportCity_PokemonFanClub_EventScript_H5::
	msgbox SlateportCity_PokemonFanClub_Text_H5, MSGBOX_NPC
	end

