BattleFrontier_BattlePyramidLobby_Text_H0::
	.string "Where the courage of TRAINERS\n"
	.string "is put to the test!\p"
	.string "Welcome to the BATTLE PYRAMID!\p"
	.string "I am your guide to\n"
	.string "the Battle Quest.$"

BattleFrontier_BattlePyramidLobby_Text_H1::
	.string "Welcome…\p"
	.string "I shall be pleased to tell you what\n"
	.string "misfortunes await in the PYRAMID…$"

BattleFrontier_BattlePyramidLobby_Text_H2::
	.string "Did you know?\p"
	.string "If you run fast, TRAINERS may\n"
	.string "notice and come after you for a\l"
	.string "battle.\p"
	.string "So, if you want to avoid TRAINERS,\n"
	.string "don't catch their eyes, but sneak\l"
	.string "cautiously and quietly past them.$"

BattleFrontier_BattlePyramidLobby_Text_H3::
	.string "Awaaaaaaarrrrgh!\p"
	.string "I had a whole lot of items, but I\n"
	.string "lost them all when I lost!\p"
	.string "Awaaaaaaarrrrgh!$"

BattleFrontier_BattlePyramidLobby_Text_H4::
	.string "The Battle Quest rules are listed.$"

