MossdeepCity_SpaceCenter_1F_Text_H0::
	.string "A rocket launch demands perfection.\n"
	.string "Not even a 1% margin of error is\l"
	.string "allowed.\p"
	.string "Even if it's 99% okay, the whole\n"
	.string "thing is useless if 1% happens to be\l"
	.string "no good.\p"
	.string "Despite that, we never stop trying.\n"
	.string "Why? It's a dream that never ends.$"

MossdeepCity_SpaceCenter_1F_Text_H1::
	.string "I was taking a stroll down the beach\n"
	.string "when I found this.\p"
	.string "It's not anything I need, so you can\n"
	.string "have it.$"

