LilycoveCity_LilycoveMuseum_2F_Text_H0::
	.string "I wish to fill this exhibit hall with\n"
	.string "modern and vibrant paintings of\l"
	.string "POKéMON.$"

LilycoveCity_LilycoveMuseum_2F_Text_H1::
	.string "It's a picture frame with\n"
	.string "pink-colored adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_H2::
	.string "It's a picture frame with\n"
	.string "pink-colored adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_H3::
	.string "It's a picture frame with\n"
	.string "yellow-colored adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_H4::
	.string "It's a picture frame with\n"
	.string "yellow-colored adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_H5::
	.string "It's a picture frame with\n"
	.string "red-colored adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_H6::
	.string "It's a picture frame with\n"
	.string "red-colored adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_H7::
	.string "It's a picture frame with\n"
	.string "blue-colored adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_H8::
	.string "It's a picture frame with\n"
	.string "blue-colored adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_H9::
	.string "It's a picture frame with\n"
	.string "green-colored adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_H10::
	.string "It's a picture frame with\n"
	.string "green-colored adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_H11::
	.string "It's a replica of a famous\n"
	.string "sculpture.\p"
	.string "It depicts an ancient BIRD POKéMON.$"

LilycoveCity_LilycoveMuseum_2F_Text_H12::
	.string "It's a replica of a famous\n"
	.string "sculpture.\p"
	.string "It depicts an ancient BIRD POKéMON.$"

