LavaridgeTown_Gym_B1F_MapScripts::
	.byte 0

LavaridgeTown_Gym_B1F_EventScript_H0::
	msgbox LavaridgeTown_Gym_B1F_Text_H0, MSGBOX_NPC
	end

LavaridgeTown_Gym_B1F_EventScript_H1::
	msgbox LavaridgeTown_Gym_B1F_Text_H1, MSGBOX_NPC
	end

LavaridgeTown_Gym_B1F_EventScript_H2::
	msgbox LavaridgeTown_Gym_B1F_Text_H2, MSGBOX_NPC
	end

LavaridgeTown_Gym_B1F_EventScript_H3::
	msgbox LavaridgeTown_Gym_B1F_Text_H3, MSGBOX_NPC
	end

