LilycoveCity_DepartmentStore_1F_Text_H0::
	.string "Welcome to LILYCOVE DEPARTMENT\n"
	.string "STORE.$"

LilycoveCity_DepartmentStore_1F_Text_H1::
	.string "This is the POKéMON LOTTERY CORNER.\p"
	.string "All shoppers at our DEPARTMENT\n"
	.string "STORE get to draw a POKéMON LOTO\l"
	.string "TICKET.\p"
	.string "If the LOTO TICKET's number matches\n"
	.string "the ID number of any of your\l"
	.string "POKéMON, you will receive a\l"
	.string "fabulous gift.\p"
	.string "Would you like to draw a POKéMON\n"
	.string "LOTO TICKET?$"

LilycoveCity_DepartmentStore_1F_Text_H2::
	.string "Whenever I come to the DEPARTMENT\n"
	.string "STORE, I always end up buying all\l"
	.string "sorts of things because it's so fun.$"

LilycoveCity_DepartmentStore_1F_Text_H3::
	.string "Today, my mom is going to buy me\n"
	.string "some nice furniture.$"

LilycoveCity_DepartmentStore_1F_Text_H4::
	.string "I'm buying something for my\n"
	.string "AZUMARILL as a reward for winning a\l"
	.string "CONTEST.$"

LilycoveCity_DepartmentStore_1F_Text_H5::
	.string "AZUMARILL: Maririroo!$"

LilycoveCity_DepartmentStore_1F_Text_H6::
	.string "1F: SERVICE COUNTER\n"
	.string "    LOTTERY CORNER\p"
	.string "2F: TRAINER'S ZONE\p"
	.string "3F: BATTLE COLLECTION\p"
	.string "4F: TM CORNER\p"
	.string "5F: POKé DOLL FLOOR\p"
	.string "ROOFTOP: ROOFTOP PLAZA$"

