Route130_MapScripts::
	.byte 0

Route130_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_RODNEY, Route130_Text_H0_0, Route130_Text_H0_1
	msgbox Route130_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route130_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_KATIE, Route130_Text_H1_0, Route130_Text_H1_1
	msgbox Route130_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route130_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_SANTIAGO, Route130_Text_H2_0, Route130_Text_H2_1
	msgbox Route130_Text_H2_2, MSGBOX_AUTOCLOSE
	end

