Route130_Text_H0_0::
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_H0_1::
	.string "This kid's awfully tough…$"

Route130_Text_H0_2::
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_H1_0::
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_H1_1::
	.string "Like the vast blue sea,\n"
	.string "the world of POKéMON spans\l"
	.string "depths beyond belief.$"

Route130_Text_H1_2::
	.string "The world's children dream\n"
	.string "of one day becoming\l"
	.string "the POKéMON CHAMPION.$"

Route130_Text_H2_0::
	.string "Floating on the open sea like this…\n"
	.string "It's peaceful.$"

Route130_Text_H2_1::
	.string "I needed to be a little less peaceful!$"

Route130_Text_H2_2::
	.string "Swimming and battling like this…\n"
	.string "I'm one happy guy…$"

