Route133_MapScripts::
	.byte 0

Route133_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_FRANKLIN, Route133_Text_H0_0, Route133_Text_H0_1
	msgbox Route133_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_LINDA, Route133_Text_H1_0, Route133_Text_H1_1
	msgbox Route133_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_DEBRA, Route133_Text_H2_0, Route133_Text_H2_1
	msgbox Route133_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_HItem78::
	finditem ITEM_BIG_PEARL
	end

Route133_EventScript_HItem79::
	finditem ITEM_STAR_PIECE
	end

Route133_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_BECK, Route133_Text_H3_0, Route133_Text_H3_1
	msgbox Route133_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_WARREN, Route133_Text_H4_0, Route133_Text_H4_1
	msgbox Route133_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_MOLLIE, Route133_Text_H5_0, Route133_Text_H5_1
	msgbox Route133_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_CONOR, Route133_Text_H6_0, Route133_Text_H6_1
	msgbox Route133_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route133_EventScript_HItem80::
	finditem ITEM_MAX_REVIVE
	end

