Route133_Text_H0::
	.string "It's just my luck that a tough TRAINER\n"
	.string "like you would drift here…\l"
	.string "I must be cursed…$"

Route133_Text_H1::
	.string "A strong child TRAINER…\n"
	.string "That's so annoying!$"

Route133_Text_H2::
	.string "A life adrift…\n"
	.string "I don't want it anymore!$"

Route133_Text_H3::
	.string "I'd like to go back to FORTREE,\n"
	.string "but I've grown to like this place, too.$"

Route133_Text_H4::
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_H5::
	.string "Keep at this, youngster. So you can\n"
	.string "become like my husband and me.$"

Route133_Text_H6::
	.string "Don't let others lead you astray.\n"
	.string "Don't lose direction as you grow older.$"

