Route133_Text_H0_0::
	.string "Did the currents carry you here,\n"
	.string "too? This must have been fated.\l"
	.string "Let's battle!$"

Route133_Text_H0_1::
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_H0_2::
	.string "It's just my luck that a tough\n"
	.string "TRAINER like you would drift here…\l"
	.string "I must be cursed…$"

Route133_Text_H1_0::
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_H1_1::
	.string "No! Please!$"

Route133_Text_H1_2::
	.string "A strong child TRAINER…\n"
	.string "That's so annoying!$"

Route133_Text_H2_0::
	.string "I've led a life of woe and misery…\n"
	.string "I've been cast away, and this is\l"
	.string "where I've drifted…$"

Route133_Text_H2_1::
	.string "Another loss…$"

Route133_Text_H2_2::
	.string "A life adrift…\n"
	.string "I don't want it anymore!$"

Route133_Text_H3_0::
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_H3_1::
	.string "You…\n"
	.string "You're stunningly cool!$"

Route133_Text_H3_2::
	.string "I'd like to go back to FORTREE, but\n"
	.string "I've grown to like this place, too.$"

Route133_Text_H4_0::
	.string "I want to win like everyone else,\n"
	.string "but I won't raise POKéMON like\l"
	.string "everyone else.$"

Route133_Text_H4_1::
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_H4_2::
	.string "It's way more fun to do things the\n"
	.string "way I want than to be like\l"
	.string "everybody else. I mean, that's\l"
	.string "obvious!$"

Route133_Text_H5_0::
	.string "I must have battled thousands\n"
	.string "of times. I've lost count.$"

Route133_Text_H5_1::
	.string "I may have lost thousands of times,\n"
	.string "but a loss still stings.$"

Route133_Text_H5_2::
	.string "Keep at this, youngster. So you can\n"
	.string "become like my husband and me.$"

Route133_Text_H6_0::
	.string "Young people are too happy to go\n"
	.string "with the flow. They're without\l"
	.string "direction.$"

Route133_Text_H6_1::
	.string "You have a firm sense of purpose.$"

Route133_Text_H6_2::
	.string "Don't let others lead you astray.\n"
	.string "Don't lose direction as you grow\l"
	.string "older.$"

