Route131_Text_H0_0::
	.string "The sea is teeming with POKéMON.\n"
	.string "It's not easy swimming, I tell you.$"

Route131_Text_H0_1::
	.string "POKéMON raised by TRAINERS are\n"
	.string "seriously tough…$"

Route131_Text_H0_2::
	.string "Gasp… Gasp…\n"
	.string "I'm wiped out…\p"
	.string "The going's easy. It's the leaving\n"
	.string "that's the hard part.\p"
	.string "Will I have any energy left to make\n"
	.string "the return trip?$"

Route131_Text_H1_0::
	.string "The sea… The sea… The sea…\n"
	.string "The sea as far as these eyes can see!\l"
	.string "I'm sick and tired of the sea!$"

Route131_Text_H1_1::
	.string "Bleah!$"

Route131_Text_H1_2::
	.string "Bored I am by the sea, but swim I must.\p"
	.string "I'm a born swimmer!\n"
	.string "That's what I am.$"

Route131_Text_H2_0::
	.string "Hi, sweetie, wait!\n"
	.string "We should battle, you and I!$"

Route131_Text_H2_1::
	.string "You're tough in spite of the way\n"
	.string "you look!$"

Route131_Text_H2_2::
	.string "Did you see a guy over there who whines\n"
	.string "that he's bored of the sea?\p"
	.string "That's all talk.\n"
	.string "He's hopelessly in love with the sea!$"

Route131_Text_H3_0::
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_H3_1::
	.string "I'm out of my depth!$"

Route131_Text_H3_2::
	.string "Maybe it's not my bathing suit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_H4_0::
	.string "RELI: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_H4_1::
	.string "RELI: We couldn't win even though we\n"
	.string "worked together…$"

Route131_Text_H4_2::
	.string "RELI: The people of PACIFIDLOG are\n"
	.string "together with the sea and POKéMON from\l"
	.string "the time they are born.$"

Route131_Text_H5_0::
	.string "IAN: I'm doing my best together with\n"
	.string "my sis!$"

Route131_Text_H5_1::
	.string "IAN: I did my best with my sis,\n"
	.string "but we still couldn't win…$"

Route131_Text_H5_2::
	.string "IAN: You know how PACIFIDLOG is\n"
	.string "a floating town?\p"
	.string "So, wherever there is the sea,\n"
	.string "that's a part of PACIFIDLOG!$"

Route131_Text_H6_0::
	.string "The people of PACIFIDLOG are\n"
	.string "a peaceful bunch.\p"
	.string "They never get angry.\n"
	.string "That goes for me, too.$"

Route131_Text_H6_1::
	.string "Oops!$"

Route131_Text_H6_2::
	.string "Tch! …Oh, wait.\n"
	.string "I'm not angry. Honestly!\p"
	.string "But, boy, you're strong!\n"
	.string "Hahaha!$"

Route131_Text_H7_0::
	.string "If you can beat me, I'll give you some\n"
	.string "great information!$"

Route131_Text_H7_1::
	.string "Oh?\n"
	.string "Did I lose?$"

Route131_Text_H7_2::
	.string "There is an odd place nearby.\n"
	.string "There's a huge tower there.\l"
	.string "Why don't you go take a look?$"

