BattleFrontier_Lounge4_Text_H0::
	.string "I wonder if they'll be airing\n"
	.string "interviews with tough TRAINERS\l"
	.string "today?$"

BattleFrontier_Lounge4_Text_H1::
	.string "If I opened a restaurant here,\n"
	.string "it'd make money for sure.$"

BattleFrontier_Lounge4_Text_H2::
	.string "Whew…\p"
	.string "I need to take a breather after\n"
	.string "some intense battles…\p"
	.string "But even now, I never take a break\n"
	.string "from plotting strategy and combos.$"

