SSTidalLowerDeck_MapScripts::
	.byte 0

SSTidalLowerDeck_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_PHILLIP, SSTidalLowerDeck_Text_H0_0, SSTidalLowerDeck_Text_H0_1
	msgbox SSTidalLowerDeck_Text_H0_2, MSGBOX_AUTOCLOSE
	end

SSTidalLowerDeck_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_LEONARD, SSTidalLowerDeck_Text_H1_0, SSTidalLowerDeck_Text_H1_1
	msgbox SSTidalLowerDeck_Text_H1_2, MSGBOX_AUTOCLOSE
	end

