SSTidalLowerDeck_Text_H0_0::
	.string "Arrrgh! I'm fed up and dog-tired of\n"
	.string "cleaning this huge place!\p"
	.string "Let's have a quick battle!$"

SSTidalLowerDeck_Text_H0_1::
	.string "Little bro, I lost!$"

SSTidalLowerDeck_Text_H0_2::
	.string "We're the CLEANUP BROTHERS!\p"
	.string "The old one dumps the detergent,\n"
	.string "and the young one does the\l"
	.string "scrubbing!$"

SSTidalLowerDeck_Text_H1_0::
	.string "This is the bottom of the ship's\n"
	.string "hull. There's plenty of room. It'll\l"
	.string "be alright for a POKéMON battle.$"

SSTidalLowerDeck_Text_H1_1::
	.string "Big bro, I lost!$"

SSTidalLowerDeck_Text_H1_2::
	.string "We're the CLEANUP BROTHERS!\p"
	.string "The old one dumps the detergent,\n"
	.string "and the young one does the\l"
	.string "scrubbing!$"

