SSTidalCorridor_Text_H0::
	.string "It'll be some time before we make land,\n"
	.string "I reckon.\p"
	.string "You can rest up in your cabin if you'd\n"
	.string "like. Your cabin's No. 2.\p"
	.string "The bed in there is soft and plushy.\n"
	.string "I can attest to how comfy it is!$"

SSTidalCorridor_Text_H1::
	.string "Go visit other cabins.\n"
	.string "TRAINERS bored of the boat trip will\l"
	.string "be itching to battle.$"

SSTidalCorridor_Text_H2::
	.string "The horizon spreads beyond\n"
	.string "the porthole.$"

SSTidalCorridor_Text_H3::
	.string "The horizon spreads beyond\n"
	.string "the porthole.$"

SSTidalCorridor_Text_H4::
	.string "The horizon spreads beyond\n"
	.string "the porthole.$"

SSTidalCorridor_Text_H5::
	.string "The horizon spreads beyond\n"
	.string "the porthole.$"

SSTidalCorridor_Text_H6::
	.string "The horizon spreads beyond\n"
	.string "the porthole.$"

SSTidalCorridor_Text_H7::
	.string "The horizon spreads beyond\n"
	.string "the porthole.$"

SSTidalCorridor_Text_H8::
	.string "The horizon spreads beyond\n"
	.string "the porthole.$"

SSTidalCorridor_Text_H9::
	.string "The horizon spreads beyond\n"
	.string "the porthole.$"

SSTidalCorridor_Text_H10::
	.string "Cabin 1$"

SSTidalCorridor_Text_H11::
	.string "Cabin 2$"

SSTidalCorridor_Text_H12::
	.string "Cabin 3$"

SSTidalCorridor_Text_H13::
	.string "Cabin 4$"

