MtPyre_3F_Text_H0_0::
	.string "The rich atmosphere of the mountain\n"
	.string "has elevated my psychic power!\p"
	.string "A mere child like you…\n"
	.string "You dream of winning?$"

MtPyre_3F_Text_H0_1::
	.string "I drown in self-pity…$"

MtPyre_3F_Text_H0_2::
	.string "My psychic powers have surely\n"
	.string "grown several times, but…$"

MtPyre_3F_Text_H1_0::
	.string "Ahahahaha!\p"
	.string "This is no place for children, least\n"
	.string "of all you!$"

MtPyre_3F_Text_H1_1::
	.string "I lost that cleanly…$"

MtPyre_3F_Text_H1_2::
	.string "This means my training is still not\n"
	.string "enough…\p"
	.string "I've got to keep working toward the\n"
	.string "summit…\p"
	.string "Go, me!$"

MtPyre_3F_Text_H2_0::
	.string "Why have you come here?$"

MtPyre_3F_Text_H2_1::
	.string "That was amazing!\n"
	.string "You're a very special TRAINER.$"

MtPyre_3F_Text_H2_2::
	.string "POKéMON no longer of this world.\n"
	.string "POKéMON that are with you now.\p"
	.string "And the POKéMON that you will meet\n"
	.string "in the future…\p"
	.string "They are all to be equally cherished.\n"
	.string "Please remember that.$"

