BattleFrontier_BattleArenaLobby_Text_H0::
	.string "Where the battling spirit of\n"
	.string "TRAINERS is put to the test!\p"
	.string "I welcome you to the BATTLE ARENA!\p"
	.string "I am your guide to the Set KO\n"
	.string "Tourney!$"

BattleFrontier_BattleArenaLobby_Text_H1::
	.string "In the BATTLE ARENA, the order of\n"
	.string "POKéMON is totally important.\p"
	.string "For example, if your first POKéMON\n"
	.string "has certain type disadvantages,\l"
	.string "try making your second POKéMON one\l"
	.string "with moves that are super effective\l"
	.string "against the first one.\p"
	.string "I think that will be a good way of\n"
	.string "making an effective team.$"

BattleFrontier_BattleArenaLobby_Text_H2::
	.string "I won in judging!\p"
	.string "Landing hits consistently on\n"
	.string "the opponent's POKéMON worked!$"

BattleFrontier_BattleArenaLobby_Text_H3::
	.string "Our match was declared a draw.\p"
	.string "When we ran out of time, both my\n"
	.string "POKéMON and the opponent's had\l"
	.string "about the same amount of HP left.$"

BattleFrontier_BattleArenaLobby_Text_H4::
	.string "I lost on the REFEREE's decision…\p"
	.string "I don't think it was a good idea to\n"
	.string "only use defensive moves and not\l"
	.string "attack…$"

BattleFrontier_BattleArenaLobby_Text_H5::
	.string "The Set KO Tourney's rules are\n"
	.string "listed.$"

