Route116_MapScripts::
	.byte 0

Route116_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_JOEY, Route116_Text_H0_0, Route116_Text_H0_1
	msgbox Route116_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route116_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_JOSE, Route116_Text_H1_0, Route116_Text_H1_1
	msgbox Route116_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route116_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_CLARK, Route116_Text_H2_0, Route116_Text_H2_1
	msgbox Route116_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route116_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_JANICE, Route116_Text_H3_0, Route116_Text_H3_1
	msgbox Route116_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route116_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_KAREN_1, Route116_Text_H4_0, Route116_Text_H4_1
	msgbox Route116_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route116_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_JERRY_1, Route116_Text_H5_0, Route116_Text_H5_1
	msgbox Route116_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route116_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_SARAH, Route116_Text_H6_0, Route116_Text_H6_1
	msgbox Route116_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route116_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_DAWSON, Route116_Text_H7_0, Route116_Text_H7_1
	msgbox Route116_Text_H7_2, MSGBOX_AUTOCLOSE
	end

Route116_EventScript_H8::
	trainerbattle_single TRAINER_HOENN_JOHNSON, Route116_Text_H8_0, Route116_Text_H8_1
	msgbox Route116_Text_H8_2, MSGBOX_AUTOCLOSE
	end

Route116_EventScript_H9::
	trainerbattle_single TRAINER_HOENN_DEVAN, Route116_Text_H9_0, Route116_Text_H9_1
	msgbox Route116_Text_H9_2, MSGBOX_AUTOCLOSE
	end

Route116_EventScript_H10::
	msgbox Route116_Text_H10, MSGBOX_SIGN
	end

Route116_EventScript_H11::
	msgbox Route116_Text_H11, MSGBOX_SIGN
	end

Route116_EventScript_H12::
	msgbox Route116_Text_H12, MSGBOX_SIGN
	end

Route116_EventScript_H13::
	msgbox Route116_Text_H13, MSGBOX_SIGN
	end

Route116_EventScript_H14::
	msgbox Route116_Text_H14, MSGBOX_SIGN
	end

