Route116_Text_H0::
	.string "Bandages are signs of toughness!\n"
	.string "I've got another one!$"

Route116_Text_H1::
	.string "BUG POKéMON evolve quickly.\n"
	.string "So they get strong quickly, too.$"

Route116_Text_H2::
	.string "It's no big deal if there's no tunnel.\n"
	.string "To a HIKER, mountains are roads!$"

Route116_Text_H3::
	.string "POKéMON that possess cuteness and\n"
	.string "power, that's ideal, I think.$"

Route116_Text_H4::
	.string "Awww, I'll never become an elegant\n"
	.string "TRAINER like ROXANNE this way!$"

Route116_Text_H5::
	.string "I'll have to redo some courses at\n"
	.string "the TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_H6::
	.string "My life of luxury affords me all that\n"
	.string "I could possibly desire.\p"
	.string "However, when it comes to POKéMON,\n"
	.string "my wealth has no meaning.$"

Route116_Text_H7::
	.string "Oh, no, no, no!\n"
	.string "You've mussed up my POKéMON's fur!\l"
	.string "You've ruined my hairdo, too!\l"
	.string "I'll have to call my stylist now!$"

Route116_Text_H8::
	.string "Want to stay here and keep\n"
	.string "me company?$"

Route116_Text_H9::
	.string "I should try different POKéMON\n"
	.string "types, that's what I ought to do.$"

Route116_Text_H10::
	.string "ROUTE 116\n"
	.string "{LEFT_ARROW} RUSTBORO CITY$"

Route116_Text_H11::
	.string "RUSTURF TUNNEL\n"
	.string "“Linking RUSTBORO and VERDANTURF\p"
	.string "“The tunnel project has been\n"
	.string "canceled.”$"

Route116_Text_H12::
	.string "TUNNELER'S REST HOUSE$"

Route116_Text_H13::
	.string "TRAINER TIPS\p"
	.string "If you want to stop a POKéMON from\n"
	.string "evolving, press the B Button while it\l"
	.string "is trying to evolve.\l"
	.string "The startled POKéMON will stop.\p"
	.string "This is called an evolution cancel.$"

Route116_Text_H14::
	.string "TRAINER TIPS\p"
	.string "Your BAG has several POCKETS.\p"
	.string "Items you obtain are automatically\n"
	.string "placed in the appropriate POCKETS.\p"
	.string "No TRAINER can afford to be without\n"
	.string "a BAG of their own.$"

