Route116_Text_H0_0::
	.string "My POKéMON rule!\n"
	.string "Check them out!$"

Route116_Text_H0_1::
	.string "Ouch! A scrape!\n"
	.string "I have to put on a bandage!$"

Route116_Text_H0_2::
	.string "Bandages are signs of toughness!\n"
	.string "I've got another one!$"

Route116_Text_H1_0::
	.string "My BUG POKéMON are tough!\n"
	.string "Let's battle!$"

Route116_Text_H1_1::
	.string "I lost!\n"
	.string "I thought I had you!$"

Route116_Text_H1_2::
	.string "BUG POKéMON evolve quickly.\n"
	.string "So they get strong quickly, too.$"

Route116_Text_H2_0::
	.string "If the tunnel doesn't go through, then\n"
	.string "I'll just go over the top.$"

Route116_Text_H2_1::
	.string "Gasp… Gasp…\n"
	.string "Losing made me tired…$"

Route116_Text_H2_2::
	.string "It's no big deal if there's no tunnel.\n"
	.string "To a HIKER, mountains are roads!$"

Route116_Text_H3_0::
	.string "Let me teach you how strong my\n"
	.string "adorable POKéMON is!$"

Route116_Text_H3_1::
	.string "You're a notch above me…$"

Route116_Text_H3_2::
	.string "POKéMON that possess cuteness and\n"
	.string "power, that's ideal, I think.$"

Route116_Text_H4_0::
	.string "I study at school, and I study on\n"
	.string "the way home, too!$"

Route116_Text_H4_1::
	.string "I'm in shock--I lost?$"

Route116_Text_H4_2::
	.string "Awww, I'll never become an elegant\n"
	.string "TRAINER like ROXANNE this way!$"

Route116_Text_H5_0::
	.string "We learn all sorts of things at the\n"
	.string "TRAINER'S SCHOOL.\p"
	.string "I want to test things out for real!$"

Route116_Text_H5_1::
	.string "I slacked off in school…\n"
	.string "That's why I lost.$"

Route116_Text_H5_2::
	.string "I'll have to redo some courses at\n"
	.string "the TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_H6_0::
	.string "Just so you know, I've never once been\n"
	.string "bested by anyone at anything.$"

Route116_Text_H6_1::
	.string "Oh, my goodness.\n"
	.string "This is a new experience for me.$"

Route116_Text_H6_2::
	.string "My life of luxury affords me all that\n"
	.string "I could possibly desire.\p"
	.string "However, when it comes to POKéMON,\n"
	.string "my wealth has no meaning.$"

Route116_Text_H7_0::
	.string "When you lay your eyes on my POKéMON's\n"
	.string "gorgeous fur, their beauty will render\l"
	.string "you helpless!$"

Route116_Text_H7_1::
	.string "Oh, baby, say it isn't so!$"

Route116_Text_H7_2::
	.string "Oh, no, no, no!\n"
	.string "You've mussed up my POKéMON's fur!\l"
	.string "You've ruined my hairdo, too!\l"
	.string "I'll have to call my stylist now!$"

Route116_Text_H8_0::
	.string "It's a dead end up here.\n"
	.string "I'm bored, so can we battle?$"

Route116_Text_H8_1::
	.string "That was fun even though I lost.$"

Route116_Text_H8_2::
	.string "Want to stay here and keep\n"
	.string "me company?$"

Route116_Text_H9_0::
	.string "We'll rock you hard!$"

Route116_Text_H9_1::
	.string "Aiyiyi!\n"
	.string "No contest at all!$"

Route116_Text_H9_2::
	.string "I should try different POKéMON\n"
	.string "types, that's what I ought to do.$"

Route116_Text_H10::
	.string "ROUTE 116\n"
	.string "{LEFT_ARROW} RUSTBORO CITY$"

Route116_Text_H11::
	.string "RUSTURF TUNNEL\n"
	.string "“Linking RUSTBORO and VERDANTURF\p"
	.string "“The tunnel project has been\n"
	.string "canceled.”$"

Route116_Text_H12::
	.string "TUNNELER'S REST HOUSE$"

Route116_Text_H13::
	.string "TRAINER TIPS\p"
	.string "If you want to stop a POKéMON from\n"
	.string "evolving, press the B Button while it\l"
	.string "is trying to evolve.\l"
	.string "The startled POKéMON will stop.\p"
	.string "This is called an evolution cancel.$"

Route116_Text_H14::
	.string "TRAINER TIPS\p"
	.string "Your BAG has several POCKETS.\p"
	.string "Items you obtain are automatically\n"
	.string "placed in the appropriate POCKETS.\p"
	.string "No TRAINER can afford to be without\n"
	.string "a BAG of their own.$"

