BillsGarden_Text_BillSecretGarden::
    .string "BILL: Whoa, you've caught 100 kinds\n"
    .string "of POKéMON already?\p"
    .string "Then I can tell you my secret.\n"
    .string "There's a garden out back.\p"
    .string "POKéMON from JOHTO and HOENN that\n"
    .string "I met on my travels play there.\p"
    .string "If one of them takes a liking to you,\n"
    .string "go ahead and take it along.\p"
    .string "Only one a day, though!\n"
    .string "I unlocked the back door for you.$"

BillsGarden_Text_BillEnjoyGarden::
    .string "BILL: How are the POKéMON in the\n"
    .string "garden doing?\p"
    .string "Only one of them can leave each day,\n"
    .string "so the others don't get lonely.$"

BillsGarden_Text_GoOutToGarden::
    .string "It's the back door to BILL's garden.\n"
    .string "Go outside?$"

BillsGarden_Text_BackDoorLocked::
    .string "It's a back door.\n"
    .string "It's locked.$"

BillsGarden_Text_WantsToComeAlong::
    .string "{STR_VAR_1} looks like it wants to\n"
    .string "come along!\p"
    .string "Take {STR_VAR_1} with you?$"

BillsGarden_Text_TookMonAlong::
    .string "{PLAYER} took {STR_VAR_1} along!$"

BillsGarden_Text_PlayingHappily::
    .string "{STR_VAR_1} is playing happily.\p"
    .string "Another POKéMON already left today…\n"
    .string "Come back after walking around a bit.$"

BillsGarden_Text_WentBackToPlaying::
    .string "{STR_VAR_1} went back to playing.$"
