#ifndef GUARD_CONSTANTS_AIRPLANE_H
#define GUARD_CONSTANTS_AIRPLANE_H

// Destinations for DoAirplaneFlightScene (VAR_0x8004)
#define AIRPLANE_DEST_KANTO 0 // VERMILION AIRPORT
#define AIRPLANE_DEST_HOENN 1 // SLATEPORT HARBOR
#define AIRPLANE_DEST_COUNT 2

#endif // GUARD_CONSTANTS_AIRPLANE_H
