#ifndef GUARD_CONSTANTS_BUG_CONTEST_H
#define GUARD_CONSTANTS_BUG_CONTEST_H

// VAR_BUG_CONTEST_STATE
#define BUG_CONTEST_NONE    0
#define BUG_CONTEST_ACTIVE  1
#define BUG_CONTEST_JUDGING 2

#endif // GUARD_CONSTANTS_BUG_CONTEST_H
