#ifndef GUARD_CONSTANTS_FLAGS_HOENN_STORY_H
#define GUARD_CONSTANTS_FLAGS_HOENN_STORY_H

// Flags the Hoenn story writes itself, as opposed to the ones the import
// script generates (0x000..0x1FF of the Hoenn flag block) and the world map's
// (0x400..). They are kept in this hand-written file so a re-import cannot
// clobber them, and they share gSaveBlock2Ptr->hoennFlags, so nothing in the
// save moves.

#define HOENN_STORY_FLAGS_START           (HOENN_FLAGS_START + 0x200)

// Hoenn's own badges. The trainer card shows Kanto's eight and its layout is
// part of the save, so Hoenn's are plain flags and an NPC reports them.
#define FLAG_HOENN_BADGE01_GET            (HOENN_STORY_FLAGS_START + 0)  // STONE
#define FLAG_HOENN_BADGE02_GET            (HOENN_STORY_FLAGS_START + 1)  // KNUCKLE (BRAWLY, stage 1)
#define FLAG_HOENN_BADGE03_GET            (HOENN_STORY_FLAGS_START + 2)  // DYNAMO
#define FLAG_HOENN_BADGE04_GET            (HOENN_STORY_FLAGS_START + 3)  // HEAT
#define FLAG_HOENN_BADGE05_GET            (HOENN_STORY_FLAGS_START + 4)  // BALANCE
#define FLAG_HOENN_BADGE06_GET            (HOENN_STORY_FLAGS_START + 5)  // FEATHER
#define FLAG_HOENN_BADGE07_GET            (HOENN_STORY_FLAGS_START + 6)  // MIND
#define FLAG_HOENN_BADGE08_GET            (HOENN_STORY_FLAGS_START + 7)  // RAIN

// Stage 1 — the Slateport harbour zone
#define FLAG_HOENN_MET_STERN              (HOENN_STORY_FLAGS_START + 8)
#define FLAG_HOENN_MUSEUM_DEFENDED        (HOENN_STORY_FLAGS_START + 9)
#define FLAG_HOENN_ARCHIE_WARNED          (HOENN_STORY_FLAGS_START + 10)
#define FLAG_HOENN_SURVEY_LETTER_GOT      (HOENN_STORY_FLAGS_START + 11)
#define FLAG_HOENN_SURVEY_LETTER_DONE     (HOENN_STORY_FLAGS_START + 12)
#define FLAG_HOENN_SCANNER_DELIVERED      (HOENN_STORY_FLAGS_START + 13)
#define FLAG_HOENN_DEEP_SEA_ITEM_TAKEN    (HOENN_STORY_FLAGS_START + 14)
#define FLAG_HOENN_ROUTE109_BROTHERS_DONE (HOENN_STORY_FLAGS_START + 15)
#define FLAG_HOENN_GOT_TM08_FROM_BRAWLY   (HOENN_STORY_FLAGS_START + 16)
#define FLAG_HOENN_GOT_TM47_IN_CAVE       (HOENN_STORY_FLAGS_START + 17)

// Objects the story shows and hides
#define FLAG_HIDE_HOENN_HARBOR_STERN      (HOENN_STORY_FLAGS_START + 18)
#define FLAG_HIDE_HOENN_MUSEUM_GRUNTS     (HOENN_STORY_FLAGS_START + 19)
#define FLAG_HIDE_HOENN_MUSEUM_ARCHIE     (HOENN_STORY_FLAGS_START + 20)
#define FLAG_HIDE_HOENN_SHIPYARD_STERN    (HOENN_STORY_FLAGS_START + 21)

// Event 7: the three places the starter PIKACHU gets a line of its own
#define FLAG_HOENN_PIKACHU_GYM_SEEN       (HOENN_STORY_FLAGS_START + 22)
#define FLAG_HOENN_PIKACHU_MUSEUM_SEEN    (HOENN_STORY_FLAGS_START + 23)
#define FLAG_HOENN_PIKACHU_SHIPYARD_SEEN  (HOENN_STORY_FLAGS_START + 24)

// The SCANNER in the wreck's captain's office (event 5)
#define FLAG_HOENN_SCANNER_FOUND          (HOENN_STORY_FLAGS_START + 25)

// Stage 2 - MAUVILLE and the cycling road
#define FLAG_HOENN_MAUVILLE_BARRIERS      (HOENN_STORY_FLAGS_START + 26)
#define FLAG_HOENN_DEFEATED_MAUVILLE_GYM  (HOENN_STORY_FLAGS_START + 27)
#define FLAG_HOENN_GOT_TM34_FROM_WATTSON  (HOENN_STORY_FLAGS_START + 28)
#define FLAG_HOENN_WATTSON_ERRAND         (HOENN_STORY_FLAGS_START + 29)
#define FLAG_HOENN_NEW_MAUVILLE_DONE      (HOENN_STORY_FLAGS_START + 30)
#define FLAG_HOENN_GOT_BASEMENT_KEY       (HOENN_STORY_FLAGS_START + 31)
#define FLAG_HOENN_CYCLING_PRIZE_1        (HOENN_STORY_FLAGS_START + 32)
#define FLAG_HOENN_CYCLING_PRIZE_2        (HOENN_STORY_FLAGS_START + 33)
#define FLAG_HOENN_CYCLING_PRIZE_3        (HOENN_STORY_FLAGS_START + 34)
#define FLAG_HOENN_TRICK_HOUSE_DONE       (HOENN_STORY_FLAGS_START + 35)
#define FLAG_HOENN_DAYCARE_OPEN           (HOENN_STORY_FLAGS_START + 36)
#define FLAG_HOENN_MET_WANDA              (HOENN_STORY_FLAGS_START + 37)

#define FLAG_HOENN_VOLTORB_1              (HOENN_STORY_FLAGS_START + 38)
#define FLAG_HOENN_VOLTORB_2              (HOENN_STORY_FLAGS_START + 39)
#define FLAG_HOENN_VOLTORB_3              (HOENN_STORY_FLAGS_START + 40)
#define FLAG_HOENN_HIDE_VOLTORB_1         (HOENN_STORY_FLAGS_START + 41)
#define FLAG_HOENN_HIDE_VOLTORB_2         (HOENN_STORY_FLAGS_START + 42)
#define FLAG_HOENN_HIDE_VOLTORB_3         (HOENN_STORY_FLAGS_START + 43)

// TRICK HOUSE puzzle 7's five switches
#define FLAG_HOENN_TRICK_PUZZLE_7_SWITCH_1 (HOENN_STORY_FLAGS_START + 44)
#define FLAG_HOENN_TRICK_PUZZLE_7_SWITCH_2 (HOENN_STORY_FLAGS_START + 45)
#define FLAG_HOENN_TRICK_PUZZLE_7_SWITCH_3 (HOENN_STORY_FLAGS_START + 46)
#define FLAG_HOENN_TRICK_PUZZLE_7_SWITCH_4 (HOENN_STORY_FLAGS_START + 47)
#define FLAG_HOENN_TRICK_PUZZLE_7_SWITCH_5 (HOENN_STORY_FLAGS_START + 48)

#define FLAG_HOENN_HIDE_TRICK_MASTER_ENTRANCE (HOENN_STORY_FLAGS_START + 49)
#define FLAG_HOENN_HIDE_TRICK_MASTER_END      (HOENN_STORY_FLAGS_START + 50)

#define FLAG_HOENN_GOT_TM17_AT_TENT       (HOENN_STORY_FLAGS_START + 51)

// TRICK HOUSE final prizes, one flag each, since v0.9.0 gives both
#define FLAG_HOENN_TRICK_PRIZE_AMULET_COIN (HOENN_STORY_FLAGS_START + 52)
#define FLAG_HOENN_TRICK_PRIZE_EXP_SHARE   (HOENN_STORY_FLAGS_START + 53)

#define HOENN_STORY_FLAGS_USED 54

#endif  // GUARD_CONSTANTS_FLAGS_HOENN_STORY_H
