Route115_MapScripts::
	.byte 0

Route115_EventScript_H0::
	msgbox Route115_Text_H0, MSGBOX_NPC
	end

Route115_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_TIMOTHY_1, Route115_Text_H1_0, Route115_Text_H1_1
	msgbox Route115_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route115_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_NOB_1, Route115_Text_H2_0, Route115_Text_H2_1
	msgbox Route115_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route115_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_CYNDY_1, Route115_Text_H3_0, Route115_Text_H3_1
	msgbox Route115_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route115_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_KOICHI, Route115_Text_H4_0, Route115_Text_H4_1
	msgbox Route115_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route115_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_HECTOR, Route115_Text_H5_0, Route115_Text_H5_1
	msgbox Route115_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route115_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_KYRA, Route115_Text_H6_0, Route115_Text_H6_1
	msgbox Route115_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route115_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_JAIDEN, Route115_Text_H7_0, Route115_Text_H7_1
	msgbox Route115_Text_H7_2, MSGBOX_AUTOCLOSE
	end

Route115_EventScript_H8::
	trainerbattle_single TRAINER_HOENN_HELENE, Route115_Text_H8_0, Route115_Text_H8_1
	msgbox Route115_Text_H8_2, MSGBOX_AUTOCLOSE
	end

Route115_EventScript_H9::
	trainerbattle_single TRAINER_HOENN_ALIX, Route115_Text_H9_0, Route115_Text_H9_1
	msgbox Route115_Text_H9_2, MSGBOX_AUTOCLOSE
	end

Route115_EventScript_H10::
	trainerbattle_single TRAINER_HOENN_MARLENE, Route115_Text_H10_0, Route115_Text_H10_1
	msgbox Route115_Text_H10_2, MSGBOX_AUTOCLOSE
	end

Route115_EventScript_H11::
	msgbox Route115_Text_H11, MSGBOX_SIGN
	end

Route115_EventScript_H12::
	msgbox Route115_Text_H12, MSGBOX_SIGN
	end

