Route115_Text_H0::
	.string "Exploring a cave isn't like walking\n"
	.string "on a road.\p"
	.string "You never know when wild POKéMON will\n"
	.string "appear. It's full of suspense.$"

Route115_Text_H1::
	.string "There is no such thing as a born genius.\n"
	.string "It all depends on effort!\l"
	.string "That is what I believe…$"

Route115_Text_H2::
	.string "I've been teaching my POKéMON karate.\p"
	.string "It looks like they'll get a lot better\n"
	.string "than me. I'm excited about that.$"

Route115_Text_H3::
	.string "The sand acts as a cushion to reduce\n"
	.string "impact and prevent injury.\l"
	.string "This is the perfect place to train.$"

Route115_Text_H4::
	.string "My MACHOP crew!\p"
	.string "So long as they seek power, I will\n"
	.string "grow strong with them!$"

Route115_Text_H5::
	.string "I have this rare POKéMON.\n"
	.string "It's enough to keep me satisfied.$"

Route115_Text_H6::
	.string "I made the mistake of trying to battle\n"
	.string "while running!\p"
	.string "I should take a run to calm down…$"

Route115_Text_H7::
	.string "But my POKéMON were ultra,\n"
	.string "weren't they?$"

Route115_Text_H8::
	.string "I rarely meet anyone who's better\n"
	.string "than me…\p"
	.string "I get it now!\n"
	.string "You're a GYM LEADER, aren't you?$"

Route115_Text_H9::
	.string "Oh, well.\n"
	.string "I think I will TELEPORT home.$"

Route115_Text_H10::
	.string "I was meditating with my POKéMON.\n"
	.string "But this place isn't very peaceful…$"

Route115_Text_H11::
	.string "ROUTE 115\n"
	.string "{DOWN_ARROW} RUSTBORO CITY$"

Route115_Text_H12::
	.string "METEOR FALLS\n"
	.string "FALLARBOR TOWN THROUGH HERE$"

