Route115_Text_H0::
	.string "Exploring a cave isn't like walking\n"
	.string "on a road.\p"
	.string "You never know when wild POKéMON\n"
	.string "will appear. It's full of suspense.$"

Route115_Text_H1_0::
	.string "Hm…\n"
	.string "You seem rather capable…\l"
	.string "Let me keep you company!$"

Route115_Text_H1_1::
	.string "You're much stronger than\n"
	.string "I'd imagined!$"

Route115_Text_H1_2::
	.string "There is no such thing as a born\n"
	.string "genius. It all depends on effort!\l"
	.string "That is what I believe…$"

Route115_Text_H2_0::
	.string "My strongest skill is busting bricks\n"
	.string "with my forehead!$"

Route115_Text_H2_1::
	.string "Ugwaaaah!\n"
	.string "My head is busted!$"

Route115_Text_H2_2::
	.string "I've been teaching my POKéMON\n"
	.string "karate.\p"
	.string "It looks like they'll get a lot\n"
	.string "better than me. I'm excited about\l"
	.string "that.$"

Route115_Text_H3_0::
	.string "This beach is my secret training\n"
	.string "spot! Don't come butting in!$"

Route115_Text_H3_1::
	.string "I haven't trained enough!$"

Route115_Text_H3_2::
	.string "The sand acts as a cushion to\n"
	.string "reduce impact and prevent injury.\l"
	.string "This is the perfect place to train.$"

Route115_Text_H4_0::
	.string "You!\p"
	.string "My MACHOP!\p"
	.string "Demand a battle!$"

Route115_Text_H4_1::
	.string "Ouch, ouch, ouch!$"

Route115_Text_H4_2::
	.string "My MACHOP crew!\p"
	.string "So long as they seek power, I will\n"
	.string "grow strong with them!$"

Route115_Text_H5_0::
	.string "I have a rare POKéMON!\n"
	.string "Would you like me to show you?$"

Route115_Text_H5_1::
	.string "You…\n"
	.string "You want my POKéMON, don't you?$"

Route115_Text_H5_2::
	.string "I have this rare POKéMON.\n"
	.string "It's enough to keep me satisfied.$"

Route115_Text_H6_0::
	.string "I'll battle while I'm running!\n"
	.string "Try to keep up with me!$"

Route115_Text_H6_1::
	.string "Gasp, gasp…$"

Route115_Text_H6_2::
	.string "I made the mistake of trying to\n"
	.string "battle while running!\p"
	.string "I should take a run to calm down…$"

Route115_Text_H7_0::
	.string "Take that!\n"
	.string "Ultra POKéMON ninja attack!$"

Route115_Text_H7_1::
	.string "Waaah!\n"
	.string "Our strategy failed!$"

Route115_Text_H7_2::
	.string "But my POKéMON were ultra,\n"
	.string "weren't they?$"

Route115_Text_H8_0::
	.string "My POKéMON have black belt-level\n"
	.string "strength!$"

Route115_Text_H8_1::
	.string "This is too humiliating!$"

Route115_Text_H8_2::
	.string "I rarely meet anyone who's better\n"
	.string "than me…\p"
	.string "I get it now!\n"
	.string "You're a GYM LEADER, aren't you?$"

Route115_Text_H9_0::
	.string "Our eyes met!\n"
	.string "There's no getting away now!$"

Route115_Text_H9_1::
	.string "Gah!\n"
	.string "Not bad!$"

Route115_Text_H9_2::
	.string "Oh, well.\n"
	.string "I think I will TELEPORT home.$"

Route115_Text_H10_0::
	.string "You've disturbed my meditation…\n"
	.string "You'll be punished for it.$"

Route115_Text_H10_1::
	.string "You've broken my concentration!$"

Route115_Text_H10_2::
	.string "I was meditating with my POKéMON.\n"
	.string "But this place isn't very peaceful…$"

Route115_Text_H11::
	.string "ROUTE 115\n"
	.string "{DOWN_ARROW} RUSTBORO CITY$"

Route115_Text_H12::
	.string "METEOR FALLS\n"
	.string "FALLARBOR TOWN THROUGH HERE$"

