LilycoveCity_DepartmentStore_5F_Text_H0::
	.string "I'm not big enough to raise POKéMON,\n"
	.string "so I'm getting a cute DOLL instead.$"

LilycoveCity_DepartmentStore_5F_Text_H1::
	.string "This place is full of cute DOLLS.\p"
	.string "I should buy some for me, instead of\n"
	.string "just for my children.$"

LilycoveCity_DepartmentStore_5F_Text_H2::
	.string "Welcome!\p"
	.string "How may I serve you?$"

LilycoveCity_DepartmentStore_5F_Text_H3::
	.string "Welcome!\p"
	.string "How may I serve you?$"

LilycoveCity_DepartmentStore_5F_Text_H4::
	.string "Welcome!\p"
	.string "How may I serve you?$"

LilycoveCity_DepartmentStore_5F_Text_H5::
	.string "Welcome!\p"
	.string "How may I serve you?$"

