RustboroCity_Gym_MapScripts::
	.byte 0

RustboroCity_Gym_EventScript_H0::
	msgbox RustboroCity_Gym_Text_H0, MSGBOX_NPC
	end

RustboroCity_Gym_EventScript_H1::
	msgbox RustboroCity_Gym_Text_H1, MSGBOX_NPC
	end

RustboroCity_Gym_EventScript_H2::
	msgbox RustboroCity_Gym_Text_H2, MSGBOX_NPC
	end

RustboroCity_Gym_EventScript_H3::
	msgbox RustboroCity_Gym_Text_H3, MSGBOX_NPC
	end

RustboroCity_Gym_EventScript_H4::
	msgbox RustboroCity_Gym_Text_H4, MSGBOX_NPC
	end

