RustboroCity_Gym_MapScripts::
	.byte 0

RustboroCity_Gym_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_ROXANNE_1, RustboroCity_Gym_Text_H0_0, RustboroCity_Gym_Text_H0_1
	msgbox RustboroCity_Gym_Text_H0_2, MSGBOX_AUTOCLOSE
	end

RustboroCity_Gym_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_JOSH, RustboroCity_Gym_Text_H1_0, RustboroCity_Gym_Text_H1_1
	msgbox RustboroCity_Gym_Text_H1_2, MSGBOX_AUTOCLOSE
	end

RustboroCity_Gym_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_TOMMY, RustboroCity_Gym_Text_H2_0, RustboroCity_Gym_Text_H2_1
	msgbox RustboroCity_Gym_Text_H2_2, MSGBOX_AUTOCLOSE
	end

RustboroCity_Gym_EventScript_H3::
	msgbox RustboroCity_Gym_Text_H3, MSGBOX_NPC
	end

RustboroCity_Gym_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_MARC, RustboroCity_Gym_Text_H4_0, RustboroCity_Gym_Text_H4_1
	msgbox RustboroCity_Gym_Text_H4_2, MSGBOX_AUTOCLOSE
	end

