RustboroCity_Gym_Text_H0_0::
	.string "Hello, I am ROXANNE, the RUSTBORO\n"
	.string "POKéMON GYM LEADER.\p"
	.string "I became a GYM LEADER so that I\n"
	.string "might apply what I learned at the\l"
	.string "POKéMON TRAINER'S SCHOOL in battle.\p"
	.string "Would you kindly demonstrate how\n"
	.string "you battle, and with which POKéMON?$"

RustboroCity_Gym_Text_H0_1::
	.string "So…\n"
	.string "I lost…\p"
	.string "It seems that I still have much more\n"
	.string "to learn…\p"
	.string "I understand.\p"
	.string "The POKéMON LEAGUE's rules state\n"
	.string "that TRAINERS are to be given this\l"
	.string "if they defeat a GYM LEADER.\p"
	.string "Please accept the official POKéMON\n"
	.string "LEAGUE STONE BADGE.$"

RustboroCity_Gym_Text_H0_2::
	.string "Since you are so strong, you should\n"
	.string "challenge other GYM LEADERS.\p"
	.string "By battling many TRAINERS, you\n"
	.string "should learn many things.$"

RustboroCity_Gym_Text_H1_0::
	.string "Don't take us GYM TRAINERS lightly!\n"
	.string "I'll show you why we're better!$"

RustboroCity_Gym_Text_H1_1::
	.string "You were too good for me…$"

RustboroCity_Gym_Text_H1_2::
	.string "You haven't seen anything of the\n"
	.string "ROCK type's terrifying power!$"

RustboroCity_Gym_Text_H2_0::
	.string "If you can't beat me, you won't\n"
	.string "stand a chance against ROXANNE!$"

RustboroCity_Gym_Text_H2_1::
	.string "Wow! You've got some potential!$"

RustboroCity_Gym_Text_H2_2::
	.string "ROXANNE is stronger than me by\n"
	.string "several times.\p"
	.string "You'd better be on your guard!$"

RustboroCity_Gym_Text_H3::
	.string "Yo, how's it going?\p"
	.string "Listen, my friend! Would you like to\n"
	.string "become the CHAMPION?\p"
	.string "I'm no TRAINER, not me, but I can\n"
	.string "sure give you winning advice.\p"
	.string "That's settled, then! We'll aim for\n"
	.string "the POKéMON CHAMPIONSHIP together!\p"
	.string "It's your job as a TRAINER to\n"
	.string "collect GYM BADGES, am I right?\p"
	.string "But GYM LEADERS aren't pushovers!\p"
	.string "And that's where I come in!\n"
	.string "I'm here to provide expert advice!\p"
	.string "ROXANNE, the GYM LEADER, is a user\n"
	.string "of ROCK-type POKéMON.\p"
	.string "The ROCK type is very durable, but\n"
	.string "it can't stand WATER-type and\l"
	.string "GRASS-type moves.\p"
	.string "Come see me afterwards, if you beat\n"
	.string "the GYM LEADER.\p"
	.string "Well, go for it!$"

RustboroCity_Gym_Text_H4_0::
	.string "We might be in the middle of town,\n"
	.string "but so what?\p"
	.string "My ROCK POKéMON need room to\n"
	.string "rampage!$"

RustboroCity_Gym_Text_H4_1::
	.string "Oh, man oh man! Our challenger is\n"
	.string "one feisty customer!$"

RustboroCity_Gym_Text_H4_2::
	.string "I have to hand it to our LEADER.\p"
	.string "It took smarts and sense for her to\n"
	.string "pick the ROCK type at her young\l"
	.string "age.$"

