Route108_MapScripts::
	.byte 0

Route108_EventScript_H0::
	msgbox Route108_Text_H0, MSGBOX_NPC
	end

Route108_EventScript_H1::
	msgbox Route108_Text_H1, MSGBOX_NPC
	end

Route108_EventScript_H2::
	msgbox Route108_Text_H2, MSGBOX_NPC
	end

Route108_EventScript_H3::
	msgbox Route108_Text_H3, MSGBOX_NPC
	end

Route108_EventScript_H4::
	msgbox Route108_Text_H4, MSGBOX_NPC
	end

Route108_EventScript_H5::
	msgbox Route108_Text_H5, MSGBOX_NPC
	end

