Route108_Text_H0_0::
	.string "My dream is to swim the world's\n"
	.string "seven seas!$"

Route108_Text_H0_1::
	.string "I won't be able to swim the seven\n"
	.string "seas like this…$"

Route108_Text_H0_2::
	.string "Playing with marine POKéMON is one\n"
	.string "of the pleasures of swimming!$"

Route108_Text_H1_0::
	.string "My liar of a boyfriend told me that\n"
	.string "I look great in a bikini…$"

Route108_Text_H1_1::
	.string "Oh, boo!$"

Route108_Text_H1_2::
	.string "Even if it's a lie, I love being told\n"
	.string "I look great…\l"
	.string "We girls are so complex…$"

Route108_Text_H2_0::
	.string "Ahoy, there! Are you going out to\n"
	.string "the ABANDONED SHIP, too?$"

Route108_Text_H2_1::
	.string "I'm sinking!\n"
	.string "Glub… Glub…$"

Route108_Text_H2_2::
	.string "Some people even go inside that\n"
	.string "ABANDONED SHIP.$"

Route108_Text_H3_0::
	.string "I love the sea!\n"
	.string "I forget all my worries when I swim!$"

Route108_Text_H3_1::
	.string "When I lose a battle, I get all\n"
	.string "stressed out!$"

Route108_Text_H3_2::
	.string "Work off your stress by swimming!\n"
	.string "It's so healthy!$"

Route108_Text_H4_0::
	.string "I take huge pride in my POKéMON.\n"
	.string "We'll show you one speedy battle!$"

Route108_Text_H4_1::
	.string "That wasn't cute at all.$"

Route108_Text_H4_2::
	.string "Since I'm at sea like this, I\n"
	.string "wouldn't mind putting on a pink,\l"
	.string "frilly swimsuit…$"

Route108_Text_H5_0::
	.string "I love WATER-type POKéMON.\n"
	.string "I love other POKéMON, too!$"

Route108_Text_H5_1::
	.string "Waaah! I lost!\n"
	.string "Waaah! Waaah!$"

Route108_Text_H5_2::
	.string "Shouting is good for me!\n"
	.string "It uplifts me!$"

