Route108_Text_H0::
	.string "Playing with marine POKéMON is one of\n"
	.string "the pleasures of swimming!$"

Route108_Text_H1::
	.string "Even if it's a lie, I love being told\n"
	.string "I look great…\l"
	.string "We girls are so complex…$"

Route108_Text_H2::
	.string "Some people even go inside that\n"
	.string "ABANDONED SHIP.$"

Route108_Text_H3::
	.string "Work off your stress by swimming!\n"
	.string "It's so healthy!$"

Route108_Text_H4::
	.string "Since I'm at sea like this, I wouldn't\n"
	.string "mind putting on a pink, frilly swimsuit…$"

Route108_Text_H5::
	.string "Shouting is good for me!\n"
	.string "It uplifts me!$"

