VerdanturfTown_Mart_Text_H1::
	.string "For any POKéMON match, X SPECIAL\n"
	.string "is crucial.\p"
	.string "It jacks up the power of some moves\n"
	.string "even though it's only for one battle.$"

VerdanturfTown_Mart_Text_H2::
	.string "They don't seem to sell any winning\n"
	.string "strategy guides for the BATTLE\l"
	.string "TENT…\p"
	.string "It seems one must rely on one's\n"
	.string "own wits after all…$"

VerdanturfTown_Mart_Text_H3::
	.string "The NEST BALL works better on\n"
	.string "weakened POKéMON.\p"
	.string "VERDANTURF is the only place you\n"
	.string "can buy it.$"

