AbandonedShip_HiddenFloorCorridors_Text_H0::
    .string "{PLAYER} turned the KEY.\p"
    .string "The lock gave, and the salt took\n"
    .string "the KEY for its trouble.$"

AbandonedShip_HiddenFloorCorridors_Text_H1::
    .string "{PLAYER} turned the KEY.\p"
    .string "The lock gave, and the salt took\n"
    .string "the KEY for its trouble.$"

AbandonedShip_HiddenFloorCorridors_Text_H2::
    .string "{PLAYER} turned the KEY.\p"
    .string "The lock gave, and the salt took\n"
    .string "the KEY for its trouble.$"

AbandonedShip_HiddenFloorCorridors_Text_H3::
    .string "{PLAYER} turned the KEY.\p"
    .string "The lock gave, and the salt took\n"
    .string "the KEY for its trouble.$"
