SlateportCity_Harbor_Text_FlyToKanto::
    .string "Welcome to the SLATEPORT counter\n"
    .string "of the airline to KANTO!\p"
    .string "The flight lands at VERMILION\n"
    .string "AIRPORT. Would you like to board\l"
    .string "now?$"

SlateportCity_Harbor_Text_FlyWarning::
    .string "Flying around HOENN? Your POKéMON\n"
    .string "can take you to any town here\l"
    .string "you've set foot in.\p"
    .string "It won't cross to KANTO, mind.\n"
    .string "For that, board our plane.$"
