Route125_Text_H0::
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_H1::
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_H2::
	.string "Whew…\n"
	.string "Which way is it to MOSSDEEP CITY?$"

Route125_Text_H3::
	.string "Your power… You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_H4::
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_H5::
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE, doesn't he?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_H6::
	.string "IRIS: KIM, are we really going into\n"
	.string "the SHOAL CAVE?\l"
	.string "We'll get all wet.$"

Route125_Text_H7::
	.string "I put a message in a bottle and put\n"
	.string "it out to sea.\p"
	.string "I'm sure that a girl SWIMMER will\n"
	.string "find it!$"

Route125_Text_H8::
	.string "I found an unsightly bottle bobbing\n"
	.string "in the waves earlier.\p"
	.string "It angers me that someone would\n"
	.string "pollute the sea!$"

