Route125_Text_H0_0::
	.string "I heard you approaching, so I hung\n"
	.string "around for you!$"

Route125_Text_H0_1::
	.string "I surrender!$"

Route125_Text_H0_2::
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_H1_0::
	.string "Hey, there!\n"
	.string "Check out my sweet POKéMON!$"

Route125_Text_H1_1::
	.string "I floundered…$"

Route125_Text_H1_2::
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_H2_0::
	.string "I'm tired of swimming.\n"
	.string "Are you up for a battle with me?$"

Route125_Text_H2_1::
	.string "You're too much!$"

Route125_Text_H2_2::
	.string "Whew…\n"
	.string "Which way is it to MOSSDEEP CITY?$"

Route125_Text_H3_0::
	.string "How would you like to take on the\n"
	.string "WATER-type POKéMON I raised?$"

Route125_Text_H3_1::
	.string "Lost it…$"

Route125_Text_H3_2::
	.string "Your power… You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_H4_0::
	.string "Ahoy! I'm a buff, tough SAILOR!\n"
	.string "I've braved the world's seas!$"

Route125_Text_H4_1::
	.string "Gwrroooar!\n"
	.string "I couldn't win!$"

Route125_Text_H4_2::
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_H5_0::
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE. Someone told me.\l"
	.string "Are you going to see him, too?$"

Route125_Text_H5_1::
	.string "KIM: I thought we would win.$"

Route125_Text_H5_2::
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE, doesn't he?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_H6_0::
	.string "IRIS: KIM, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_H6_1::
	.string "IRIS: Oh, we came sort of close.$"

Route125_Text_H6_2::
	.string "IRIS: KIM, are we really going into\n"
	.string "the SHOAL CAVE?\l"
	.string "We'll get all wet.$"

Route125_Text_H7_0::
	.string "Why would a BIRDKEEPER like me\n"
	.string "come out to the sea?$"

Route125_Text_H7_1::
	.string "Okay.\n"
	.string "I'll tell you why I'm here.$"

Route125_Text_H7_2::
	.string "I put a message in a bottle and put\n"
	.string "it out to sea.\p"
	.string "I'm sure that a girl SWIMMER will\n"
	.string "find it!$"

Route125_Text_H8_0::
	.string "Hey! Was it you throwing garbage\n"
	.string "into the sea?$"

Route125_Text_H8_1::
	.string "Oh, you weren't throwing trash into\n"
	.string "the sea.$"

Route125_Text_H8_2::
	.string "I found an unsightly bottle bobbing\n"
	.string "in the waves earlier.\p"
	.string "It angers me that someone would\n"
	.string "pollute the sea!$"

