BattleFrontier_BattlePikeLobby_MapScripts::
	.byte 0

BattleFrontier_BattlePikeLobby_EventScript_H0::
	msgbox BattleFrontier_BattlePikeLobby_Text_H0, MSGBOX_NPC
	end

BattleFrontier_BattlePikeLobby_EventScript_H1::
	msgbox BattleFrontier_BattlePikeLobby_Text_H1, MSGBOX_NPC
	end

BattleFrontier_BattlePikeLobby_EventScript_H2::
	msgbox BattleFrontier_BattlePikeLobby_Text_H2, MSGBOX_NPC
	end

BattleFrontier_BattlePikeLobby_EventScript_H3::
	msgbox BattleFrontier_BattlePikeLobby_Text_H3, MSGBOX_NPC
	end

BattleFrontier_BattlePikeLobby_EventScript_H4::
	msgbox BattleFrontier_BattlePikeLobby_Text_H4, MSGBOX_SIGN
	end

