BattleFrontier_BattlePikeLobby_Text_H0::
	.string "Where the luck of TRAINERS\n"
	.string "is put to the test…\p"
	.string "Welcome to the BATTLE PIKE…\p"
	.string "I am your guide to the BATTLE\n"
	.string "PIKE…$"

BattleFrontier_BattlePikeLobby_Text_H1::
	.string "Arrgh! I blew my chance!\n"
	.string "I was one room away from the goal!\p"
	.string "In this place, you'd better watch\n"
	.string "out for poison, freezing, and so on.$"

BattleFrontier_BattlePikeLobby_Text_H2::
	.string "I've completed the challenge 10\n"
	.string "times now, but I've never had to\l"
	.string "battle a TRAINER once.$"

BattleFrontier_BattlePikeLobby_Text_H3::
	.string "Listen! Listen!\p"
	.string "Don't you think that the special\n"
	.string "abilities of POKéMON will be useful\l"
	.string "here?$"

BattleFrontier_BattlePikeLobby_Text_H4::
	.string "The Battle Choice's rules are listed.$"

