SevenIsland_TanobyRuins_EmbeddedChamber_Text_SeaMural::
    .string "A mural of a huge POKéMON rising\n"
    .string "from a stormy sea.$"

SevenIsland_TanobyRuins_EmbeddedChamber_Text_SeaMuralOrb::
    .string "A mural of a huge POKéMON rising\n"
    .string "from a stormy sea.\p"
    .string "A blue orb is set into the mural.\n"
    .string "Take it?$"

SevenIsland_TanobyRuins_EmbeddedChamber_Text_LandMural::
    .string "A mural of a huge POKéMON standing\n"
    .string "on land that pours with lava.$"

SevenIsland_TanobyRuins_EmbeddedChamber_Text_LandMuralOrb::
    .string "A mural of a huge POKéMON standing\n"
    .string "on land that pours with lava.\p"
    .string "A red orb is set into the mural.\n"
    .string "Take it?$"

SevenIsland_TanobyRuins_EmbeddedChamber_Text_WallMarkings::
    .string "There are strange markings on the\n"
    .string "wall. It seems to be sealed…$"

SevenIsland_TanobyRuins_EmbeddedChamber_Text_BlueOrbGlows::
    .string "The BLUE ORB began to glow…$"

SevenIsland_TanobyRuins_EmbeddedChamber_Text_RedOrbGlows::
    .string "The RED ORB began to glow…$"

SevenIsland_TanobyRuins_EmbeddedChamber_Text_SkyRumbles::
    .string "A roar echoed down from high\n"
    .string "above…$"

SevenIsland_TanobyRuins_EmbeddedChamber_Text_WallSplitOpen::
    .string "The wall split open!$"

SevenIsland_TanobyRuins_EmbeddedChamber_Text_Roar::
    .string "Gyaoooh!$"
