PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice…\p"
    .string "If you're confused, ask for HELP!\n"
    .string "Press the L or R Button!$"

PalletTown_PlayersHouse_2F_Text_TourneyTrophy::
    .string "The CHAMPION TOURNAMENT trophy.\p"
    .string "Every name in the draw is engraved\n"
    .string "on it, and {PLAYER}'s is on top.$"
