SlateportCity_Text_H0::
	.string "Whew… I'm just bushed…\p"
	.string "I hiked over from MAUVILLE CITY.\n"
	.string "But, boy, this city's huge.\p"
	.string "If I'd known this, I would've ridden\n"
	.string "my BIKE here.$"

SlateportCity_Text_H1::
	.string "STERN, the fellow who built the\n"
	.string "MUSEUM, also happens to be the\l"
	.string "leader of an undersea exploration\l"
	.string "team.\p"
	.string "So, everyone calls him CAPT. STERN.$"

SlateportCity_Text_H2::
	.string "Wroooar! I'm going to compete in\n"
	.string "the BATTLE TENT, too!\p"
	.string "But before that, I need to catch\n"
	.string "some POKéMON!$"

SlateportCity_Text_H3::
	.string "What is that over there?\n"
	.string "That long line…$"

SlateportCity_Text_H4::
	.string "Ooh, look at this!\p"
	.string "The seaweed you can get around\n"
	.string "these parts is fresh and full of\l"
	.string "life.\p"
	.string "Why, it looks like it can even rear\n"
	.string "up and attack!$"

SlateportCity_Text_H5::
	.string "Where the water is clean, the fruits\n"
	.string "of bountiful harvest gather.\p"
	.string "And where people gather, a market\n"
	.string "soon starts.\p"
	.string "That is how a town is born and\n"
	.string "grows.$"

SlateportCity_Text_H6::
	.string "Shopping where you can breathe the\n"
	.string "scent of the ocean…\p"
	.string "SLATEPORT is such a wonderful\n"
	.string "place!$"

SlateportCity_Text_H7::
	.string "The sea is just so vast…\p"
	.string "Could the sea have been made by\n"
	.string "the tears shed by POKéMON?$"

SlateportCity_Text_H8::
	.string "Do you know what they do with old\n"
	.string "ships that become too creaky to\l"
	.string "sail?\p"
	.string "They sink them in the sea so they\n"
	.string "become habitats for POKéMON.$"

SlateportCity_Text_H9::
	.string "Whenever I visit here, I get carried\n"
	.string "away and buy too much.$"

SlateportCity_Text_H10::
	.string "Recently, a BATTLE TENT was built\n"
	.string "in SLATEPORT.\p"
	.string "GYMS are fun, but the BATTLE TENT's\n"
	.string "awesome in its own way.\p"
	.string "You should go find tough POKéMON\n"
	.string "for the BATTLE TENT!$"

SlateportCity_Text_H11::
	.string "If you want to change your\n"
	.string "POKéMON's nickname, you'll have to\l"
	.string "get the NAME RATER to help you.$"

SlateportCity_Text_H12::
	.string "Any POKéMON you get in a trade,\n"
	.string "you can't change its nickname.\p"
	.string "The original TRAINER's love for that\n"
	.string "POKéMON is in the nickname.$"

SlateportCity_Text_H13::
	.string "Welcome!\p"
	.string "How may I serve you?$"

SlateportCity_Text_H14::
	.string "Welcome!\p"
	.string "How may I serve you?$"

SlateportCity_Text_H15::
	.string "The light of the lighthouse reaches\n"
	.string "dozens of miles away.\p"
	.string "I wonder if it doesn't startle\n"
	.string "POKéMON in the sea.$"

SlateportCity_Text_H16::
	.string "Oh?\n"
	.string "Your {STR_VAR_1}…$"

SlateportCity_Text_H18::
	.string "If a wild POKéMON gets hurt, it\n"
	.string "heals itself by chewing on BERRIES.\p"
	.string "Did you know that?\p"
	.string "Somebody saw that and got the idea\n"
	.string "of making medicine from BERRIES.\p"
	.string "Did you know that?\p"
	.string "To turn BERRIES into medicine,\n"
	.string "they must be crushed into powder.\p"
	.string "Did you know that?\p"
	.string "You seem to have an interest\n"
	.string "in BERRIES!\p"
	.string "I've got something good for someone\n"
	.string "like you.$"

SlateportCity_Text_H19::
	.string "NAME RATER'S HOUSE\n"
	.string "“POKéMON nicknames rated.”$"

SlateportCity_Text_H20::
	.string "SLATEPORT HARBOR\p"
	.string "“The ferry S.S. TIDAL is under\n"
	.string "construction in the SHIPYARD.\p"
	.string "“Service is scheduled to begin\n"
	.string "shortly.”$"

SlateportCity_Text_H21::
	.string "SLATEPORT MARKET\n"
	.string "“Unique items found nowhere else!”$"

SlateportCity_Text_H22::
	.string "“The endless sea sustains\n"
	.string "all life.”\p"
	.string "OCEANIC MUSEUM$"

SlateportCity_Text_H23::
	.string "SLATEPORT CITY\p"
	.string "“The port where people and POKéMON\n"
	.string "cross paths.”$"

SlateportCity_Text_H24::
	.string "POKéMON FAN CLUB\n"
	.string "“Calling all fans of POKéMON!”$"

SlateportCity_Text_H25::
	.string "BATTLE TENT SLATEPORT SITE\n"
	.string "“Find it! The ultimate POKéMON!”$"

SlateportCity_Text_H26::
	.string "STERN'S SHIPYARD\p"
	.string "“Wanted: A sailor capable of sailing\n"
	.string "in all currents.”$"

