LilycoveCity_PokemonTrainerFanClub_Text_H0::
	.string "I can't help it, I can only get to\n"
	.string "like BRAWLY…$"

LilycoveCity_PokemonTrainerFanClub_Text_H1::
	.string "I hate to say this, but the TRAINER\n"
	.string "everybody's talking about is\l"
	.string "{STR_VAR_1}, no question about it!\p"
	.string "That TRAINER's power…\n"
	.string "It's out of the ordinary.$"

LilycoveCity_PokemonTrainerFanClub_Text_H2::
	.string "NORMAN battled with more power,\n"
	.string "charisma, and showmanship than you.\p"
	.string "Even though people may say that\n"
	.string "you're strong…\p"
	.string "You've still got a long way to go\n"
	.string "compared to your father.$"

LilycoveCity_PokemonTrainerFanClub_Text_H3::
	.string "{STR_VAR_1} is really cool…\p"
	.string "Everyone thinks so, right, right?$"

