Route102_Text_H0::
	.string "I'm…not very tall, so I sink right\n"
	.string "into tall grass.\p"
	.string "The grass goes up my nose and…\n"
	.string "Fwafwafwafwafwa…\p"
	.string "Fwatchoo!$"

Route102_Text_H1::
	.string "Listen, you. If you're strong,\n"
	.string "you should have told me before!$"

Route102_Text_H2::
	.string "If you lock eyes with a TRAINER,\n"
	.string "you have to challenge! It's a rule!$"

Route102_Text_H3::
	.string "To keep winning my way up, I see that\n"
	.string "I have to catch more POKéMON.$"

Route102_Text_H4::
	.string "I'm going to catch a whole bunch of\n"
	.string "POKéMON!$"

Route102_Text_H5::
	.string "I haven't won once yet…\n"
	.string "I wish I would win soon…$"

Route102_Text_H6::
	.string "ROUTE 102\n"
	.string "{LEFT_ARROW} PETALBURG CITY$"

Route102_Text_H7::
	.string "ROUTE 102\n"
	.string "{RIGHT_ARROW} OLDALE TOWN$"

