Route102_Text_H0::
	.string "I'm…not very tall, so I sink right\n"
	.string "into tall grass.\p"
	.string "The grass goes up my nose and…\n"
	.string "Fwafwafwafwafwa…\p"
	.string "Fwatchoo!$"

Route102_Text_H1_0::
	.string "If you have POKéMON with you, then\n"
	.string "you're an official POKéMON TRAINER!\l"
	.string "You can't say no to my challenge!$"

Route102_Text_H1_1::
	.string "Arrgh, I lost…\n"
	.string "I should have trained mine more…$"

Route102_Text_H1_2::
	.string "Listen, you. If you're strong,\n"
	.string "you should have told me before!$"

Route102_Text_H2_0::
	.string "Hahah! Our eyes met! I'll take you\n"
	.string "on with my BUG POKéMON!$"

Route102_Text_H2_1::
	.string "Ow! Down and out!$"

Route102_Text_H2_2::
	.string "If you lock eyes with a TRAINER,\n"
	.string "you have to challenge! It's a rule!$"

Route102_Text_H3_0::
	.string "I'm going to keep winning and aim\n"
	.string "to be the best TRAINER.\p"
	.string "Help me further my career!$"

Route102_Text_H3_1::
	.string "I ended up furthering your career…$"

Route102_Text_H3_2::
	.string "To keep winning my way up, I see\n"
	.string "that I have to catch more POKéMON.$"

Route102_Text_H4::
	.string "I'm going to catch a whole bunch of\n"
	.string "POKéMON!$"

Route102_Text_H5_0::
	.string "Did you just become a TRAINER?\n"
	.string "We're both beginners!$"

Route102_Text_H5_1::
	.string "I called you because I thought\n"
	.string "I could beat you…$"

Route102_Text_H5_2::
	.string "I haven't won once yet…\n"
	.string "I wish I would win soon…$"

Route102_Text_H6::
	.string "ROUTE 102\n"
	.string "{LEFT_ARROW} PETALBURG CITY$"

Route102_Text_H7::
	.string "ROUTE 102\n"
	.string "{RIGHT_ARROW} OLDALE TOWN$"

