Route105_Text_H0::
	.string "If you are drowning, the signal is to\n"
	.string "wave one arm toward the beach.$"

Route105_Text_H1::
	.string "Why is the sea blue?\p"
	.string "I learned about that at the MUSEUM in\n"
	.string "SLATEPORT, but I forgot.$"

Route105_Text_H2::
	.string "Your body weight is reduced to just\n"
	.string "one tenth in the water.\p"
	.string "That would make me…\n"
	.string "Whoops! I'm not telling you my weight!$"

Route105_Text_H3::
	.string "I want to be told I'm relaxing to be\n"
	.string "with. Giggle.$"

Route105_Text_H4::
	.string "I can spend hours and hours staring\n"
	.string "at a nice rock without growing bored.$"

Route105_Text_H5::
	.string "Yeah, for me, the sky is a much better\n"
	.string "match than the sea.$"

Route105_Text_H6::
	.string "I'm sure there are many secrets to be\n"
	.string "discovered in the world's seas.\p"
	.string "I mean to find them all!$"

