Route105_Text_H0_0::
	.string "Whew! I was worried that a kid was\n"
	.string "drowning when I saw you.\p"
	.string "You seem to be okay, so what do you\n"
	.string "say to a battle?$"

Route105_Text_H0_1::
	.string "Glub… Glub…$"

Route105_Text_H0_2::
	.string "If you are drowning, the signal is to\n"
	.string "wave one arm toward the beach.$"

Route105_Text_H1_0::
	.string "Swimming the deep blue sea…\n"
	.string "It feels the greatest!$"

Route105_Text_H1_1::
	.string "I lost…\n"
	.string "Now I'm feeling blue…$"

Route105_Text_H1_2::
	.string "Why is the sea blue?\p"
	.string "I learned about that at the MUSEUM in\n"
	.string "SLATEPORT, but I forgot.$"

Route105_Text_H2_0::
	.string "My body feels lighter in the water.\n"
	.string "It's as if I've gotten slimmer!$"

Route105_Text_H2_1::
	.string "I'm floating…$"

Route105_Text_H2_2::
	.string "Your body weight is reduced to just\n"
	.string "one tenth in the water.\p"
	.string "That would make me…\n"
	.string "Whoops! I'm not telling you my weight!$"

Route105_Text_H3_0::
	.string "The blue, blue sky…\n"
	.string "The vast sea…\l"
	.string "It's so peaceful…$"

Route105_Text_H3_1::
	.string "I lost while I was lounging!$"

Route105_Text_H3_2::
	.string "I want to be told I'm relaxing to be\n"
	.string "with. Giggle.$"

Route105_Text_H4_0::
	.string "There's supposed to be a mystical\n"
	.string "rock around here.\l"
	.string "Do you know anything about it?$"

Route105_Text_H4_1::
	.string "I was thinking too much about that\n"
	.string "rock, while my POKéMON remained weak…$"

Route105_Text_H4_2::
	.string "I can spend hours and hours staring\n"
	.string "at a nice rock without growing bored.$"

Route105_Text_H5_0::
	.string "I'm exhausted from swimming.\n"
	.string "I'm just not used to it.\p"
	.string "I need a battle for a change of pace!$"

Route105_Text_H5_1::
	.string "I lost because I battled at sea.$"

Route105_Text_H5_2::
	.string "Yeah, for me, the sky is a much better\n"
	.string "match than the sea.$"

Route105_Text_H6_0::
	.string "I'm convinced that the sea keeps\n"
	.string "secrets from us.$"

Route105_Text_H6_1::
	.string "Yes…\n"
	.string "I am no good at battling…$"

Route105_Text_H6_2::
	.string "I'm sure there are many secrets to be\n"
	.string "discovered in the world's seas.\p"
	.string "I mean to find them all!$"

