VerdanturfTown_House_Text_H0::
	.string "Far away, deep in EVER GRANDE CITY,\n"
	.string "is the POKéMON LEAGUE.\p"
	.string "The TRAINERS who gather there are\n"
	.string "all frighteningly well skilled.$"

VerdanturfTown_House_Text_H1::
	.string "In the POKéMON LEAGUE, I think the\n"
	.string "rules say that you have to battle\l"
	.string "the ELITE FOUR all in a row.\p"
	.string "If you lose to any of them, you\n"
	.string "have to begin your challenge again\l"
	.string "from the first one.$"

