BattleFrontier_Lounge2_MapScripts::
	.byte 0

BattleFrontier_Lounge2_EventScript_H0::
	msgbox BattleFrontier_Lounge2_Text_H0, MSGBOX_NPC
	end

BattleFrontier_Lounge2_EventScript_H1::
	msgbox BattleFrontier_Lounge2_Text_H1, MSGBOX_NPC
	end

BattleFrontier_Lounge2_EventScript_H2::
	msgbox BattleFrontier_Lounge2_Text_H2, MSGBOX_NPC
	end

BattleFrontier_Lounge2_EventScript_H3::
	msgbox BattleFrontier_Lounge2_Text_H3, MSGBOX_NPC
	end

BattleFrontier_Lounge2_EventScript_H4::
	msgbox BattleFrontier_Lounge2_Text_H4, MSGBOX_NPC
	end

