Route104_MapScripts::
	.byte 0

Route104_EventScript_H0::
	msgbox Route104_Text_H0, MSGBOX_NPC
	end

Route104_EventScript_H1::
	msgbox Route104_Text_H1, MSGBOX_NPC
	end

Route104_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_HALEY_1, Route104_Text_H2_0, Route104_Text_H2_1
	msgbox Route104_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route104_EventScript_H3::
	msgbox Route104_Text_H3, MSGBOX_NPC
	end

Route104_EventScript_H4::
	msgbox Route104_Text_H4, MSGBOX_NPC
	end

Route104_EventScript_H5::
	msgbox Route104_Text_H5, MSGBOX_NPC
	end

Route104_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_IVAN, Route104_Text_H6_0, Route104_Text_H6_1
	msgbox Route104_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route104_EventScript_H7::
	msgbox Route104_Text_H7, MSGBOX_NPC
	end

Route104_EventScript_HItem9::
	finditem ITEM_PP_UP
	end

Route104_EventScript_H8::
	trainerbattle_double TRAINER_HOENN_GINA_AND_MIA_1, Route104_Text_H8_0, Route104_Text_H8_1, Route104_Text_H8_1
	msgbox Route104_Text_H8_2, MSGBOX_AUTOCLOSE
	end

Route104_EventScript_H9::
	trainerbattle_double TRAINER_HOENN_GINA_AND_MIA_1, Route104_Text_H9_0, Route104_Text_H9_1, Route104_Text_H9_1
	msgbox Route104_Text_H9_2, MSGBOX_AUTOCLOSE
	end

Route104_EventScript_H10::
	trainerbattle_single TRAINER_HOENN_WINSTON_1, Route104_Text_H10_0, Route104_Text_H10_1
	msgbox Route104_Text_H10_2, MSGBOX_AUTOCLOSE
	end

Route104_EventScript_H11::
	trainerbattle_single TRAINER_HOENN_CINDY_1, Route104_Text_H11_0, Route104_Text_H11_1
	msgbox Route104_Text_H11_2, MSGBOX_AUTOCLOSE
	end

Route104_EventScript_HItem10::
	finditem ITEM_POKE_BALL
	end

Route104_EventScript_H12::
	trainerbattle_single TRAINER_HOENN_BILLY, Route104_Text_H12_0, Route104_Text_H12_1
	msgbox Route104_Text_H12_2, MSGBOX_AUTOCLOSE
	end

Route104_EventScript_HItem11::
	finditem ITEM_X_ACCURACY
	end

Route104_EventScript_HItem12::
	finditem ITEM_POTION
	end

Route104_EventScript_H13::
	msgbox Route104_Text_H13, MSGBOX_NPC
	end

Route104_EventScript_H14::
	trainerbattle_single TRAINER_HOENN_DARIAN, Route104_Text_H14_0, Route104_Text_H14_1
	msgbox Route104_Text_H14_2, MSGBOX_AUTOCLOSE
	end

Route104_EventScript_H15::
	msgbox Route104_Text_H15, MSGBOX_SIGN
	end

Route104_EventScript_H16::
	msgbox Route104_Text_H16, MSGBOX_SIGN
	end

Route104_EventScript_H17::
	msgbox Route104_Text_H17, MSGBOX_SIGN
	end

Route104_EventScript_H18::
	msgbox Route104_Text_H18, MSGBOX_SIGN
	end

Route104_EventScript_H19::
	msgbox Route104_Text_H19, MSGBOX_SIGN
	end

