Route104_Text_H0::
	.string "The sea, huh?\p"
	.string "I wonder what it's like at the bottom\n"
	.string "of the sea?$"

Route104_Text_H1::
	.string "That seaside cottage is where\n"
	.string "MR. BRINEY lives.\p"
	.string "He was once a mighty sailor who\n"
	.string "never feared the sea, however\l"
	.string "stormy.$"

Route104_Text_H2_0::
	.string "Should I…\n"
	.string "Or shouldn't I?\p"
	.string "Okay, sure, I will battle!$"

Route104_Text_H2_1::
	.string "I shouldn't have battled…$"

Route104_Text_H2_2::
	.string "If you're faced with a decision and\n"
	.string "you let someone else choose for\l"
	.string "you, you will regret it, however\l"
	.string "things turn out.$"

Route104_Text_H3::
	.string "If you're going to throw a POKé\n"
	.string "BALL, weaken the wild POKéMON first.\p"
	.string "It will be easier to catch if it's\n"
	.string "been poisoned, burned, or lulled to\l"
	.string "sleep.$"

Route104_Text_H4::
	.string "You're a thief if you try to steal\n"
	.string "someone else's POKéMON.\p"
	.string "You should throw POKé BALLS only at\n"
	.string "wild POKéMON.$"

Route104_Text_H5::
	.string "Oh, no, I'm not a TRAINER.\p"
	.string "But that's right, if TRAINERS lock\n"
	.string "eyes, it's a challenge to battle.\p"
	.string "If you don't want to battle, stay\n"
	.string "out of their sight.$"

Route104_Text_H6_0::
	.string "Why keep it a secret?\n"
	.string "I'm the WATER POKéMON expert!\p"
	.string "Huh?\n"
	.string "You don't know me?$"

Route104_Text_H6_1::
	.string "I thought I wasn't too bad, if I may\n"
	.string "say so, but I guess not… Bleah…$"

Route104_Text_H6_2::
	.string "I got too into fishing.\n"
	.string "I forgot I had to raise my POKéMON…$"

Route104_Text_H7::
	.string "If you see BERRIES growing in loamy\n"
	.string "soil, feel free to take them.\p"
	.string "But make sure you plant a BERRY in\n"
	.string "the same spot. That's common\l"
	.string "courtesy.\p"
	.string "Here, I'll share this with you.$"

Route104_Text_H8_0::
	.string "GINA: Okay, let's battle with our\n"
	.string "POKéMON!$"

Route104_Text_H8_1::
	.string "GINA: Losing upsets me!$"

Route104_Text_H8_2::
	.string "GINA: You are strong!\n"
	.string "We have to train lots more!$"

Route104_Text_H9_0::
	.string "MIA: We are twins, so we battle\n"
	.string "POKéMON together.$"

Route104_Text_H9_1::
	.string "MIA: We battled together, but we\n"
	.string "both lost…$"

Route104_Text_H9_2::
	.string "MIA: We will train our POKéMON more\n"
	.string "and be strong like you.$"

Route104_Text_H10_0::
	.string "Oh, sure, I'll accept your\n"
	.string "challenge. I have a lot of money.$"

Route104_Text_H10_1::
	.string "Why couldn't I win?$"

Route104_Text_H10_2::
	.string "There are some things money can't\n"
	.string "buy. That's POKéMON…$"

Route104_Text_H11_0::
	.string "We must have been fated to meet.\n"
	.string "May I ask you for a battle?$"

Route104_Text_H11_1::
	.string "Oh, my!$"

Route104_Text_H11_2::
	.string "“Hello” is the beginning of\n"
	.string "“good-bye.” I hope we meet again.$"

Route104_Text_H12_0::
	.string "Leaving footprints in the sand is\n"
	.string "so fun!$"

Route104_Text_H12_1::
	.string "Waah! I got sand in my runners!\n"
	.string "They're all gritty!$"

Route104_Text_H12_2::
	.string "I want to leave my footprints in\n"
	.string "the sand everywhere, but they\l"
	.string "disappear quickly…$"

Route104_Text_H13::
	.string "I like filling my mouth with seeds,\n"
	.string "then spitting them out fast!\p"
	.string "You can have this, so you try it\n"
	.string "out!\p"
	.string "Use it on a POKéMON, and it will\n"
	.string "learn a move for firing seeds\l"
	.string "rapidly.$"

Route104_Text_H14_0::
	.string "I fished up a tough-looking\n"
	.string "POKéMON!\p"
	.string "It has this magical quality to it!\n"
	.string "It surely looks tough, yes it does!$"

Route104_Text_H14_1::
	.string "What the…$"

Route104_Text_H14_2::
	.string "Hey, MAGIKARP, you sure don't live\n"
	.string "up to your name, do you?$"

Route104_Text_H15::
	.string "MR. BRINEY'S COTTAGE$"

Route104_Text_H16::
	.string "ROUTE 1O4\n"
	.string "{RIGHT_ARROW} PETALBURG CITY$"

Route104_Text_H17::
	.string "ROUTE 1O4\n"
	.string "{UP_ARROW} RUSTBORO CITY$"

Route104_Text_H18::
	.string "PRETTY PETAL FLOWER SHOP$"

Route104_Text_H19::
	.string "TRAINER TIPS\p"
	.string "In the HOENN region there are pairs\n"
	.string "of TRAINERS who challenge others\l"
	.string "for 2-on-2 POKéMON battles called\l"
	.string "DOUBLE BATTLES.\p"
	.string "In a DOUBLE BATTLE, the TRAINER\n"
	.string "must send out two POKéMON, the one\l"
	.string "at the left of the list and the top\l"
	.string "one. Watch how POKéMON are lined\l"
	.string "up.$"

