CeruleanCave_B1F_Text_Mew::
    .string "Mew!$"


CeruleanCave_B1F_Text_AShadowStandsThere::
    .string "A dark shadow stands where\n"
    .string "MEWTWO used to be…$"

CeruleanCave_B1F_Text_ShadowACloneStrongerThanMe::
    .string "…A clone stronger than I?\p"
    .string "Humans do tell such foolish\n"
    .string "stories.\p"
    .string "There is no MEW3.\n"
    .string "There is only what you caught.$"

CeruleanCave_B1F_Text_TheShadowVanished::
    .string "The shadow faded into the dark…$"

CeruleanCave_B1F_Text_CapsuleShardsScattered::
    .string "Shards of a cracked capsule are\n"
    .string "scattered on the ground.$"

CeruleanCave_B1F_Text_JustARumorAfterAll::
    .string "There is nothing else here.\n"
    .string "MEW3 was just a rumor after all.$"
