Route110_TrickHousePuzzle8_Text_H0_0::
	.string "Not many TRAINERS have made it\n"
	.string "this far.$"

Route110_TrickHousePuzzle8_Text_H0_1::
	.string "That must mean you're tough, too…$"

Route110_TrickHousePuzzle8_Text_H0_2::
	.string "You've beaten the POKéMON LEAGUE\n"
	.string "CHAMPION? That's too much!$"

Route110_TrickHousePuzzle8_Text_H1_0::
	.string "You've been slugging through the\n"
	.string "TRICK HOUSE challenge, too.$"

Route110_TrickHousePuzzle8_Text_H1_1::
	.string "I see…\n"
	.string "You possess an extraordinary style.$"

Route110_TrickHousePuzzle8_Text_H1_2::
	.string "Seeing someone like you should\n"
	.string "please the TRICK MASTER.$"

Route110_TrickHousePuzzle8_Text_H2_0::
	.string "Consider yourself lucky to be\n"
	.string "battling me!$"

Route110_TrickHousePuzzle8_Text_H2_1::
	.string "This isn't right!\n"
	.string "I can't lose!$"

Route110_TrickHousePuzzle8_Text_H2_2::
	.string "It's a miracle that you beat me.\n"
	.string "You can brag about it.$"

