SootopolisCity_PokemonCenter_1F_MapScripts::
	.byte 0

SootopolisCity_PokemonCenter_1F_EventScript_H0::
	msgbox SootopolisCity_PokemonCenter_1F_Text_H0, MSGBOX_NPC
	end

SootopolisCity_PokemonCenter_1F_EventScript_H1::
	msgbox SootopolisCity_PokemonCenter_1F_Text_H1, MSGBOX_NPC
	end

SootopolisCity_PokemonCenter_1F_EventScript_H2::
	msgbox SootopolisCity_PokemonCenter_1F_Text_H2, MSGBOX_NPC
	end

