SootopolisCity_PokemonCenter_1F_Text_H0::
	.string "Everyone in town has taken refuge\n"
	.string "and won't come out of their homes.\p"
	.string "Even I would rather not venture\n"
	.string "outside.$"

SootopolisCity_PokemonCenter_1F_Text_H1::
	.string "Aren't POKéMON our friends?\p"
	.string "Why are they going wild this way?$"

SootopolisCity_PokemonCenter_1F_Text_H2::
	.string "Sigh…\p"
	.string "SOOTOPOLIS's GYM LEADER is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a DOUBLE-EDGE.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your POKéMON\n"
	.string "the move DOUBLE-EDGE!$"

