Route124_Text_H0_0::
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON,\n"
	.string "I can serve as your pilot.$"

Route124_Text_H0_1::
	.string "I lost my bearings in battle!$"

Route124_Text_H0_2::
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the POKéNAV's MAP.$"

Route124_Text_H1_0::
	.string "Hm! You're riding a POKéMON instead\n"
	.string "of swimming yourself…\p"
	.string "I am envious!$"

Route124_Text_H1_1::
	.string "Oh!\n"
	.string "I can't…$"

Route124_Text_H1_2::
	.string "I'm getting chilled…\n"
	.string "I've been in the water too long…\p"
	.string "I wish I could ride a POKéMON like you…$"

Route124_Text_H2_0::
	.string "If you just float in the sea like\n"
	.string "this, POKéMON come around to play.$"

Route124_Text_H2_1::
	.string "Oh, darn.\n"
	.string "I've gone and lost.$"

Route124_Text_H2_2::
	.string "While swimming, I noticed that some\n"
	.string "POKéMON attack, and some just watch.\p"
	.string "I guess POKéMON have personalities\n"
	.string "of their own.$"

Route124_Text_H3_0::
	.string "I'm growing bored of swimming…\n"
	.string "How about a battle?$"

Route124_Text_H3_1::
	.string "I had no idea that you were\n"
	.string "this strong!$"

Route124_Text_H3_2::
	.string "All the effort you put in must have\n"
	.string "made you this strong.$"

Route124_Text_H4_0::
	.string "Fufufufu… I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Plumbing the depths is where I excel!$"

Route124_Text_H4_1::
	.string "Glub, glub, glub…\n"
	.string "I'm sinking…$"

Route124_Text_H4_2::
	.string "I have it on good authority that\n"
	.string "there's a DIVE spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again…$"

Route124_Text_H5_0::
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I won't have to dwell\n"
	.string "on that!$"

Route124_Text_H5_1::
	.string "LILA: ROY! It's your fault we lost!\n"
	.string "You're in for it later!$"

Route124_Text_H5_2::
	.string "LILA: Sigh…\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a nice boyfriend…$"

Route124_Text_H6_0::
	.string "ROY: My big sister is tough at POKéMON!\p"
	.string "Don't cry when you lose!$"

Route124_Text_H6_1::
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out…$"

Route124_Text_H6_2::
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_H7_0::
	.string "Here I am swimming by my lonesome\n"
	.string "on this wide, beautiful sea.\p"
	.string "There's no other word for it.\n"
	.string "This is pathetic!$"

Route124_Text_H7_1::
	.string "I'm feeling blue.\n"
	.string "Blue as the sky…$"

Route124_Text_H7_2::
	.string "I should chat up lady SWIMMERS\n"
	.string "and invite them on a long swim.$"

Route124_Text_H8_0::
	.string "I'm not going to lose to some\n"
	.string "surfer TRAINER.$"

Route124_Text_H8_1::
	.string "I've only got sweat in my eyes!\n"
	.string "I am not crying!$"

Route124_Text_H8_2::
	.string "You can find pretty colored shards\n"
	.string "of things around here.$"

Route124_Text_H9::
	.string "HUNTER'S HOUSE$"

