Route109_Text_H0::
	.string "Hiyah!\p"
	.string "My sculpted abs have nothing to do\n"
	.string "with POKéMON battles!$"

Route109_Text_H1::
	.string "Cheeks are the most prone to burning!$"

Route109_Text_H2::
	.string "In the best port was the best\n"
	.string "TRAINER…$"

Route109_Text_H3::
	.string "I'm usually stronger than this!\n"
	.string "I'm just seasick as a dog!\p"
	.string "I'm a SAILOR, but…$"

Route109_Text_H4::
	.string "I'm getting famished… My inner tube\n"
	.string "looks like a giant doughnut…$"

Route109_Text_H5::
	.string "If you look at the beach from the sky,\n"
	.string "it looks like a big flower garden!$"

Route109_Text_H6::
	.string "Yo, TRAINERS!\n"
	.string "Whether you're hot to trot,\l"
	.string "or cool cat not,\l"
	.string "chill at my papa's spot!$"

Route109_Text_H7::
	.string "How did you get to be so strong?$"

Route109_Text_H8::
	.string "My inner tube is a fashion item.\n"
	.string "I can't be seen without it.$"

Route109_Text_H9::
	.string "This dude thinks you're a big one.\n"
	.string "No, you're a big-one-to-be!$"

Route109_Text_H10::
	.string "Our sand castle's taking a long time\n"
	.string "to make.$"

Route109_Text_H11::
	.string "You can have this!$"

Route109_Text_H12::
	.string "Little kids can dart around so quickly…\p"
	.string "You don't dare take your eyes off them\n"
	.string "for an instant. It's very taxing.\p"
	.string "Mine are with my POKéMON, so they\n"
	.string "should be okay, but…$"

Route109_Text_H13::
	.string "MEL: Um, PAUL, are you angry with me?\n"
	.string "Please don't be angry.$"

Route109_Text_H14::
	.string "PAUL: Well, don't tell anyone that\n"
	.string "we're here.\l"
	.string "This is just our private world of two!$"

Route109_Text_H15::
	.string "The water around these parts is clean.\p"
	.string "But, I get my ZIGZAGOON to pick up\n"
	.string "litter from the shoreline at times.\p"
	.string "Dirty water becomes rain and joins our\n"
	.string "rivers, which we drink from…\p"
	.string "If we pollute the sea, it all comes\n"
	.string "back to haunt us eventually.$"

Route109_Text_H16::
	.string "ZIGZAGOON: Guguu?$"

Route109_Text_H17::
	.string "When I learn how to swim, I think\n"
	.string "my POKéMON will become tougher.$"

Route109_Text_H18::
	.string "After I showed you my round inner\n"
	.string "tube, too…$"

Route109_Text_H19::
	.string "For a guy as macho as me, a port\n"
	.string "is the perfect setting!\p"
	.string "I guess I'll head for SLATEPORT.$"

Route109_Text_H20::
	.string "SEASHORE HOUSE\p"
	.string "“May hot battles rage on hot sands!\n"
	.string "The place for hot TRAINERS!”$"

Route109_Text_H21::
	.string "TRAINER TIPS\p"
	.string "POKéMON at the same level may not\n"
	.string "always have identical stats.\p"
	.string "POKéMON raised by TRAINERS are said\n"
	.string "to grow stronger than wild POKéMON.$"

