Route109_Text_H0_0::
	.string "Hiyah! Look at my chiseled abs!\n"
	.string "This is what you call “cut”!$"

Route109_Text_H0_1::
	.string "Aiyah!\n"
	.string "Flubbed out!$"

Route109_Text_H0_2::
	.string "Hiyah!\p"
	.string "My sculpted abs have nothing to do\n"
	.string "with POKéMON battles!$"

Route109_Text_H1_0::
	.string "Are you properly protected against\n"
	.string "the sun?$"

Route109_Text_H1_1::
	.string "Ouch, ouch, ouch!$"

Route109_Text_H1_2::
	.string "Cheeks are the most prone to burning!$"

Route109_Text_H2_0::
	.string "I've laid anchor in ports around\n"
	.string "the world, but SLATEPORT's the best.$"

Route109_Text_H2_1::
	.string "You're the best!$"

Route109_Text_H2_2::
	.string "In the best port was the best\n"
	.string "TRAINER…$"

Route109_Text_H3_0::
	.string "Urrrrppp…\n"
	.string "Battle? With me?$"

Route109_Text_H3_1::
	.string "Urp… Ooooooohhhhhh…\n"
	.string "Urrrrpppp…$"

Route109_Text_H3_2::
	.string "I'm usually stronger than this!\n"
	.string "I'm just seasick as a dog!\p"
	.string "I'm a SAILOR, but…$"

Route109_Text_H4_0::
	.string "I'm thirsty… I could go for a SODA POP\n"
	.string "at the SEASHORE HOUSE…$"

Route109_Text_H4_1::
	.string "Groan…$"

Route109_Text_H4_2::
	.string "I'm getting famished… My inner tube\n"
	.string "looks like a giant doughnut…$"

Route109_Text_H5_0::
	.string "Doesn't a beach umbrella look like\n"
	.string "a giant flower?$"

Route109_Text_H5_1::
	.string "Mommy!$"

Route109_Text_H5_2::
	.string "If you look at the beach from the sky,\n"
	.string "it looks like a big flower garden!$"

Route109_Text_H6::
	.string "Yo, TRAINERS!\n"
	.string "Whether you're hot to trot,\l"
	.string "or cool cat not,\l"
	.string "chill at my papa's spot!$"

Route109_Text_H7_0::
	.string "Hi, big TRAINER.\n"
	.string "Will you battle with me?$"

Route109_Text_H7_1::
	.string "Oh, you're strong.$"

Route109_Text_H7_2::
	.string "How did you get to be so strong?$"

Route109_Text_H8_0::
	.string "I can't swim without my inner tube,\n"
	.string "but I won't lose at POKéMON!$"

Route109_Text_H8_1::
	.string "Did I lose because I have an inner\n"
	.string "tube?$"

Route109_Text_H8_2::
	.string "My inner tube is a fashion item.\n"
	.string "I can't be seen without it.$"

Route109_Text_H9_0::
	.string "Wahahah! This dude's going to catch\n"
	.string "himself a big one!$"

Route109_Text_H9_1::
	.string "This dude just lost one…$"

Route109_Text_H9_2::
	.string "This dude thinks you're a big one.\n"
	.string "No, you're a big-one-to-be!$"

Route109_Text_H10::
	.string "Our sand castle's taking a long time\n"
	.string "to make.$"

Route109_Text_H11::
	.string "You can have this!$"

Route109_Text_H12::
	.string "Little kids can dart around so quickly…\p"
	.string "You don't dare take your eyes off them\n"
	.string "for an instant. It's very taxing.\p"
	.string "Mine are with my POKéMON, so they\n"
	.string "should be okay, but…$"

Route109_Text_H13_0::
	.string "MEL: We're, like, totally in love.\n"
	.string "Our romance is heating up all of HOENN!$"

Route109_Text_H13_1::
	.string "MEL: We lost, and it's my fault!\n"
	.string "PAUL will hate me!$"

Route109_Text_H13_2::
	.string "MEL: Um, PAUL, are you angry with me?\n"
	.string "Please don't be angry.$"

Route109_Text_H14_0::
	.string "PAUL: Well, this is a mood-breaker.\p"
	.string "I wish you wouldn't disturb our\n"
	.string "precious time together.$"

Route109_Text_H14_1::
	.string "PAUL: Well, I give up.$"

Route109_Text_H14_2::
	.string "PAUL: Well, don't tell anyone that\n"
	.string "we're here.\l"
	.string "This is just our private world of two!$"

Route109_Text_H15::
	.string "The water around these parts is clean.\p"
	.string "But, I get my ZIGZAGOON to pick up\n"
	.string "litter from the shoreline at times.\p"
	.string "Dirty water becomes rain and joins our\n"
	.string "rivers, which we drink from…\p"
	.string "If we pollute the sea, it all comes\n"
	.string "back to haunt us eventually.$"

Route109_Text_H16::
	.string "ZIGZAGOON: Guguu?$"

Route109_Text_H17_0::
	.string "I can't swim, so I'm pretending\n"
	.string "to swim.$"

Route109_Text_H17_1::
	.string "I thought so!\n"
	.string "I didn't think we could win.$"

Route109_Text_H17_2::
	.string "When I learn how to swim, I think\n"
	.string "my POKéMON will become tougher.$"

Route109_Text_H18_0::
	.string "Tadaah! See?\n"
	.string "My inner tube's round!$"

Route109_Text_H18_1::
	.string "Oh, oh!\n"
	.string "Too bad!$"

Route109_Text_H18_2::
	.string "After I showed you my round inner\n"
	.string "tube, too…$"

Route109_Text_H19_0::
	.string "For a guy as macho as me, this kind\n"
	.string "of POKéMON is the perfect match!$"

Route109_Text_H19_1::
	.string "I'm cool even in defeat, hey?$"

Route109_Text_H19_2::
	.string "For a guy as macho as me, a port\n"
	.string "is the perfect setting!\p"
	.string "I guess I'll head for SLATEPORT.$"

Route109_Text_H20::
	.string "SEASHORE HOUSE\p"
	.string "“May hot battles rage on hot sands!\n"
	.string "The place for hot TRAINERS!”$"

Route109_Text_H21::
	.string "TRAINER TIPS\p"
	.string "POKéMON at the same level may not\n"
	.string "always have identical stats.\p"
	.string "POKéMON raised by TRAINERS are said\n"
	.string "to grow stronger than wild POKéMON.$"

