Route123_MapScripts::
	.byte 0

Route123_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_WENDY, Route123_Text_H0_0, Route123_Text_H0_1
	msgbox Route123_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_BRAXTON, Route123_Text_H1_0, Route123_Text_H1_1
	msgbox Route123_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H2::
	msgbox Route123_Text_H2, MSGBOX_NPC
	end

Route123_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_VIOLET, Route123_Text_H3_0, Route123_Text_H3_1
	msgbox Route123_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H4::
	trainerbattle_double TRAINER_HOENN_MIU_AND_YUKI, Route123_Text_H4_0, Route123_Text_H4_1, Route123_Text_H4_1
	msgbox Route123_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H5::
	trainerbattle_double TRAINER_HOENN_MIU_AND_YUKI, Route123_Text_H5_0, Route123_Text_H5_1, Route123_Text_H5_1
	msgbox Route123_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_CAMERON_1, Route123_Text_H6_0, Route123_Text_H6_1
	msgbox Route123_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_JACKI_1, Route123_Text_H7_0, Route123_Text_H7_1
	msgbox Route123_Text_H7_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H8::
	trainerbattle_single TRAINER_HOENN_KINDRA, Route123_Text_H8_0, Route123_Text_H8_1
	msgbox Route123_Text_H8_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H9::
	trainerbattle_single TRAINER_HOENN_JONAS, Route123_Text_H9_0, Route123_Text_H9_1
	msgbox Route123_Text_H9_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H10::
	trainerbattle_single TRAINER_HOENN_KAYLEY, Route123_Text_H10_0, Route123_Text_H10_1
	msgbox Route123_Text_H10_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H11::
	trainerbattle_single TRAINER_HOENN_ED, Route123_Text_H11_0, Route123_Text_H11_1
	msgbox Route123_Text_H11_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H12::
	trainerbattle_single TRAINER_HOENN_FERNANDO_1, Route123_Text_H12_0, Route123_Text_H12_1
	msgbox Route123_Text_H12_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H13::
	trainerbattle_single TRAINER_HOENN_ALBERTO, Route123_Text_H13_0, Route123_Text_H13_1
	msgbox Route123_Text_H13_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H14::
	trainerbattle_single TRAINER_HOENN_FREDRICK, Route123_Text_H14_0, Route123_Text_H14_1
	msgbox Route123_Text_H14_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H15::
	trainerbattle_single TRAINER_HOENN_JAZMYN, Route123_Text_H15_0, Route123_Text_H15_1
	msgbox Route123_Text_H15_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H16::
	trainerbattle_single TRAINER_HOENN_DAVIS, Route123_Text_H16_0, Route123_Text_H16_1
	msgbox Route123_Text_H16_2, MSGBOX_AUTOCLOSE
	end

Route123_EventScript_H17::
	msgbox Route123_Text_H17, MSGBOX_SIGN
	end

Route123_EventScript_H18::
	msgbox Route123_Text_H18, MSGBOX_SIGN
	end

Route123_EventScript_H19::
	msgbox Route123_Text_H19, MSGBOX_SIGN
	end

