Route123_Text_H0::
	.string "To best even me…\n"
	.string "Your strength is marvelous!$"

Route123_Text_H1::
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_H2::
	.string "I love GRASS-type POKéMON!\p"
	.string "Do you have any GRASS-type POKéMON?$"

Route123_Text_H3::
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_H4::
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_H5::
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_H6::
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you…$"

Route123_Text_H7::
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_H8::
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits…$"

Route123_Text_H9::
	.string "I'm going to ambush a weaker-looking\n"
	.string "TRAINER next time.$"

Route123_Text_H10::
	.string "Using accessories effectively is\n"
	.string "the secret behind fashion appeal.$"

Route123_Text_H11::
	.string "Hehe, I'm swiping your battling ideas!\n"
	.string "I think they'll make me better.$"

Route123_Text_H12::
	.string "You're rock steady.\n"
	.string "I'd like to write a tune about you.$"

Route123_Text_H13::
	.string "I gather BIRD POKéMON feathers that\n"
	.string "scatter during battles.\p"
	.string "I'm going to make a hat with\n"
	.string "BIRD POKéMON feathers.$"

Route123_Text_H14::
	.string "Contribute to your allowance?\n"
	.string "Wasn't the prize money enough?$"

Route123_Text_H15::
	.string "They say that you can't judge a person\n"
	.string "by their appearance.\p"
	.string "But often, their looks don't lie…$"

Route123_Text_H16::
	.string "Don't tell my brother I lost.\n"
	.string "You have to keep it a secret!$"

Route123_Text_H17::
	.string "{UP_ARROW} MT. PYRE\n"
	.string "“Forbidden to the faint of heart.”$"

Route123_Text_H18::
	.string "{RIGHT_ARROW} ROUTE 123\n"
	.string "{LEFT_ARROW} ROUTE 118$"

Route123_Text_H19::
	.string "BERRY MASTER'S HOUSE$"

