Route123_Text_H0_0::
	.string "Want to determine how strong you\n"
	.string "are? I'll be the test!$"

Route123_Text_H0_1::
	.string "You passed with flying colors!$"

Route123_Text_H0_2::
	.string "To best even me…\n"
	.string "Your strength is marvelous!$"

Route123_Text_H1_0::
	.string "You seem to have a big collection\n"
	.string "of GYM BADGES.\p"
	.string "Let me see if you're actually worthy\n"
	.string "of those BADGES!$"

Route123_Text_H1_1::
	.string "Oh, you're worthy, all right!$"

Route123_Text_H1_2::
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_H2::
	.string "I love GRASS-type POKéMON!\p"
	.string "Do you have any GRASS-type\n"
	.string "POKéMON?$"

Route123_Text_H3_0::
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_H3_1::
	.string "Oh…\n"
	.string "I smell the bitter scent of misery…$"

Route123_Text_H3_2::
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_H4_0::
	.string "YUKI: Okay!\n"
	.string "We're beating the TRAINER's POKéMON!$"

Route123_Text_H4_1::
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_H4_2::
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_H5_0::
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "POKéMON won't cry when they lose.$"

Route123_Text_H5_1::
	.string "MIU: Uh-oh, we lost.$"

Route123_Text_H5_2::
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_H6_0::
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_H6_1::
	.string "I feel sad…$"

Route123_Text_H6_2::
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you…$"

Route123_Text_H7_0::
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_H7_1::
	.string "Overwhelmed!$"

Route123_Text_H7_2::
	.string "We all have psychic powers. We've\n"
	.string "just forgotten how to use them.$"

Route123_Text_H8_0::
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\l"
	.string "Will your POKéMON sleep?$"

Route123_Text_H8_1::
	.string "Overflowing with vitality…$"

Route123_Text_H8_2::
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits…$"

Route123_Text_H9_0::
	.string "I lay in ambush, and a TRAINER has\n"
	.string "landed in my trap!$"

Route123_Text_H9_1::
	.string "If you don't lose, how am I\n"
	.string "supposed to have fun playing ninja?$"

Route123_Text_H9_2::
	.string "I'm going to ambush a weaker-looking\n"
	.string "TRAINER next time.$"

Route123_Text_H10_0::
	.string "I just bought this parasol. My\n"
	.string "cuteness should be up by a third!$"

Route123_Text_H10_1::
	.string "You're better than me by about\n"
	.string "five times!$"

Route123_Text_H10_2::
	.string "Using accessories effectively is\n"
	.string "the secret behind fashion appeal.$"

Route123_Text_H11_0::
	.string "When there are no TRAINERS around,\n"
	.string "I let my POKéMON battle each other.\l"
	.string "I watch them.$"

Route123_Text_H11_1::
	.string "I kind of like your POKéMON.$"

Route123_Text_H11_2::
	.string "Hehe, I'm swiping your battling\n"
	.string "ideas! I think they'll make me\l"
	.string "better.$"

Route123_Text_H12_0::
	.string "I'll turn your lights out while\n"
	.string "I rip through this tune!$"

Route123_Text_H12_1::
	.string "Hey, hold it!\n"
	.string "I was still playing the intro!$"

Route123_Text_H12_2::
	.string "You're rock steady.\n"
	.string "I'd like to write a tune about you.$"

Route123_Text_H13_0::
	.string "I have to tell you, BIRD POKéMON\n"
	.string "are my obsession!\p"
	.string "Birds are cool!\n"
	.string "They're the best!$"

Route123_Text_H13_1::
	.string "Even in defeat, BIRD POKéMON are\n"
	.string "cool!$"

Route123_Text_H13_2::
	.string "I gather BIRD POKéMON feathers that\n"
	.string "scatter during battles.\p"
	.string "I'm going to make a hat with\n"
	.string "BIRD POKéMON feathers.$"

Route123_Text_H14_0::
	.string "Hello, child!\n"
	.string "Can you spare some time?$"

Route123_Text_H14_1::
	.string "Ah, a mighty capable child!\n"
	.string "Let me contribute to your allowance.$"

Route123_Text_H14_2::
	.string "Contribute to your allowance?\n"
	.string "Wasn't the prize money enough?$"

Route123_Text_H15_0::
	.string "My confidence will get a boost by\n"
	.string "beating someone obviously strong!$"

Route123_Text_H15_1::
	.string "There goes my confidence…$"

Route123_Text_H15_2::
	.string "They say that you can't judge a\n"
	.string "person by their appearance.\p"
	.string "But often, their looks don't lie…$"

Route123_Text_H16_0::
	.string "This is my awesome BUG POKéMON!\n"
	.string "My big brother got it for me.$"

Route123_Text_H16_1::
	.string "Waaaah!\n"
	.string "You meanie!$"

Route123_Text_H16_2::
	.string "Don't tell my brother I lost.\n"
	.string "You have to keep it a secret!$"

Route123_Text_H17::
	.string "{UP_ARROW} MT. PYRE\n"
	.string "“Forbidden to the faint of heart.”$"

Route123_Text_H18::
	.string "{RIGHT_ARROW} ROUTE 123\n"
	.string "{LEFT_ARROW} ROUTE 118$"

Route123_Text_H19::
	.string "BERRY MASTER'S HOUSE$"

