Route127_MapScripts::
	.byte 0

Route127_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_CAMDEN, Route127_Text_H0_0, Route127_Text_H0_1
	msgbox Route127_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route127_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_DONNY, Route127_Text_H1_0, Route127_Text_H1_1
	msgbox Route127_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route127_EventScript_HItem73::
	finditem ITEM_ZINC
	end

Route127_EventScript_HItem74::
	finditem ITEM_CARBOS
	end

Route127_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_JONAH, Route127_Text_H2_0, Route127_Text_H2_1
	msgbox Route127_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route127_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_ROGER, Route127_Text_H3_0, Route127_Text_H3_1
	msgbox Route127_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route127_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_HENRY, Route127_Text_H4_0, Route127_Text_H4_1
	msgbox Route127_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route127_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_AIDAN, Route127_Text_H5_0, Route127_Text_H5_1
	msgbox Route127_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route127_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_KOJI_1, Route127_Text_H6_0, Route127_Text_H6_1
	msgbox Route127_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route127_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_ATHENA, Route127_Text_H7_0, Route127_Text_H7_1
	msgbox Route127_Text_H7_2, MSGBOX_AUTOCLOSE
	end

Route127_EventScript_HItem75::
	finditem ITEM_RARE_CANDY
	end

