Route127_Text_H0_0::
	.string "I can see it in your face.\n"
	.string "You want to challenge me.$"

Route127_Text_H0_1::
	.string "Awawawawawa…$"

Route127_Text_H0_2::
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_H1_0::
	.string "Do you have a rival whom you just\n"
	.string "hate to lose against?$"

Route127_Text_H1_1::
	.string "Arrrgh!\n"
	.string "I hate losing!$"

Route127_Text_H1_2::
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_H2_0::
	.string "Through fishing, I have attained a\n"
	.string "state of becalmed serenity…\p"
	.string "Please, allow me to demonstrate…$"

Route127_Text_H2_1::
	.string "Though I have lost, my heart remains\n"
	.string "calm…$"

Route127_Text_H2_2::
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water…$"

Route127_Text_H3_0::
	.string "Well, hey! This is a match between\n"
	.string "a POKéMON fan and a fishing buff!$"

Route127_Text_H3_1::
	.string "No! My line's all tangled!\n"
	.string "The party's over!$"

Route127_Text_H3_2::
	.string "My fishing line's doing a dance!\n"
	.string "The tangle tango! Hahaha, snarl!$"

Route127_Text_H4_0::
	.string "Whoops! Don't tell me I snagged\n"
	.string "a SURFING POKéMON?$"

Route127_Text_H4_1::
	.string "I can't keep up!$"

Route127_Text_H4_2::
	.string "It'd be a handful if I hooked\n"
	.string "your tough POKéMON!$"

Route127_Text_H5_0::
	.string "BIRD POKéMON have excellent vision.\n"
	.string "They spot prey from great heights.$"

Route127_Text_H5_1::
	.string "Whew… I give up.$"

Route127_Text_H5_2::
	.string "There're lots of diving spots in\n"
	.string "the sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"

Route127_Text_H6_0::
	.string "Run in your bare feet.\n"
	.string "That will toughen up your soles!$"

Route127_Text_H6_1::
	.string "Yowch!\n"
	.string "I got a pebble under a toenail!$"

Route127_Text_H6_2::
	.string "Going barefoot feels great.\n"
	.string "But your RUNNING SHOES are cool, too.$"

Route127_Text_H7_0::
	.string "We should have a slow and methodical\n"
	.string "match.$"

Route127_Text_H7_1::
	.string "You didn't give me the chance to\n"
	.string "do any strategizing.$"

Route127_Text_H7_2::
	.string "When I'm surrounded by the blue sea\n"
	.string "and sky, it feels as if time slows down.$"

