Route127_Text_H0::
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_H1::
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_H2::
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water…$"

Route127_Text_H3::
	.string "My fishing line's doing a dance!\n"
	.string "The tangle tango! Hahaha, snarl!$"

Route127_Text_H4::
	.string "It'd be a handful if I hooked\n"
	.string "your tough POKéMON!$"

Route127_Text_H5::
	.string "There're lots of diving spots in\n"
	.string "the sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"

Route127_Text_H6::
	.string "Going barefoot feels great.\n"
	.string "But your RUNNING SHOES are cool, too.$"

Route127_Text_H7::
	.string "When I'm surrounded by the blue sea\n"
	.string "and sky, it feels as if time slows down.$"

