VictoryRoad_B1F_MapScripts::
	.byte 0

VictoryRoad_B1F_EventScript_H0::
	msgbox VictoryRoad_B1F_Text_H0, MSGBOX_NPC
	end

VictoryRoad_B1F_EventScript_H1::
	msgbox VictoryRoad_B1F_Text_H1, MSGBOX_NPC
	end

VictoryRoad_B1F_EventScript_H2::
	msgbox VictoryRoad_B1F_Text_H2, MSGBOX_NPC
	end

VictoryRoad_B1F_EventScript_H3::
	msgbox VictoryRoad_B1F_Text_H3, MSGBOX_NPC
	end

VictoryRoad_B1F_EventScript_H4::
	msgbox VictoryRoad_B1F_Text_H4, MSGBOX_NPC
	end

