RusturfTunnel_Text_H0_0::
	.string "What do you call a wild man up in the\n"
	.string "mountains? A mountain man, right?\p"
	.string "So why don't they call a POKéMON in\n"
	.string "the mountains a mountain POKéMON?$"

RusturfTunnel_Text_H0_1::
	.string "My POKéMON…\n"
	.string "Ran out of power…$"

RusturfTunnel_Text_H0_2::
	.string "They halted development here to\n"
	.string "protect POKéMON, right?\l"
	.string "There's a feel-good story!$"

