SilverMountain_Summit_Text_Silence::
    .string "…………$"

SilverMountain_Summit_Text_Footprints::
    .string "Only footprints were left in the\n"
    .string "snow. They led to the edge of the\l"
    .string "summit, and stopped.$"

SilverMountain_Summit_Text_Memorial::
    .string "Someone has carved words into the\n"
    .string "ice on the rock:\p"
    .string "“A TRAINER and a PIKACHU stood\n"
    .string "here, at the top of the world.”$"

SilverMountain_Summit_Text_JustSnow::
    .string "The rock is covered in thick snow.$"
