Route107_MapScripts::
	.byte 0

Route107_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_DARRIN, Route107_Text_H0_0, Route107_Text_H0_1
	msgbox Route107_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route107_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_TONY_1, Route107_Text_H1_0, Route107_Text_H1_1
	msgbox Route107_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route107_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_DENISE, Route107_Text_H2_0, Route107_Text_H2_1
	msgbox Route107_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route107_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_BETH, Route107_Text_H3_0, Route107_Text_H3_1
	msgbox Route107_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route107_EventScript_H4::
	trainerbattle_double TRAINER_HOENN_LISA_AND_RAY, Route107_Text_H4_0, Route107_Text_H4_1, Route107_Text_H4_1
	msgbox Route107_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route107_EventScript_H5::
	trainerbattle_double TRAINER_HOENN_LISA_AND_RAY, Route107_Text_H5_0, Route107_Text_H5_1, Route107_Text_H5_1
	msgbox Route107_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route107_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_CAMRON, Route107_Text_H6_0, Route107_Text_H6_1
	msgbox Route107_Text_H6_2, MSGBOX_AUTOCLOSE
	end
