Route107_Text_H0_0::
	.string "Yawn…\p"
	.string "I must have drifted off to sleep\n"
	.string "while I was drifting in the waves.$"

Route107_Text_H0_1::
	.string "Ahaha, I lost…\n"
	.string "I'll take a snooze, I think…$"

Route107_Text_H0_2::
	.string "Floating and being rocked by\n"
	.string "the waves--it's like sleeping in\l"
	.string "a plush, comfy bed.$"

Route107_Text_H1_0::
	.string "The sea is like my backyard.\n"
	.string "Let's battle!$"

Route107_Text_H1_1::
	.string "I lost on my home field…\n"
	.string "I'm in shock!$"

Route107_Text_H1_2::
	.string "I swim the seas with a heart full of\n"
	.string "dreams…\p"
	.string "It's a song!\n"
	.string "Anyways, I'm swimming some more.$"

Route107_Text_H2_0::
	.string "Do you know a little town called\n"
	.string "DEWFORD?$"

Route107_Text_H2_1::
	.string "I hate this!$"

Route107_Text_H2_2::
	.string "A weird saying is getting really\n"
	.string "trendy at DEWFORD HALL.$"

Route107_Text_H3_0::
	.string "Did you want to battle me?\n"
	.string "Sure, I'll go with you!$"

Route107_Text_H3_1::
	.string "I wasn't good enough for you.$"

Route107_Text_H3_2::
	.string "I think you're going to keep getting\n"
	.string "better. I'll go for it, too!$"

Route107_Text_H4_0::
	.string "LISA: We challenge you as a sister\n"
	.string "and brother!$"

Route107_Text_H4_1::
	.string "LISA: Awesome.\n"
	.string "You're in a different class of tough.$"

Route107_Text_H4_2::
	.string "LISA: Do you have any friends who\n"
	.string "would go to the beach with you?$"

Route107_Text_H5_0::
	.string "RAY: We always battle POKéMON,\n"
	.string "me and my sister.\p"
	.string "I always lose, but we can beat you\n"
	.string "2-on-2!$"

Route107_Text_H5_1::
	.string "RAY: Wowee, you're at a higher level\n"
	.string "than us!$"

Route107_Text_H5_2::
	.string "RAY: My sister gave me my POKéMON.\n"
	.string "I raised it, and now it's my\l"
	.string "important partner!$"

Route107_Text_H6_0::
	.string "I'm in the middle of a triathlon,\n"
	.string "but I'm nowhere near tired!$"

Route107_Text_H6_1::
	.string "That exhausted me…$"

Route107_Text_H6_2::
	.string "I still have swimming and running\n"
	.string "left to do after this.\p"
	.string "Am I going to be okay?$"

