Route107_Text_H0::
	.string "Floating and being rocked by\n"
	.string "the waves--it's like sleeping in\l"
	.string "a plush, comfy bed.$"

Route107_Text_H1::
	.string "I swim the seas with a heart full of\n"
	.string "dreams…\p"
	.string "It's a song!\n"
	.string "Anyways, I'm swimming some more.$"

Route107_Text_H2::
	.string "A weird saying is getting really\n"
	.string "trendy at DEWFORD HALL.$"

Route107_Text_H3::
	.string "I think you're going to keep getting\n"
	.string "better. I'll go for it, too!$"

Route107_Text_H4::
	.string "LISA: Do you have any friends who\n"
	.string "would go to the beach with you?$"

Route107_Text_H5::
	.string "RAY: My sister gave me my POKéMON.\n"
	.string "I raised it, and now it's my important\l"
	.string "partner!$"

Route107_Text_H6::
	.string "I still have swimming and running left\n"
	.string "to do after this.\p"
	.string "Am I going to be okay?$"

