Route110_MapScripts::
	.byte 0

Route110_EventScript_H0::
	msgbox Route110_Text_H0, MSGBOX_NPC
	end

Route110_EventScript_H1::
	msgbox Route110_Text_H1, MSGBOX_NPC
	end

Route110_EventScript_H2::
	msgbox Route110_Text_H2, MSGBOX_NPC
	end

Route110_EventScript_H3::
	msgbox Route110_Text_H3, MSGBOX_NPC
	end

Route110_EventScript_H4::
	msgbox Route110_Text_H4, MSGBOX_NPC
	end

Route110_EventScript_H5::
	msgbox Route110_Text_H5, MSGBOX_NPC
	end

Route110_EventScript_H6::
	msgbox Route110_Text_H6, MSGBOX_NPC
	end

Route110_EventScript_H7::
	msgbox Route110_Text_H7, MSGBOX_NPC
	end

Route110_EventScript_H8::
	msgbox Route110_Text_H8, MSGBOX_NPC
	end

Route110_EventScript_H9::
	msgbox Route110_Text_H9, MSGBOX_NPC
	end

Route110_EventScript_H10::
	msgbox Route110_Text_H10, MSGBOX_NPC
	end

Route110_EventScript_H11::
	msgbox Route110_Text_H11, MSGBOX_NPC
	end

Route110_EventScript_H12::
	msgbox Route110_Text_H12, MSGBOX_NPC
	end

Route110_EventScript_H13::
	msgbox Route110_Text_H13, MSGBOX_NPC
	end

Route110_EventScript_H14::
	msgbox Route110_Text_H14, MSGBOX_NPC
	end

Route110_EventScript_H15::
	msgbox Route110_Text_H15, MSGBOX_NPC
	end

Route110_EventScript_H16::
	msgbox Route110_Text_H16, MSGBOX_NPC
	end

Route110_EventScript_H17::
	msgbox Route110_Text_H17, MSGBOX_NPC
	end

Route110_EventScript_H18::
	msgbox Route110_Text_H18, MSGBOX_NPC
	end

Route110_EventScript_H19::
	msgbox Route110_Text_H19, MSGBOX_NPC
	end

Route110_EventScript_H20::
	msgbox Route110_Text_H20, MSGBOX_NPC
	end

Route110_EventScript_H21::
	msgbox Route110_Text_H21, MSGBOX_NPC
	end

Route110_EventScript_H22::
	msgbox Route110_Text_H22, MSGBOX_SIGN
	end

Route110_EventScript_H23::
	msgbox Route110_Text_H23, MSGBOX_SIGN
	end

Route110_EventScript_H24::
	msgbox Route110_Text_H24, MSGBOX_SIGN
	end

Route110_EventScript_H25::
	msgbox Route110_Text_H25, MSGBOX_SIGN
	end

Route110_EventScript_H26::
	msgbox Route110_Text_H26, MSGBOX_SIGN
	end

Route110_EventScript_H27::
	msgbox Route110_Text_H27, MSGBOX_SIGN
	end

Route110_EventScript_H28::
	msgbox Route110_Text_H28, MSGBOX_SIGN
	end

Route110_EventScript_H29::
	msgbox Route110_Text_H29, MSGBOX_SIGN
	end

Route110_EventScript_H30::
	msgbox Route110_Text_H30, MSGBOX_SIGN
	end

Route110_EventScript_H31::
	msgbox Route110_Text_H31, MSGBOX_SIGN
	end

Route110_EventScript_H32::
	msgbox Route110_Text_H32, MSGBOX_SIGN
	end

