Route110_Text_H0::
	.string "Which should I choose?\p"
	.string "Make a beeline for MAUVILLE on\n"
	.string "CYCLING ROAD, or take the low road\l"
	.string "and look for POKéMON?$"

Route110_Text_H1::
	.string "Learning techniques will make BIKE\n"
	.string "riding even more fun.\p"
	.string "There are some places that you can\n"
	.string "reach only by using a BIKE\l"
	.string "technique.$"

Route110_Text_H2::
	.string "I don't have a BIKE, so I'll take\n"
	.string "a leisurely walk on the low road.$"

Route110_Text_H3::
	.string "Oh, hey, you got that BIKE from\n"
	.string "RYDEL!\p"
	.string "Oh, it's glaringly obvious.\n"
	.string "It says right on your bike…\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL…\n"
	.string "That name's everywhere.\p"
	.string "You should ride it around all over\n"
	.string "the place--it's good advertising!$"

Route110_Text_H4::
	.string "The two roads, one above, one\n"
	.string "below…\p"
	.string "A road each for people and POKéMON.\n"
	.string "Perhaps that is right and fair.$"

Route110_Text_H5::
	.string "How do you like the way my raven-\n"
	.string "colored hair streams behind me?\p"
	.string "I grew my hair out just for that.$"

Route110_Text_H6::
	.string "Wouldn't it be great to ride a BIKE\n"
	.string "at full speed on CYCLING ROAD?$"

Route110_Text_H7_0::
	.string "I've been riding without stopping.\n"
	.string "My thighs are like rocks!$"

Route110_Text_H7_1::
	.string "I'm worried about muscle cramps…$"

Route110_Text_H7_2::
	.string "Oh, you have some GYM BADGES?\n"
	.string "No wonder you're so strong!$"

Route110_Text_H8_0::
	.string "Yo, you!\n"
	.string "Can you keep up with my speed?$"

Route110_Text_H8_1::
	.string "Crash and burn!$"

Route110_Text_H8_2::
	.string "Speed alone won't let me win at\n"
	.string "POKéMON. I need to reconsider this…$"

Route110_Text_H9_0::
	.string "The triathlon is hard in the extreme.\p"
	.string "You have to complete the three\n"
	.string "events of swimming, cycling, and\l"
	.string "running.$"

Route110_Text_H9_1::
	.string "POKéMON battles are hard, too!$"

Route110_Text_H9_2::
	.string "I'm exhausted, so I need a break.\n"
	.string "It's important to get proper rest.$"

Route110_Text_H10_0::
	.string "Don't panic if your BIKE's going\n"
	.string "fast!$"

Route110_Text_H10_1::
	.string "I shouldn't panic during POKéMON\n"
	.string "battles…$"

Route110_Text_H10_2::
	.string "There's no need to panic or stress.\n"
	.string "Take it easy. There's plenty of time.$"

Route110_Text_H11_0::
	.string "I have foreseen your intentions!\n"
	.string "I cannot possibly lose!$"

Route110_Text_H11_1::
	.string "I failed to prophesize my own\n"
	.string "demise!$"

Route110_Text_H11_2::
	.string "I see your future…\p"
	.string "Hmm…\n"
	.string "I see a shining light…$"

Route110_Text_H12_0::
	.string "Ahahahaha!\n"
	.string "I'll dazzle you with my wonders!$"

Route110_Text_H12_1::
	.string "I wondrously lost!$"

Route110_Text_H12_2::
	.string "You managed to win only because it\n"
	.string "was a wonder! Yes, a wonder! Don't\l"
	.string "think you can win all the time!$"

Route110_Text_H13_0::
	.string "Could I see your POKéMON?\n"
	.string "Just one look, please?$"

Route110_Text_H13_1::
	.string "I wanted to complete\n"
	.string "my collection…$"

Route110_Text_H13_2::
	.string "When I see a POKéMON that I don't\n"
	.string "know, my passion as a collector is\l"
	.string "ignited!$"

Route110_Text_H14_0::
	.string "Hey!\n"
	.string "Don't sneak up behind me like that!$"

Route110_Text_H14_1::
	.string "I lost!\n"
	.string "Drat!$"

Route110_Text_H14_2::
	.string "Fishing is all about concentration.\n"
	.string "You have to focus on the floater.$"

Route110_Text_H15::
	.string "Regardless of the results, I count\n"
	.string "on seeing more challenges from you.\l"
	.string "Always aim higher!$"

Route110_Text_H16_0::
	.string "Whoa! Watch it! I guess you're not\n"
	.string "used to BIKE racing.$"

Route110_Text_H16_1::
	.string "Whoa!\n"
	.string "My brakes failed!$"

Route110_Text_H16_2::
	.string "Flat tires and brake problems can\n"
	.string "cause serious injury!\l"
	.string "Inspect your BIKE for problems!$"

Route110_Text_H17_0::
	.string "I found some cool POKéMON in the\n"
	.string "grass around here!$"

Route110_Text_H17_1::
	.string "Being cool isn't enough to win…$"

Route110_Text_H17_2::
	.string "It's hard to battle with POKéMON you\n"
	.string "just caught.$"

Route110_Text_H18_0::
	.string "Ahahaha! I would go anywhere to\n"
	.string "show off my delightful POKéMON.$"

Route110_Text_H18_1::
	.string "Oh, dear, this won't do.$"

Route110_Text_H18_2::
	.string "Rather than battling, perhaps I\n"
	.string "should show off my POKéMON at the\l"
	.string "FAN CLUB.$"

Route110_Text_H19_0::
	.string "When cute POKéMON help each other…\n"
	.string "You won't see a more adorable sight!$"

Route110_Text_H19_1::
	.string "Have you no compassion or pity?$"

Route110_Text_H19_2::
	.string "Okay, okay, you've done the best\n"
	.string "you could, my pretties.$"

Route110_Text_H20_0::
	.string "I fell off CYCLING ROAD…\p"
	.string "I'll get over my embarrassment by\n"
	.string "battling with you!$"

Route110_Text_H20_1::
	.string "Oops!\n"
	.string "I ended up losing!$"

Route110_Text_H20_2::
	.string "Falling… Losing…\n"
	.string "This is so humiliating for me!$"

Route110_Text_H21_0::
	.string "Okay! Full-throttle time! If you\n"
	.string "can't groove, you get left behind!$"

Route110_Text_H21_1::
	.string "You got into the groove all right…$"

Route110_Text_H21_2::
	.string "This isn't going to bring me down!\n"
	.string "Losing has made me a better man!$"

Route110_Text_H22::
	.string "“TEAM AQUA was here!”\p"
	.string "Someone painted that onto this sign,\n"
	.string "but then someone else painted over\l"
	.string "it.\p"
	.string "“TEAM MAGMA rules!” is what it\n"
	.string "says now.$"

Route110_Text_H23::
	.string "SEASIDE PARKING$"

Route110_Text_H24::
	.string "SEASIDE CYCLING ROAD$"

Route110_Text_H25::
	.string "ROUTE 110\n"
	.string "{DOWN_ARROW} SLATEPORT CITY$"

Route110_Text_H26::
	.string "ROUTE 110\n"
	.string "{LEFT_ARROW} ROUTE 103$"

Route110_Text_H27::
	.string "ROUTE 110\n"
	.string "{UP_ARROW} MAUVILLE CITY$"

Route110_Text_H28::
	.string "TRAINER TIPS\p"
	.string "The foe can be made helpless by\n"
	.string "paralyzing it or causing it to sleep.\p"
	.string "It is an important technique for\n"
	.string "POKéMON battles.$"

Route110_Text_H29::
	.string "TRAINER TIPS\p"
	.string "The items in the BAG can be\n"
	.string "reorganized by pressing SELECT.$"

Route110_Text_H30::
	.string "“Three steps {RIGHT_ARROW} and two steps {UP_ARROW}\n"
	.string "to reach the wondrous TRICK HOUSE.”$"

Route110_Text_H31::
	.string "THE BEST RECORD TO DATE…\p"
	.string "No. of collisions: {STR_VAR_1}\p"
	.string "Elapsed time: {STR_VAR_2}$"

Route110_Text_H32::
	.string "SEASIDE CYCLING ROAD$"

