LilycoveCity_DepartmentStore_3F_Text_H0::
	.string "For quickly toughening up POKéMON,\n"
	.string "items are the best.\p"
	.string "PROTEIN boosts ATTACK,\n"
	.string "and CALCIUM raises SP. ATK.$"

LilycoveCity_DepartmentStore_3F_Text_H1::
	.string "I want my POKéMON to have more\n"
	.string "endurance.\p"
	.string "I'm trying to decide whether to raise\n"
	.string "DEFENSE with IRON, or SP. DEF with\l"
	.string "ZINC.$"

LilycoveCity_DepartmentStore_3F_Text_H2::
	.string "I gave a CARBOS to my POKéMON,\n"
	.string "and its SPEED went up.$"

