CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "Me?\n"
    .string "I'm the programmer!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "I'm the graphic artist!\n"
    .string "I drew you!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "I wrote the story!\n"
    .string "Isn't ERIKA cute?\p"
    .string "I like MISTY a lot, too!\n"
    .string "Oh, and SABRINA, I like her!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "Is that right?\p"
    .string "I'm the game designer!\p"
    .string "Filling up your POKéDEX is tough,\n"
    .string "but don't quit!\p"
    .string "When you finish, come tell me!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "Wow! Excellent!\n"
    .string "You completed your POKéDEX!\l"
    .string "Congratulations!\l"
    .string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "It's the game program! Messing with\n"
    .string "it could bug out the game!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "Someone's playing a game instead of\n"
    .string "working!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "It's the script!\n"
    .string "Better not look at the ending!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "GAME FREAK Development Room$"


CeladonCity_Condominiums_3F_Text_ThatManyRareCandies::
    .string "Wh-what?! 99 RARE CANDIES?!\p"
    .string "…You didn't get those from a bug,\n"
    .string "did you?\p"
    .string "Back when POKéMON first came out,\n"
    .string "kids swore there was a trick.\p"
    .string "Meet a strange POKéMON off\n"
    .string "CINNABAR's coast, and the 6th item\l"
    .string "in your bag would jump past 100!\p"
    .string "We never, ever meant for that to\n"
    .string "happen!\p"
    .string "Ahem. I'll just take one of those\n"
    .string "back, for, er, research.$"

CeladonCity_Condominiums_3F_Text_HandedOverRareCandy::
    .string "{PLAYER} handed over one RARE\n"
    .string "CANDY.\p"
    .string "DESIGNER: Phew… That looks much\n"
    .string "more believable now.$"
