Route111_MapScripts::
	.byte 0

Route111_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_HEIDI, Route111_Text_H0_0, Route111_Text_H0_1
	msgbox Route111_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H1::
	msgbox Route111_Text_H1, MSGBOX_NPC
	end

Route111_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_DREW, Route111_Text_H2_0, Route111_Text_H2_1
	msgbox Route111_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_DUSTY_1, Route111_Text_H3_0, Route111_Text_H3_1
	msgbox Route111_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_BEAU, Route111_Text_H4_0, Route111_Text_H4_1
	msgbox Route111_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_BECKY, Route111_Text_H5_0, Route111_Text_H5_1
	msgbox Route111_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H6::
	msgbox Route111_Text_H6, MSGBOX_NPC
	end

Route111_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_IRENE, Route111_Text_H7_0, Route111_Text_H7_1
	msgbox Route111_Text_H7_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H8::
	trainerbattle_single TRAINER_HOENN_TRAVIS, Route111_Text_H8_0, Route111_Text_H8_1
	msgbox Route111_Text_H8_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H9::
	trainerbattle_single TRAINER_HOENN_DAISUKE, Route111_Text_H9_0, Route111_Text_H9_1
	msgbox Route111_Text_H9_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H10::
	trainerbattle_single TRAINER_HOENN_BROOKE_1, Route111_Text_H10_0, Route111_Text_H10_1
	msgbox Route111_Text_H10_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H11::
	trainerbattle_single TRAINER_HOENN_WILTON_1, Route111_Text_H11_0, Route111_Text_H11_1
	msgbox Route111_Text_H11_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H12::
	msgbox Route111_Text_H12, MSGBOX_NPC
	end

Route111_EventScript_H13::
	trainerbattle_single TRAINER_HOENN_TYRON, Route111_Text_H13_0, Route111_Text_H13_1
	msgbox Route111_Text_H13_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H14::
	trainerbattle_single TRAINER_HOENN_CELINA, Route111_Text_H14_0, Route111_Text_H14_1
	msgbox Route111_Text_H14_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H15::
	trainerbattle_single TRAINER_HOENN_BIANCA, Route111_Text_H15_0, Route111_Text_H15_1
	msgbox Route111_Text_H15_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H16::
	trainerbattle_single TRAINER_HOENN_HAYDEN, Route111_Text_H16_0, Route111_Text_H16_1
	msgbox Route111_Text_H16_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H17::
	trainerbattle_single TRAINER_HOENN_BRYAN, Route111_Text_H17_0, Route111_Text_H17_1
	msgbox Route111_Text_H17_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H18::
	trainerbattle_single TRAINER_HOENN_CELIA, Route111_Text_H18_0, Route111_Text_H18_1
	msgbox Route111_Text_H18_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H19::
	trainerbattle_single TRAINER_HOENN_BRANDEN, Route111_Text_H19_0, Route111_Text_H19_1
	msgbox Route111_Text_H19_2, MSGBOX_AUTOCLOSE
	end

Route111_EventScript_H20::
	msgbox Route111_Text_H20, MSGBOX_NPC
	end

Route111_EventScript_H21::
	msgbox Route111_Text_H21, MSGBOX_SIGN
	end

Route111_EventScript_H22::
	msgbox Route111_Text_H22, MSGBOX_SIGN
	end

Route111_EventScript_H23::
	msgbox Route111_Text_H23, MSGBOX_SIGN
	end

Route111_EventScript_H24::
	msgbox Route111_Text_H24, MSGBOX_SIGN
	end

Route111_EventScript_H25::
	msgbox Route111_Text_H25, MSGBOX_SIGN
	end

Route111_EventScript_H26::
	msgbox Route111_Text_H26, MSGBOX_SIGN
	end

Route111_EventScript_H27::
	msgbox Route111_Text_H27, MSGBOX_SIGN
	end

