Route111_Text_H0_0::
	.string "I'm having a picnic in the desert.\p"
	.string "You can always find a TRAINER,\n"
	.string "so I can enjoy a battle here, too!$"

Route111_Text_H0_1::
	.string "Ohhh! You're mean!$"

Route111_Text_H0_2::
	.string "When you're battling in a sandstorm,\n"
	.string "watch out for your POKéMON's HP.\p"
	.string "It can faint if you don't keep\n"
	.string "an eye on it!$"

Route111_Text_H1::
	.string "If you don't raise your POKéMON some\n"
	.string "more, it could be tough to keep winning\l"
	.string "up through the ranks.\p"
	.string "I've heard the POKéMON LEAGUE's\n"
	.string "ELITE FOUR are far stronger than\l"
	.string "any GYM LEADER.$"

Route111_Text_H2_0::
	.string "Oh, hey! Those GO-GOGGLES suit you.\n"
	.string "But I think they look better on me.\p"
	.string "Let's decide who they look better on\n"
	.string "with a battle!$"

Route111_Text_H2_1::
	.string "I couldn't see what was happening at\n"
	.string "my sides because of the GO-GOGGLES.$"

Route111_Text_H2_2::
	.string "The GO-GOGGLES make it possible to\n"
	.string "get through sandstorms.\l"
	.string "That makes me happy!$"

Route111_Text_H3_0::
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\l"
	.string "I am to be challenged?$"

Route111_Text_H3_1::
	.string "While I have searched for ruins,\n"
	.string "I've not searched for strong POKéMON.$"

Route111_Text_H3_2::
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years?\n"
	.string "Which was it now?$"

Route111_Text_H4_0::
	.string "Wearing these GO-GOGGLES makes me\n"
	.string "feel like a superhero.\l"
	.string "Right now, nobody can beat me!$"

Route111_Text_H4_1::
	.string "I can't win on spirit alone…$"

Route111_Text_H4_2::
	.string "I'm going to be a real hero one day.\n"
	.string "I'm going to work harder to make me\l"
	.string "and my POKéMON stronger.$"

Route111_Text_H5_0::
	.string "I heard there are fossils to be found\n"
	.string "in the desert. Where could they be?$"

Route111_Text_H5_1::
	.string "I came up short…$"

Route111_Text_H5_2::
	.string "If they can find fossils in the desert,\n"
	.string "it must have been a sea before.$"

Route111_Text_H6::
	.string "I watered the plants every day.\n"
	.string "They grew lots of flowers.\p"
	.string "And they gave me lots of BERRIES, too.\p"
	.string "Here you go!\n"
	.string "You can have it!$"

Route111_Text_H7_0::
	.string "I don't know where you're going,\n"
	.string "but would you like to battle?$"

Route111_Text_H7_1::
	.string "Oh, you're disgustingly good!$"

Route111_Text_H7_2::
	.string "I'm thinking that I should go to\n"
	.string "MT. CHIMNEY, but the view around\l"
	.string "here is very nice, too.$"

Route111_Text_H8_0::
	.string "I'm full of pep!\n"
	.string "And my POKéMON is peppy, too!$"

Route111_Text_H8_1::
	.string "My POKéMON lost its pep…$"

Route111_Text_H8_2::
	.string "When I see a TRAINER with a lot of pep,\n"
	.string "I can't help looking.$"

Route111_Text_H9_0::
	.string "To train myself, I challenge all\n"
	.string "whom I meet!$"

Route111_Text_H9_1::
	.string "Uncle! I give up!$"

Route111_Text_H9_2::
	.string "All I can do is keep training until\n"
	.string "I can defeat strong TRAINERS such\l"
	.string "as yourself.$"

Route111_Text_H10_0::
	.string "Oh, your POKéMON look like serious\n"
	.string "actors.\l"
	.string "I have to ask you for an engagement.$"

Route111_Text_H10_1::
	.string "They didn't just look strong,\n"
	.string "they are strong!$"

Route111_Text_H10_2::
	.string "I thought I was raising my POKéMON\n"
	.string "diligently, but, oh no, there is still\l"
	.string "much to be done.$"

Route111_Text_H11_0::
	.string "Show me how much you've toughened\n"
	.string "your POKéMON.$"

Route111_Text_H11_1::
	.string "I see, you've toughened them\n"
	.string "considerably.$"

Route111_Text_H11_2::
	.string "POKéMON and TRAINERS learn much\n"
	.string "through battling.\p"
	.string "What's important is to never give up\n"
	.string "even if you lose.$"

Route111_Text_H12::
	.string "I challenged the WINSTRATE family,\n"
	.string "but four matches in a row is tough\l"
	.string "going… They destroyed me.$"

Route111_Text_H13_0::
	.string "This is my favorite kind of POKéMON!$"

Route111_Text_H13_1::
	.string "Wait!\n"
	.string "Did you get a good look at my POKéMON?$"

Route111_Text_H13_2::
	.string "When having a battle, I get a kick out\n"
	.string "of showing off my POKéMON.\p"
	.string "I bet everyone feels that way when\n"
	.string "they enter a battle!$"

Route111_Text_H14_0::
	.string "Show me how to put a little excitement\n"
	.string "into my life.$"

Route111_Text_H14_1::
	.string "Oh… My…\n"
	.string "That was too much excitement.$"

Route111_Text_H14_2::
	.string "My pulse is still racing.\n"
	.string "You're one fabulous TRAINER.$"

Route111_Text_H15_0::
	.string "Did you come from MAUVILLE?\n"
	.string "Then you should be full of energy!$"

Route111_Text_H15_1::
	.string "Ooh lala!\n"
	.string "That's a lot to take!$"

Route111_Text_H15_2::
	.string "This road here…\n"
	.string "You have quite a ways to travel.$"

Route111_Text_H16_0::
	.string "When you're as famished as I am,\n"
	.string "there is no room for pity!$"

Route111_Text_H16_1::
	.string "Groan…$"

Route111_Text_H16_2::
	.string "My stomach is grumbling!\n"
	.string "Maybe I can grill some BERRIES…$"

Route111_Text_H17_0::
	.string "How tough are you?\n"
	.string "We shall expose that secret!$"

Route111_Text_H17_1::
	.string "Oh! Your strength!\n"
	.string "It is shrouded in mystery!$"

Route111_Text_H17_2::
	.string "This desert hoards mysteries in\n"
	.string "its shifting sands!$"

Route111_Text_H18_0::
	.string "I shouldn't have come to a place like\n"
	.string "this for a picnic!$"

Route111_Text_H18_1::
	.string "Aww!\n"
	.string "I really shouldn't have come!$"

Route111_Text_H18_2::
	.string "In a sandstorm like this, I can't set\n"
	.string "the places for a picnic even with my\l"
	.string "GO-GOGGLES on…$"

Route111_Text_H19_0::
	.string "I'll give you some of my sandwich\n"
	.string "if you'll lose.$"

Route111_Text_H19_1::
	.string "Tch! I thought a sandwich would be\n"
	.string "enough of a bribe…$"

Route111_Text_H19_2::
	.string "My SANDSHREW loves eating\n"
	.string "my sandwiches.$"

Route111_Text_H20::
	.string "There should be a tower made of sand\n"
	.string "around here somewhere.\p"
	.string "But for some reason, it can be seen\n"
	.string "sometimes, and sometimes not.\p"
	.string "That's why I call it the MIRAGE TOWER.$"

Route111_Text_H21::
	.string "“Our family's hearts beat as one!”\n"
	.string "THE WINSTRATE'S HOUSE$"

Route111_Text_H22::
	.string "ROUTE 111\n"
	.string "{DOWN_ARROW} MAUVILLE CITY$"

Route111_Text_H23::
	.string "ROUTE 111\n"
	.string "{LEFT_ARROW} ROUTE 112$"

Route111_Text_H24::
	.string "ROUTE 111\n"
	.string "{LEFT_ARROW} ROUTE 113$"

Route111_Text_H25::
	.string "OLD LADY'S REST STOP\n"
	.string "“Come in and rest your tired bones.”$"

Route111_Text_H26::
	.string "TRAINER TIPS\p"
	.string "One of the indicators of a POKéMON's\n"
	.string "powerfulness is SP. ATK. It stands for\l"
	.string "“SPECIAL ATTACK.”\p"
	.string "Likewise, SP. DEF stands for “SPECIAL\n"
	.string "DEFENSE.”$"

Route111_Text_H27::
	.string "{RIGHT_ARROW} TRAINER HILL ENTRANCE\p"
	.string "“Scale the heights, you hot-blooded\n"
	.string "TRAINERS!”$"

