BattleFrontier_RankingHall_Text_H0::
	.string "This is the RANKING HALL.\p"
	.string "This is where we recognize the\n"
	.string "immortal TRAINERS who left great\l"
	.string "records in BATTLE FRONTIER events.$"

BattleFrontier_RankingHall_Text_H1::
	.string "Hi, is your name on this list?$"

BattleFrontier_RankingHall_Text_H2::
	.string "Hmm…\n"
	.string "My name's not up there…\p"
	.string "Well, it's only natural since I\n"
	.string "haven't taken any challenges yet.$"

BattleFrontier_RankingHall_Text_H3::
	.string "BATTLE DOME, BATTLE PIKE,\n"
	.string "and BATTLE FACTORY Records$"

BattleFrontier_RankingHall_Text_H4::
	.string "BATTLE PALACE, BATTLE ARENA,\n"
	.string "and BATTLE PYRAMID Records$"

