RocketHideout_B1F_Text_Grunt1Intro::
    .string "Who are you?\n"
    .string "How did you get here?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "Oww!\n"
    .string "Beaten!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "Blast it… You're dissing TEAM\n"
    .string "ROCKET, aren't you?$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "You broke into TEAM ROCKET's\n"
    .string "operation? What nerve!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "Boom!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "You're not going to get away with\n"
    .string "this, brat!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "Intruder alert!$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "I can't do it!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "SILPH SCOPE? Humph!\n"
    .string "I don't know where it is.$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "Why did you come here?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "This won't do!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "Okay, I'll talk…\n"
    .string "Take the elevator to see my BOSS.$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "Are you lost, you little mouse?$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "Why…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "Uh-oh, that ruckus somehow opened\n"
    .string "the door!$"


RocketHideout_B1F_Text_CameraGrunt1Intro::
    .string "Hey!\n"
    .string "Intruder alert!$"

RocketHideout_B1F_Text_CameraGrunt1Defeat::
    .string "Dang… I failed…$"

RocketHideout_B1F_Text_CameraGrunt2Intro::
    .string "It's my turn!\n"
    .string "There's no escape!$"

RocketHideout_B1F_Text_CameraGrunt2Defeat::
    .string "Surveillance cams are in the\n"
    .string "POKéMON statues.$"

RocketHideout_B1F_Text_CameraGrunt2PostBattle::
    .string "We'd have kept coming if you hadn't\n"
    .string "beaten us both…\p"
    .string "The cams and the traps below all\n"
    .string "run off the emergency generator!$"

RocketHideout_B1F_Text_PersianStatueCamera::
    .string "It's a PERSIAN statue…\p"
    .string "Its eyes are glowing. They look\n"
    .string "like camera lenses!$"

RocketHideout_B1F_Text_PersianStatueOff::
    .string "It's a PERSIAN statue.\n"
    .string "The glow in its eyes has gone out.$"
