Route134_MapScripts::
	.byte 0

Route134_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_JACK, Route134_Text_H0_0, Route134_Text_H0_1
	msgbox Route134_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route134_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_LAUREL, Route134_Text_H1_0, Route134_Text_H1_1
	msgbox Route134_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route134_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_AARON, Route134_Text_H2_0, Route134_Text_H2_1
	msgbox Route134_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route134_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_ALEX, Route134_Text_H3_0, Route134_Text_H3_1
	msgbox Route134_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route134_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_HITOSHI, Route134_Text_H4_0, Route134_Text_H4_1
	msgbox Route134_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route134_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_MARLEY, Route134_Text_H5_0, Route134_Text_H5_1
	msgbox Route134_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route134_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_KELVIN, Route134_Text_H6_0, Route134_Text_H6_1
	msgbox Route134_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route134_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_REYNA, Route134_Text_H7_0, Route134_Text_H7_1
	msgbox Route134_Text_H7_2, MSGBOX_AUTOCLOSE
	end

Route134_EventScript_H8::
	trainerbattle_single TRAINER_HOENN_HUDSON, Route134_Text_H8_0, Route134_Text_H8_1
	msgbox Route134_Text_H8_2, MSGBOX_AUTOCLOSE
	end

Route134_EventScript_HItem81::
	finditem ITEM_CARBOS
	end

Route134_EventScript_HItem82::
	finditem ITEM_STAR_PIECE
	end

