Route134_Text_H0_0::
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_H0_1::
	.string "Aiyeeeeh!$"

Route134_Text_H0_2::
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_H1_0::
	.string "My LUVDISC are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_H1_1::
	.string "Oopsie!$"

Route134_Text_H1_2::
	.string "There's a collector who's after\n"
	.string "the SCALES of LUVDISC.$"

Route134_Text_H2_0::
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_H2_1::
	.string "I willingly concede defeat.$"

Route134_Text_H2_2::
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"

Route134_Text_H3_0::
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_H3_1::
	.string "Tuckered out again…$"

Route134_Text_H3_2::
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight…$"

Route134_Text_H4_0::
	.string "You're a POKéMON TRAINER.\n"
	.string "No need for words. We battle now.$"

Route134_Text_H4_1::
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_H4_2::
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed…$"

Route134_Text_H5_0::
	.string "Can your POKéMON dodge our\n"
	.string "lightning-quick attacks?$"

Route134_Text_H5_1::
	.string "I never knew such a technique existed!\n"
	.string "You've defeated us thoroughly.$"

Route134_Text_H5_2::
	.string "I haven't lost my passion for speed.\n"
	.string "I will try harder.$"

Route134_Text_H6_0::
	.string "O-our boat!\n"
	.string "The tide carried it away!$"

Route134_Text_H6_1::
	.string "Awawawawah!\n"
	.string "Please, stop! Please!$"

Route134_Text_H6_2::
	.string "If we can't SURF, how are we supposed\n"
	.string "to get home?\p"
	.string "Actually, I know a fainted POKéMON\n"
	.string "can still SURF, but it feels wrong.$"

Route134_Text_H7_0::
	.string "My POKéMON can't be taken down\n"
	.string "easily!$"

Route134_Text_H7_1::
	.string "You're kidding!\n"
	.string "Explain how I lost!$"

Route134_Text_H7_2::
	.string "Haha!\n"
	.string "You won, all right!\p"
	.string "I'll work my way back up by taking on\n"
	.string "TRAINERS I happen to meet!$"

Route134_Text_H8_0::
	.string "Listen, have you seen another SAILOR\n"
	.string "around here?$"

Route134_Text_H8_1::
	.string "Now, that's something!$"

Route134_Text_H8_2::
	.string "Our boat drifted out to sea.\p"
	.string "My buddy's a timid fellow, so I'm\n"
	.string "worried about him.$"

