Route134_Text_H0::
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_H1::
	.string "There's a collector who's after\n"
	.string "the SCALES of LUVDISC.$"

Route134_Text_H2::
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"

Route134_Text_H3::
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight…$"

Route134_Text_H4::
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed…$"

Route134_Text_H5::
	.string "I haven't lost my passion for speed.\n"
	.string "I will try harder.$"

Route134_Text_H6::
	.string "If we can't SURF, how are we supposed\n"
	.string "to get home?\p"
	.string "Actually, I know a fainted POKéMON\n"
	.string "can still SURF, but it feels wrong.$"

Route134_Text_H7::
	.string "Haha!\n"
	.string "You won, all right!\p"
	.string "I'll work my way back up by taking on\n"
	.string "TRAINERS I happen to meet!$"

Route134_Text_H8::
	.string "Our boat drifted out to sea.\p"
	.string "My buddy's a timid fellow, so I'm\n"
	.string "worried about him.$"

