PacifidlogTown_House3_Text_H0::
	.string "Is that a POKéDEX?\p"
	.string "Did you get to meet a lot of\n"
	.string "different POKéMON?\p"
	.string "I wish I was like you.$"

PacifidlogTown_House3_Text_H1::
	.string "Check out this {STR_VAR_2}!\p"
	.string "It's the {STR_VAR_2} that I caught\n"
	.string "yesterday to celebrate my birthday!\p"
	.string "Oh, I can see that you want it!\n"
	.string "After all, it's priceless!\p"
	.string "I'll tell you what. I might be\n"
	.string "willing to trade it for a\l"
	.string "{STR_VAR_1}.$"

