RocketHideout_B4F_Text_GiovanniIntro::
    .string "So! I must say, I am impressed you\n"
    .string "got here.\p"
    .string "TEAM ROCKET captures POKéMON from\n"
    .string "around the world.\p"
    .string "They're important tools for keeping\n"
    .string "our criminal enterprise going.\p"
    .string "I am the leader, GIOVANNI!\p"
    .string "For your insolence, you will feel a\n"
    .string "world of pain!$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "WHAT!\n"
    .string "This can't be!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "I see that you raise POKéMON with\n"
    .string "utmost care.\p"
    .string "A child like you would never\n"
    .string "understand what I hope to achieve.\p"
    .string "I shall step aside this time!\p"
    .string "I hope we meet again…$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "I know you!\n"
    .string "You ruined our plans at MT. MOON!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "Burned again!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "Do you have something against TEAM\n"
    .string "ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "How can you not see the beauty of\n"
    .string "our evil?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "Ayaya!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "BOSS!\n"
    .string "I'm sorry I failed you!$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "The elevator doesn't work?\n"
    .string "Who has the LIFT KEY?$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "No!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "Oh, no!\n"
    .string "I dropped the LIFT KEY!$"

RocketHideout_B4F_Text_JessieJamesStop::
    .string "Not one more step, twerp!$"

RocketHideout_B4F_Text_JessieJamesIntro::
    .string "JESSIE: You embarrassed us in front\n"
    .string "of the whole cave at MT. MOON!\p"
    .string "JAMES: And in our own BASE, the\n"
    .string "score gets settled!$"

RocketHideout_B4F_Text_JessieJamesDefeat::
    .string "Not even on home ground…$"

RocketHideout_B4F_Text_JessieJamesBlastOff::
    .string "MEOWTH: Retreat! Dis way, dis way!$"

RocketHideout_B4F_Text_SomethingClattered::
    .string "Something heavy clattered to the\n"
    .string "floor where they stood.$"

RocketHideout_B4F_Text_PikachuRefusesStone::
    .string "PIKACHU took one look at the\n"
    .string "THUNDER STONE and turned away.\p"
    .string "It seems happy just as it is.$"
