MtPyre_Summit_Text_H0::
	.string "MT. PYRE is where we calm the\n"
	.string "spirits of POKéMON that have passed\l"
	.string "on…\p"
	.string "This is a high place where one can\n"
	.string "see all of HOENN…\p"
	.string "The disembodied spirits of POKéMON\n"
	.string "must find solace here…\p"
	.string "Is it coincidence that you are here…\p"
	.string "Will you hear out my tale? A tale\n"
	.string "long told in the HOENN region?$"

MtPyre_Summit_Text_H1::
	.string "The BLUE ORB and RED ORB taken by\n"
	.string "those sinister men…\p"
	.string "They must never be apart… I fear\n"
	.string "something terrible will happen…$"

