// Hoenn tileset animations (generated by tools/hoenn_import/import_tileset_anims.py)

static const u16 sTilesetAnims_EmGeneral_Flower_Frame0[] = INCBIN_U16("data/tilesets/primary/em_general/anim/flower/0.4bpp");
static const u16 sTilesetAnims_EmGeneral_Flower_Frame1[] = INCBIN_U16("data/tilesets/primary/em_general/anim/flower/1.4bpp");
static const u16 sTilesetAnims_EmGeneral_Flower_Frame2[] = INCBIN_U16("data/tilesets/primary/em_general/anim/flower/2.4bpp");

static const u16 *const sTilesetAnims_EmGeneral_Flower[] = {
    sTilesetAnims_EmGeneral_Flower_Frame0,
    sTilesetAnims_EmGeneral_Flower_Frame1,
    sTilesetAnims_EmGeneral_Flower_Frame0,
    sTilesetAnims_EmGeneral_Flower_Frame2,
};

static const u16 sTilesetAnims_EmGeneral_Water_Frame0[] = INCBIN_U16("data/tilesets/primary/em_general/anim/water/0.4bpp");
static const u16 sTilesetAnims_EmGeneral_Water_Frame1[] = INCBIN_U16("data/tilesets/primary/em_general/anim/water/1.4bpp");
static const u16 sTilesetAnims_EmGeneral_Water_Frame2[] = INCBIN_U16("data/tilesets/primary/em_general/anim/water/2.4bpp");
static const u16 sTilesetAnims_EmGeneral_Water_Frame3[] = INCBIN_U16("data/tilesets/primary/em_general/anim/water/3.4bpp");
static const u16 sTilesetAnims_EmGeneral_Water_Frame4[] = INCBIN_U16("data/tilesets/primary/em_general/anim/water/4.4bpp");
static const u16 sTilesetAnims_EmGeneral_Water_Frame5[] = INCBIN_U16("data/tilesets/primary/em_general/anim/water/5.4bpp");
static const u16 sTilesetAnims_EmGeneral_Water_Frame6[] = INCBIN_U16("data/tilesets/primary/em_general/anim/water/6.4bpp");
static const u16 sTilesetAnims_EmGeneral_Water_Frame7[] = INCBIN_U16("data/tilesets/primary/em_general/anim/water/7.4bpp");

static const u16 *const sTilesetAnims_EmGeneral_Water[] = {
    sTilesetAnims_EmGeneral_Water_Frame0,
    sTilesetAnims_EmGeneral_Water_Frame1,
    sTilesetAnims_EmGeneral_Water_Frame2,
    sTilesetAnims_EmGeneral_Water_Frame3,
    sTilesetAnims_EmGeneral_Water_Frame4,
    sTilesetAnims_EmGeneral_Water_Frame5,
    sTilesetAnims_EmGeneral_Water_Frame6,
    sTilesetAnims_EmGeneral_Water_Frame7,
};

static const u16 sTilesetAnims_EmGeneral_SandWaterEdge_Frame0[] = INCBIN_U16("data/tilesets/primary/em_general/anim/sand_water_edge/0.4bpp");
static const u16 sTilesetAnims_EmGeneral_SandWaterEdge_Frame1[] = INCBIN_U16("data/tilesets/primary/em_general/anim/sand_water_edge/1.4bpp");
static const u16 sTilesetAnims_EmGeneral_SandWaterEdge_Frame2[] = INCBIN_U16("data/tilesets/primary/em_general/anim/sand_water_edge/2.4bpp");
static const u16 sTilesetAnims_EmGeneral_SandWaterEdge_Frame3[] = INCBIN_U16("data/tilesets/primary/em_general/anim/sand_water_edge/3.4bpp");
static const u16 sTilesetAnims_EmGeneral_SandWaterEdge_Frame4[] = INCBIN_U16("data/tilesets/primary/em_general/anim/sand_water_edge/4.4bpp");
static const u16 sTilesetAnims_EmGeneral_SandWaterEdge_Frame5[] = INCBIN_U16("data/tilesets/primary/em_general/anim/sand_water_edge/5.4bpp");
static const u16 sTilesetAnims_EmGeneral_SandWaterEdge_Frame6[] = INCBIN_U16("data/tilesets/primary/em_general/anim/sand_water_edge/6.4bpp");

static const u16 *const sTilesetAnims_EmGeneral_SandWaterEdge[] = {
    sTilesetAnims_EmGeneral_SandWaterEdge_Frame0,
    sTilesetAnims_EmGeneral_SandWaterEdge_Frame1,
    sTilesetAnims_EmGeneral_SandWaterEdge_Frame2,
    sTilesetAnims_EmGeneral_SandWaterEdge_Frame3,
    sTilesetAnims_EmGeneral_SandWaterEdge_Frame4,
    sTilesetAnims_EmGeneral_SandWaterEdge_Frame5,
    sTilesetAnims_EmGeneral_SandWaterEdge_Frame6,
    sTilesetAnims_EmGeneral_SandWaterEdge_Frame0,
};

static const u16 sTilesetAnims_EmGeneral_Waterfall_Frame0[] = INCBIN_U16("data/tilesets/primary/em_general/anim/waterfall/0.4bpp");
static const u16 sTilesetAnims_EmGeneral_Waterfall_Frame1[] = INCBIN_U16("data/tilesets/primary/em_general/anim/waterfall/1.4bpp");
static const u16 sTilesetAnims_EmGeneral_Waterfall_Frame2[] = INCBIN_U16("data/tilesets/primary/em_general/anim/waterfall/2.4bpp");
static const u16 sTilesetAnims_EmGeneral_Waterfall_Frame3[] = INCBIN_U16("data/tilesets/primary/em_general/anim/waterfall/3.4bpp");

static const u16 *const sTilesetAnims_EmGeneral_Waterfall[] = {
    sTilesetAnims_EmGeneral_Waterfall_Frame0,
    sTilesetAnims_EmGeneral_Waterfall_Frame1,
    sTilesetAnims_EmGeneral_Waterfall_Frame2,
    sTilesetAnims_EmGeneral_Waterfall_Frame3,
};

static const u16 sTilesetAnims_EmGeneral_LandWaterEdge_Frame0[] = INCBIN_U16("data/tilesets/primary/em_general/anim/land_water_edge/0.4bpp");
static const u16 sTilesetAnims_EmGeneral_LandWaterEdge_Frame1[] = INCBIN_U16("data/tilesets/primary/em_general/anim/land_water_edge/1.4bpp");
static const u16 sTilesetAnims_EmGeneral_LandWaterEdge_Frame2[] = INCBIN_U16("data/tilesets/primary/em_general/anim/land_water_edge/2.4bpp");
static const u16 sTilesetAnims_EmGeneral_LandWaterEdge_Frame3[] = INCBIN_U16("data/tilesets/primary/em_general/anim/land_water_edge/3.4bpp");

static const u16 *const sTilesetAnims_EmGeneral_LandWaterEdge[] = {
    sTilesetAnims_EmGeneral_LandWaterEdge_Frame0,
    sTilesetAnims_EmGeneral_LandWaterEdge_Frame1,
    sTilesetAnims_EmGeneral_LandWaterEdge_Frame2,
    sTilesetAnims_EmGeneral_LandWaterEdge_Frame3,
};

static const u16 sTilesetAnims_EmRustboro_WindyWater_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_rustboro/anim/windy_water/0.4bpp");
static const u16 sTilesetAnims_EmRustboro_WindyWater_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_rustboro/anim/windy_water/1.4bpp");
static const u16 sTilesetAnims_EmRustboro_WindyWater_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_rustboro/anim/windy_water/2.4bpp");
static const u16 sTilesetAnims_EmRustboro_WindyWater_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_rustboro/anim/windy_water/3.4bpp");
static const u16 sTilesetAnims_EmRustboro_WindyWater_Frame4[] = INCBIN_U16("data/tilesets/secondary/em_rustboro/anim/windy_water/4.4bpp");
static const u16 sTilesetAnims_EmRustboro_WindyWater_Frame5[] = INCBIN_U16("data/tilesets/secondary/em_rustboro/anim/windy_water/5.4bpp");
static const u16 sTilesetAnims_EmRustboro_WindyWater_Frame6[] = INCBIN_U16("data/tilesets/secondary/em_rustboro/anim/windy_water/6.4bpp");
static const u16 sTilesetAnims_EmRustboro_WindyWater_Frame7[] = INCBIN_U16("data/tilesets/secondary/em_rustboro/anim/windy_water/7.4bpp");

static const u16 *const sTilesetAnims_EmRustboro_WindyWater[] = {
    sTilesetAnims_EmRustboro_WindyWater_Frame0,
    sTilesetAnims_EmRustboro_WindyWater_Frame1,
    sTilesetAnims_EmRustboro_WindyWater_Frame2,
    sTilesetAnims_EmRustboro_WindyWater_Frame3,
    sTilesetAnims_EmRustboro_WindyWater_Frame4,
    sTilesetAnims_EmRustboro_WindyWater_Frame5,
    sTilesetAnims_EmRustboro_WindyWater_Frame6,
    sTilesetAnims_EmRustboro_WindyWater_Frame7,
};

static u16 *const sTilesetAnims_EmRustboro_WindyWater_VDests[] = {
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 128)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 132)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 136)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 140)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 144)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 148)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 152)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 156))
};

static const u16 sTilesetAnims_EmRustboro_Fountain_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_rustboro/anim/fountain/0.4bpp");
static const u16 sTilesetAnims_EmRustboro_Fountain_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_rustboro/anim/fountain/1.4bpp");

static const u16 *const sTilesetAnims_EmRustboro_Fountain[] = {
    sTilesetAnims_EmRustboro_Fountain_Frame0,
    sTilesetAnims_EmRustboro_Fountain_Frame1,
};

static const u16 sTilesetAnims_EmDewford_Flag_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_dewford/anim/flag/0.4bpp");
static const u16 sTilesetAnims_EmDewford_Flag_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_dewford/anim/flag/1.4bpp");
static const u16 sTilesetAnims_EmDewford_Flag_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_dewford/anim/flag/2.4bpp");
static const u16 sTilesetAnims_EmDewford_Flag_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_dewford/anim/flag/3.4bpp");

static const u16 *const sTilesetAnims_EmDewford_Flag[] = {
    sTilesetAnims_EmDewford_Flag_Frame0,
    sTilesetAnims_EmDewford_Flag_Frame1,
    sTilesetAnims_EmDewford_Flag_Frame2,
    sTilesetAnims_EmDewford_Flag_Frame3,
};

static const u16 sTilesetAnims_EmSlateport_Balloons_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_slateport/anim/balloons/0.4bpp");
static const u16 sTilesetAnims_EmSlateport_Balloons_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_slateport/anim/balloons/1.4bpp");
static const u16 sTilesetAnims_EmSlateport_Balloons_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_slateport/anim/balloons/2.4bpp");
static const u16 sTilesetAnims_EmSlateport_Balloons_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_slateport/anim/balloons/3.4bpp");

static const u16 *const sTilesetAnims_EmSlateport_Balloons[] = {
    sTilesetAnims_EmSlateport_Balloons_Frame0,
    sTilesetAnims_EmSlateport_Balloons_Frame1,
    sTilesetAnims_EmSlateport_Balloons_Frame2,
    sTilesetAnims_EmSlateport_Balloons_Frame3,
};

static const u16 sTilesetAnims_EmMauville_Flower1_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_mauville/anim/flower_1/0.4bpp");
static const u16 sTilesetAnims_EmMauville_Flower1_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_mauville/anim/flower_1/1.4bpp");
static const u16 sTilesetAnims_EmMauville_Flower1_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_mauville/anim/flower_1/2.4bpp");
static const u16 sTilesetAnims_EmMauville_Flower1_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_mauville/anim/flower_1/3.4bpp");

static const u16 *const sTilesetAnims_EmMauville_Flower1[] = {
    sTilesetAnims_EmMauville_Flower1_Frame0,
    sTilesetAnims_EmMauville_Flower1_Frame0,
    sTilesetAnims_EmMauville_Flower1_Frame1,
    sTilesetAnims_EmMauville_Flower1_Frame2,
    sTilesetAnims_EmMauville_Flower1_Frame3,
    sTilesetAnims_EmMauville_Flower1_Frame3,
    sTilesetAnims_EmMauville_Flower1_Frame3,
    sTilesetAnims_EmMauville_Flower1_Frame3,
    sTilesetAnims_EmMauville_Flower1_Frame3,
    sTilesetAnims_EmMauville_Flower1_Frame3,
    sTilesetAnims_EmMauville_Flower1_Frame2,
    sTilesetAnims_EmMauville_Flower1_Frame1,
};

static const u16 sTilesetAnims_EmMauville_Flower2_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_mauville/anim/flower_2/0.4bpp");
static const u16 sTilesetAnims_EmMauville_Flower2_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_mauville/anim/flower_2/1.4bpp");
static const u16 sTilesetAnims_EmMauville_Flower2_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_mauville/anim/flower_2/2.4bpp");
static const u16 sTilesetAnims_EmMauville_Flower2_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_mauville/anim/flower_2/3.4bpp");

static const u16 *const sTilesetAnims_EmMauville_Flower2[] = {
    sTilesetAnims_EmMauville_Flower2_Frame0,
    sTilesetAnims_EmMauville_Flower2_Frame0,
    sTilesetAnims_EmMauville_Flower2_Frame1,
    sTilesetAnims_EmMauville_Flower2_Frame2,
    sTilesetAnims_EmMauville_Flower2_Frame3,
    sTilesetAnims_EmMauville_Flower2_Frame3,
    sTilesetAnims_EmMauville_Flower2_Frame3,
    sTilesetAnims_EmMauville_Flower2_Frame3,
    sTilesetAnims_EmMauville_Flower2_Frame3,
    sTilesetAnims_EmMauville_Flower2_Frame3,
    sTilesetAnims_EmMauville_Flower2_Frame2,
    sTilesetAnims_EmMauville_Flower2_Frame1,
};

static u16 *const sTilesetAnims_EmMauville_Flower1_VDests[] = {
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 96)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 100)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 104)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 108)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 112)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 116)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 120)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 124))
};

static u16 *const sTilesetAnims_EmMauville_Flower2_VDests[] = {
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 128)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 132)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 136)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 140)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 144)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 148)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 152)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 156))
};

static const u16 sTilesetAnims_EmMauville_Flower1_Frame4[] = INCBIN_U16("data/tilesets/secondary/em_mauville/anim/flower_1/4.4bpp");

static const u16 *const sTilesetAnims_EmMauville_Flower1_B[] = {
    sTilesetAnims_EmMauville_Flower1_Frame0,
    sTilesetAnims_EmMauville_Flower1_Frame0,
    sTilesetAnims_EmMauville_Flower1_Frame4,
    sTilesetAnims_EmMauville_Flower1_Frame4,
};

static const u16 sTilesetAnims_EmMauville_Flower2_Frame4[] = INCBIN_U16("data/tilesets/secondary/em_mauville/anim/flower_2/4.4bpp");

static const u16 *const sTilesetAnims_EmMauville_Flower2_B[] = {
    sTilesetAnims_EmMauville_Flower2_Frame0,
    sTilesetAnims_EmMauville_Flower2_Frame0,
    sTilesetAnims_EmMauville_Flower2_Frame4,
    sTilesetAnims_EmMauville_Flower2_Frame4,
};

static const u16 sTilesetAnims_EmLavaridge_Steam_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_lavaridge/anim/steam/0.4bpp");
static const u16 sTilesetAnims_EmLavaridge_Steam_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_lavaridge/anim/steam/1.4bpp");
static const u16 sTilesetAnims_EmLavaridge_Steam_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_lavaridge/anim/steam/2.4bpp");
static const u16 sTilesetAnims_EmLavaridge_Steam_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_lavaridge/anim/steam/3.4bpp");

static const u16 *const sTilesetAnims_EmLavaridge_Steam[] = {
    sTilesetAnims_EmLavaridge_Steam_Frame0,
    sTilesetAnims_EmLavaridge_Steam_Frame1,
    sTilesetAnims_EmLavaridge_Steam_Frame2,
    sTilesetAnims_EmLavaridge_Steam_Frame3,
};

static const u16 sTilesetAnims_EmLavaridge_Cave_Lava_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_cave/anim/lava/0.4bpp");
static const u16 sTilesetAnims_EmLavaridge_Cave_Lava_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_cave/anim/lava/1.4bpp");
static const u16 sTilesetAnims_EmLavaridge_Cave_Lava_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_cave/anim/lava/2.4bpp");
static const u16 sTilesetAnims_EmLavaridge_Cave_Lava_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_cave/anim/lava/3.4bpp");

static const u16 *const sTilesetAnims_EmLavaridge_Cave_Lava[] = {
    sTilesetAnims_EmLavaridge_Cave_Lava_Frame0,
    sTilesetAnims_EmLavaridge_Cave_Lava_Frame1,
    sTilesetAnims_EmLavaridge_Cave_Lava_Frame2,
    sTilesetAnims_EmLavaridge_Cave_Lava_Frame3,
};

static const u16 sTilesetAnims_EmEverGrande_Flowers_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_ever_grande/anim/flowers/0.4bpp");
static const u16 sTilesetAnims_EmEverGrande_Flowers_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_ever_grande/anim/flowers/1.4bpp");
static const u16 sTilesetAnims_EmEverGrande_Flowers_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_ever_grande/anim/flowers/2.4bpp");
static const u16 sTilesetAnims_EmEverGrande_Flowers_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_ever_grande/anim/flowers/3.4bpp");
static const u16 sTilesetAnims_EmEverGrande_Flowers_Frame4[] = INCBIN_U16("data/tilesets/secondary/em_ever_grande/anim/flowers/4.4bpp");
static const u16 sTilesetAnims_EmEverGrande_Flowers_Frame5[] = INCBIN_U16("data/tilesets/secondary/em_ever_grande/anim/flowers/5.4bpp");
static const u16 sTilesetAnims_EmEverGrande_Flowers_Frame6[] = INCBIN_U16("data/tilesets/secondary/em_ever_grande/anim/flowers/6.4bpp");
static const u16 sTilesetAnims_EmEverGrande_Flowers_Frame7[] = INCBIN_U16("data/tilesets/secondary/em_ever_grande/anim/flowers/7.4bpp");

static const u16 *const sTilesetAnims_EmEverGrande_Flowers[] = {
    sTilesetAnims_EmEverGrande_Flowers_Frame0,
    sTilesetAnims_EmEverGrande_Flowers_Frame1,
    sTilesetAnims_EmEverGrande_Flowers_Frame2,
    sTilesetAnims_EmEverGrande_Flowers_Frame3,
    sTilesetAnims_EmEverGrande_Flowers_Frame4,
    sTilesetAnims_EmEverGrande_Flowers_Frame5,
    sTilesetAnims_EmEverGrande_Flowers_Frame6,
    sTilesetAnims_EmEverGrande_Flowers_Frame7,
};

static u16 *const sTilesetAnims_EmEverGrande_VDests[] = {
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 224)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 228)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 232)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 236)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 240)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 244)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 248)),
    (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 252))
};

static const u16 sTilesetAnims_EmPacifidlog_LogBridges_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_pacifidlog/anim/log_bridges/0.4bpp");
static const u16 sTilesetAnims_EmPacifidlog_LogBridges_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_pacifidlog/anim/log_bridges/1.4bpp");
static const u16 sTilesetAnims_EmPacifidlog_LogBridges_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_pacifidlog/anim/log_bridges/2.4bpp");

static const u16 *const sTilesetAnims_EmPacifidlog_LogBridges[] = {
    sTilesetAnims_EmPacifidlog_LogBridges_Frame0,
    sTilesetAnims_EmPacifidlog_LogBridges_Frame1,
    sTilesetAnims_EmPacifidlog_LogBridges_Frame2,
    sTilesetAnims_EmPacifidlog_LogBridges_Frame1,
};

static const u16 sTilesetAnims_EmPacifidlog_WaterCurrents_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_pacifidlog/anim/water_currents/0.4bpp");
static const u16 sTilesetAnims_EmPacifidlog_WaterCurrents_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_pacifidlog/anim/water_currents/1.4bpp");
static const u16 sTilesetAnims_EmPacifidlog_WaterCurrents_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_pacifidlog/anim/water_currents/2.4bpp");
static const u16 sTilesetAnims_EmPacifidlog_WaterCurrents_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_pacifidlog/anim/water_currents/3.4bpp");
static const u16 sTilesetAnims_EmPacifidlog_WaterCurrents_Frame4[] = INCBIN_U16("data/tilesets/secondary/em_pacifidlog/anim/water_currents/4.4bpp");
static const u16 sTilesetAnims_EmPacifidlog_WaterCurrents_Frame5[] = INCBIN_U16("data/tilesets/secondary/em_pacifidlog/anim/water_currents/5.4bpp");
static const u16 sTilesetAnims_EmPacifidlog_WaterCurrents_Frame6[] = INCBIN_U16("data/tilesets/secondary/em_pacifidlog/anim/water_currents/6.4bpp");
static const u16 sTilesetAnims_EmPacifidlog_WaterCurrents_Frame7[] = INCBIN_U16("data/tilesets/secondary/em_pacifidlog/anim/water_currents/7.4bpp");

static const u16 *const sTilesetAnims_EmPacifidlog_WaterCurrents[] = {
    sTilesetAnims_EmPacifidlog_WaterCurrents_Frame0,
    sTilesetAnims_EmPacifidlog_WaterCurrents_Frame1,
    sTilesetAnims_EmPacifidlog_WaterCurrents_Frame2,
    sTilesetAnims_EmPacifidlog_WaterCurrents_Frame3,
    sTilesetAnims_EmPacifidlog_WaterCurrents_Frame4,
    sTilesetAnims_EmPacifidlog_WaterCurrents_Frame5,
    sTilesetAnims_EmPacifidlog_WaterCurrents_Frame6,
    sTilesetAnims_EmPacifidlog_WaterCurrents_Frame7,
};

static const u16 sTilesetAnims_EmSootopolis_StormyWater_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis/anim/stormy_water/0_kyogre.4bpp", "data/tilesets/secondary/em_sootopolis/anim/stormy_water/0_groudon.4bpp");
static const u16 sTilesetAnims_EmSootopolis_StormyWater_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis/anim/stormy_water/1_kyogre.4bpp", "data/tilesets/secondary/em_sootopolis/anim/stormy_water/1_groudon.4bpp");
static const u16 sTilesetAnims_EmSootopolis_StormyWater_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis/anim/stormy_water/2_kyogre.4bpp", "data/tilesets/secondary/em_sootopolis/anim/stormy_water/2_groudon.4bpp");
static const u16 sTilesetAnims_EmSootopolis_StormyWater_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis/anim/stormy_water/3_kyogre.4bpp", "data/tilesets/secondary/em_sootopolis/anim/stormy_water/3_groudon.4bpp");
static const u16 sTilesetAnims_EmSootopolis_StormyWater_Frame4[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis/anim/stormy_water/4_kyogre.4bpp", "data/tilesets/secondary/em_sootopolis/anim/stormy_water/4_groudon.4bpp");
static const u16 sTilesetAnims_EmSootopolis_StormyWater_Frame5[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis/anim/stormy_water/5_kyogre.4bpp", "data/tilesets/secondary/em_sootopolis/anim/stormy_water/5_groudon.4bpp");
static const u16 sTilesetAnims_EmSootopolis_StormyWater_Frame6[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis/anim/stormy_water/6_kyogre.4bpp", "data/tilesets/secondary/em_sootopolis/anim/stormy_water/6_groudon.4bpp");
static const u16 sTilesetAnims_EmSootopolis_StormyWater_Frame7[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis/anim/stormy_water/7_kyogre.4bpp", "data/tilesets/secondary/em_sootopolis/anim/stormy_water/7_groudon.4bpp");

static const u16 *const sTilesetAnims_EmSootopolis_StormyWater[] = {
    sTilesetAnims_EmSootopolis_StormyWater_Frame0,
    sTilesetAnims_EmSootopolis_StormyWater_Frame1,
    sTilesetAnims_EmSootopolis_StormyWater_Frame2,
    sTilesetAnims_EmSootopolis_StormyWater_Frame3,
    sTilesetAnims_EmSootopolis_StormyWater_Frame4,
    sTilesetAnims_EmSootopolis_StormyWater_Frame5,
    sTilesetAnims_EmSootopolis_StormyWater_Frame6,
    sTilesetAnims_EmSootopolis_StormyWater_Frame7,
};

static const u16 sTilesetAnims_EmBattleFrontierOutsideWest_Flag_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_battle_frontier_outside_west/anim/flag/0.4bpp");
static const u16 sTilesetAnims_EmBattleFrontierOutsideWest_Flag_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_battle_frontier_outside_west/anim/flag/1.4bpp");
static const u16 sTilesetAnims_EmBattleFrontierOutsideWest_Flag_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_battle_frontier_outside_west/anim/flag/2.4bpp");
static const u16 sTilesetAnims_EmBattleFrontierOutsideWest_Flag_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_battle_frontier_outside_west/anim/flag/3.4bpp");

static const u16 *const sTilesetAnims_EmBattleFrontierOutsideWest_Flag[] = {
    sTilesetAnims_EmBattleFrontierOutsideWest_Flag_Frame0,
    sTilesetAnims_EmBattleFrontierOutsideWest_Flag_Frame1,
    sTilesetAnims_EmBattleFrontierOutsideWest_Flag_Frame2,
    sTilesetAnims_EmBattleFrontierOutsideWest_Flag_Frame3,
};

static const u16 sTilesetAnims_EmBattleFrontierOutsideEast_Flag_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_battle_frontier_outside_east/anim/flag/0.4bpp");
static const u16 sTilesetAnims_EmBattleFrontierOutsideEast_Flag_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_battle_frontier_outside_east/anim/flag/1.4bpp");
static const u16 sTilesetAnims_EmBattleFrontierOutsideEast_Flag_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_battle_frontier_outside_east/anim/flag/2.4bpp");
static const u16 sTilesetAnims_EmBattleFrontierOutsideEast_Flag_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_battle_frontier_outside_east/anim/flag/3.4bpp");

static const u16 *const sTilesetAnims_EmBattleFrontierOutsideEast_Flag[] = {
    sTilesetAnims_EmBattleFrontierOutsideEast_Flag_Frame0,
    sTilesetAnims_EmBattleFrontierOutsideEast_Flag_Frame1,
    sTilesetAnims_EmBattleFrontierOutsideEast_Flag_Frame2,
    sTilesetAnims_EmBattleFrontierOutsideEast_Flag_Frame3,
};

static const u16 sTilesetAnims_EmBuilding_TvTurnedOn_Frame0[] = INCBIN_U16("data/tilesets/primary/em_building/anim/tv_turned_on/0.4bpp");
static const u16 sTilesetAnims_EmBuilding_TvTurnedOn_Frame1[] = INCBIN_U16("data/tilesets/primary/em_building/anim/tv_turned_on/1.4bpp");

static const u16 *const sTilesetAnims_EmBuilding_TvTurnedOn[] = {
    sTilesetAnims_EmBuilding_TvTurnedOn_Frame0,
    sTilesetAnims_EmBuilding_TvTurnedOn_Frame1,
};

static const u16 sTilesetAnims_EmBikeShop_BlinkingLights_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_bike_shop/anim/blinking_lights/0.4bpp");
static const u16 sTilesetAnims_EmBikeShop_BlinkingLights_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_bike_shop/anim/blinking_lights/1.4bpp");

static const u16 *const sTilesetAnims_EmBikeShop_BlinkingLights[] = {
    sTilesetAnims_EmBikeShop_BlinkingLights_Frame0,
    sTilesetAnims_EmBikeShop_BlinkingLights_Frame1,
};

static const u16 sTilesetAnims_EmUnderwater_Seaweed_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_underwater/anim/seaweed/0.4bpp");
static const u16 sTilesetAnims_EmUnderwater_Seaweed_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_underwater/anim/seaweed/1.4bpp");
static const u16 sTilesetAnims_EmUnderwater_Seaweed_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_underwater/anim/seaweed/2.4bpp");
static const u16 sTilesetAnims_EmUnderwater_Seaweed_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_underwater/anim/seaweed/3.4bpp");

static const u16 *const sTilesetAnims_EmUnderwater_Seaweed[] = {
    sTilesetAnims_EmUnderwater_Seaweed_Frame0,
    sTilesetAnims_EmUnderwater_Seaweed_Frame1,
    sTilesetAnims_EmUnderwater_Seaweed_Frame2,
    sTilesetAnims_EmUnderwater_Seaweed_Frame3,
};

static const u16 sTilesetAnims_EmSootopolisGym_SideWaterfall_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis_gym/anim/side_waterfall/0.4bpp");
static const u16 sTilesetAnims_EmSootopolisGym_SideWaterfall_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis_gym/anim/side_waterfall/1.4bpp");
static const u16 sTilesetAnims_EmSootopolisGym_SideWaterfall_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis_gym/anim/side_waterfall/2.4bpp");

static const u16 *const sTilesetAnims_EmSootopolisGym_SideWaterfall[] = {
    sTilesetAnims_EmSootopolisGym_SideWaterfall_Frame0,
    sTilesetAnims_EmSootopolisGym_SideWaterfall_Frame1,
    sTilesetAnims_EmSootopolisGym_SideWaterfall_Frame2,
};

static const u16 sTilesetAnims_EmSootopolisGym_FrontWaterfall_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis_gym/anim/front_waterfall/0.4bpp");
static const u16 sTilesetAnims_EmSootopolisGym_FrontWaterfall_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis_gym/anim/front_waterfall/1.4bpp");
static const u16 sTilesetAnims_EmSootopolisGym_FrontWaterfall_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_sootopolis_gym/anim/front_waterfall/2.4bpp");

static const u16 *const sTilesetAnims_EmSootopolisGym_FrontWaterfall[] = {
    sTilesetAnims_EmSootopolisGym_FrontWaterfall_Frame0,
    sTilesetAnims_EmSootopolisGym_FrontWaterfall_Frame1,
    sTilesetAnims_EmSootopolisGym_FrontWaterfall_Frame2,
};

static const u16 sTilesetAnims_EmMauvilleGym_ElectricGates_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_mauville_gym/anim/electric_gates/0.4bpp");
static const u16 sTilesetAnims_EmMauvilleGym_ElectricGates_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_mauville_gym/anim/electric_gates/1.4bpp");

static const u16 *const sTilesetAnims_EmMauvilleGym_ElectricGates[] = {
    sTilesetAnims_EmMauvilleGym_ElectricGates_Frame0,
    sTilesetAnims_EmMauvilleGym_ElectricGates_Frame1,
};

static const u16 sTilesetAnims_EmEliteFour_FloorLight_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_elite_four/anim/floor_light/0.4bpp");
static const u16 sTilesetAnims_EmEliteFour_FloorLight_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_elite_four/anim/floor_light/1.4bpp");

static const u16 *const sTilesetAnims_EmEliteFour_FloorLight[] = {
    sTilesetAnims_EmEliteFour_FloorLight_Frame0,
    sTilesetAnims_EmEliteFour_FloorLight_Frame1,
};

static const u16 sTilesetAnims_EmEliteFour_WallLights_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_elite_four/anim/wall_lights/0.4bpp");
static const u16 sTilesetAnims_EmEliteFour_WallLights_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_elite_four/anim/wall_lights/1.4bpp");
static const u16 sTilesetAnims_EmEliteFour_WallLights_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_elite_four/anim/wall_lights/2.4bpp");
static const u16 sTilesetAnims_EmEliteFour_WallLights_Frame3[] = INCBIN_U16("data/tilesets/secondary/em_elite_four/anim/wall_lights/3.4bpp");

static const u16 *const sTilesetAnims_EmEliteFour_WallLights[] = {
    sTilesetAnims_EmEliteFour_WallLights_Frame0,
    sTilesetAnims_EmEliteFour_WallLights_Frame1,
    sTilesetAnims_EmEliteFour_WallLights_Frame2,
    sTilesetAnims_EmEliteFour_WallLights_Frame3,
};

static const u16 sTilesetAnims_EmBattlePyramid_Torch_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_battle_pyramid/anim/torch/0.4bpp");
static const u16 sTilesetAnims_EmBattlePyramid_Torch_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_battle_pyramid/anim/torch/1.4bpp");
static const u16 sTilesetAnims_EmBattlePyramid_Torch_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_battle_pyramid/anim/torch/2.4bpp");

static const u16 *const sTilesetAnims_EmBattlePyramid_Torch[] = {
    sTilesetAnims_EmBattlePyramid_Torch_Frame0,
    sTilesetAnims_EmBattlePyramid_Torch_Frame1,
    sTilesetAnims_EmBattlePyramid_Torch_Frame2,
};

static const u16 sTilesetAnims_EmBattlePyramid_StatueShadow_Frame0[] = INCBIN_U16("data/tilesets/secondary/em_battle_pyramid/anim/statue_shadow/0.4bpp");
static const u16 sTilesetAnims_EmBattlePyramid_StatueShadow_Frame1[] = INCBIN_U16("data/tilesets/secondary/em_battle_pyramid/anim/statue_shadow/1.4bpp");
static const u16 sTilesetAnims_EmBattlePyramid_StatueShadow_Frame2[] = INCBIN_U16("data/tilesets/secondary/em_battle_pyramid/anim/statue_shadow/2.4bpp");

static const u16 *const sTilesetAnims_EmBattlePyramid_StatueShadow[] = {
    sTilesetAnims_EmBattlePyramid_StatueShadow_Frame0,
    sTilesetAnims_EmBattlePyramid_StatueShadow_Frame1,
    sTilesetAnims_EmBattlePyramid_StatueShadow_Frame2,
};


void InitTilesetAnim_EmGeneral(void)
{
    sPrimaryTilesetAnimCounter = 0;
    sPrimaryTilesetAnimCounterMax = 256;
    sPrimaryTilesetAnimCallback = TilesetAnim_EmGeneral;
}

void InitTilesetAnim_EmPetalburg(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = NULL;
}

void InitTilesetAnim_EmRustboro(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmRustboro;
}

void InitTilesetAnim_EmDewford(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmDewford;
}

void InitTilesetAnim_EmSlateport(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmSlateport;
}

void InitTilesetAnim_EmMauville(void)
{
    sSecondaryTilesetAnimCounter = sPrimaryTilesetAnimCounter;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmMauville;
}

void InitTilesetAnim_EmLavaridge(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmLavaridge;
}

void InitTilesetAnim_EmFallarbor(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = NULL;
}

void InitTilesetAnim_EmFortree(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = NULL;
}

void InitTilesetAnim_EmLilycove(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = NULL;
}

void InitTilesetAnim_EmMossdeep(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = NULL;
}

void InitTilesetAnim_EmEverGrande(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmEverGrande;
}

void InitTilesetAnim_EmPacifidlog(void)
{
    sSecondaryTilesetAnimCounter = sPrimaryTilesetAnimCounter;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmPacifidlog;
}

void InitTilesetAnim_EmSootopolis(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmSootopolis;
}

void InitTilesetAnim_EmBattleFrontierOutsideWest(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmBattleFrontierOutsideWest;
}

void InitTilesetAnim_EmBattleFrontierOutsideEast(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmBattleFrontierOutsideEast;
}

void InitTilesetAnim_EmBuilding(void)
{
    sPrimaryTilesetAnimCounter = 0;
    sPrimaryTilesetAnimCounterMax = 256;
    sPrimaryTilesetAnimCallback = TilesetAnim_EmBuilding;
}

void InitTilesetAnim_EmCave(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmCave;
}

void InitTilesetAnim_EmBikeShop(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmBikeShop;
}

void InitTilesetAnim_EmUnderwater(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = 128;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmUnderwater;
}

void InitTilesetAnim_EmSootopolisGym(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = 240;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmSootopolisGym;
}

void InitTilesetAnim_EmMauvilleGym(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmMauvilleGym;
}

void InitTilesetAnim_EmEliteFour(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = 128;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmEliteFour;
}

void InitTilesetAnim_EmBattlePyramid(void)
{
    sSecondaryTilesetAnimCounter = 0;
    sSecondaryTilesetAnimCounterMax = sPrimaryTilesetAnimCounterMax;
    sSecondaryTilesetAnimCallback = TilesetAnim_EmBattlePyramid;
}

static void TilesetAnim_EmGeneral(u16 timer)
{
    if (timer % 16 == 0)
        QueueAnimTiles_EmGeneral_Flower(timer / 16);
    if (timer % 16 == 1)
        QueueAnimTiles_EmGeneral_Water(timer / 16);
    if (timer % 16 == 2)
        QueueAnimTiles_EmGeneral_SandWaterEdge(timer / 16);
    if (timer % 16 == 3)
        QueueAnimTiles_EmGeneral_Waterfall(timer / 16);
    if (timer % 16 == 4)
        QueueAnimTiles_EmGeneral_LandWaterEdge(timer / 16);
}

static void TilesetAnim_EmRustboro(u16 timer)
{
    if (timer % 8 == 0)
    {
        QueueAnimTiles_EmRustboro_WindyWater(timer / 8, 0);
        QueueAnimTiles_EmRustboro_Fountain(timer / 8);
    }
    if (timer % 8 == 1)
        QueueAnimTiles_EmRustboro_WindyWater(timer / 8, 1);
    if (timer % 8 == 2)
        QueueAnimTiles_EmRustboro_WindyWater(timer / 8, 2);
    if (timer % 8 == 3)
        QueueAnimTiles_EmRustboro_WindyWater(timer / 8, 3);
    if (timer % 8 == 4)
        QueueAnimTiles_EmRustboro_WindyWater(timer / 8, 4);
    if (timer % 8 == 5)
        QueueAnimTiles_EmRustboro_WindyWater(timer / 8, 5);
    if (timer % 8 == 6)
        QueueAnimTiles_EmRustboro_WindyWater(timer / 8, 6);
    if (timer % 8 == 7)
        QueueAnimTiles_EmRustboro_WindyWater(timer / 8, 7);
}

static void TilesetAnim_EmDewford(u16 timer)
{
    if (timer % 8 == 0)
        QueueAnimTiles_EmDewford_Flag(timer / 8);
}

static void TilesetAnim_EmSlateport(u16 timer)
{
    if (timer % 16 == 0)
        QueueAnimTiles_EmSlateport_Balloons(timer / 16);
}

static void TilesetAnim_EmMauville(u16 timer)
{
    if (timer % 8 == 0)
        QueueAnimTiles_EmMauville_Flowers(timer / 8, 0);
    if (timer % 8 == 1)
        QueueAnimTiles_EmMauville_Flowers(timer / 8, 1);
    if (timer % 8 == 2)
        QueueAnimTiles_EmMauville_Flowers(timer / 8, 2);
    if (timer % 8 == 3)
        QueueAnimTiles_EmMauville_Flowers(timer / 8, 3);
    if (timer % 8 == 4)
        QueueAnimTiles_EmMauville_Flowers(timer / 8, 4);
    if (timer % 8 == 5)
        QueueAnimTiles_EmMauville_Flowers(timer / 8, 5);
    if (timer % 8 == 6)
        QueueAnimTiles_EmMauville_Flowers(timer / 8, 6);
    if (timer % 8 == 7)
        QueueAnimTiles_EmMauville_Flowers(timer / 8, 7);
}

static void TilesetAnim_EmLavaridge(u16 timer)
{
    if (timer % 16 == 0)
        QueueAnimTiles_EmLavaridge_Steam(timer / 16);
    if (timer % 16 == 1)
        QueueAnimTiles_EmLavaridge_Lava(timer / 16);
}

static void TilesetAnim_EmEverGrande(u16 timer)
{
    if (timer % 8 == 0)
        QueueAnimTiles_EmEverGrande_Flowers(timer / 8, 0);
    if (timer % 8 == 1)
        QueueAnimTiles_EmEverGrande_Flowers(timer / 8, 1);
    if (timer % 8 == 2)
        QueueAnimTiles_EmEverGrande_Flowers(timer / 8, 2);
    if (timer % 8 == 3)
        QueueAnimTiles_EmEverGrande_Flowers(timer / 8, 3);
    if (timer % 8 == 4)
        QueueAnimTiles_EmEverGrande_Flowers(timer / 8, 4);
    if (timer % 8 == 5)
        QueueAnimTiles_EmEverGrande_Flowers(timer / 8, 5);
    if (timer % 8 == 6)
        QueueAnimTiles_EmEverGrande_Flowers(timer / 8, 6);
    if (timer % 8 == 7)
        QueueAnimTiles_EmEverGrande_Flowers(timer / 8, 7);
}

static void TilesetAnim_EmPacifidlog(u16 timer)
{
    if (timer % 16 == 0)
        QueueAnimTiles_EmPacifidlog_LogBridges(timer / 16);
    if (timer % 16 == 1)
        QueueAnimTiles_EmPacifidlog_WaterCurrents(timer / 16);
}

static void TilesetAnim_EmSootopolis(u16 timer)
{
    if (timer % 16 == 0)
        QueueAnimTiles_EmSootopolis_StormyWater(timer / 16);
}

static void TilesetAnim_EmBattleFrontierOutsideWest(u16 timer)
{
    if (timer % 8 == 0)
        QueueAnimTiles_EmBattleFrontierOutsideWest_Flag(timer / 8);
}

static void TilesetAnim_EmBattleFrontierOutsideEast(u16 timer)
{
    if (timer % 8 == 0)
        QueueAnimTiles_EmBattleFrontierOutsideEast_Flag(timer / 8);
}

static void TilesetAnim_EmBuilding(u16 timer)
{
    if (timer % 8 == 0)
        QueueAnimTiles_EmBuilding_TVTurnedOn(timer / 8);
}

static void TilesetAnim_EmCave(u16 timer)
{
    if (timer % 16 == 1)
        QueueAnimTiles_EmCave_Lava(timer / 16);
}

static void TilesetAnim_EmBikeShop(u16 timer)
{
    if (timer % 4 == 0)
        QueueAnimTiles_EmBikeShop_BlinkingLights(timer / 4);
}

static void TilesetAnim_EmUnderwater(u16 timer)
{
    if (timer % 16 == 0)
        QueueAnimTiles_EmUnderwater_Seaweed(timer / 16);
}

static void TilesetAnim_EmSootopolisGym(u16 timer)
{
    if (timer % 8 == 0)
        QueueAnimTiles_EmSootopolisGym_Waterfalls(timer / 8);
}

static void TilesetAnim_EmMauvilleGym(u16 timer)
{
    if (timer % 2 == 0)
        QueueAnimTiles_EmMauvilleGym_ElectricGates(timer / 2);
}

static void TilesetAnim_EmEliteFour(u16 timer)
{
    if (timer % 64 == 1)
        QueueAnimTiles_EmEliteFour_GroundLights(timer / 64);
    if (timer % 8 == 1)
        QueueAnimTiles_EmEliteFour_WallLights(timer / 8);
}

static void TilesetAnim_EmBattlePyramid(u16 timer)
{
    if (timer % 8 == 0)
    {
        QueueAnimTiles_EmBattlePyramid_Torch(timer / 8);
        QueueAnimTiles_EmBattlePyramid_StatueShadow(timer / 8);
    }
}

static void QueueAnimTiles_EmGeneral_Flower(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmGeneral_Flower);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmGeneral_Flower[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(508)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmGeneral_Water(u16 timer)
{
    u8 i = timer % ARRAY_COUNT(sTilesetAnims_EmGeneral_Water);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmGeneral_Water[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(432)), 30 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmGeneral_SandWaterEdge(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmGeneral_SandWaterEdge);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmGeneral_SandWaterEdge[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(464)), 10 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmGeneral_Waterfall(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmGeneral_Waterfall);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmGeneral_Waterfall[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(496)), 6 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmGeneral_LandWaterEdge(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmGeneral_LandWaterEdge);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmGeneral_LandWaterEdge[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(480)), 10 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmRustboro_WindyWater(u16 timer_div, u8 timer_mod)
{
    timer_div -= timer_mod;
    timer_div %= ARRAY_COUNT(sTilesetAnims_EmRustboro_WindyWater);
    if (sTilesetAnims_EmRustboro_WindyWater[timer_div])
        AppendTilesetAnimToBuffer(sTilesetAnims_EmRustboro_WindyWater[timer_div], sTilesetAnims_EmRustboro_WindyWater_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmRustboro_Fountain(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmRustboro_Fountain);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmRustboro_Fountain[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 448)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmDewford_Flag(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmDewford_Flag);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmDewford_Flag[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 170)), 6 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmSlateport_Balloons(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmSlateport_Balloons);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmSlateport_Balloons[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 224)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmMauville_Flowers(u16 timer_div, u8 timer_mod)
{
    timer_div -= timer_mod;
    if (timer_div < min(ARRAY_COUNT(sTilesetAnims_EmMauville_Flower1), ARRAY_COUNT(sTilesetAnims_EmMauville_Flower2)))
    {
        timer_div %= min(ARRAY_COUNT(sTilesetAnims_EmMauville_Flower1), ARRAY_COUNT(sTilesetAnims_EmMauville_Flower2));
        AppendTilesetAnimToBuffer(sTilesetAnims_EmMauville_Flower1[timer_div], sTilesetAnims_EmMauville_Flower1_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
        AppendTilesetAnimToBuffer(sTilesetAnims_EmMauville_Flower2[timer_div], sTilesetAnims_EmMauville_Flower2_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
    }
    else
    {
        timer_div %= min(ARRAY_COUNT(sTilesetAnims_EmMauville_Flower1_B), ARRAY_COUNT(sTilesetAnims_EmMauville_Flower2_B));
        AppendTilesetAnimToBuffer(sTilesetAnims_EmMauville_Flower1_B[timer_div], sTilesetAnims_EmMauville_Flower1_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
        AppendTilesetAnimToBuffer(sTilesetAnims_EmMauville_Flower2_B[timer_div], sTilesetAnims_EmMauville_Flower2_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
    }
}

static void QueueAnimTiles_EmLavaridge_Steam(u8 timer)
{
    u8 i = timer % ARRAY_COUNT(sTilesetAnims_EmLavaridge_Steam);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmLavaridge_Steam[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 288)), 4 * TILE_SIZE_4BPP);

    i = (timer + 2) % (int)ARRAY_COUNT(sTilesetAnims_EmLavaridge_Steam);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmLavaridge_Steam[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 292)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmLavaridge_Lava(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmLavaridge_Cave_Lava);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmLavaridge_Cave_Lava[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 160)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmEverGrande_Flowers(u16 timer_div, u8 timer_mod)
{
    timer_div -= timer_mod;
    timer_div %= ARRAY_COUNT(sTilesetAnims_EmEverGrande_Flowers);

    AppendTilesetAnimToBuffer(sTilesetAnims_EmEverGrande_Flowers[timer_div], sTilesetAnims_EmEverGrande_VDests[timer_mod], 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmPacifidlog_LogBridges(u8 timer)
{
    u8 i = timer % ARRAY_COUNT(sTilesetAnims_EmPacifidlog_LogBridges);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmPacifidlog_LogBridges[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 464)), 30 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmPacifidlog_WaterCurrents(u8 timer)
{
    u8 i = timer % ARRAY_COUNT(sTilesetAnims_EmPacifidlog_WaterCurrents);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmPacifidlog_WaterCurrents[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 496)), 8 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmSootopolis_StormyWater(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmSootopolis_StormyWater);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmSootopolis_StormyWater[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 240)), 96 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmBattleFrontierOutsideWest_Flag(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmBattleFrontierOutsideWest_Flag);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmBattleFrontierOutsideWest_Flag[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 218)), 6 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmBattleFrontierOutsideEast_Flag(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmBattleFrontierOutsideEast_Flag);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmBattleFrontierOutsideEast_Flag[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 218)), 6 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmBuilding_TVTurnedOn(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmBuilding_TvTurnedOn);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmBuilding_TvTurnedOn[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(496)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmCave_Lava(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmLavaridge_Cave_Lava);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmLavaridge_Cave_Lava[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 416)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmBikeShop_BlinkingLights(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmBikeShop_BlinkingLights);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmBikeShop_BlinkingLights[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 496)), 9 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmUnderwater_Seaweed(u8 timer)
{
    u8 i = timer % ARRAY_COUNT(sTilesetAnims_EmUnderwater_Seaweed);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmUnderwater_Seaweed[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 496)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmSootopolisGym_Waterfalls(u16 timer)
{
    u16 i = timer % min(ARRAY_COUNT(sTilesetAnims_EmSootopolisGym_SideWaterfall), ARRAY_COUNT(sTilesetAnims_EmSootopolisGym_FrontWaterfall));
    AppendTilesetAnimToBuffer(sTilesetAnims_EmSootopolisGym_SideWaterfall[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 496)), 12 * TILE_SIZE_4BPP);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmSootopolisGym_FrontWaterfall[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 464)), 20 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmMauvilleGym_ElectricGates(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmMauvilleGym_ElectricGates);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmMauvilleGym_ElectricGates[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 144)), 16 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmEliteFour_GroundLights(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmEliteFour_FloorLight);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmEliteFour_FloorLight[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 480)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmEliteFour_WallLights(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmEliteFour_WallLights);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmEliteFour_WallLights[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 504)), 1 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmBattlePyramid_Torch(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmBattlePyramid_Torch);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmBattlePyramid_Torch[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 151)), 8 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_EmBattlePyramid_StatueShadow(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(sTilesetAnims_EmBattlePyramid_StatueShadow);
    AppendTilesetAnimToBuffer(sTilesetAnims_EmBattlePyramid_StatueShadow[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(512 + 135)), 8 * TILE_SIZE_4BPP);
}
