SlateportCity_SternsShipyard_1F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_1F_EventScript_H0::
	msgbox SlateportCity_SternsShipyard_1F_Text_H0, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_1F_EventScript_H1::
	msgbox SlateportCity_SternsShipyard_1F_Text_H1, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_1F_EventScript_H2::
	msgbox SlateportCity_SternsShipyard_1F_Text_H2, MSGBOX_NPC
	end

