AbandonedShip_Rooms2_1F_Text_H0_0::
	.string "DAN: While searching for treasures,\n"
	.string "we discovered a TRAINER!$"

AbandonedShip_Rooms2_1F_Text_H0_1::
	.string "DAN: We couldn't win even though\n"
	.string "we worked together…$"

AbandonedShip_Rooms2_1F_Text_H0_2::
	.string "DAN: We can't find any treasures… I\n"
	.string "wonder if someone got them already?$"

AbandonedShip_Rooms2_1F_Text_H1_0::
	.string "KIRA: Oh? We were searching for\n"
	.string "treasures. But we discovered a\l"
	.string "TRAINER instead!$"

AbandonedShip_Rooms2_1F_Text_H1_1::
	.string "KIRA: Ooh, so strong!$"

AbandonedShip_Rooms2_1F_Text_H1_2::
	.string "KIRA: Where could the treasures be?\p"
	.string "I've already decided what I'm buying\n"
	.string "when we find the treasures!$"

AbandonedShip_Rooms2_1F_Text_H2_0::
	.string "Strength and compassion…\n"
	.string "Those are a TRAINER's treasures!$"

AbandonedShip_Rooms2_1F_Text_H2_1::
	.string "Ah, there is something about you\n"
	.string "that sparkles.$"

AbandonedShip_Rooms2_1F_Text_H2_2::
	.string "In a cabin somewhere on board,\n"
	.string "I saw something sparkle.$"

AbandonedShip_Rooms2_1F_Text_H3_0::
	.string "I'm not good at swimming,\n"
	.string "but I am good at battles!$"

AbandonedShip_Rooms2_1F_Text_H3_1::
	.string "Oops.\n"
	.string "That didn't go very well.$"

AbandonedShip_Rooms2_1F_Text_H3_2::
	.string "Walking around barefoot in this ship\n"
	.string "is kind of gross.$"

