AbandonedShip_Rooms2_1F_Text_H0::
	.string "DAN: We can't find any treasures…\n"
	.string "I wonder if someone got them already?$"

AbandonedShip_Rooms2_1F_Text_H1::
	.string "KIRA: Where could the treasures be?\p"
	.string "I've already decided what I'm buying\n"
	.string "when we find the treasures!$"

AbandonedShip_Rooms2_1F_Text_H2::
	.string "In a cabin somewhere on board,\n"
	.string "I saw something sparkle.$"

AbandonedShip_Rooms2_1F_Text_H3::
	.string "Walking around barefoot in this ship\n"
	.string "is kind of gross.$"

