MtPyre_2F_MapScripts::
	.byte 0

MtPyre_2F_EventScript_H0::
	msgbox MtPyre_2F_Text_H0, MSGBOX_NPC
	end

MtPyre_2F_EventScript_H1::
	msgbox MtPyre_2F_Text_H1, MSGBOX_NPC
	end

MtPyre_2F_EventScript_H2::
	msgbox MtPyre_2F_Text_H2, MSGBOX_NPC
	end

MtPyre_2F_EventScript_H3::
	msgbox MtPyre_2F_Text_H3, MSGBOX_NPC
	end

MtPyre_2F_EventScript_H4::
	msgbox MtPyre_2F_Text_H4, MSGBOX_NPC
	end

MtPyre_2F_EventScript_H5::
	msgbox MtPyre_2F_Text_H5, MSGBOX_NPC
	end

MtPyre_2F_EventScript_H6::
	msgbox MtPyre_2F_Text_H6, MSGBOX_NPC
	end

