DewfordTown_MapScripts::
	.byte 0

DewfordTown_EventScript_H0::
	msgbox DewfordTown_Text_H0, MSGBOX_NPC
	end

DewfordTown_EventScript_H1::
	msgbox DewfordTown_Text_H1, MSGBOX_NPC
	end

DewfordTown_EventScript_H2::
	msgbox DewfordTown_Text_H2, MSGBOX_NPC
	end

DewfordTown_EventScript_H3::
	msgbox DewfordTown_Text_H3, MSGBOX_SIGN
	end

DewfordTown_EventScript_H4::
	msgbox DewfordTown_Text_H4, MSGBOX_SIGN
	end

DewfordTown_EventScript_H5::
	msgbox DewfordTown_Text_H5, MSGBOX_SIGN
	end

