BattleFrontier_BattleFactoryLobby_Text_H0::
	.string "Hi!\n"
	.string "You, there!\p"
	.string "Are you thinking that the events\n"
	.string "here are easy since you don't need\l"
	.string "to have a raised team of POKéMON?\p"
	.string "I wouldn't be too sure about winning\n"
	.string "that easily.\p"
	.string "If you don't have thorough\n"
	.string "knowledge about POKéMON and their\l"
	.string "moves, it will be tough to keep\l"
	.string "winning.$"

BattleFrontier_BattleFactoryLobby_Text_H1::
	.string "I swapped for a weak POKéMON… I\n"
	.string "thought it was a good kind to have…\p"
	.string "They wiped the floor with us…$"

BattleFrontier_BattleFactoryLobby_Text_H2::
	.string "Things haven't been going my way\n"
	.string "at all.\p"
	.string "You need to check your opponent's\n"
	.string "POKéMON during battle to see if\l"
	.string "they're any good.$"

BattleFrontier_BattleFactoryLobby_Text_H3::
	.string "You know how the staff here give\n"
	.string "you a few hints about your next\l"
	.string "opponent?\p"
	.string "Well, I'm a full-grown man, but I\n"
	.string "have trouble figuring out their\l"
	.string "hints.$"

BattleFrontier_BattleFactoryLobby_Text_H4::
	.string "The Battle Swap rules are listed.$"

