EverGrandeCity_PhoebesRoom_Text_H0::
	.string "Ahahaha!\p"
	.string "I'm PHOEBE of the ELITE FOUR.\n"
	.string "I did my training on MT. PYRE.\p"
	.string "While I trained, I gained the ability\n"
	.string "to commune with GHOST-type POKéMON.\p"
	.string "Yes, the bond I developed with\n"
	.string "POKéMON is extremely tight.\p"
	.string "So, come on, just try and see if you\n"
	.string "can even inflict damage on my\l"
	.string "POKéMON!$"

