Route4_Text_TrippedOverGeodude::
    .string "Ouch! I tripped over a rocky\n"
    .string "POKéMON, GEODUDE!$"

Route4_Text_CrissyIntro::
    .string "I came to MT. MOON in search of\n"
    .string "mushroom POKéMON.$"

Route4_Text_CrissyDefeat::
    .string "After all I did to catch them!$"

Route4_Text_CrissyPostBattle::
    .string "There might not be any more\n"
    .string "mushrooms here.\p"
    .string "I think I got them all.$"

Route4_Text_MtMoonEntrance::
    .string "MT. MOON\n"
    .string "Tunnel Entrance$"

Route4_Text_RouteSign::
    .string "ROUTE 4\n"
    .string "MT. MOON - CERULEAN CITY$"

Text_MegaPunchTeach::
    .string "A punch of roaring ferocity!\p"
    .string "Packed with destructive power!\p"
    .string "When the chips are down,\n"
    .string "MEGA PUNCH is the ultimate attack!\l"
    .string "You agree, yes?\p"
    .string "Now!\n"
    .string "Let me teach it to your POKéMON!$"

Text_MegaPunchDeclined::
    .string "You'll be back when you understand\n"
    .string "the worth of MEGA PUNCH.$"

Text_MegaPunchWhichMon::
    .string "Fine!\n"
    .string "Which POKéMON will learn it?$"

Text_MegaPunchTaught::
    .string "Now, we are comrades in the way of\n"
    .string "punching! Come back any time, and\l"
    .string "bring more POKéMON to teach!\p"
    .string "That fool over there teaches only\n"
    .string "his silly kicking. Learn it too, if\l"
    .string "you must, and see which is better!$"

Text_MegaPunchAgain::
    .string "Back for more MEGA PUNCH?\n"
    .string "Shall I teach another POKéMON?$"

Text_MegaPunchTaughtAgain::
    .string "Another fist of fury! Hah!$"

Text_MegaKickTeach::
    .string "A kick of brutal ferocity!\p"
    .string "Packed with destructive power!\p"
    .string "When you get right down to it,\n"
    .string "MEGA KICK is the ultimate attack!\l"
    .string "Don't you agree?\p"
    .string "Okay!\n"
    .string "I'll teach it to your POKéMON!$"

Text_MegaKickDeclined::
    .string "You'll come crawling back when you\n"
    .string "realize the value of MEGA KICK.$"

Text_MegaKickWhichMon::
    .string "All right!\n"
    .string "Which POKéMON wants to learn it?$"

Text_MegaKickTaught::
    .string "Now, we are soul mates in the way\n"
    .string "of kicking! I'll teach it again,\l"
    .string "to as many POKéMON as you like!\p"
    .string "That nitwit over there teaches only\n"
    .string "simple punching. Go learn it too,\l"
    .string "then prove that kicking wins!$"

Text_MegaKickAgain::
    .string "More MEGA KICK? I'll teach it to\n"
    .string "another POKéMON. All right?$"

Text_MegaKickTaughtAgain::
    .string "Another mighty leg! Kick on!$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Oh, wow, that's the BOULDERBADGE!\n"
    .string "You got it from BROCK, didn't you?\p"
    .string "BROCK is cool. He's not just tough.\n"
    .string "People like and respect him.\p"
    .string "I want to become a GYM LEADER\n"
    .string "like him.$"
