SootopolisCity_House4_Text_H0::
	.string "Listen up, and I'll tell you\n"
	.string "something good.\p"
	.string "There's supposed to be an ancient\n"
	.string "ruin in the sea around here.\p"
	.string "There could be treasures just\n"
	.string "waiting to be discovered down there.$"

SootopolisCity_House4_Text_H1::
	.string "Ancient treasures…\p"
	.string "It would be nice if they existed,\n"
	.string "but even if they didn't, it would be\l"
	.string "so beautiful to take an underwater\l"
	.string "stroll with my POKéMON.$"

SootopolisCity_House4_Text_H2::
	.string "AZUMARILL: Marurii.$"

