MauvilleCity_BikeShop_MapScripts::
	.byte 0

MauvilleCity_BikeShop_EventScript_H0::
	msgbox MauvilleCity_BikeShop_Text_H0, MSGBOX_NPC
	end

MauvilleCity_BikeShop_EventScript_H1::
	msgbox MauvilleCity_BikeShop_Text_H1, MSGBOX_NPC
	end

MauvilleCity_BikeShop_EventScript_H2::
	msgbox MauvilleCity_BikeShop_Text_H2, MSGBOX_SIGN
	end

MauvilleCity_BikeShop_EventScript_H3::
	msgbox MauvilleCity_BikeShop_Text_H3, MSGBOX_SIGN
	end

