AbandonedShip_HiddenFloorRooms_MapScripts::
	.byte 0

AbandonedShip_HiddenFloorRooms_EventScript_H0::
	msgbox AbandonedShip_HiddenFloorRooms_Text_H0, MSGBOX_SIGN
	end

AbandonedShip_HiddenFloorRooms_EventScript_H1::
	msgbox AbandonedShip_HiddenFloorRooms_Text_H1, MSGBOX_SIGN
	end

AbandonedShip_HiddenFloorRooms_EventScript_H2::
	msgbox AbandonedShip_HiddenFloorRooms_Text_H2, MSGBOX_SIGN
	end

AbandonedShip_HiddenFloorRooms_EventScript_H3::
	msgbox AbandonedShip_HiddenFloorRooms_Text_H3, MSGBOX_SIGN
	end

AbandonedShip_HiddenFloorRooms_EventScript_H4::
	msgbox AbandonedShip_HiddenFloorRooms_Text_H4, MSGBOX_SIGN
	end

AbandonedShip_HiddenFloorRooms_EventScript_H5::
	msgbox AbandonedShip_HiddenFloorRooms_Text_H5, MSGBOX_SIGN
	end

