

@ BEGIN PATCH (tools/hoenn_import/patches)
AbandonedShip_HiddenFloorRooms_Text_H0::
    .string "Something catches the light down\n"
    .string "here. It's a tin lid.$"

AbandonedShip_HiddenFloorRooms_Text_H1::
    .string "Something catches the light down\n"
    .string "here. It's a tin lid.$"

AbandonedShip_HiddenFloorRooms_Text_H2::
    .string "Something catches the light down\n"
    .string "here. It's a tin lid.$"

AbandonedShip_HiddenFloorRooms_Text_H3::
    .string "Something catches the light down\n"
    .string "here. It's a tin lid.$"

AbandonedShip_HiddenFloorRooms_Text_H4::
    .string "Something catches the light down\n"
    .string "here. It's a tin lid.$"

AbandonedShip_HiddenFloorRooms_Text_H5::
    .string "Something catches the light down\n"
    .string "here. It's a tin lid.$"
@ END PATCH
