AbandonedShip_HiddenFloorRooms_Text_H0::
	.string "It's bright and shiny!\n"
	.string "But it's just trash…$"

AbandonedShip_HiddenFloorRooms_Text_H1::
	.string "It's bright and shiny!\n"
	.string "But it's just trash…$"

AbandonedShip_HiddenFloorRooms_Text_H2::
	.string "It's bright and shiny!\n"
	.string "But it's just trash…$"

AbandonedShip_HiddenFloorRooms_Text_H3::
	.string "It's bright and shiny!\n"
	.string "But it's just trash…$"

AbandonedShip_HiddenFloorRooms_Text_H4::
	.string "It's bright and shiny!\n"
	.string "But it's just trash…$"

AbandonedShip_HiddenFloorRooms_Text_H5::
	.string "It's bright and shiny!\n"
	.string "But it's just trash…$"

