PacifidlogTown_PokemonCenter_1F_MapScripts::
	.byte 0

PacifidlogTown_PokemonCenter_1F_EventScript_H0::
	msgbox PacifidlogTown_PokemonCenter_1F_Text_H0, MSGBOX_NPC
	end

PacifidlogTown_PokemonCenter_1F_EventScript_H1::
	msgbox PacifidlogTown_PokemonCenter_1F_Text_H1, MSGBOX_NPC
	end

PacifidlogTown_PokemonCenter_1F_EventScript_H2::
	msgbox PacifidlogTown_PokemonCenter_1F_Text_H2, MSGBOX_NPC
	end

PacifidlogTown_PokemonCenter_1F_EventScript_H3::
	msgbox PacifidlogTown_PokemonCenter_1F_Text_H3, MSGBOX_NPC
	end

