AbandonedShip_Corridors_1F_Text_H0::
	.string "Isn't it fun here?\n"
	.string "I get excited just being here!$"

AbandonedShip_Corridors_1F_Text_H1_0::
	.string "What's so funny about having my inner\n"
	.string "tube aboard the ship?$"

AbandonedShip_Corridors_1F_Text_H1_1::
	.string "Whoa, you overwhelmed me!$"

AbandonedShip_Corridors_1F_Text_H1_2::
	.string "It's not easy throwing POKé BALLS\n"
	.string "while hanging on to an inner tube!$"

