Route103_MapScripts::
	.byte 0

Route103_EventScript_H0::
	msgbox Route103_Text_H0, MSGBOX_NPC
	end

Route103_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_DAISY, Route103_Text_H1_0, Route103_Text_H1_1
	msgbox Route103_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route103_EventScript_H2::
	trainerbattle_double TRAINER_HOENN_AMY_AND_LIV_1, Route103_Text_H2_0, Route103_Text_H2_1, Route103_Text_H2_1
	msgbox Route103_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route103_EventScript_H3::
	trainerbattle_double TRAINER_HOENN_AMY_AND_LIV_1, Route103_Text_H3_0, Route103_Text_H3_1, Route103_Text_H3_1
	msgbox Route103_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route103_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_ANDREW, Route103_Text_H4_0, Route103_Text_H4_1
	msgbox Route103_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route103_EventScript_H5::
	msgbox Route103_Text_H5, MSGBOX_NPC
	end

Route103_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_MIGUEL_1, Route103_Text_H6_0, Route103_Text_H6_1
	msgbox Route103_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route103_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_RHETT, Route103_Text_H7_0, Route103_Text_H7_1
	msgbox Route103_Text_H7_2, MSGBOX_AUTOCLOSE
	end

Route103_EventScript_H8::
	trainerbattle_single TRAINER_HOENN_MARCOS, Route103_Text_H8_0, Route103_Text_H8_1
	msgbox Route103_Text_H8_2, MSGBOX_AUTOCLOSE
	end

Route103_EventScript_H9::
	trainerbattle_single TRAINER_HOENN_ISABELLE, Route103_Text_H9_0, Route103_Text_H9_1
	msgbox Route103_Text_H9_2, MSGBOX_AUTOCLOSE
	end

Route103_EventScript_H10::
	trainerbattle_single TRAINER_HOENN_PETE, Route103_Text_H10_0, Route103_Text_H10_1
	msgbox Route103_Text_H10_2, MSGBOX_AUTOCLOSE
	end

Route103_EventScript_H11::
	msgbox Route103_Text_H11, MSGBOX_SIGN
	end

