Route103_Text_H0::
	.string "If you cross the sea from here,\n"
	.string "it'll be a shortcut to OLDALE TOWN.\p"
	.string "Fufufu, that's useful, isn't it?$"

Route103_Text_H1_0::
	.string "Did you feel the tug of our\n"
	.string "soul-soothing fragrance?$"

Route103_Text_H1_1::
	.string "You weren't led astray by our aroma…$"

Route103_Text_H1_2::
	.string "Aromatherapy is a form of mental\n"
	.string "healing that works with fragrances.$"

Route103_Text_H2_0::
	.string "LIV: We battle together as one\n"
	.string "team.$"

Route103_Text_H2_1::
	.string "LIV: Oh, we lost, big sister…$"

Route103_Text_H2_2::
	.string "LIV: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But we still lost…$"

Route103_Text_H3_0::
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We battle together!$"

Route103_Text_H3_1::
	.string "AMY: Uh-oh, we lost.$"

Route103_Text_H3_2::
	.string "AMY: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two TRAINERS.$"

Route103_Text_H4_0::
	.string "Gah! My fishing line's all snarled\n"
	.string "up! I'm getting frustrated and mean!\l"
	.string "That's it! Battle me!$"

Route103_Text_H4_1::
	.string "Gah! Lost it!\n"
	.string "I'm even more annoyed now!$"

Route103_Text_H4_2::
	.string "Gah, I'm still boiling mad…\n"
	.string "Grrrrr…$"

Route103_Text_H5::
	.string "My POKéMON is staggeringly tired…\n"
	.string "I should have brought a POTION…$"

Route103_Text_H6_0::
	.string "My POKéMON is delightfully adorable!\n"
	.string "Don't be shy--I'll show you!$"

Route103_Text_H6_1::
	.string "Oh, my gosh!\n"
	.string "My darling POKéMON!$"

Route103_Text_H6_2::
	.string "My delightful POKéMON looks darling\n"
	.string "even when it's fainted!$"

Route103_Text_H7_0::
	.string "Whoa! How'd you get into a space\n"
	.string "this small?$"

Route103_Text_H7_1::
	.string "Whoa!\n"
	.string "The kid can rock!$"

Route103_Text_H7_2::
	.string "Do you like cramped quarters\n"
	.string "like this?$"

Route103_Text_H8_0::
	.string "Did my guitar's wailing draw you in?$"

Route103_Text_H8_1::
	.string "My one-man show is ruined…$"

Route103_Text_H8_2::
	.string "I was playing my guitar where few\n"
	.string "people were around, but a lot of\l"
	.string "fans have gathered.\p"
	.string "Heh, maybe I should turn pro.$"

Route103_Text_H9_0::
	.string "Watch where you're going!\n"
	.string "We're going to crash!$"

Route103_Text_H9_1::
	.string "Groan…$"

Route103_Text_H9_2::
	.string "I'm a poor swimmer so I was\n"
	.string "practicing… Sorry for almost crashing\l"
	.string "into you.$"

Route103_Text_H10_0::
	.string "This sort of distance…\n"
	.string "You should just swim it!$"

Route103_Text_H10_1::
	.string "Oh, that's good going!$"

Route103_Text_H10_2::
	.string "Oh, I understand where you're coming\n"
	.string "from now.\p"
	.string "If I had a POKéMON that trusty,\n"
	.string "I'd want to SURF on it, too!$"

Route103_Text_H11::
	.string "ROUTE 103\n"
	.string "{DOWN_ARROW} OLDALE TOWN$"

