Route103_Text_H0::
	.string "If you cross the sea from here,\n"
	.string "it'll be a shortcut to OLDALE TOWN.\p"
	.string "Fufufu, that's useful, isn't it?$"

Route103_Text_H1::
	.string "Aromatherapy is a form of mental\n"
	.string "healing that works with fragrances.$"

Route103_Text_H2::
	.string "LIV: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But we still lost…$"

Route103_Text_H3::
	.string "AMY: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two TRAINERS.$"

Route103_Text_H4::
	.string "Gah, I'm still boiling mad…\n"
	.string "Grrrrr…$"

Route103_Text_H5::
	.string "My POKéMON is staggeringly tired…\n"
	.string "I should have brought a POTION…$"

Route103_Text_H6::
	.string "My delightful POKéMON looks darling\n"
	.string "even when it's fainted!$"

Route103_Text_H7::
	.string "Do you like cramped quarters\n"
	.string "like this?$"

Route103_Text_H8::
	.string "I was playing my guitar where few\n"
	.string "people were around, but a lot of fans\l"
	.string "have gathered.\p"
	.string "Heh, maybe I should turn pro.$"

Route103_Text_H9::
	.string "I'm a poor swimmer so I was practicing…\n"
	.string "Sorry for almost crashing into you.$"

Route103_Text_H10::
	.string "Oh, I understand where you're coming\n"
	.string "from now.\p"
	.string "If I had a POKéMON that trusty,\n"
	.string "I'd want to SURF on it, too!$"

Route103_Text_H11::
	.string "ROUTE 103\n"
	.string "{DOWN_ARROW} OLDALE TOWN$"

