FortreeCity_MapScripts::
	.byte 0

FortreeCity_EventScript_H0::
	msgbox FortreeCity_Text_H0, MSGBOX_NPC
	end

FortreeCity_EventScript_H1::
	msgbox FortreeCity_Text_H1, MSGBOX_NPC
	end

FortreeCity_EventScript_H2::
	msgbox FortreeCity_Text_H2, MSGBOX_NPC
	end

FortreeCity_EventScript_H3::
	msgbox FortreeCity_Text_H3, MSGBOX_NPC
	end

FortreeCity_EventScript_H4::
	msgbox FortreeCity_Text_H4, MSGBOX_NPC
	end

FortreeCity_EventScript_H5::
	msgbox FortreeCity_Text_H5, MSGBOX_NPC
	end

FortreeCity_EventScript_H6::
	msgbox FortreeCity_Text_H6, MSGBOX_SIGN
	end

FortreeCity_EventScript_H7::
	msgbox FortreeCity_Text_H7, MSGBOX_SIGN
	end

