Route110_TrickHousePuzzle6_Text_H0::
	.string "I'm sure having a good time checking\n"
	.string "this place out.\p"
	.string "It's a challenge I've found worth\n"
	.string "repeating!$"

Route110_TrickHousePuzzle6_Text_H1::
	.string "Ehehehe… I guess I lost because\n"
	.string "I was trying to cheat.$"

Route110_TrickHousePuzzle6_Text_H2::
	.string "You don't seem to be affected at all.\n"
	.string "Or do you have your poker face on?$"

