Route110_TrickHousePuzzle6_Text_H0_0::
	.string "When I heard there was a strange\n"
	.string "house, I had to check it out.$"

Route110_TrickHousePuzzle6_Text_H0_1::
	.string "I've discovered a tough TRAINER!$"

Route110_TrickHousePuzzle6_Text_H0_2::
	.string "I'm sure having a good time checking\n"
	.string "this place out.\p"
	.string "It's a challenge I've found worth\n"
	.string "repeating!$"

Route110_TrickHousePuzzle6_Text_H1_0::
	.string "Maybe I could get my BIRD POKéMON\n"
	.string "to fly over the wall…$"

Route110_TrickHousePuzzle6_Text_H1_1::
	.string "Gwaaah! I blew it!$"

Route110_TrickHousePuzzle6_Text_H1_2::
	.string "Ehehehe… I guess I lost because\n"
	.string "I was trying to cheat.$"

Route110_TrickHousePuzzle6_Text_H2_0::
	.string "I'm getting dizzy from these rotating\n"
	.string "doors…$"

Route110_TrickHousePuzzle6_Text_H2_1::
	.string "Everything's spinning around and\n"
	.string "around. I can't take this anymore…$"

Route110_TrickHousePuzzle6_Text_H2_2::
	.string "You don't seem to be affected at all.\n"
	.string "Or do you have your poker face on?$"

