BattleFrontier_ReceptionGate_MapScripts::
	.byte 0

BattleFrontier_ReceptionGate_EventScript_H0::
	msgbox BattleFrontier_ReceptionGate_Text_H0, MSGBOX_NPC
	end

BattleFrontier_ReceptionGate_EventScript_H1::
	msgbox BattleFrontier_ReceptionGate_Text_H1, MSGBOX_NPC
	end

BattleFrontier_ReceptionGate_EventScript_H2::
	msgbox BattleFrontier_ReceptionGate_Text_H2, MSGBOX_NPC
	end

BattleFrontier_ReceptionGate_EventScript_H3::
	msgbox BattleFrontier_ReceptionGate_Text_H3, MSGBOX_NPC
	end

