BattleFrontier_ReceptionGate_Text_H0::
	.string "The front lines of POKéMON battling!\n"
	.string "Welcome to the BATTLE FRONTIER!$"

BattleFrontier_ReceptionGate_Text_H1::
	.string "I'm your guide to the various\n"
	.string "facilities here in the BATTLE\l"
	.string "FRONTIER.$"

BattleFrontier_ReceptionGate_Text_H2::
	.string "I'm your guide to the basic rules\n"
	.string "that are common to all the\l"
	.string "challenges offered by the facilities\l"
	.string "in the BATTLE FRONTIER.$"

BattleFrontier_ReceptionGate_Text_H3::
	.string "I'm your guide to the FRONTIER\n"
	.string "PASS.$"

