Route132_MapScripts::
	.byte 0

Route132_EventScript_H0::
	msgbox Route132_Text_H0, MSGBOX_NPC
	end

Route132_EventScript_H1::
	msgbox Route132_Text_H1, MSGBOX_NPC
	end

Route132_EventScript_H2::
	msgbox Route132_Text_H2, MSGBOX_NPC
	end

Route132_EventScript_H3::
	msgbox Route132_Text_H3, MSGBOX_NPC
	end

Route132_EventScript_H4::
	msgbox Route132_Text_H4, MSGBOX_NPC
	end

Route132_EventScript_H5::
	msgbox Route132_Text_H5, MSGBOX_NPC
	end

Route132_EventScript_H6::
	msgbox Route132_Text_H6, MSGBOX_NPC
	end

Route132_EventScript_H7::
	msgbox Route132_Text_H7, MSGBOX_NPC
	end

