Route132_Text_H0_0::
	.string "I used to catch colds all the time\n"
	.string "as a kid, but I became totally fit\l"
	.string "after I started swimming.$"

Route132_Text_H0_1::
	.string "I crave more power…$"

Route132_Text_H0_2::
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_H1_0::
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_H1_1::
	.string "Oh, please, no!$"

Route132_Text_H1_2::
	.string "If I get swept away, I'll lose all\n"
	.string "my sense of place…$"

Route132_Text_H2_0::
	.string "I contemplate POKéMON 24 hours a\n"
	.string "day. How could you possibly beat\l"
	.string "me?$"

Route132_Text_H2_1::
	.string "I lose.\n"
	.string "I will concede defeat.$"

Route132_Text_H2_2::
	.string "Urggh… You're a POKéMON fanatic,\n"
	.string "aren't you?\p"
	.string "You must contemplate POKéMON 24\n"
	.string "hours a day, don't you?$"

Route132_Text_H3_0::
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_H3_1::
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_H3_2::
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge\l"
	.string "of victory and defeat!$"

Route132_Text_H4_0::
	.string "Now where could my wife have gone?\n"
	.string "I'm always with her.\l"
	.string "I wonder if I can win on my own.$"

Route132_Text_H4_1::
	.string "Ah, I see that I couldn't manage\n"
	.string "to win on my own after all.$"

Route132_Text_H4_2::
	.string "My wife must be looking for me.\n"
	.string "I'd best go find her right away.$"

Route132_Text_H5_0::
	.string "I liked training here by myself. It's\n"
	.string "awful that all these people came!$"

Route132_Text_H5_1::
	.string "Okay! I won't complain about other\n"
	.string "people being here.$"

Route132_Text_H5_2::
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other\l"
	.string "team.$"

Route132_Text_H6_0::
	.string "I'm always with my husband,\n"
	.string "but I can win even without him.$"

Route132_Text_H6_1::
	.string "Oh, I guess I wasn't good enough.$"

Route132_Text_H6_2::
	.string "That young man over there looks\n"
	.string "just like my husband when he was\l"
	.string "young.\p"
	.string "He's making me blush!$"

Route132_Text_H7_0::
	.string "Someone's been watching me intently.\n"
	.string "Was it you?$"

Route132_Text_H7_1::
	.string "Wow!\n"
	.string "That's pretty strong, all right!$"

Route132_Text_H7_2::
	.string "I can't shake this feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

