Route132_Text_H0::
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_H1::
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place…$"

Route132_Text_H2::
	.string "Urggh…\n"
	.string "You're a POKéMON fanatic, aren't you?\p"
	.string "You must contemplate POKéMON 24 hours\n"
	.string "a day, don't you?$"

Route132_Text_H3::
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_H4::
	.string "My wife must be looking for me.\n"
	.string "I'd best go find her right away.$"

Route132_Text_H5::
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other team.$"

Route132_Text_H6::
	.string "That young man over there looks just\n"
	.string "like my husband when he was young.\p"
	.string "He's making me blush!$"

Route132_Text_H7::
	.string "I can't shake this feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

