CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "Only skilled TRAINERS can collect\n"
    .string "POKéMON BADGES.\p"
    .string "I see you have at least one.\p"
    .string "Those BADGES have amazing secrets,\n"
    .string "did you know?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "Now then…\p"
    .string "Which of the eight BADGES should\n"
    .string "I describe?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Come visit me anytime you wish.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "The ATTACK stat of all your\n"
    .string "POKéMON increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "FLASH outside of battle.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "POKéMON up to Lv. 30 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "CUT outside of battle.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "The SPEED stat of all your\n"
    .string "POKéMON increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "FLY outside of battle.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "POKéMON up to Lv. 50 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "STRENGTH outside of battle.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "The DEFENSE stat of all your\n"
    .string "POKéMON increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "SURF outside of battle.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "POKéMON up to Lv. 70 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "ROCK SMASH outside of battle.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "The SP. ATK and SP. DEF stats of\n"
    .string "all your POKéMON rise a little bit.\p"
    .string "It also lets you use the move\n"
    .string "WATERFALL outside of battle.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "All POKéMON will obey you!$"


CeruleanCity_House1_Text_ISawABluePikachu::
    .string "Hey, listen! I saw a blue PIKACHU!\p"
    .string "It was splashing around the water\n"
    .string "inside the cave by the river.\p"
    .string "Nobody believes me… But I really,\n"
    .string "really saw it! Go see for yourself!$"

CeruleanCity_House1_Text_YouCaughtItShowMe::
    .string "You caught the blue PIKACHU?!\n"
    .string "No way! Bring it here and show me!$"

CeruleanCity_House1_Text_ItWasRealTakeThis::
    .string "Whoa! That's it! That's the one\n"
    .string "I saw!\p"
    .string "Huh? It's not a PIKACHU, it's a\n"
    .string "MARILL?\p"
    .string "…Well, I was still right! It was\n"
    .string "real! Here, take this!$"

CeruleanCity_House1_Text_RumorBoyThanks::
    .string "I found that blue stone by the\n"
    .string "river. It looks just like PIKABLU!$"
