ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "There's a POKéMON CENTER in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't\n"
    .string "be shy about healing POKéMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "POKéMON CENTERS heal your tired,\n"
    .string "hurt, or fainted POKéMON.\p"
    .string "They make all POKéMON completely\n"
    .string "healthy.$"

ViridianCity_PokemonCenter_1F_Text_JessieWantAllMons::
    .string "JESSIE: Every POKéMON resting in\n"
    .string "this CENTER is ours now!$"

ViridianCity_PokemonCenter_1F_Text_NurseOhNo::
    .string "NURSE: Oh no! Not the POKéMON in\n"
    .string "my care!$"

ViridianCity_PokemonCenter_1F_Text_PikachuSparks::
    .string "PIKACHU jumped in front of you,\n"
    .string "cheeks crackling!$"

ViridianCity_PokemonCenter_1F_Text_CenterPikachuJoinIn::
    .string "The PIKACHU resting in the CENTER\n"
    .string "joined in with a THUNDERBOLT!$"

ViridianCity_PokemonCenter_1F_Text_MeowthNoticesPikachu::
    .string "MEOWTH: Ow ow ow…\n"
    .string "Wait. That PIKACHU up front…\p"
    .string "It's no ordinary PIKACHU! Its\n"
    .string "power's way off the charts!\p"
    .string "The BOSS would pay a fortune for a\n"
    .string "PIKACHU like that!$"

ViridianCity_PokemonCenter_1F_Text_NurseThankYou::
    .string "NURSE: Thank you! Your PIKACHU\n"
    .string "saved every POKéMON here.\p"
    .string "Please, let me look after your team\n"
    .string "for a moment.$"

ViridianCity_PokemonCenter_1F_Text_NurseRested::
    .string "NURSE: There, all rested. Watch out\n"
    .string "for those three. They looked like\l"
    .string "they'd be back.$"

