AbandonedShip_Rooms_1F_Text_H0::
	.string "Ships of this sort are rare, so I'm\n"
	.string "taking a look around.\p"
	.string "Hmhm…\n"
	.string "There appear to be other cabins…$"

AbandonedShip_Rooms_1F_Text_H1::
	.string "The man next door…\p"
	.string "He says he's just sightseeing,\n"
	.string "but I don't know about that.$"

AbandonedShip_Rooms_1F_Text_H2::
	.string "I'm in trouble with my mom, so I ran.\n"
	.string "Keep it a secret where I am!$"

