MauvilleCity_Gym_MapScripts::
	.byte 0

MauvilleCity_Gym_EventScript_H0::
	msgbox MauvilleCity_Gym_Text_H0, MSGBOX_NPC
	end

MauvilleCity_Gym_EventScript_H1::
	msgbox MauvilleCity_Gym_Text_H1, MSGBOX_NPC
	end

MauvilleCity_Gym_EventScript_H2::
	msgbox MauvilleCity_Gym_Text_H2, MSGBOX_NPC
	end

MauvilleCity_Gym_EventScript_H3::
	msgbox MauvilleCity_Gym_Text_H3, MSGBOX_NPC
	end

MauvilleCity_Gym_EventScript_H4::
	msgbox MauvilleCity_Gym_Text_H4, MSGBOX_NPC
	end

MauvilleCity_Gym_EventScript_H5::
	msgbox MauvilleCity_Gym_Text_H5, MSGBOX_NPC
	end

