MauvilleCity_Gym_MapScripts::
	.byte 0

MauvilleCity_Gym_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_SHAWN, MauvilleCity_Gym_Text_H0_0, MauvilleCity_Gym_Text_H0_1
	msgbox MauvilleCity_Gym_Text_H0_2, MSGBOX_AUTOCLOSE
	end

MauvilleCity_Gym_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_VIVIAN, MauvilleCity_Gym_Text_H1_0, MauvilleCity_Gym_Text_H1_1
	msgbox MauvilleCity_Gym_Text_H1_2, MSGBOX_AUTOCLOSE
	end

MauvilleCity_Gym_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_BEN, MauvilleCity_Gym_Text_H2_0, MauvilleCity_Gym_Text_H2_1
	msgbox MauvilleCity_Gym_Text_H2_2, MSGBOX_AUTOCLOSE
	end

MauvilleCity_Gym_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_KIRK, MauvilleCity_Gym_Text_H3_0, MauvilleCity_Gym_Text_H3_1
	msgbox MauvilleCity_Gym_Text_H3_2, MSGBOX_AUTOCLOSE
	end

MauvilleCity_Gym_EventScript_H4::
	msgbox MauvilleCity_Gym_Text_H4, MSGBOX_NPC
	end

MauvilleCity_Gym_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_ANGELO, MauvilleCity_Gym_Text_H5_0, MauvilleCity_Gym_Text_H5_1
	msgbox MauvilleCity_Gym_Text_H5_2, MSGBOX_AUTOCLOSE
	end

