NewMauville_Inside_MapScripts::
	.byte 0

NewMauville_Inside_EventScript_HItem121::
	finditem ITEM_ULTRA_BALL
	end

NewMauville_Inside_EventScript_HItem122::
	finditem ITEM_ESCAPE_ROPE
	end

NewMauville_Inside_EventScript_HItem123::
	finditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_HItem124::
	finditem ITEM_FULL_HEAL
	end

NewMauville_Inside_EventScript_HItem125::
	finditem ITEM_PARALYZE_HEAL
	end

NewMauville_Inside_EventScript_H0::
	msgbox NewMauville_Inside_Text_H0, MSGBOX_SIGN
	end

NewMauville_Inside_EventScript_H1::
	msgbox NewMauville_Inside_Text_H1, MSGBOX_SIGN
	end

NewMauville_Inside_EventScript_H2::
	msgbox NewMauville_Inside_Text_H2, MSGBOX_SIGN
	end

NewMauville_Inside_EventScript_H3::
	msgbox NewMauville_Inside_Text_H3, MSGBOX_SIGN
	end

NewMauville_Inside_EventScript_H4::
	msgbox NewMauville_Inside_Text_H4, MSGBOX_SIGN
	end

NewMauville_Inside_EventScript_H5::
	msgbox NewMauville_Inside_Text_H5, MSGBOX_SIGN
	end

NewMauville_Inside_EventScript_H6::
	msgbox NewMauville_Inside_Text_H6, MSGBOX_SIGN
	end

NewMauville_Inside_EventScript_H7::
	msgbox NewMauville_Inside_Text_H7, MSGBOX_SIGN
	end

