Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: Hey! {PLAYER}!\p"
	.string "You're off to the POKéMON LEAGUE?\n"
	.string "Forget about it!\p"
	.string "You probably don't have any\n"
	.string "BADGES, do you?\p"
	.string "The guard won't let you through\n"
	.string "without them.\p"
	.string "By the way, did your POKéMON get\n"
	.string "any stronger?$"

Route22_Text_EarlyRivalDefeat::
	.string "Awww!\n"
	.string "You just lucked out!$"

Route22_Text_EarlyRivalPostBattle::
	.string "I heard the POKéMON LEAGUE is\n"
	.string "crawling with tough TRAINERS.\p"
	.string "I have to figure out how to get\n"
	.string "past them.\p"
	.string "You should quit dawdling and get a\n"
	.string "move on!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: What? {PLAYER}!\n"
	.string "What a surprise to see you here!\p"
	.string "So you're going to the POKéMON\n"
	.string "LEAGUE?\p"
	.string "You collected all the BADGES, too?\n"
	.string "That's cool!\p"
	.string "Then I'll whip you, {PLAYER}, as a\n"
	.string "warm-up for the POKéMON LEAGUE!\p"
	.string "Come on!$"

Route22_Text_LateRivalDefeat::
	.string "What!?\p"
	.string "I was just careless, you!$"

Route22_Text_LateRivalPostBattle::
	.string "That loosened me up.\n"
	.string "I'm ready for the POKéMON LEAGUE!\p"
	.string "{PLAYER}, you need more practice.\p"
	.string "But hey, you know that!\n"
	.string "I'm out of here. Smell ya!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign::
	.string "POKéMON LEAGUE\n"
	.string "Front Gate$"


Route22_Text_SleepyMan::
    .string "I walked too far today looking for\n"
    .string "POKéMON.\p"
    .string "My feet hurt and I'm sleepy…\p"
    .string "If I were a wild POKéMON, I'd be\n"
    .string "easy to catch…\p"
    .string "…Zzzz…$"

Route22_Text_SleepyManGotMail::
    .string "…Zzzz… Huh?\p"
    .string "What's that? You have MAIL for me?$"

Route22_Text_HandOverMailMon::
    .string "{PLAYER} handed over the POKéMON\n"
    .string "holding the MAIL.$"

Route22_Text_SleepyManReadingMail::
    .string "Let's see…\p"
    .string "…THE BEST TRAINER GOES THERE…\p"
    .string "Heh, he means the POKéMON LEAGUE\n"
    .string "up this road. That's good to know.\p"
    .string "Thanks for bringing this to me.\p"
    .string "My friend's a good guy, and you're\n"
    .string "swell too!\p"
    .string "I'd like to do something good in\n"
    .string "return too!\p"
    .string "I know! I want you to have this!$"

Route22_Text_SleepyManDescribeAerialAce::
    .string "TM40 is AERIAL ACE.\p"
    .string "It's a swift move that never misses,\n"
    .string "just like my buddy's SPEAROW!\p"
    .string "…Zzzz…$"

Route22_Text_SleepyManDeclined::
    .string "What? You don't have it with you?\n"
    .string "…Zzzz…$"

Route22_Text_SleepyManMissingMail::
    .string "Why is this POKéMON so special?\n"
    .string "It doesn't have any MAIL.$"

Route22_Text_SleepyManWrongMail::
    .string "This MAIL isn't for me.$"

Route22_Text_SleepyManCantTakeLastMon::
    .string "If I take that POKéMON, what will\n"
    .string "you use in battle?$"
