SilphCo_11F_MapScripts::
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_11F_OnLoad
	map_script MAP_SCRIPT_ON_TRANSITION, SilphCo_11F_OnTransition
	.byte 0

SilphCo_11F_OnTransition::
	call SilphCo_11F_EventScript_HideJessieJames
	end

SilphCo_11F_OnLoad::
	call_if_unset FLAG_SILPH_11F_DOOR, EventScript_Close11FDoor
	end

SilphCo_11F_EventScript_President::
	lock
	faceplayer
	goto_if_set FLAG_GOT_MASTER_BALL_FROM_SILPH, SilphCo_11F_EventScript_AlreadyGotMasterBall
	checkplayergender
	call_if_eq VAR_RESULT, MALE, SilphCo_11F_EventScript_PresidentThanksMale
	call_if_eq VAR_RESULT, FEMALE, SilphCo_11F_EventScript_PresidentThanksFemale
	checkitemspace ITEM_MASTER_BALL
	goto_if_eq VAR_RESULT, FALSE, SilphCo_11F_EventScript_NoRoomForMasterBall
	giveitem_msg SilphCo_11F_Text_ObtainedMasterBallFromPresident, ITEM_MASTER_BALL, 1, MUS_OBTAIN_KEY_ITEM
	msgbox SilphCo_11F_Text_ThatsOurSecretPrototype
	setflag FLAG_GOT_MASTER_BALL_FROM_SILPH
	release
	end

SilphCo_11F_EventScript_PresidentThanksMale::
	msgbox SilphCo_11F_Text_ThanksForSavingMeDearBoy
	return

SilphCo_11F_EventScript_PresidentThanksFemale::
	msgbox SilphCo_11F_Text_ThanksForSavingMeDearGirl
	return

SilphCo_11F_EventScript_NoRoomForMasterBall::
	msgbox SilphCo_11F_Text_YouHaveNoRoomForThis
	release
	end

SilphCo_11F_EventScript_AlreadyGotMasterBall::
	msgbox SilphCo_11F_Text_ThatsOurSecretPrototype
	release
	end

SilphCo_11F_EventScript_Secretary::
	msgbox SilphCo_11F_Text_ThanksForRescuingUs, MSGBOX_NPC
	end

SilphCo_11F_EventScript_GiovanniTriggerLeft::
	lockall
	setvar VAR_TEMP_1, 0
	goto SilphCo_11F_EventScript_BattleGiovanni
	end

SilphCo_11F_EventScript_GiovanniTriggerRight::
	lockall
	setvar VAR_TEMP_1, 1
	goto SilphCo_11F_EventScript_BattleGiovanni
	end

SilphCo_11F_EventScript_BattleGiovanni::
	textcolor NPC_TEXT_COLOR_MALE
	applymovement LOCALID_SILPH_CO_GIOVANNI, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	delay 25
	msgbox SilphCo_11F_Text_GiovanniIntro
	closemessage
	call_if_eq VAR_TEMP_1, 0, SilphCo_11F_EventScript_GiovanniApproachLeft
	call_if_eq VAR_TEMP_1, 1, SilphCo_11F_EventScript_GiovanniApproachRight
	setvar VAR_LAST_TALKED, LOCALID_SILPH_CO_GIOVANNI
	trainerbattle_no_intro TRAINER_BOSS_GIOVANNI_2, SilphCo_11F_Text_GiovanniDefeat
	msgbox SilphCo_11F_Text_GiovanniPostBattle
	closemessage
	fadescreen FADE_TO_BLACK
	removeobject LOCALID_SILPH_CO_GIOVANNI
	removeobject LOCALID_SILPH_CO_11F_GRUNT1
	removeobject LOCALID_SILPH_CO_11F_GRUNT2
	fadescreen FADE_FROM_BLACK
	setvar VAR_MAP_SCENE_SILPH_CO_11F, 1
	setflag FLAG_HIDE_SAFFRON_ROCKETS
	clearflag FLAG_HIDE_SAFFRON_CIVILIANS
	releaseall
	end

SilphCo_11F_EventScript_GiovanniApproachLeft::
	applymovement LOCALID_SILPH_CO_GIOVANNI, SilphCo_11F_Movement_GiovanniApproachLeft
	applymovement LOCALID_PLAYER, SilphCo_11F_Movement_PlayerFaceGiovanni
	waitmovement 0
	return

SilphCo_11F_EventScript_GiovanniApproachRight::
	applymovement LOCALID_SILPH_CO_GIOVANNI, SilphCo_11F_Movement_GiovanniApproachRight
	waitmovement 0
	return

SilphCo_11F_Movement_GiovanniApproachLeft::
	walk_down
	walk_down
	walk_down
	walk_down
	walk_in_place_faster_left
	step_end

SilphCo_11F_Movement_GiovanniApproachRight::
	walk_down
	walk_down
	walk_down
	step_end

SilphCo_11F_Movement_PlayerFaceGiovanni::
	delay_16
	delay_16
	delay_16
	delay_8
	delay_4
	walk_in_place_faster_right
	step_end

@ Unused
SilphCo_11F_EventScript_Monitor::
	msgbox SilphCo_11F_Text_MonitorHasMonsOnIt, MSGBOX_SIGN
	end

SilphCo_11F_EventScript_FloorSign::
	msgbox SilphCo_11F_Text_FloorSign, MSGBOX_SIGN
	end

SilphCo_11F_EventScript_Grunt1::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_40, SilphCo_11F_Text_Grunt1Intro, SilphCo_11F_Text_Grunt1Defeat
	msgbox SilphCo_11F_Text_Grunt1PostBattle, MSGBOX_AUTOCLOSE
	end

SilphCo_11F_EventScript_Grunt2::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_41, SilphCo_11F_Text_Grunt2Intro, SilphCo_11F_Text_Grunt2Defeat
	msgbox SilphCo_11F_Text_Grunt2PostBattle, MSGBOX_AUTOCLOSE
	end

SilphCo_11F_EventScript_JessieJamesTrigger0::
	lockall
	setvar VAR_TEMP_1, 0
	goto SilphCo_11F_EventScript_JessieJames
	end

SilphCo_11F_EventScript_JessieJamesTrigger1::
	lockall
	setvar VAR_TEMP_1, 1
	goto SilphCo_11F_EventScript_JessieJames
	end

SilphCo_11F_EventScript_JessieJamesTrigger2::
	lockall
	setvar VAR_TEMP_1, 2
	goto SilphCo_11F_EventScript_JessieJames
	end

@ Jessie & James ambush the player, as in Pokémon Yellow.
SilphCo_11F_EventScript_JessieJames::
	textcolor NPC_TEXT_COLOR_NEUTRAL
	playbgm MUS_ENCOUNTER_ROCKET, 0
	msgbox SilphCo_11F_Text_JessieJamesStop
	closemessage
	applymovement LOCALID_PLAYER, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	call_if_eq VAR_TEMP_1, 0, SilphCo_11F_EventScript_JessieJamesAppear0
	call_if_eq VAR_TEMP_1, 1, SilphCo_11F_EventScript_JessieJamesAppear1
	call_if_eq VAR_TEMP_1, 2, SilphCo_11F_EventScript_JessieJamesAppear2
	msgbox SilphCo_11F_Text_JessieJamesIntro
	closemessage
	setvar VAR_LAST_TALKED, LOCALID_SILPH_CO_JESSIE
	trainerbattle_no_intro TRAINER_JESSIE_JAMES_SILPH_CO, SilphCo_11F_Text_JessieJamesDefeat
	msgbox SilphCo_11F_Text_JessieJamesBlastOff
	closemessage
	fadescreen FADE_TO_BLACK
	removeobject LOCALID_SILPH_CO_JESSIE
	removeobject LOCALID_SILPH_CO_JAMES
	fadescreen FADE_FROM_BLACK
	setvar VAR_MAP_SCENE_SILPH_CO_11F_JESSIE_JAMES, 1
	releaseall
	end

SilphCo_11F_EventScript_JessieJamesAppear0::
	setobjectxyperm LOCALID_SILPH_CO_JESSIE, 0, 11
	setobjectxyperm LOCALID_SILPH_CO_JAMES, 1, 11
	addobject LOCALID_SILPH_CO_JESSIE
	addobject LOCALID_SILPH_CO_JAMES
	applymovement LOCALID_SILPH_CO_JESSIE, SilphCo_11F_EventScript_JessieJamesMovement0
	applymovement LOCALID_SILPH_CO_JAMES, SilphCo_11F_EventScript_JessieJamesMovement0
	waitmovement 0
	return

SilphCo_11F_EventScript_JessieJamesMovement0:
	walk_up
	walk_up
	walk_up
	step_end

SilphCo_11F_EventScript_JessieJamesAppear1::
	setobjectxyperm LOCALID_SILPH_CO_JESSIE, 1, 11
	setobjectxyperm LOCALID_SILPH_CO_JAMES, 2, 11
	addobject LOCALID_SILPH_CO_JESSIE
	addobject LOCALID_SILPH_CO_JAMES
	applymovement LOCALID_SILPH_CO_JESSIE, SilphCo_11F_EventScript_JessieJamesMovement1
	applymovement LOCALID_SILPH_CO_JAMES, SilphCo_11F_EventScript_JessieJamesMovement1
	waitmovement 0
	return

SilphCo_11F_EventScript_JessieJamesMovement1:
	walk_up
	walk_up
	walk_up
	step_end

SilphCo_11F_EventScript_JessieJamesAppear2::
	setobjectxyperm LOCALID_SILPH_CO_JESSIE, 2, 11
	setobjectxyperm LOCALID_SILPH_CO_JAMES, 1, 11
	addobject LOCALID_SILPH_CO_JESSIE
	addobject LOCALID_SILPH_CO_JAMES
	applymovement LOCALID_SILPH_CO_JESSIE, SilphCo_11F_EventScript_JessieJamesMovement2
	applymovement LOCALID_SILPH_CO_JAMES, SilphCo_11F_EventScript_JessieJamesMovement2
	waitmovement 0
	return

SilphCo_11F_EventScript_JessieJamesMovement2:
	walk_up
	walk_up
	walk_up
	step_end

SilphCo_11F_EventScript_HideJessieJames::
	setflag FLAG_HIDE_SILPH_CO_11F_JESSIE_JAMES
	return
