SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "PRESIDENT: Oh, dear boy!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "I have to thank you in some way.\p"
    .string "Because I am rich, I can give you\n"
    .string "anything.\p"
    .string "Here, maybe this will do.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "PRESIDENT: Oh, dear girl!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "I have to thank you in some way.\p"
    .string "Because I am rich, I can give you\n"
    .string "anything.\p"
    .string "Here, maybe this will do.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER} obtained a MASTER BALL\n"
    .string "from the PRESIDENT!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "PRESIDENT: You can't buy that\n"
    .string "anywhere.\p"
    .string "It's our secret prototype MASTER\n"
    .string "BALL.\p"
    .string "It will catch any POKéMON without\n"
    .string "fail!\p"
    .string "You should be quiet about using it,\n"
    .string "though.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "You have no room for this.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "SECRETARY: Thank you for rescuing\n"
    .string "all of us.\p"
    .string "We, from the PRESIDENT down,\n"
    .string "are indebted to you.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "Ah, {PLAYER}!\n"
    .string "So we meet again!\p"
    .string "The PRESIDENT and I are discussing\n"
    .string "a vital business proposition.\p"
    .string "Keep your nose out of grown-up\n"
    .string "matters…\p"
    .string "Or, experience a world of pain!$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "Arrgh!!\n"
    .string "I lost again!?$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "Blast it all!\n"
    .string "You ruined our plans for SILPH!\p"
    .string "But, TEAM ROCKET will never fall!\p"
    .string "{PLAYER}! Never forget that all\n"
    .string "POKéMON exist for TEAM ROCKET!\p"
    .string "I must go, but I shall return!$"

SilphCo_11F_Text_Grunt2Intro::
    .string "Stop right there!\n"
    .string "Don't you move!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "Don't…\n"
    .string "Please!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "So, you want to see my BOSS?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "Halt! Do you have an appointment\n"
    .string "with my BOSS?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "Gaah!\n"
    .string "Demolished!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Watch your step…\n"
    .string "My BOSS likes his POKéMON tough!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "The monitor has POKéMON on it!$"

SilphCo_11F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "11F$"

SilphCo_11F_Text_JessieJamesStop::
    .string "Hold it right there, brat!$"

SilphCo_11F_Text_JessieJamesIntro::
    .string "Our BOSS is in a meeting!\p"
    .string "You better not disturb him!$"

SilphCo_11F_Text_JessieJamesDefeat::
    .string "Like always…$"

SilphCo_11F_Text_JessieJamesBlastOff::
    .string "TEAM ROCKET, blast off at the\n"
    .string "speed of light!\p"
    .string "Again…$"

SilphCo_11F_Text_NTools::
    .string "N: The man in black called\n"
    .string "POKéMON tools.\p"
    .string "This company made a BALL that\n"
    .string "catches anything, no matter what\l"
    .string "it wants.\p"
    .string "I wanted to see who would stand\n"
    .string "up to them. It was you.$"

SilphCo_11F_Text_NLetsBattle::
    .string "N: Let me hear your PIKACHU one\n"
    .string "more time!$"

SilphCo_11F_Text_NDefeat::
    .string "Your answer is so loud, I can't\n"
    .string "argue with it.$"

SilphCo_11F_Text_NAfter::
    .string "N: When the POKéMON LEAGUE is\n"
    .string "behind you, come find me.\p"
    .string "I'll be at the end of the WATER\n"
    .string "PATH on SIX ISLAND, where the sea\l"
    .string "is quiet enough to hear everything.$"
