AbandonedShip_Corridors_B1F_Text_H0::
	.string "Yay!\n"
	.string "It's a ship!$"

AbandonedShip_Corridors_B1F_Text_H1_0::
	.string "When we go out to sea, we SAILORS\n"
	.string "always bring our POKéMON.\l"
	.string "How about a quick battle?$"

AbandonedShip_Corridors_B1F_Text_H1_1::
	.string "Whoops, I'm sunk!$"

AbandonedShip_Corridors_B1F_Text_H1_2::
	.string "The ship's bottom has sunk into the\n"
	.string "depths.\p"
	.string "If a POKéMON knew how to go\n"
	.string "underwater, we might make some\l"
	.string "progress…$"

AbandonedShip_Corridors_B1F_Text_H2::
	.string "{PLAYER} inserted and turned the\n"
	.string "STORAGE KEY.\p"
	.string "The inserted KEY stuck fast,\n"
	.string "but the door opened.$"

