Route119_House_Text_H0::
	.string "I heard about a cave called the CAVE\n"
	.string "OF ORIGIN.\p"
	.string "People rumor that the spirits of\n"
	.string "POKéMON are revived there. Could\l"
	.string "something like that really happen?$"

Route119_House_Text_H1::
	.string "WINGULL: Pihyoh!$"

Route119_House_Text_H2::
	.string "WINGULL: Pihyoh!$"

Route119_House_Text_H3::
	.string "WINGULL: Pihyoh!$"

Route119_House_Text_H4::
	.string "WINGULL: Pihyoh!$"

Route119_House_Text_H5::
	.string "WINGULL: Pihyoh!$"

Route119_House_Text_H6::
	.string "WINGULL: Pihyoh!$"

