DewfordTown_Hall_MapScripts::
	.byte 0

DewfordTown_Hall_EventScript_H0::
	msgbox DewfordTown_Hall_Text_H0, MSGBOX_NPC
	end

DewfordTown_Hall_EventScript_H1::
	msgbox DewfordTown_Hall_Text_H1, MSGBOX_NPC
	end

DewfordTown_Hall_EventScript_H2::
	msgbox DewfordTown_Hall_Text_H2, MSGBOX_NPC
	end

DewfordTown_Hall_EventScript_H3::
	msgbox DewfordTown_Hall_Text_H3, MSGBOX_NPC
	end

DewfordTown_Hall_EventScript_H4::
	msgbox DewfordTown_Hall_Text_H4, MSGBOX_NPC
	end

DewfordTown_Hall_EventScript_H5::
	msgbox DewfordTown_Hall_Text_H5, MSGBOX_NPC
	end

DewfordTown_Hall_EventScript_H6::
	msgbox DewfordTown_Hall_Text_H6, MSGBOX_SIGN
	end

