BattleFrontier_Lounge5_MapScripts::
	.byte 0

BattleFrontier_Lounge5_EventScript_H0::
	msgbox BattleFrontier_Lounge5_Text_H0, MSGBOX_NPC
	end

BattleFrontier_Lounge5_EventScript_H1::
	msgbox BattleFrontier_Lounge5_Text_H1, MSGBOX_NPC
	end

BattleFrontier_Lounge5_EventScript_H2::
	msgbox BattleFrontier_Lounge5_Text_H2, MSGBOX_NPC
	end

BattleFrontier_Lounge5_EventScript_H3::
	msgbox BattleFrontier_Lounge5_Text_H3, MSGBOX_NPC
	end

