BattleFrontier_Lounge5_Text_H0::
	.string "Ehehe! I can tell what POKéMON are\n"
	.string "thinking!\p"
	.string "Please!\n"
	.string "Can I see your POKéMON?$"

BattleFrontier_Lounge5_Text_H1::
	.string "How charming!\n"
	.string "That little lady claims she can\l"
	.string "understand POKéMON!$"

BattleFrontier_Lounge5_Text_H2::
	.string "I have this feeling that the little\n"
	.string "girl is saying something profound.$"

BattleFrontier_Lounge5_Text_H3::
	.string "I know something!\p"
	.string "That little girl plays at the red\n"
	.string "house a lot!$"

