RocketHideout_B2F_Text_GruntIntro::
    .string "BOSS said you can see ghosts with\n"
    .string "the SILPH SCOPE.$"

RocketHideout_B2F_Text_GruntDefeat::
    .string "I surrender!$"

RocketHideout_B2F_Text_GruntPostBattle::
    .string "The TEAM ROCKET HQ has four\n"
    .string "underground floors.\p"
    .string "Think you can reach the BOSS?$"


RocketHideout_B2F_Text_ItWasATrap::
    .string "It was a trap!\n"
    .string "The POKé BALL was a {STR_VAR_1}!$"

RocketHideout_B2F_Text_EmergencyGenerator::
    .string "EMERGENCY GENERATOR\n"
    .string "Powering: SECURITY CAMS, TRAPS\p"
    .string "Shut it down?$"

RocketHideout_B2F_Text_GeneratorShutDown::
    .string "The generator whirred to a stop.\p"
    .string "The security cameras and traps\n"
    .string "have lost their power!$"

RocketHideout_B2F_Text_GeneratorIsOff::
    .string "The emergency generator is off.$"
