RustboroCity_DevonCorp_3F_MapScripts::
	.byte 0

RustboroCity_DevonCorp_3F_EventScript_H0::
	msgbox RustboroCity_DevonCorp_3F_Text_H0, MSGBOX_NPC
	end

RustboroCity_DevonCorp_3F_EventScript_H1::
	msgbox RustboroCity_DevonCorp_3F_Text_H1, MSGBOX_NPC
	end

RustboroCity_DevonCorp_3F_EventScript_H2::
	msgbox RustboroCity_DevonCorp_3F_Text_H2, MSGBOX_SIGN
	end

RustboroCity_DevonCorp_3F_EventScript_H3::
	msgbox RustboroCity_DevonCorp_3F_Text_H3, MSGBOX_SIGN
	end

