RustboroCity_DevonCorp_3F_Text_H0::
	.string "MR. STONE: I'm counting on you!$"

RustboroCity_DevonCorp_3F_Text_H1::
	.string "MR. STONE: I'm counting on you!$"

RustboroCity_DevonCorp_3F_Text_H2::
	.string "It's a collection of rare rocks and\n"
	.string "stones assembled by the PRESIDENT.$"

RustboroCity_DevonCorp_3F_Text_H3::
	.string "It's a collection of rare rocks and\n"
	.string "stones assembled by the PRESIDENT.$"

