Route106_Text_H0_0::
	.string "Hahahah! I'm a lousy runner, but in\n"
	.string "the water you can't catch me!$"

Route106_Text_H0_1::
	.string "I give up!$"

Route106_Text_H0_2::
	.string "I wouldn't lose in a swim race…$"

Route106_Text_H1_0::
	.string "The sea is my backyard. I'm not\n"
	.string "going to take it easy because you're\l"
	.string "a kid!$"

Route106_Text_H1_1::
	.string "Did you take it easy on me by any\n"
	.string "chance?$"

Route106_Text_H1_2::
	.string "Drifting along with the waves… I\n"
	.string "love it! Why don't you give it a\l"
	.string "try?$"

Route106_Text_H2_0::
	.string "Which do you prefer, fishing in the\n"
	.string "sea or a stream?$"

Route106_Text_H2_1::
	.string "Like in deep-sea fishing, I lost\n"
	.string "spectacularly!$"

Route106_Text_H2_2::
	.string "Fishing is the greatest whether it's\n"
	.string "in the sea or a stream.\l"
	.string "You agree with me, right?$"

Route106_Text_H3_0::
	.string "What do people do if they need to\n"
	.string "go to a washroom?\p"
	.string "What if my ROD hooks a big one while\n"
	.string "I'm in the washroom? I just can't\l"
	.string "go…$"

Route106_Text_H3_1::
	.string "I lost because I'm trying to not go\n"
	.string "to the washroom…$"

Route106_Text_H3_2::
	.string "Oh, no! I've got this feeling I'll\n"
	.string "hook a big one!$"

Route106_Text_H4::
	.string "TRAINER TIPS\p"
	.string "Advice on catching POKéMON with a\n"
	.string "ROD: Press the A Button if you get a\l"
	.string "bite.$"

