Route106_Text_H0::
	.string "I wouldn't lose in a swim race…$"

Route106_Text_H1::
	.string "Drifting along with the waves…\n"
	.string "I love it! Why don't you give it a try?$"

Route106_Text_H2::
	.string "Fishing is the greatest whether it's\n"
	.string "in the sea or a stream.\l"
	.string "You agree with me, right?$"

Route106_Text_H3::
	.string "Oh, no! I've got this feeling I'll hook\n"
	.string "a big one!$"

Route106_Text_H4::
	.string "TRAINER TIPS\p"
	.string "Advice on catching POKéMON with a ROD:\n"
	.string "Press the A Button if you get a bite.$"

