Route128_MapScripts::
	.byte 0

Route128_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_ISAIAH_1, Route128_Text_H0_0, Route128_Text_H0_1
	msgbox Route128_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route128_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_KATELYN_1, Route128_Text_H1_0, Route128_Text_H1_1
	msgbox Route128_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route128_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_WAYNE, Route128_Text_H2_0, Route128_Text_H2_1
	msgbox Route128_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route128_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_RUBEN, Route128_Text_H3_0, Route128_Text_H3_1
	msgbox Route128_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route128_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_ALEXA, Route128_Text_H4_0, Route128_Text_H4_1
	msgbox Route128_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route128_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_CARLEE, Route128_Text_H5_0, Route128_Text_H5_1
	msgbox Route128_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route128_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_HARRISON, Route128_Text_H6_0, Route128_Text_H6_1
	msgbox Route128_Text_H6_2, MSGBOX_AUTOCLOSE
	end

