Route128_Text_H0_0::
	.string "EVER GRANDE CITY is still a long ways\n"
	.string "away…$"

Route128_Text_H0_1::
	.string "My first victory seems to be far\n"
	.string "away, too…$"

Route128_Text_H0_2::
	.string "My whole life has been about losing,\n"
	.string "but I will never give up!$"

Route128_Text_H1_0::
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon.\p"
	.string "It's a grueling race that consists\n"
	.string "of three events.$"

Route128_Text_H1_1::
	.string "A POKéMON battle is grueling, too…$"

Route128_Text_H1_2::
	.string "I have to ride a BIKE next, but…\n"
	.string "I'm about to throw in the towel…$"

Route128_Text_H2_0::
	.string "I want to visit EVER GRANDE, so I\n"
	.string "caught myself a POKéMON that knows\l"
	.string "the move WATERFALL to crest the falls.$"

Route128_Text_H2_1::
	.string "I'm crestfallen!$"

Route128_Text_H2_2::
	.string "Awww, phooey!\p"
	.string "My POKéMON knows WATERFALL, but\n"
	.string "I don't have the SOOTOPOLIS GYM BADGE!$"

Route128_Text_H3_0::
	.string "There is no stronger TRAINER than I!$"

Route128_Text_H3_1::
	.string "This can't be!$"

Route128_Text_H3_2::
	.string "There probably is no stronger TRAINER\n"
	.string "than you!$"

Route128_Text_H4_0::
	.string "We've been working so hard to mount\n"
	.string "a POKéMON LEAGUE challenge…\p"
	.string "We can't afford to lose now!$"

Route128_Text_H4_1::
	.string "Oh!\n"
	.string "How could this happen?!$"

Route128_Text_H4_2::
	.string "After all I've done to get here,\n"
	.string "I won't give up after one setback.$"

Route128_Text_H5_0::
	.string "The sunlight seems to be more harsh\n"
	.string "in this area.$"

Route128_Text_H5_1::
	.string "I couldn't see very well because of\n"
	.string "the sun's glare.$"

Route128_Text_H5_2::
	.string "I should go back soon.\n"
	.string "I need to reapply my sunscreen.$"

Route128_Text_H6_0::
	.string "You're looking awfully tough.\n"
	.string "I wonder if I can win?$"

Route128_Text_H6_1::
	.string "Ouch!\n"
	.string "I guess it was impossible to win.$"

Route128_Text_H6_2::
	.string "There are tough TRAINERS galore\n"
	.string "around EVER GRANDE.\p"
	.string "Do you think I may be out\n"
	.string "of my league?$"

