Route128_Text_H0::
	.string "My whole life has been about losing,\n"
	.string "but I will never give up!$"

Route128_Text_H1::
	.string "I have to ride a BIKE next, but…\n"
	.string "I'm about to throw in the towel…$"

Route128_Text_H2::
	.string "Awww, phooey!\p"
	.string "My POKéMON knows WATERFALL, but\n"
	.string "I don't have the SOOTOPOLIS GYM BADGE!$"

Route128_Text_H3::
	.string "There probably is no stronger TRAINER\n"
	.string "than you!$"

Route128_Text_H4::
	.string "After all I've done to get here,\n"
	.string "I won't give up after one setback.$"

Route128_Text_H5::
	.string "I should go back soon.\n"
	.string "I need to reapply my sunscreen.$"

Route128_Text_H6::
	.string "There are tough TRAINERS galore\n"
	.string "around EVER GRANDE.\p"
	.string "Do you think I may be out\n"
	.string "of my league?$"

