SSAnne_1F_Corridor_Text_LeStrongSilentType::
    .string "Bonjour!\n"
    .string "I am le waiter on this ship!\p"
    .string "I will be happy to serve you\n"
    .string "anything you please!\p"
    .string "… … …\n"
    .string "Ah! Le strong silent type!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
    .string "The passengers are restless from\n"
    .string "this long voyage.\p"
    .string "You might be challenged by the\n"
    .string "more bored ones!$"

SSAnne_1F_Corridor_Text_SalesmanPitch::
    .string "SALESMAN: This MAGIKARP is special,\n"
    .string "friend. It lays golden eggs!\p"
    .string "Yours for just ¥500!$"

SSAnne_1F_Corridor_Text_JamesBuys::
    .string "JAMES: Golden eggs?! We'll be rich!\n"
    .string "SOLD!$"

SSAnne_1F_Corridor_Text_JessieScolds::
    .string "JESSIE: JAMES, you fool! MAGIKARP\n"
    .string "can't lay golden eggs!\p"
    .string "You bought another one?!$"

SSAnne_1F_Corridor_Text_MeowthPlan::
    .string "MEOWTH: Forget the fish! Tonight\n"
    .string "at the captain's party, every\l"
    .string "passenger's POKéMON gets snatched!\p"
    .string "A whole ship's worth of loot!$"

SSAnne_1F_Corridor_Text_MeowthSpotsPikachu::
    .string "MEOWTH: Uh-oh… It's the twerp with\n"
    .string "the super PIKACHU! It heard\l"
    .string "everything!$"

SSAnne_1F_Corridor_Text_MeowthSpotsKid::
    .string "MEOWTH: Uh-oh… That kid heard\n"
    .string "everything!$"

SSAnne_1F_Corridor_Text_JessieCallGrunts::
    .string "JESSIE: Don't just stand there!\n"
    .string "GRUNTS, deal with that brat!$"

SSAnne_1F_Corridor_Text_Grunt1Intro::
    .string "GRUNT: Nobody spoils TEAM ROCKET's\n"
    .string "big night at sea!$"

SSAnne_1F_Corridor_Text_Grunt1Defeat::
    .string "Seasick… I'm seasick…$"

SSAnne_1F_Corridor_Text_Grunt2Intro::
    .string "GRUNT: My turn! You'll be walking\n"
    .string "the plank!$"

SSAnne_1F_Corridor_Text_Grunt2Defeat::
    .string "Man overboard!$"

SSAnne_1F_Corridor_Text_JamesMagikarpToTheRescue::
    .string "JAMES: Useless grunts! Behold my\n"
    .string "golden-egg MAGIKARP!$"

SSAnne_1F_Corridor_Text_RocketBattleIntro::
    .string "JESSIE & JAMES: This ship's POKéMON\n"
    .string "are ours!$"

SSAnne_1F_Corridor_Text_RocketDefeat::
    .string "Sunk… again!$"

SSAnne_1F_Corridor_Text_SalesmanLaughs::
    .string "SALESMAN: Hah! That fellow paid me\n"
    .string "¥500 for a MAGIKARP that can only\l"
    .string "SPLASH!\p"
    .string "And you sent them packing. Here,\n"
    .string "this is on the house!$"

SSAnne_1F_Corridor_Text_SalesmanBye::
    .string "SALESMAN: A NUGGET sells for a\n"
    .string "pretty penny. Now, if you'll excuse\l"
    .string "me, I have MAGIKARP to sell!$"

