CeruleanCity_Gym_Text_MistyIntro::
    .string "Hi, you're a new face!\p"
    .string "Only those TRAINERS who have a\n"
    .string "policy about POKéMON can turn pro.\p"
    .string "What is your approach when you\n"
    .string "catch and train POKéMON?\p"
    .string "My policy is an all-out offensive\n"
    .string "with WATER-type POKéMON!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM03 teaches WATER PULSE.\p"
    .string "Use it on an aquatic POKéMON!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "The CASCADEBADGE makes all\n"
    .string "POKéMON up to Lv. 30 obey.\p"
    .string "That includes even outsiders you\n"
    .string "got in trades.\p"
    .string "There's more. You can now use CUT\n"
    .string "anytime, even out of battle.\p"
    .string "You can CUT down small trees to\n"
    .string "open new pathways.\p"
    .string "You can also have my favorite TM.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} received TM03\n"
    .string "from MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "You better make room for this!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Wow!\n"
    .string "You're too much!\p"
    .string "All right!\p"
    .string "You can have the CASCADEBADGE to\n"
    .string "show you beat me.$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "What? You?\n"
    .string "I'm more than good enough for you!\p"
    .string "MISTY won't have to be bothered.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "You overwhelmed me!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "You have to face other TRAINERS\n"
    .string "to see how good you really are.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "Splash!\p"
    .string "I'm first up!\n"
    .string "Let's do it!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "That can't be!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "MISTY is a TRAINER who's going to\n"
    .string "keep improving.\p"
    .string "She won't lose to someone like you!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Let me give you some advice!\p"
    .string "The LEADER, MISTY, is a pro who\n"
    .string "uses WATER-type POKéMON.\p"
    .string "You can drain all their water with\n"
    .string "GRASS-type POKéMON.\p"
    .string "Or, you might use ELECTRIC-type\n"
    .string "POKéMON and zap them!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "You beat MISTY!\n"
    .string "See, what'd I tell ya?\p"
    .string "You and me, kid, we make a pretty\n"
    .string "darn-good team!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

CeruleanCity_Gym_Text_JessieWaterShow::
    .string "JESSIE: The famous CERULEAN water\n"
    .string "show! Its stars will look lovely\l"
    .string "in TEAM ROCKET's aquarium!$"

CeruleanCity_Gym_Text_JamesDrainPool::
    .string "JAMES: And we'll pull the plug on\n"
    .string "the pool on our way out!$"

CeruleanCity_Gym_Text_MistyNotInMyGym::
    .string "MISTY: Not in my gym, you don't!\n"
    .string "{PLAYER}, give me a hand here!$"

CeruleanCity_Gym_Text_MeowthSpotsPikachu::
    .string "MEOWTH: The twerp with the super\n"
    .string "PIKACHU again? Fine by me! We'll\l"
    .string "bag it with the rest!$"

CeruleanCity_Gym_Text_RocketBattleIntro::
    .string "JESSIE & JAMES: Stand aside, or\n"
    .string "get washed away!$"

CeruleanCity_Gym_Text_RocketDefeat::
    .string "All wet… again!$"

CeruleanCity_Gym_Text_MistyThanks::
    .string "MISTY: Hmph! Those three have some\n"
    .string "nerve, crashing my gym.\p"
    .string "Thanks for the help. Here, you've\n"
    .string "earned this.$"

CeruleanCity_Gym_Text_MistyMysticWater::
    .string "MISTY: MYSTIC WATER powers up\n"
    .string "WATER-type moves. Good for a\l"
    .string "PIKACHU that SURFS, too!$"

CeruleanCity_Gym_Text_MistyWaterStone::
    .string "MISTY: And this WATER STONE was\n"
    .string "a prop for the show. Keep it.\p"
    .string "I'd rather it went to someone who\n"
    .string "actually protects POKéMON.$"
