OldaleTown_Text_H0::
	.string "I want to take a rest, so I'm saving my\n"
	.string "progress.$"

OldaleTown_Text_H1::
	.string "Hi!\n"
	.string "I work at a POKéMON MART.\p"
	.string "Can I get you to come with me?$"

OldaleTown_Text_H2::
	.string "I just discovered the footprints of\n"
	.string "a rare POKéMON!\p"
	.string "Wait until I finish sketching\n"
	.string "them, okay?$"

OldaleTown_Text_H3::
	.string "OLDALE TOWN\n"
	.string "“Where things start off scarce.”$"

