Route111_WinstrateFamilysHouse_MapScripts::
	.byte 0

Route111_WinstrateFamilysHouse_EventScript_H0::
	msgbox Route111_WinstrateFamilysHouse_Text_H0, MSGBOX_NPC
	end

Route111_WinstrateFamilysHouse_EventScript_H1::
	msgbox Route111_WinstrateFamilysHouse_Text_H1, MSGBOX_NPC
	end

Route111_WinstrateFamilysHouse_EventScript_H2::
	msgbox Route111_WinstrateFamilysHouse_Text_H2, MSGBOX_NPC
	end

Route111_WinstrateFamilysHouse_EventScript_H3::
	msgbox Route111_WinstrateFamilysHouse_Text_H3, MSGBOX_NPC
	end

