MeteorFalls_1F_2R_Text_H0_0::
	.string "This is where we DRAGON users do\n"
	.string "our training.\p"
	.string "The CHAMPION even visits. Now do\n"
	.string "you see how special it is here?$"

MeteorFalls_1F_2R_Text_H0_1::
	.string "Urgh!\n"
	.string "I didn't expect you to be so strong!$"

MeteorFalls_1F_2R_Text_H0_2::
	.string "The road ahead remains long and\n"
	.string "harsh.\p"
	.string "When will my POKéMON and I become\n"
	.string "the best?$"

MeteorFalls_1F_2R_Text_H1_0::
	.string "JOHN: We've always battled POKéMON\n"
	.string "together as a twosome.\l"
	.string "We've confidence in ourselves.$"

MeteorFalls_1F_2R_Text_H1_1::
	.string "JOHN: Oh, my.\n"
	.string "We've lost, dear wife.$"

MeteorFalls_1F_2R_Text_H1_2::
	.string "JOHN: We've been married for\n"
	.string "fifty years.\p"
	.string "Come to think of it, I've yet to\n"
	.string "beat my dear wife in a battle.$"

MeteorFalls_1F_2R_Text_H2_0::
	.string "JAY: We've been married for\n"
	.string "fifty years.\p"
	.string "The bond we share as a couple could\n"
	.string "never be broken.$"

MeteorFalls_1F_2R_Text_H2_1::
	.string "JAY: Oh, dear.\n"
	.string "We've lost, my dear husband.$"

MeteorFalls_1F_2R_Text_H2_2::
	.string "JAY: Fifty years of marriage…\p"
	.string "If we ever argued, we always\n"
	.string "settled it with a POKéMON battle…$"

