MtPyre_6F_Text_H0_0::
	.string "When I'm here…\n"
	.string "A curious power flows into me…$"

MtPyre_6F_Text_H0_1::
	.string "The power is ebbing away…$"

MtPyre_6F_Text_H0_2::
	.string "Perhaps the power is from the spirits\n"
	.string "of POKéMON in fitful sleep here…$"

MtPyre_6F_Text_H1_0::
	.string "Have you lost your bearings?\n"
	.string "Have no fear for I am here!$"

MtPyre_6F_Text_H1_1::
	.string "Weren't you lost?$"

MtPyre_6F_Text_H1_2::
	.string "I had this feeling that a lost TRAINER\n"
	.string "would be panicked and easy to beat.\p"
	.string "It's dirty and I won't try it again…$"

