Route109_SeashoreHouse_MapScripts::
	.byte 0

Route109_SeashoreHouse_EventScript_H0::
	msgbox Route109_SeashoreHouse_Text_H0, MSGBOX_NPC
	end

Route109_SeashoreHouse_EventScript_H1::
	msgbox Route109_SeashoreHouse_Text_H1, MSGBOX_NPC
	end

Route109_SeashoreHouse_EventScript_H2::
	msgbox Route109_SeashoreHouse_Text_H2, MSGBOX_NPC
	end

Route109_SeashoreHouse_EventScript_H3::
	msgbox Route109_SeashoreHouse_Text_H3, MSGBOX_NPC
	end

