Route109_SeashoreHouse_Text_H0::
	.string "I'm the owner of the SEASHORE\n"
	.string "HOUSE. But you can call me MR. SEA!\p"
	.string "What I love above all is to see hot\n"
	.string "POKéMON battles.\p"
	.string "Let me see that your heart burns\n"
	.string "hot!\p"
	.string "If you can defeat all the TRAINERS\n"
	.string "here, I'll reward your efforts.$"

Route109_SeashoreHouse_Text_H1_0::
	.string "If you're looking for a battle in the\n"
	.string "SEASHORE HOUSE, you'll find no\l"
	.string "hotter TRAINER than me, matey!$"

Route109_SeashoreHouse_Text_H1_1::
	.string "That was a hot battle!\n"
	.string "I can accept that loss, matey!$"

Route109_SeashoreHouse_Text_H1_2::
	.string "Whenever I'm in SLATEPORT, I enjoy\n"
	.string "hot battles and ice-cold SODA POP!$"

Route109_SeashoreHouse_Text_H2_0::
	.string "I'm going to show you how great\n"
	.string "my POKéMON are, but don't cry!$"

Route109_SeashoreHouse_Text_H2_1::
	.string "…I lost, but I won't cry…$"

Route109_SeashoreHouse_Text_H2_2::
	.string "If one of my POKéMON knew the move\n"
	.string "for carrying me across water on its\l"
	.string "back, I could get rid of this inner\l"
	.string "tube.$"

Route109_SeashoreHouse_Text_H3_0::
	.string "Boring battles aren't worth the\n"
	.string "effort.\p"
	.string "Fiery hot battles are what toughen\n"
	.string "up TRAINERS and POKéMON!$"

Route109_SeashoreHouse_Text_H3_1::
	.string "That's hot!$"

Route109_SeashoreHouse_Text_H3_2::
	.string "Whew, I'm all thirsty.\n"
	.string "Maybe I'll have a SODA POP.$"

