Route119_WeatherInstitute_1F_Text_H0::
	.string "Wow, you're really strong!\p"
	.string "I wish I could be a POKéMON TRAINER\n"
	.string "like you!$"

Route119_WeatherInstitute_1F_Text_H1::
	.string "There's a bed…\n"
	.string "Let's take a rest.$"

Route119_WeatherInstitute_1F_Text_H2::
	.string "There's a bed…\n"
	.string "Let's take a rest.$"

Route119_WeatherInstitute_1F_Text_H3::
	.string "There's a bed…\n"
	.string "Let's take a rest.$"

Route119_WeatherInstitute_1F_Text_H4::
	.string "There's a bed…\n"
	.string "Let's take a rest.$"

