Route121_MapScripts::
	.byte 0

Route121_EventScript_H0::
	msgbox Route121_Text_H0, MSGBOX_NPC
	end

Route121_EventScript_H1::
	msgbox Route121_Text_H1, MSGBOX_NPC
	end

Route121_EventScript_H2::
	msgbox Route121_Text_H2, MSGBOX_NPC
	end

Route121_EventScript_H3::
	msgbox Route121_Text_H3, MSGBOX_NPC
	end

Route121_EventScript_H4::
	msgbox Route121_Text_H4, MSGBOX_NPC
	end

Route121_EventScript_H5::
	msgbox Route121_Text_H5, MSGBOX_NPC
	end

Route121_EventScript_H6::
	msgbox Route121_Text_H6, MSGBOX_NPC
	end

Route121_EventScript_H7::
	msgbox Route121_Text_H7, MSGBOX_NPC
	end

Route121_EventScript_H8::
	msgbox Route121_Text_H8, MSGBOX_NPC
	end

Route121_EventScript_H9::
	msgbox Route121_Text_H9, MSGBOX_NPC
	end

Route121_EventScript_H10::
	msgbox Route121_Text_H10, MSGBOX_NPC
	end

Route121_EventScript_H11::
	msgbox Route121_Text_H11, MSGBOX_NPC
	end

Route121_EventScript_H12::
	msgbox Route121_Text_H12, MSGBOX_SIGN
	end

Route121_EventScript_H13::
	msgbox Route121_Text_H13, MSGBOX_SIGN
	end

