Route121_MapScripts::
	.byte 0

Route121_EventScript_H0::
	msgbox Route121_Text_H0, MSGBOX_NPC
	end

Route121_EventScript_H1::
	trainerbattle_double TRAINER_HOENN_KATE_AND_JOY, Route121_Text_H1_0, Route121_Text_H1_1, Route121_Text_H1_1
	msgbox Route121_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route121_EventScript_H2::
	trainerbattle_double TRAINER_HOENN_KATE_AND_JOY, Route121_Text_H2_0, Route121_Text_H2_1, Route121_Text_H2_1
	msgbox Route121_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route121_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_VANESSA, Route121_Text_H3_0, Route121_Text_H3_1
	msgbox Route121_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route121_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_WALTER_1, Route121_Text_H4_0, Route121_Text_H4_1
	msgbox Route121_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route121_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_TAMMY, Route121_Text_H5_0, Route121_Text_H5_1
	msgbox Route121_Text_H5_2, MSGBOX_AUTOCLOSE
	end

Route121_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_JESSICA_1, Route121_Text_H6_0, Route121_Text_H6_1
	msgbox Route121_Text_H6_2, MSGBOX_AUTOCLOSE
	end

Route121_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_CALE, Route121_Text_H7_0, Route121_Text_H7_1
	msgbox Route121_Text_H7_2, MSGBOX_AUTOCLOSE
	end

Route121_EventScript_H8::
	trainerbattle_single TRAINER_HOENN_MYLES, Route121_Text_H8_0, Route121_Text_H8_1
	msgbox Route121_Text_H8_2, MSGBOX_AUTOCLOSE
	end

Route121_EventScript_H9::
	trainerbattle_single TRAINER_HOENN_PAT, Route121_Text_H9_0, Route121_Text_H9_1
	msgbox Route121_Text_H9_2, MSGBOX_AUTOCLOSE
	end

Route121_EventScript_H10::
	trainerbattle_single TRAINER_HOENN_MARCEL, Route121_Text_H10_0, Route121_Text_H10_1
	msgbox Route121_Text_H10_2, MSGBOX_AUTOCLOSE
	end

Route121_EventScript_H11::
	trainerbattle_single TRAINER_HOENN_CRISTIN_1, Route121_Text_H11_0, Route121_Text_H11_1
	msgbox Route121_Text_H11_2, MSGBOX_AUTOCLOSE
	end

Route121_EventScript_H12::
	msgbox Route121_Text_H12, MSGBOX_SIGN
	end

Route121_EventScript_H13::
	msgbox Route121_Text_H13, MSGBOX_SIGN
	end

