Route121_Text_H0::
	.string "Ahead looms MT. PYRE…\p"
	.string "It is a natural monument to the spirits \n"
	.string "of departed POKéMON…$"

Route121_Text_H1::
	.string "KATE: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them…$"

Route121_Text_H2::
	.string "JOY: Ehehe, I'll have to train with KATE,\n"
	.string "my senior student partner, again.$"

Route121_Text_H3::
	.string "I'm going to a CONTEST in LILYCOVE.\p"
	.string "My POKéMON should have no problem\n"
	.string "sweeping the MASTER CLASS.$"

Route121_Text_H4::
	.string "I would like to circle the globe once\n"
	.string "again with my POKéMON.$"

Route121_Text_H5::
	.string "MT. PYRE…\n"
	.string "There is a mysterious power\l"
	.string "at work there…$"

Route121_Text_H6::
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_H7::
	.string "I bought too much stuff at\n"
	.string "the LILYCOVE DEPT. STORE.\p"
	.string "It's up the road from here.\n"
	.string "I wish I had a BAG like yours.$"

Route121_Text_H8::
	.string "They're great, your POKéMON!\n"
	.string "How do you raise them?$"

Route121_Text_H9::
	.string "I raise every POKéMON with the same\n"
	.string "love and care--I don't pick favorites.$"

Route121_Text_H10::
	.string "I may have to train my gang some more\n"
	.string "before entering any CONTEST.$"

Route121_Text_H11::
	.string "I didn't expect to lose this easily…\n"
	.string "I'll win next time!$"

Route121_Text_H12::
	.string "MT. PYRE PIER\p"
	.string "…The sign is old and worn out.\n"
	.string "The words are barely legible…$"

Route121_Text_H13::
	.string "“Filled with rare POKéMON!”\n"
	.string "SAFARI ZONE$"

