Route121_Text_H0::
	.string "Ahead looms MT. PYRE…\p"
	.string "It is a natural monument to the spirits \n"
	.string "of departed POKéMON…$"

Route121_Text_H1_0::
	.string "KATE: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_H1_1::
	.string "KATE: I blew it in front of my junior\n"
	.string "student partner…$"

Route121_Text_H1_2::
	.string "KATE: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them…$"

Route121_Text_H2_0::
	.string "JOY: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_H2_1::
	.string "JOY: Please forgive me, KATE!$"

Route121_Text_H2_2::
	.string "JOY: Ehehe, I'll have to train with KATE,\n"
	.string "my senior student partner, again.$"

Route121_Text_H3_0::
	.string "Will you play with my delightfully\n"
	.string "pretty POKéMON?$"

Route121_Text_H3_1::
	.string "This isn't what I meant!$"

Route121_Text_H3_2::
	.string "I'm going to a CONTEST in LILYCOVE.\p"
	.string "My POKéMON should have no problem\n"
	.string "sweeping the MASTER CLASS.$"

Route121_Text_H4_0::
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_H4_1::
	.string "Ah, well played.$"

Route121_Text_H4_2::
	.string "I would like to circle the globe once\n"
	.string "again with my POKéMON.$"

Route121_Text_H5_0::
	.string "There are powers beyond our\n"
	.string "understanding in the world…$"

Route121_Text_H5_1::
	.string "I have lost…$"

Route121_Text_H5_2::
	.string "MT. PYRE…\n"
	.string "There is a mysterious power\l"
	.string "at work there…$"

Route121_Text_H6_0::
	.string "Stop! Have a good look at my precious\n"
	.string "POKéMON!$"

Route121_Text_H6_1::
	.string "Oh, how dare you!\n"
	.string "Don't take it so seriously!$"

Route121_Text_H6_2::
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_H7_0::
	.string "Can't you see that I have all this\n"
	.string "stuff with me?\p"
	.string "Despite that, you still insist that\n"
	.string "we battle?$"

Route121_Text_H7_1::
	.string "Of course I lost!\n"
	.string "I'm holding stuff in both hands!$"

Route121_Text_H7_2::
	.string "I bought too much stuff at\n"
	.string "the LILYCOVE DEPT. STORE.\p"
	.string "It's up the road from here.\n"
	.string "I wish I had a BAG like yours.$"

Route121_Text_H8_0::
	.string "There's nothing I love more than\n"
	.string "checking out other people's POKéMON!$"

Route121_Text_H8_1::
	.string "Super awesome!$"

Route121_Text_H8_2::
	.string "They're great, your POKéMON!\n"
	.string "How do you raise them?$"

Route121_Text_H9_0::
	.string "I want everybody to see the POKéMON\n"
	.string "I've raised!$"

Route121_Text_H9_1::
	.string "Wow!\n"
	.string "Spectacular!$"

Route121_Text_H9_2::
	.string "I raise every POKéMON with the same\n"
	.string "love and care--I don't pick favorites.$"

Route121_Text_H10_0::
	.string "My POKéMON have never tasted defeat!\n"
	.string "On their next win, I'm entering them\l"
	.string "in CONTESTS.$"

Route121_Text_H10_1::
	.string "Oh, now what happened here?$"

Route121_Text_H10_2::
	.string "I may have to train my gang some more\n"
	.string "before entering any CONTEST.$"

Route121_Text_H11_0::
	.string "I have this routine.\n"
	.string "Defeat five TRAINERS a day.\l"
	.string "Guess what? You're number five!$"

Route121_Text_H11_1::
	.string "No!\n"
	.string "You're horrid!$"

Route121_Text_H11_2::
	.string "I didn't expect to lose this easily…\n"
	.string "I'll win next time!$"

Route121_Text_H12::
	.string "MT. PYRE PIER\p"
	.string "…The sign is old and worn out.\n"
	.string "The words are barely legible…$"

Route121_Text_H13::
	.string "“Filled with rare POKéMON!”\n"
	.string "SAFARI ZONE$"

