	.section .rodata

	.include "asm/macros/m4a.inc"
	.include "asm/macros/music_voice.inc"

@ BEGIN HOENN MUSIC (generated by tools/hoenn_import/import_music.py)
	.include "sound/hoenn_keysplit_tables.inc"
@ END HOENN MUSIC
	.include "sound/voice_groups.inc"
	.include "sound/keysplit_tables.inc"
	.include "sound/programmable_wave_data.inc"
	.include "sound/music_player_table.inc"
	.include "sound/song_table.inc"
	.include "sound/direct_sound_data.inc"

	.align 2
