PetalburgCity_MapScripts::
	.byte 0

PetalburgCity_EventScript_H0::
	msgbox PetalburgCity_Text_H0, MSGBOX_NPC
	end

PetalburgCity_EventScript_H1::
	msgbox PetalburgCity_Text_H1, MSGBOX_NPC
	end

PetalburgCity_EventScript_HItem0::
	finditem ITEM_MAX_REVIVE
	end

PetalburgCity_EventScript_HItem1::
	finditem ITEM_ETHER
	end

PetalburgCity_EventScript_H2::
	msgbox PetalburgCity_Text_H2, MSGBOX_NPC
	end

PetalburgCity_EventScript_H3::
	msgbox PetalburgCity_Text_H3, MSGBOX_SIGN
	end

PetalburgCity_EventScript_H4::
	msgbox PetalburgCity_Text_H4, MSGBOX_SIGN
	end

PetalburgCity_EventScript_H5::
	msgbox PetalburgCity_Text_H5, MSGBOX_SIGN
	end

