BattleFrontier_OutsideWest_MapScripts::
	.byte 0

BattleFrontier_OutsideWest_EventScript_H0::
	msgbox BattleFrontier_OutsideWest_Text_H0, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H1::
	msgbox BattleFrontier_OutsideWest_Text_H1, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H2::
	msgbox BattleFrontier_OutsideWest_Text_H2, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H3::
	msgbox BattleFrontier_OutsideWest_Text_H3, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H4::
	msgbox BattleFrontier_OutsideWest_Text_H4, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H5::
	msgbox BattleFrontier_OutsideWest_Text_H5, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H6::
	msgbox BattleFrontier_OutsideWest_Text_H6, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H7::
	msgbox BattleFrontier_OutsideWest_Text_H7, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H8::
	msgbox BattleFrontier_OutsideWest_Text_H8, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H9::
	msgbox BattleFrontier_OutsideWest_Text_H9, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H10::
	msgbox BattleFrontier_OutsideWest_Text_H10, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H11::
	msgbox BattleFrontier_OutsideWest_Text_H11, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H12::
	msgbox BattleFrontier_OutsideWest_Text_H12, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H13::
	msgbox BattleFrontier_OutsideWest_Text_H13, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H14::
	msgbox BattleFrontier_OutsideWest_Text_H14, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H15::
	msgbox BattleFrontier_OutsideWest_Text_H15, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H16::
	msgbox BattleFrontier_OutsideWest_Text_H16, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H17::
	msgbox BattleFrontier_OutsideWest_Text_H17, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H18::
	msgbox BattleFrontier_OutsideWest_Text_H18, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H19::
	msgbox BattleFrontier_OutsideWest_Text_H19, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H20::
	msgbox BattleFrontier_OutsideWest_Text_H20, MSGBOX_NPC
	end

BattleFrontier_OutsideWest_EventScript_H21::
	msgbox BattleFrontier_OutsideWest_Text_H21, MSGBOX_SIGN
	end

BattleFrontier_OutsideWest_EventScript_H22::
	msgbox BattleFrontier_OutsideWest_Text_H22, MSGBOX_SIGN
	end

BattleFrontier_OutsideWest_EventScript_H23::
	msgbox BattleFrontier_OutsideWest_Text_H23, MSGBOX_SIGN
	end

