BattleFrontier_OutsideWest_Text_H0::
	.string "I'm the best out of all my friends.\n"
	.string "But here…\l"
	.string "I've been useless!$"

BattleFrontier_OutsideWest_Text_H1::
	.string "Hello, are you here for the ferry?\n"
	.string "May I see your TICKET?$"

BattleFrontier_OutsideWest_Text_H2::
	.string "Ah, so this here is the BATTLE\n"
	.string "DOME? I won't let GENTLEMEN beat\l"
	.string "me!\p"
	.string "But where is the entrance?$"

BattleFrontier_OutsideWest_Text_H3::
	.string "It's not as if just anyone can come\n"
	.string "here, you know?\p"
	.string "Only those TRAINERS who've been\n"
	.string "recognized as tough are brought\l"
	.string "here.\p"
	.string "That's why many TRAINERS don't even\n"
	.string "know about the BATTLE FRONTIER.$"

BattleFrontier_OutsideWest_Text_H4::
	.string "I've finally arrived at the BATTLE\n"
	.string "FRONTIER!\p"
	.string "I'm sure to grab attention with\n"
	.string "my looks and ability!$"

BattleFrontier_OutsideWest_Text_H5::
	.string "Munch, munch…\p"
	.string "It looks like this square's filled\n"
	.string "with tough people.\p"
	.string "Munch, munch…$"

BattleFrontier_OutsideWest_Text_H6::
	.string "Oh? You're off to challenge\n"
	.string "the BATTLE DOME?\p"
	.string "I'll wish you the best of luck.\n"
	.string "Let us both win our way up and meet\l"
	.string "in challenges.$"

BattleFrontier_OutsideWest_Text_H7::
	.string "There used to be nothing here not\n"
	.string "all that long ago.\p"
	.string "But, now look at this place!\n"
	.string "Amazing! I'll bring my mother out to\l"
	.string "see this.$"

BattleFrontier_OutsideWest_Text_H8::
	.string "I'm scared of going into the BATTLE\n"
	.string "PIKE because of SEVIPER…\p"
	.string "B-but I came all the way here, so I\n"
	.string "will try to conquer everything!\l"
	.string "…Shudder…$"

BattleFrontier_OutsideWest_Text_H9::
	.string "Let's play rock, paper, scissors!\n"
	.string "One, two, three!\p"
	.string "… … … … … …$"

BattleFrontier_OutsideWest_Text_H10::
	.string "That's the BATTLE FACTORY.\n"
	.string "You can rent strong POKéMON there.\p"
	.string "But it makes me wonder.\n"
	.string "Who's raising those rental POKéMON?$"

BattleFrontier_OutsideWest_Text_H11::
	.string "Today, I'm going to keep battling,\n"
	.string "no matter what, until I get a\l"
	.string "Symbol.$"

BattleFrontier_OutsideWest_Text_H12::
	.string "The BATTLE FRONTIER… I've long\n"
	.string "dreamed about a place like it.$"

BattleFrontier_OutsideWest_Text_H13::
	.string "I believe I'm the only person here\n"
	.string "who, for some unknown reason, would\l"
	.string "choose fishing over battling.\p"
	.string "Huh? You can't catch anything here?\n"
	.string "That's disappointing…$"

BattleFrontier_OutsideWest_Text_H14::
	.string "I wanted to take a challenge as\n"
	.string "soon as I arrived here.\p"
	.string "But on the way, I got seasick…\n"
	.string "Urrrrp…$"

BattleFrontier_OutsideWest_Text_H15::
	.string "Crunch, munch…\p"
	.string "A while back, I met this older girl\n"
	.string "at the BATTLE PIKE.\p"
	.string "She had these eyes that were scary\n"
	.string "in a real ornery way.\p"
	.string "Crunch, munch…\p"
	.string "She got all furious: “Will you quit\n"
	.string "eating!” Then she whaled on me.\p"
	.string "It was a hair-raising kind of\n"
	.string "scary experience, sure enough.\p"
	.string "Crunch, munch…$"

BattleFrontier_OutsideWest_Text_H16::
	.string "Huh? Will you listen to yourself?\n"
	.string "That's nothing!\p"
	.string "Why, the last time I cheered for\n"
	.string "him, our eyes met and sparks flew!$"

BattleFrontier_OutsideWest_Text_H17::
	.string "Whaaaaaat?!\n"
	.string "Pfft!\p"
	.string "That only happened because I\n"
	.string "happened to be sitting next to you!\p"
	.string "The DOME ACE only looked our way\n"
	.string "because my cheering was so loud!$"

BattleFrontier_OutsideWest_Text_H18::
	.string "Oh, shush!\n"
	.string "Keep that racket down!\p"
	.string "You fair-weather fans should stick\n"
	.string "to cheering for some GYM LEADER!\p"
	.string "The DOME ACE is mine!\n"
	.string "The only idol for me!$"

BattleFrontier_OutsideWest_Text_H19::
	.string "Those people squabbling over there…\p"
	.string "It's hard to believe, but they once\n"
	.string "were TRAINERS, and good ones, too.\p"
	.string "They used to be incredibly tough,\n"
	.string "and they were famous, too.\p"
	.string "But they were obliterated by this\n"
	.string "certain TRAINER at a tournament.\p"
	.string "They were so thoroughly whipped,\n"
	.string "they became smitten by the TRAINER.\p"
	.string "Now they're just fans of the\n"
	.string "TRAINER. They go cheer for their\l"
	.string "idol at the BATTLE DOME every day\l"
	.string "now.$"

BattleFrontier_OutsideWest_Text_H20::
	.string "I heard a rumor that someone saw a\n"
	.string "POKéMON with an unusually long tail\l"
	.string "somewhere in the BATTLE FRONTIER.\p"
	.string "It must be adorable. I'm sure of it…\p"
	.string "Oh, challenges can wait. I feel\n"
	.string "driven to find the delightful\l"
	.string "creature!$"

BattleFrontier_OutsideWest_Text_H21::
	.string "This is the BATTLE DOME! Your path\n"
	.string "to the invincible superstar!$"

BattleFrontier_OutsideWest_Text_H22::
	.string "This is the BATTLE PIKE!\n"
	.string "Choose one of three paths!$"

BattleFrontier_OutsideWest_Text_H23::
	.string "This is the BATTLE FACTORY!\n"
	.string "Seek out the toughest POKéMON!$"

