LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "I recently moved to this town.\p"
    .string "I hear that MR. FUJI's not from\n"
    .string "these parts originally, either.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "That's odd, MR. FUJI isn't here.\n"
    .string "Where'd he go?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "MR. FUJI had been praying alone\n"
    .string "for CUBONE's mother.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "This is really MR. FUJI's house.\p"
    .string "He's really kind.\p"
    .string "He looks after abandoned and\n"
    .string "orphaned POKéMON.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "It's so warm!\n"
    .string "POKéMON are so nice to hug.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "NIDORINO: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "MR. FUJI: {PLAYER}…\p"
    .string "Your POKéDEX quest is one that\n"
    .string "requires strong dedication.\p"
    .string "Without deep love for POKéMON,\n"
    .string "your quest may fail.\p"
    .string "I'm not sure if this will help you,\n"
    .string "but I'd like you to have it.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} received a POKé FLUTE\n"
    .string "from MR. FUJI.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "Upon hearing the POKé FLUTE,\n"
    .string "sleeping POKéMON will spring awake.\p"
    .string "Try using it on POKéMON that are\n"
    .string "sleeping obstacles.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "You must make room for this!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "MR. FUJI: Has my POKé FLUTE\n"
    .string "helped you?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "POKéMON FAN MAGAZINE\n"
    .string "Monthly Grand Prize Drawing!\p"
    .string "The application form is…\p"
    .string "Gone! It's been clipped out.\n"
    .string "Someone must have applied already.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "POKéMON magazines line the shelf.\p"
    .string "POKéMON INSIDER…\p"
    .string "POKéMON FAN…$"


LavenderTown_VolunteerPokemonHouse_Text_FujiTravelerLeftStone::
    .string "MR. FUJI: Ah, {PLAYER}.\n"
    .string "You have become the CHAMPION…\p"
    .string "A traveler from a far land once\n"
    .string "left this stone with me.\p"
    .string "It is called the ENIGMA STONE.\n"
    .string "He said it calls to dragons that\l"
    .string "fly faster than jet planes…$"

LavenderTown_VolunteerPokemonHouse_Text_FujiTheStoneIsGlowing::
    .string "Oh, my! The stone is glowing red\n"
    .string "and blue in your presence!$"

LavenderTown_VolunteerPokemonHouse_Text_RadioNewsBirdsOverKanto::
    .string "…This is POKéMON NEWS!\p"
    .string "A red bird POKéMON and a blue bird\n"
    .string "POKéMON have been sighted flying\l"
    .string "together over KANTO!\p"
    .string "They are said to move so fast that\n"
    .string "no one has been able to catch up!$"

LavenderTown_VolunteerPokemonHouse_Text_FujiTakeTheStone::
    .string "MR. FUJI: A red bird and a blue\n"
    .string "bird… The stone must have woken\l"
    .string "them.\p"
    .string "Please take it. It chose you.$"

LavenderTown_VolunteerPokemonHouse_Text_FujiLatiReminder::
    .string "MR. FUJI: The two dragons roam all\n"
    .string "over KANTO's routes.\p"
    .string "They flee fast. Do not give up if\n"
    .string "you meet them.$"
