Route114_FossilManiacsHouse_MapScripts::
	.byte 0

Route114_FossilManiacsHouse_EventScript_H0::
	msgbox Route114_FossilManiacsHouse_Text_H0, MSGBOX_NPC
	end

Route114_FossilManiacsHouse_EventScript_H1::
	msgbox Route114_FossilManiacsHouse_Text_H1, MSGBOX_SIGN
	end

Route114_FossilManiacsHouse_EventScript_H2::
	msgbox Route114_FossilManiacsHouse_Text_H2, MSGBOX_SIGN
	end

Route114_FossilManiacsHouse_EventScript_H3::
	msgbox Route114_FossilManiacsHouse_Text_H3, MSGBOX_SIGN
	end

Route114_FossilManiacsHouse_EventScript_H4::
	msgbox Route114_FossilManiacsHouse_Text_H4, MSGBOX_SIGN
	end

