FortreeCity_House5_Text_H0::
	.string "The tree houses of FORTREE are great!\p"
	.string "I think it's the number one town for\n"
	.string "living together with POKéMON.$"

FortreeCity_House5_Text_H1::
	.string "ZIGZAGOON: Bufuu!$"

FortreeCity_House5_Text_H2::
	.string "POKéMON and people have adapted to\n"
	.string "nature for survival.\p"
	.string "There's no need to make nature\n"
	.string "conform to the way we want to live.$"

