Route114_MapScripts::
	.byte 0

Route114_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_LENNY, Route114_Text_H0_0, Route114_Text_H0_1
	msgbox Route114_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_LUCAS_1, Route114_Text_H1_0, Route114_Text_H1_1
	msgbox Route114_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_SHANE, Route114_Text_H2_0, Route114_Text_H2_1
	msgbox Route114_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_NANCY, Route114_Text_H3_0, Route114_Text_H3_1
	msgbox Route114_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_STEVE_1, Route114_Text_H4_0, Route114_Text_H4_1
	msgbox Route114_Text_H4_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H5::
	msgbox Route114_Text_H5, MSGBOX_NPC
	end

Route114_EventScript_H6::
	msgbox Route114_Text_H6, MSGBOX_NPC
	end

Route114_EventScript_H7::
	msgbox Route114_Text_H7, MSGBOX_NPC
	end

Route114_EventScript_H8::
	trainerbattle_single TRAINER_HOENN_NOLAN, Route114_Text_H8_0, Route114_Text_H8_1
	msgbox Route114_Text_H8_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H9::
	trainerbattle_single TRAINER_HOENN_CLAUDE, Route114_Text_H9_0, Route114_Text_H9_1
	msgbox Route114_Text_H9_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H10::
	trainerbattle_single TRAINER_HOENN_BERNIE_1, Route114_Text_H10_0, Route114_Text_H10_1
	msgbox Route114_Text_H10_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H11::
	trainerbattle_double TRAINER_HOENN_TYRA_AND_IVY, Route114_Text_H11_0, Route114_Text_H11_1, Route114_Text_H11_1
	msgbox Route114_Text_H11_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H12::
	trainerbattle_double TRAINER_HOENN_TYRA_AND_IVY, Route114_Text_H12_0, Route114_Text_H12_1, Route114_Text_H12_1
	msgbox Route114_Text_H12_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H13::
	trainerbattle_single TRAINER_HOENN_CHARLOTTE, Route114_Text_H13_0, Route114_Text_H13_1
	msgbox Route114_Text_H13_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H14::
	trainerbattle_single TRAINER_HOENN_ANGELINA, Route114_Text_H14_0, Route114_Text_H14_1
	msgbox Route114_Text_H14_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H15::
	trainerbattle_single TRAINER_HOENN_KAI, Route114_Text_H15_0, Route114_Text_H15_1
	msgbox Route114_Text_H15_2, MSGBOX_AUTOCLOSE
	end

Route114_EventScript_H16::
	msgbox Route114_Text_H16, MSGBOX_SIGN
	end

Route114_EventScript_H17::
	msgbox Route114_Text_H17, MSGBOX_SIGN
	end

Route114_EventScript_H18::
	msgbox Route114_Text_H18, MSGBOX_SIGN
	end

