Route114_Text_H0::
	.string "When I was a wee tyke, I believed there\n"
	.string "was someone copying me and shouting\l"
	.string "back, “Yodelayhihoo.”$"

Route114_Text_H1::
	.string "In the winter, mountains turn deadly\n"
	.string "with blizzards and avalanches.$"

Route114_Text_H2::
	.string "I think it's great that I can go\n"
	.string "camping with my POKéMON.$"

Route114_Text_H3::
	.string "I just had a tasty meal.\n"
	.string "I'm getting drowsy…$"

Route114_Text_H4::
	.string "A big body that's all lumpy and hard,\n"
	.string "enormous horns, and vicious fangs…\p"
	.string "Ufufufufu…\n"
	.string "I wish I had a POKéMON like that…$"

Route114_Text_H5::
	.string "All my POKéMON does is ROAR…\n"
	.string "No one dares to come near me…\p"
	.string "Sigh… If you would, please take\n"
	.string "this TM away…$"

Route114_Text_H6::
	.string "Bow! Bowwow!$"

Route114_Text_H7::
	.string "I love using the BERRY CRUSH machine,\n"
	.string "so I'm collecting BERRIES.\p"
	.string "I'll share one with you, if you'd like.$"

Route114_Text_H8::
	.string "This time I'll do it!\p"
	.string "I always think that, so I can't walk\n"
	.string "away from fishing or POKéMON.$"

Route114_Text_H9::
	.string "I think I'll try my luck at landing\n"
	.string "a big one at METEOR FALLS.\p"
	.string "There has to be something in there.\n"
	.string "I just know it.$"

Route114_Text_H10::
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_H11::
	.string "IVY: I started training POKéMON\n"
	.string "because TYRA, my student mentor,\l"
	.string "taught me!$"

Route114_Text_H12::
	.string "TYRA: I was teaching my junior IVY\n"
	.string "about POKéMON.$"

Route114_Text_H13::
	.string "I don't want a POKéMON that's\n"
	.string "just cute.\p"
	.string "I adore cute ones that have a quirk\n"
	.string "or two!$"

Route114_Text_H14::
	.string "Some POKéMON change so much when\n"
	.string "they evolve, it's startling!$"

Route114_Text_H15::
	.string "Okay!\n"
	.string "I'll just fish me a bigger one!$"

Route114_Text_H16::
	.string "METEOR FALLS\n"
	.string "RUSTBORO CITY THROUGH HERE$"

Route114_Text_H17::
	.string "FOSSIL MANIAC'S HOUSE\n"
	.string "“Fossils gratefully accepted!”$"

Route114_Text_H18::
	.string "LANETTE'S HOUSE$"

