Route114_Text_H0_0::
	.string "Yodelayhihoo!\p"
	.string "… …\p"
	.string "You're supposed to shout\n"
	.string "“yodelayhihoo” since it doesn't\l"
	.string "echo here!$"

Route114_Text_H0_1::
	.string "Yodelayhihoo!$"

Route114_Text_H0_2::
	.string "When I was a wee tyke, I believed there\n"
	.string "was someone copying me and shouting\l"
	.string "back, “Yodelayhihoo.”$"

Route114_Text_H1_0::
	.string "If you're not prepared, you shouldn't\n"
	.string "be up in the mountains!$"

Route114_Text_H1_1::
	.string "The mountains are unforgiving…$"

Route114_Text_H1_2::
	.string "In the winter, mountains turn deadly\n"
	.string "with blizzards and avalanches.$"

Route114_Text_H2_0::
	.string "Camping's fun! You can fish, roast\n"
	.string "marshmallows, and tell spooky stories!\p"
	.string "But the best of all are the POKéMON\n"
	.string "battles!$"

Route114_Text_H2_1::
	.string "Way too strong!$"

Route114_Text_H2_2::
	.string "I think it's great that I can go\n"
	.string "camping with my POKéMON.$"

Route114_Text_H3_0::
	.string "I need to exercise after a meal.\n"
	.string "Let's have a match!$"

Route114_Text_H3_1::
	.string "Oh, no!$"

Route114_Text_H3_2::
	.string "I just had a tasty meal.\n"
	.string "I'm getting drowsy…$"

Route114_Text_H4_0::
	.string "Ufufufufufu…\n"
	.string "Want to battle against my POKéMON?$"

Route114_Text_H4_1::
	.string "M-My POKéMON…$"

Route114_Text_H4_2::
	.string "A big body that's all lumpy and hard,\n"
	.string "enormous horns, and vicious fangs…\p"
	.string "Ufufufufu…\n"
	.string "I wish I had a POKéMON like that…$"

Route114_Text_H5::
	.string "All my POKéMON does is ROAR…\n"
	.string "No one dares to come near me…\p"
	.string "Sigh… If you would, please take\n"
	.string "this TM away…$"

Route114_Text_H6::
	.string "Bow! Bowwow!$"

Route114_Text_H7::
	.string "I love using the BERRY CRUSH machine,\n"
	.string "so I'm collecting BERRIES.\p"
	.string "I'll share one with you, if you'd like.$"

Route114_Text_H8_0::
	.string "I like to fish. But I also like to\n"
	.string "battle!\p"
	.string "If anyone challenges me, I'm there,\n"
	.string "even if I'm fishing.$"

Route114_Text_H8_1::
	.string "I like to battle, but that doesn't\n"
	.string "mean I'm good at it…$"

Route114_Text_H8_2::
	.string "This time I'll do it!\p"
	.string "I always think that, so I can't walk\n"
	.string "away from fishing or POKéMON.$"

Route114_Text_H9_0::
	.string "If we were fishing, you wouldn't stand\n"
	.string "a chance against me.\l"
	.string "So, bring on your POKéMON!$"

Route114_Text_H9_1::
	.string "If we were fishing, I would've won…$"

Route114_Text_H9_2::
	.string "I think I'll try my luck at landing\n"
	.string "a big one at METEOR FALLS.\p"
	.string "There has to be something in there.\n"
	.string "I just know it.$"

Route114_Text_H10_0::
	.string "If you're lighting a campfire,\n"
	.string "make sure you have water handy.$"

Route114_Text_H10_1::
	.string "Thanks for dousing my fire!$"

Route114_Text_H10_2::
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_H11_0::
	.string "IVY: Who taught you about POKéMON?$"

Route114_Text_H11_1::
	.string "IVY: What an amazing battle style!$"

Route114_Text_H11_2::
	.string "IVY: I started training POKéMON\n"
	.string "because TYRA, my student mentor,\l"
	.string "taught me!$"

Route114_Text_H12_0::
	.string "TYRA: Well, sure.\n"
	.string "I'm in the mood for it.\l"
	.string "I'll teach you a little about POKéMON.$"

Route114_Text_H12_1::
	.string "TYRA: What an amazing battle style!$"

Route114_Text_H12_2::
	.string "TYRA: I was teaching my junior IVY\n"
	.string "about POKéMON.$"

Route114_Text_H13_0::
	.string "Me!\n"
	.string "I'm not just a pretty face!$"

Route114_Text_H13_1::
	.string "That wasn't cute in the least!$"

Route114_Text_H13_2::
	.string "I don't want a POKéMON that's\n"
	.string "just cute.\p"
	.string "I adore cute ones that have a quirk\n"
	.string "or two!$"

Route114_Text_H14_0::
	.string "Have you made your POKéMON evolve\n"
	.string "very much?$"

Route114_Text_H14_1::
	.string "Oh, I see.\n"
	.string "That's good to know.$"

Route114_Text_H14_2::
	.string "Some POKéMON change so much when\n"
	.string "they evolve, it's startling!$"

Route114_Text_H15_0::
	.string "I landed a big one!\n"
	.string "A huge one, I tell you!$"

Route114_Text_H15_1::
	.string "What was that about?\n"
	.string "Did mine lose in size?$"

Route114_Text_H15_2::
	.string "Okay!\n"
	.string "I'll just fish me a bigger one!$"

Route114_Text_H16::
	.string "METEOR FALLS\n"
	.string "RUSTBORO CITY THROUGH HERE$"

Route114_Text_H17::
	.string "FOSSIL MANIAC'S HOUSE\n"
	.string "“Fossils gratefully accepted!”$"

Route114_Text_H18::
	.string "LANETTE'S HOUSE$"

