Route118_MapScripts::
	.byte 0

Route118_EventScript_H0::
	msgbox Route118_Text_H0, MSGBOX_NPC
	end

Route118_EventScript_H1::
	msgbox Route118_Text_H1, MSGBOX_NPC
	end

Route118_EventScript_H2::
	msgbox Route118_Text_H2, MSGBOX_NPC
	end

Route118_EventScript_H3::
	msgbox Route118_Text_H3, MSGBOX_NPC
	end

Route118_EventScript_H4::
	msgbox Route118_Text_H4, MSGBOX_NPC
	end

Route118_EventScript_H5::
	msgbox Route118_Text_H5, MSGBOX_NPC
	end

Route118_EventScript_H6::
	msgbox Route118_Text_H6, MSGBOX_NPC
	end

Route118_EventScript_H7::
	msgbox Route118_Text_H7, MSGBOX_NPC
	end

Route118_EventScript_H8::
	msgbox Route118_Text_H8, MSGBOX_NPC
	end

Route118_EventScript_H9::
	msgbox Route118_Text_H9, MSGBOX_SIGN
	end

Route118_EventScript_H10::
	msgbox Route118_Text_H10, MSGBOX_SIGN
	end

