Route118_Text_H0_0::
	.string "BIRD POKéMON that FLY elegantly in\n"
	.string "the sky… They're the best!$"

Route118_Text_H0_1::
	.string "Urgh…\n"
	.string "I crashed…$"

Route118_Text_H0_2::
	.string "You've got great POKéMON.\n"
	.string "I'll have to train mine better.$"

Route118_Text_H1::
	.string "Even if there isn't a boat, you can\n"
	.string "cross rivers and the sea if you have\l"
	.string "a POKéMON that knows SURF.\p"
	.string "POKéMON can be counted on to do so\n"
	.string "much!$"

Route118_Text_H2::
	.string "Hmm!\n"
	.string "A GOOD ROD is really good!\p"
	.string "Wouldn't you agree?$"

Route118_Text_H3_0::
	.string "The aroma of flowers has a magical\n"
	.string "power. It cleanses us body and soul.$"

Route118_Text_H3_1::
	.string "Oh, dear me.\n"
	.string "I seem to have lost.$"

Route118_Text_H3_2::
	.string "Flowers, POKéMON…\n"
	.string "I love whatever smells nice.\p"
	.string "Stinky things…\n"
	.string "I'll pass.$"

Route118_Text_H4_0::
	.string "For FISHERMEN, equipment is the key.\p"
	.string "But for TRAINERS, the key\n"
	.string "ingredients are POKéMON and heart,\l"
	.string "of course!$"

Route118_Text_H4_1::
	.string "I was beaten in heart?$"

Route118_Text_H4_2::
	.string "Come to think of it, fishing is a\n"
	.string "battle between a FISHERMAN and a\l"
	.string "POKéMON.$"

Route118_Text_H5_0::
	.string "Take flight!\n"
	.string "My BIRD POKéMON!$"

Route118_Text_H5_1::
	.string "They did take flight…$"

Route118_Text_H5_2::
	.string "If they'd get stronger, they'd be\n"
	.string "able to fly more freely…$"

Route118_Text_H6_0::
	.string "I'm a FISHERMAN, but also a\n"
	.string "TRAINER. I'm raising the POKéMON I\l"
	.string "caught.$"

Route118_Text_H6_1::
	.string "I thought I was doing okay in my\n"
	.string "training…$"

Route118_Text_H6_2::
	.string "I couldn't win by training POKéMON\n"
	.string "while I fished…\p"
	.string "Was I doing things in half measures?$"

Route118_Text_H7_0::
	.string "Let my melody rock your soul!$"

Route118_Text_H7_1::
	.string "La-lalala…$"

Route118_Text_H7_2::
	.string "An electric guitar doesn't always\n"
	.string "have to be noisy…\p"
	.string "It can be strummed to squeeze out\n"
	.string "this heart-stirring melody…$"

Route118_Text_H8_0::
	.string "Go, go, go!\n"
	.string "POKéMON 1, 2, and 3!$"

Route118_Text_H8_1::
	.string "Come in, POKéMON! Are you okay?\n"
	.string "POKéMON 1, 2, and 3?!$"

Route118_Text_H8_2::
	.string "Isn't it cool that I have a POKéMON\n"
	.string "battle team?\p"
	.string "You can copy me--I don't mind!$"

Route118_Text_H9::
	.string "ROUTE 118\n"
	.string "{LEFT_ARROW} MAUVILLE CITY$"

Route118_Text_H10::
	.string "ROUTE 118\n"
	.string "{UP_ARROW} ROUTE 119$"

