Route118_Text_H0::
	.string "You've got great POKéMON.\n"
	.string "I'll have to train mine better.$"

Route118_Text_H1::
	.string "Even if there isn't a boat, you can\n"
	.string "cross rivers and the sea if you have\l"
	.string "a POKéMON that knows SURF.\p"
	.string "POKéMON can be counted on to do so\n"
	.string "much!$"

Route118_Text_H2::
	.string "Hmm!\n"
	.string "A GOOD ROD is really good!\p"
	.string "Wouldn't you agree?$"

Route118_Text_H3::
	.string "Flowers, POKéMON…\n"
	.string "I love whatever smells nice.\p"
	.string "Stinky things…\n"
	.string "I'll pass.$"

Route118_Text_H4::
	.string "Come to think of it, fishing is a battle\n"
	.string "between a FISHERMAN and a POKéMON.$"

Route118_Text_H5::
	.string "If they'd get stronger, they'd be able\n"
	.string "to fly more freely…$"

Route118_Text_H6::
	.string "I couldn't win by training POKéMON\n"
	.string "while I fished…\p"
	.string "Was I doing things in half measures?$"

Route118_Text_H7::
	.string "An electric guitar doesn't always\n"
	.string "have to be noisy…\p"
	.string "It can be strummed to squeeze out\n"
	.string "this heart-stirring melody…$"

Route118_Text_H8::
	.string "Isn't it cool that I have a POKéMON\n"
	.string "battle team?\p"
	.string "You can copy me--I don't mind!$"

Route118_Text_H9::
	.string "ROUTE 118\n"
	.string "{LEFT_ARROW} MAUVILLE CITY$"

Route118_Text_H10::
	.string "ROUTE 118\n"
	.string "{UP_ARROW} ROUTE 119$"

