VictoryRoad_B2F_Text_H0_0::
	.string "I trained together with my whole\n"
	.string "family, every one of us! I'm not\l"
	.string "losing to anyone!$"

VictoryRoad_B2F_Text_H0_1::
	.string "Better than my family?!\n"
	.string "Is that possible?!$"

VictoryRoad_B2F_Text_H0_2::
	.string "I was better than everyone in my\n"
	.string "family. I've never lost before…\p"
	.string "I've lost my confidence…\n"
	.string "Maybe I'll go home…$"

VictoryRoad_B2F_Text_H1_0::
	.string "I'd heard that there was a tough\n"
	.string "little kid around. Do they mean you?$"

VictoryRoad_B2F_Text_H1_1::
	.string "The little shrimp is tough!$"

VictoryRoad_B2F_Text_H1_2::
	.string "The rumors I heard, that tough\n"
	.string "little kid is from PETALBURG CITY.$"

VictoryRoad_B2F_Text_H2_0::
	.string "You must be getting a little tired.$"

VictoryRoad_B2F_Text_H2_1::
	.string "No signs of tiring at all!$"

VictoryRoad_B2F_Text_H2_2::
	.string "VICTORY ROAD and the POKéMON\n"
	.string "LEAGUE are long and grueling\l"
	.string "challenges. Beware of fatigue!$"

VictoryRoad_B2F_Text_H3_0::
	.string "You shouldn't get complacent just\n"
	.string "because you have a lot of GYM\l"
	.string "BADGES.\p"
	.string "There's always going to be someone\n"
	.string "who's better than you!$"

VictoryRoad_B2F_Text_H3_1::
	.string "You're better than me!$"

VictoryRoad_B2F_Text_H3_2::
	.string "Gaze on your collected BADGES and\n"
	.string "remember the TRAINERS you've faced.$"

VictoryRoad_B2F_Text_H4_0::
	.string "The elite among the elite gather in\n"
	.string "this cave.\p"
	.string "How are you finding it?$"

VictoryRoad_B2F_Text_H4_1::
	.string "Not rattled in the least bit!$"

VictoryRoad_B2F_Text_H4_2::
	.string "You do have guts! I like that!\n"
	.string "Keep it going!$"

VictoryRoad_B2F_Text_H5_0::
	.string "I've come this far, but the tension's\n"
	.string "giving me awful stomach pain…$"

VictoryRoad_B2F_Text_H5_1::
	.string "Ooh…\n"
	.string "It hurts…$"

VictoryRoad_B2F_Text_H5_2::
	.string "I can't help getting all tense\n"
	.string "knowing that I'm nearing the POKéMON\l"
	.string "LEAGUE.\p"
	.string "It's all I can do to feign calm.$"

