Route116_TunnelersRestHouse_Text_H0::
	.string "That RUSTURF TUNNEL there…\p"
	.string "At first, we had a huge work crew\n"
	.string "boring through rock with the latest\l"
	.string "machinery. But, we had to stop.\p"
	.string "It turns out that we would have had\n"
	.string "a negative effect on wild POKéMON in\l"
	.string "the area.\p"
	.string "So, we've got nothing to do but loll\n"
	.string "around here doing nothing.$"

Route116_TunnelersRestHouse_Text_H1::
	.string "To get to VERDANTURF without using\n"
	.string "this TUNNEL, you'd have to cross the\l"
	.string "sea to DEWFORD, sail on to\l"
	.string "SLATEPORT, then travel through\l"
	.string "MAUVILLE.$"

Route116_TunnelersRestHouse_Text_H2::
	.string "There's a man digging his way to\n"
	.string "VERDANTURF all by his lonesome.\l"
	.string "He's desperate to get through.\p"
	.string "He says that if he digs little by\n"
	.string "little without using machines, he\l"
	.string "won't disturb POKéMON, and he'll\l"
	.string "avoid harming the natural\l"
	.string "environment.\p"
	.string "I wonder if he made it through yet.$"

