DewfordTown_House1_Text_H0::
	.string "I left the major port of SLATEPORT\n"
	.string "CITY when I married my husband\l"
	.string "here.\p"
	.string "Life goes by slowly on this little\n"
	.string "island. But being surrounded by the\l"
	.string "beautiful sea--that's happiness, too.$"

DewfordTown_House1_Text_H1::
	.string "There's a lot to be said for living\n"
	.string "on a small island like this in\l"
	.string "harmony with POKéMON and the family.$"

DewfordTown_House1_Text_H2::
	.string "ZIGZAGOON: Guguuh!$"

