LilycoveCity_DepartmentStore_4F_Text_H0::
	.string "Hmm…\p"
	.string "An attacking move…\n"
	.string "Or a defensive move…\p"
	.string "It's no easy matter to decide which\n"
	.string "TM moves should be taught to\l"
	.string "POKéMON…$"

LilycoveCity_DepartmentStore_4F_Text_H1::
	.string "There are so many different kinds of\n"
	.string "TM moves.\p"
	.string "A catalog I read said there are\n"
	.string "fifty different kinds.$"

LilycoveCity_DepartmentStore_4F_Text_H2::
	.string "I'd like to get all the different\n"
	.string "TMs, but a POKéMON learns only four\l"
	.string "moves.$"

