Route117_Text_H0::
	.string "What do you think?\n"
	.string "Aren't these flowers pretty?\p"
	.string "I planted them all!$"

Route117_Text_H1::
	.string "The air is tasty here!$"

Route117_Text_H2::
	.string "I may have blown it…\p"
	.string "I might have dropped to last during\n"
	.string "that battle…$"

Route117_Text_H3::
	.string "Try raising POKéMON with more\n"
	.string "attention to their character traits.$"

Route117_Text_H4::
	.string "POKéMON isn't all about power.\p"
	.string "Polishing a unique aspect of one's\n"
	.string "character is another way of enjoying\l"
	.string "POKéMON.$"

Route117_Text_H5::
	.string "Training is meaningful only if you\n"
	.string "keep it up regularly.\p"
	.string "Okay! I'll resume my training!\n"
	.string "Tomorrow!$"

Route117_Text_H6::
	.string "All I did was follow my heart, and now\n"
	.string "they call me a BUG MANIAC…\p"
	.string "Still, I am an expert on BUG POKéMON,\n"
	.string "so it's only natural that they call me\l"
	.string "a BUG MANIAC.$"

Route117_Text_H7::
	.string "MEG: I dragged ANNA down…\n"
	.string "If I didn't, she would have won!$"

Route117_Text_H8::
	.string "ANNA: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_H9::
	.string "I left my POKéMON at the DAY CARE.\p"
	.string "When I got it back, it had a new move\n"
	.string "that I didn't teach it.\l"
	.string "I was really, really surprised.$"

Route117_Text_H10::
	.string "PSYCHIC POKéMON are complex.\n"
	.string "You should try catching some.$"

Route117_Text_H11::
	.string "I think that if you worry about losing,\n"
	.string "you're more likely to lose.$"

Route117_Text_H12::
	.string "It feels wonderful to go for a jog\n"
	.string "while looking at flowers.$"

Route117_Text_H13::
	.string "ROUTE 117\n"
	.string "{LEFT_ARROW} VERDANTURF TOWN$"

Route117_Text_H14::
	.string "ROUTE 117\n"
	.string "{RIGHT_ARROW} MAUVILLE CITY$"

Route117_Text_H15::
	.string "POKéMON DAY CARE\n"
	.string "“Let us raise your POKéMON.”$"

