Route117_Text_H0::
	.string "What do you think?\n"
	.string "Aren't these flowers pretty?\p"
	.string "I planted them all!$"

Route117_Text_H1::
	.string "The air is tasty here!$"

Route117_Text_H2_0::
	.string "I'm in the middle of a triathlon,\n"
	.string "but, whatever, let's have a battle!$"

Route117_Text_H2_1::
	.string "I ran out of energy!$"

Route117_Text_H2_2::
	.string "I may have blown it…\p"
	.string "I might have dropped to last during\n"
	.string "that battle…$"

Route117_Text_H3_0::
	.string "Please, allow me to evaluate if you\n"
	.string "have raised your POKéMON properly.$"

Route117_Text_H3_1::
	.string "Yes, they are growing properly.$"

Route117_Text_H3_2::
	.string "Try raising POKéMON with more\n"
	.string "attention to their character traits.$"

Route117_Text_H4_0::
	.string "Listen, could I get you to battle\n"
	.string "the POKéMON I'm raising?$"

Route117_Text_H4_1::
	.string "You've raised yours superbly…$"

Route117_Text_H4_2::
	.string "POKéMON isn't all about power.\p"
	.string "Polishing a unique aspect of one's\n"
	.string "character is another way of enjoying\l"
	.string "POKéMON.$"

Route117_Text_H5_0::
	.string "I do my triathlon training with\n"
	.string "POKéMON, so I'm pretty confident\l"
	.string "about my speed.$"

Route117_Text_H5_1::
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_H5_2::
	.string "Training is meaningful only if you\n"
	.string "keep it up regularly.\p"
	.string "Okay! I'll resume my training!\n"
	.string "Tomorrow!$"

Route117_Text_H6_0::
	.string "Once a BUG CATCHER!\n"
	.string "And now a BUG MANIAC!\p"
	.string "But my love for POKéMON remains\n"
	.string "unchanged!$"

Route117_Text_H6_1::
	.string "My ineptitude also remains\n"
	.string "unchanged…$"

Route117_Text_H6_2::
	.string "All I did was follow my heart, and\n"
	.string "now they call me a BUG MANIAC…\p"
	.string "Still, I am an expert on BUG\n"
	.string "POKéMON, so it's only natural that\l"
	.string "they call me a BUG MANIAC.$"

Route117_Text_H7_0::
	.string "MEG: I'm going to tag up with my\n"
	.string "super senior student partner and\l"
	.string "beat you!$"

Route117_Text_H7_1::
	.string "MEG: Oh, no!\n"
	.string "I'm sorry, ANNA! I let you down…$"

Route117_Text_H7_2::
	.string "MEG: I dragged ANNA down…\n"
	.string "If I didn't, she would have won!$"

Route117_Text_H8_0::
	.string "ANNA: I'm with my pretty junior\n"
	.string "student partner. I have to do good!$"

Route117_Text_H8_1::
	.string "ANNA: I'm with my pretty junior\n"
	.string "student partner! Let me win!$"

Route117_Text_H8_2::
	.string "ANNA: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_H9::
	.string "I left my POKéMON at the DAY CARE.\p"
	.string "When I got it back, it had a new\n"
	.string "move that I didn't teach it. I was\l"
	.string "really, really surprised.$"

Route117_Text_H10_0::
	.string "Let me demonstrate the power\n"
	.string "hidden within a PSYCHIC POKéMON!$"

Route117_Text_H10_1::
	.string "Astonishing!$"

Route117_Text_H10_2::
	.string "PSYCHIC POKéMON are complex.\n"
	.string "You should try catching some.$"

Route117_Text_H11_0::
	.string "Concentrate on getting the win.\n"
	.string "That's how I battle!$"

Route117_Text_H11_1::
	.string "I don't waste any time being angry\n"
	.string "over a loss--I would rather train.$"

Route117_Text_H11_2::
	.string "I think that if you worry about\n"
	.string "losing, you're more likely to lose.$"

Route117_Text_H12_0::
	.string "Isn't it nice? To battle while\n"
	.string "looking at pretty flowers?$"

Route117_Text_H12_1::
	.string "Oh, that's quite impressive!$"

Route117_Text_H12_2::
	.string "It feels wonderful to go for a jog\n"
	.string "while looking at flowers.$"

Route117_Text_H13::
	.string "ROUTE 117\n"
	.string "{LEFT_ARROW} VERDANTURF TOWN$"

Route117_Text_H14::
	.string "ROUTE 117\n"
	.string "{RIGHT_ARROW} MAUVILLE CITY$"

Route117_Text_H15::
	.string "POKéMON DAY CARE\n"
	.string "“Let us raise your POKéMON.”$"
