SootopolisCity_House3_Text_H0::
	.string "You're a POKéMON TRAINER, aren't\n"
	.string "you?\p"
	.string "SOOTOPOLIS's JUAN has many fans.\n"
	.string "Even more than his student WALLACE!\p"
	.string "Do you have any?$"

SootopolisCity_House3_Text_H1::
	.string "Dedicated fans come over from even\n"
	.string "outside of HOENN.\p"
	.string "It was really wild when I went to\n"
	.string "the TRAINER FAN CLUB in LILYCOVE.$"

