LavaridgeTown_Text_H0::
	.string "Oh, you like hot springs, do you?\p"
	.string "That's surprising for one as young\n"
	.string "as you.$"

LavaridgeTown_Text_H1::
	.string "We draw as much hot water as we\n"
	.string "need, and yet the hot springs never\l"
	.string "run dry.\p"
	.string "Isn't it magical?\p"
	.string "These hot springs appear near active\n"
	.string "volcanoes. Veins of water under the\l"
	.string "ground are heated by magma to well\l"
	.string "up as hot springs.$"

LavaridgeTown_Text_H2::
	.string "Being buried in this hot sand is…\n"
	.string "Sigh…\p"
	.string "So warm and heavenly…\p"
	.string "Eh? Gyaah! Ouch!\p"
	.string "A POKéMON nipped my backside!$"

LavaridgeTown_Text_H3::
	.string "I bathe in the hot springs every\n"
	.string "day.\p"
	.string "I want to become a beautiful and\n"
	.string "strong GYM LEADER like FLANNERY.$"

LavaridgeTown_Text_H4::
	.string "If people put POKéMON in hot\n"
	.string "springs, it might be seriously\l"
	.string "strange.\p"
	.string "Why, it might be an electric bath,\n"
	.string "or a bubble bath, or even a lava\l"
	.string "bath…$"

LavaridgeTown_Text_H5::
	.string "They're claiming that these hot\n"
	.string "springs are good for calming nervous\l"
	.string "tension, relieving aching muscles,\l"
	.string "solving romantic problems, and\l"
	.string "attracting money…$"

LavaridgeTown_Text_H6::
	.string "I have here an EGG.\p"
	.string "I'd hoped to hatch it by covering it\n"
	.string "in hot sand by the hot springs. But\l"
	.string "that doesn't seem to be enough…\p"
	.string "I've heard it would be best if it\n"
	.string "were kept together with POKéMON and\l"
	.string "carried about.\p"
	.string "You are a TRAINER, yes?\n"
	.string "And your POKéMON radiate vitality.\p"
	.string "So, what say you?\n"
	.string "Will you take this EGG to hatch?$"

LavaridgeTown_Text_H7::
	.string "POKéMON HERB SHOP\n"
	.string "“Bitter taste--better cure!”$"

LavaridgeTown_Text_H8::
	.string "LAVARIDGE TOWN POKéMON GYM LEADER:\n"
	.string "FLANNERY “One with a fiery passion\l"
	.string "that burns!”$"

LavaridgeTown_Text_H9::
	.string "LAVARIDGE TOWN\p"
	.string "“POKéMON CENTER HOT SPRINGS\n"
	.string "An excellent place for relaxing!”$"

