JaggedPass_MapScripts::
	.byte 0

JaggedPass_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_ERIC, JaggedPass_Text_H0_0, JaggedPass_Text_H0_1
	msgbox JaggedPass_Text_H0_2, MSGBOX_AUTOCLOSE
	end

JaggedPass_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_ETHAN_1, JaggedPass_Text_H1_0, JaggedPass_Text_H1_1
	msgbox JaggedPass_Text_H1_2, MSGBOX_AUTOCLOSE
	end

JaggedPass_EventScript_HItem98::
	finditem ITEM_BURN_HEAL
	end

JaggedPass_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_DIANA_1, JaggedPass_Text_H2_0, JaggedPass_Text_H2_1
	msgbox JaggedPass_Text_H2_2, MSGBOX_AUTOCLOSE
	end

JaggedPass_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_AUTUMN, JaggedPass_Text_H3_0, JaggedPass_Text_H3_1
	msgbox JaggedPass_Text_H3_2, MSGBOX_AUTOCLOSE
	end

JaggedPass_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_JULIO, JaggedPass_Text_H4_0, JaggedPass_Text_H4_1
	msgbox JaggedPass_Text_H4_2, MSGBOX_AUTOCLOSE
	end

