JaggedPass_Text_H0_0::
	.string "MT. CHIMNEY's JAGGED PASS…\p"
	.string "Now this is what I've always wanted\n"
	.string "in a mountain.\p"
	.string "This jagged bumpiness…\n"
	.string "It rocks my soul!$"

JaggedPass_Text_H0_1::
	.string "Losing left me bitter!$"

JaggedPass_Text_H0_2::
	.string "Yes, I did lose at POKéMON…\p"
	.string "But, when it comes to the love of\n"
	.string "the mountains, I have you beat!$"

JaggedPass_Text_H1_0::
	.string "JAGGED PASS is hard to walk on.\n"
	.string "It's a good place for training.$"

JaggedPass_Text_H1_1::
	.string "It was all over while we were still\n"
	.string "trying to find a good footing…$"

JaggedPass_Text_H1_2::
	.string "If I had an ACRO BIKE, I'd be able\n"
	.string "to jump ledges.$"

JaggedPass_Text_H2_0::
	.string "This place isn't your casual hike.\n"
	.string "It's not suited for a picnic.$"

JaggedPass_Text_H2_1::
	.string "Ohhh, no!\n"
	.string "The ground is too bumpy…$"

JaggedPass_Text_H2_2::
	.string "Did you know?\p"
	.string "Some people cleverly ride their\n"
	.string "bicycles up this horribly bumpy\l"
	.string "pass.$"

JaggedPass_Text_H3_0::
	.string "I climb this hill every day.\n"
	.string "I have confidence in my strength!$"

JaggedPass_Text_H3_1::
	.string "Hmm…\n"
	.string "What went wrong?$"

JaggedPass_Text_H3_2::
	.string "What is that odd rock protrusion\n"
	.string "a little up the hill from here?$"

JaggedPass_Text_H4_0::
	.string "Aiyeeh! It's awfully scary to shoot\n"
	.string "down the mountain in one go!$"

JaggedPass_Text_H4_1::
	.string "I feel like I'm falling apart…$"

JaggedPass_Text_H4_2::
	.string "My bicycle bounced around so much,\n"
	.string "my rear end's sore…$"

