JaggedPass_Text_H0::
	.string "Yes, I did lose at POKéMON…\p"
	.string "But, when it comes to the love of\n"
	.string "the mountains, I have you beat!$"

JaggedPass_Text_H1::
	.string "If I had an ACRO BIKE, I'd be able to\n"
	.string "jump ledges.$"

JaggedPass_Text_H2::
	.string "Did you know?\p"
	.string "Some people cleverly ride their\n"
	.string "bicycles up this horribly bumpy pass.$"

JaggedPass_Text_H3::
	.string "What is that odd rock protrusion\n"
	.string "a little up the hill from here?$"

JaggedPass_Text_H4::
	.string "My bicycle bounced around so much,\n"
	.string "my rear end's sore…$"

