PetalburgCity_Gym_MapScripts::
	.byte 0

PetalburgCity_Gym_EventScript_H0::
	msgbox PetalburgCity_Gym_Text_H0, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_H1::
	msgbox PetalburgCity_Gym_Text_H1, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_H2::
	msgbox PetalburgCity_Gym_Text_H2, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_H3::
	msgbox PetalburgCity_Gym_Text_H3, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_H4::
	msgbox PetalburgCity_Gym_Text_H4, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_H5::
	msgbox PetalburgCity_Gym_Text_H5, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_H6::
	msgbox PetalburgCity_Gym_Text_H6, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_H7::
	msgbox PetalburgCity_Gym_Text_H7, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H8::
	msgbox PetalburgCity_Gym_Text_H8, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H9::
	msgbox PetalburgCity_Gym_Text_H9, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H10::
	msgbox PetalburgCity_Gym_Text_H10, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H11::
	msgbox PetalburgCity_Gym_Text_H11, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H12::
	msgbox PetalburgCity_Gym_Text_H12, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H13::
	msgbox PetalburgCity_Gym_Text_H13, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H14::
	msgbox PetalburgCity_Gym_Text_H14, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H15::
	msgbox PetalburgCity_Gym_Text_H15, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H16::
	msgbox PetalburgCity_Gym_Text_H16, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H17::
	msgbox PetalburgCity_Gym_Text_H17, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H18::
	msgbox PetalburgCity_Gym_Text_H18, MSGBOX_SIGN
	end

