PetalburgCity_Gym_MapScripts::
	.byte 0

PetalburgCity_Gym_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_MARY, PetalburgCity_Gym_Text_H0_0, PetalburgCity_Gym_Text_H0_1
	msgbox PetalburgCity_Gym_Text_H0_2, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_RANDALL, PetalburgCity_Gym_Text_H1_0, PetalburgCity_Gym_Text_H1_1
	msgbox PetalburgCity_Gym_Text_H1_2, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_PARKER, PetalburgCity_Gym_Text_H2_0, PetalburgCity_Gym_Text_H2_1
	msgbox PetalburgCity_Gym_Text_H2_2, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_ALEXIA, PetalburgCity_Gym_Text_H3_0, PetalburgCity_Gym_Text_H3_1
	msgbox PetalburgCity_Gym_Text_H3_2, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_GEORGE, PetalburgCity_Gym_Text_H4_0, PetalburgCity_Gym_Text_H4_1
	msgbox PetalburgCity_Gym_Text_H4_2, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_JODY, PetalburgCity_Gym_Text_H5_0, PetalburgCity_Gym_Text_H5_1
	msgbox PetalburgCity_Gym_Text_H5_2, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_BERKE, PetalburgCity_Gym_Text_H6_0, PetalburgCity_Gym_Text_H6_1
	msgbox PetalburgCity_Gym_Text_H6_2, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_H7::
	msgbox PetalburgCity_Gym_Text_H7, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H8::
	msgbox PetalburgCity_Gym_Text_H8, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H9::
	msgbox PetalburgCity_Gym_Text_H9, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H10::
	msgbox PetalburgCity_Gym_Text_H10, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H11::
	msgbox PetalburgCity_Gym_Text_H11, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H12::
	msgbox PetalburgCity_Gym_Text_H12, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H13::
	msgbox PetalburgCity_Gym_Text_H13, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H14::
	msgbox PetalburgCity_Gym_Text_H14, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H15::
	msgbox PetalburgCity_Gym_Text_H15, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H16::
	msgbox PetalburgCity_Gym_Text_H16, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H17::
	msgbox PetalburgCity_Gym_Text_H17, MSGBOX_SIGN
	end

PetalburgCity_Gym_EventScript_H18::
	msgbox PetalburgCity_Gym_Text_H18, MSGBOX_SIGN
	end

