Route110_TrickHousePuzzle2_Text_H0_0::
	.string "Which switch closes which hole?$"

Route110_TrickHousePuzzle2_Text_H0_1::
	.string "After that battle, I'm even more\n"
	.string "confused!$"

Route110_TrickHousePuzzle2_Text_H0_2::
	.string "Can I get you to push all the buttons\n"
	.string "for me?$"

Route110_TrickHousePuzzle2_Text_H1_0::
	.string "Oh! You're on your second TRICK HOUSE\n"
	.string "challenge!$"

Route110_TrickHousePuzzle2_Text_H1_1::
	.string "You're good at battling too?$"

Route110_TrickHousePuzzle2_Text_H1_2::
	.string "The TRICK MASTER rigged all the tricks\n"
	.string "in this house all by himself.$"

Route110_TrickHousePuzzle2_Text_H2_0::
	.string "I want to make my own GYM one day.\n"
	.string "So, I'm studying how to set traps.$"

Route110_TrickHousePuzzle2_Text_H2_1::
	.string "I didn't study battling enough!$"

Route110_TrickHousePuzzle2_Text_H2_2::
	.string "You're strong, aren't you?\n"
	.string "Maybe even enough to be a GYM LEADER!$"

