SlateportCity_BattleTentLobby_Text_H0::
	.string "Welcome to the BATTLE TENT\n"
	.string "SLATEPORT SITE!\p"
	.string "I am your guide to the Battle Swap\n"
	.string "Tournament.$"

SlateportCity_BattleTentLobby_Text_H1::
	.string "So, like, I couldn't find myself any\n"
	.string "POKéMON that were, like, for me.\p"
	.string "So, I figured, like, hey, I should\n"
	.string "file a complaint to the guy there?\p"
	.string "And he wouldn't hear me out, like,\n"
	.string "hey! So, like, total bummer, man!\p"
	.string "Hey, like, you! Zip it, you know?\n"
	.string "Just, you know, take this!$"

SlateportCity_BattleTentLobby_Text_H2::
	.string "I don't really like BUG POKéMON,\n"
	.string "but maybe I'll try using some for\l"
	.string "a change of pace.\p"
	.string "Who knows, I might even get to like\n"
	.string "them!$"

SlateportCity_BattleTentLobby_Text_H3::
	.string "You can battle all you want here\n"
	.string "even if you don't have any tough\l"
	.string "POKéMON.$"

SlateportCity_BattleTentLobby_Text_H4::
	.string "Wouldn't it be nice if they had more\n"
	.string "of a selection?$"

SlateportCity_BattleTentLobby_Text_H5::
	.string "The Battle Swap rules are listed.$"

