#ifndef GUARD_TILESET_ANIMS_H
#define GUARD_TILESET_ANIMS_H

void InitTilesetAnimations(void);
void InitSecondaryTilesetAnimation(void);
void UpdateTilesetAnimations(void);
void TransferTilesetAnimsBuffer(void);

void InitTilesetAnim_General(void);
void InitTilesetAnim_CeladonCity(void);
void InitTilesetAnim_VermilionGym(void);
void InitTilesetAnim_CeladonGym(void);
void InitTilesetAnim_SilphCo(void);
void InitTilesetAnim_MtEmber(void);

// BEGIN HOENN TILESET ANIMS (generated by tools/hoenn_import/import_tileset_anims.py)
void InitTilesetAnim_EmBattleFrontierOutsideEast(void);
void InitTilesetAnim_EmBattleFrontierOutsideWest(void);
void InitTilesetAnim_EmBattlePyramid(void);
void InitTilesetAnim_EmBikeShop(void);
void InitTilesetAnim_EmBuilding(void);
void InitTilesetAnim_EmCave(void);
void InitTilesetAnim_EmDewford(void);
void InitTilesetAnim_EmEliteFour(void);
void InitTilesetAnim_EmEverGrande(void);
void InitTilesetAnim_EmFallarbor(void);
void InitTilesetAnim_EmFortree(void);
void InitTilesetAnim_EmGeneral(void);
void InitTilesetAnim_EmLavaridge(void);
void InitTilesetAnim_EmLilycove(void);
void InitTilesetAnim_EmMauville(void);
void InitTilesetAnim_EmMauvilleGym(void);
void InitTilesetAnim_EmMossdeep(void);
void InitTilesetAnim_EmPacifidlog(void);
void InitTilesetAnim_EmPetalburg(void);
void InitTilesetAnim_EmRustboro(void);
void InitTilesetAnim_EmSlateport(void);
void InitTilesetAnim_EmSootopolis(void);
void InitTilesetAnim_EmSootopolisGym(void);
void InitTilesetAnim_EmUnderwater(void);
// END HOENN TILESET ANIMS
#endif // GUARD_TILESET_ANIMS_H
