HoennVictoryRoad_1F_MapScripts::
	.byte 0

HoennVictoryRoad_1F_EventScript_H0::
	msgbox HoennVictoryRoad_1F_Text_H0, MSGBOX_NPC
	end

HoennVictoryRoad_1F_EventScript_H1::
	msgbox HoennVictoryRoad_1F_Text_H1, MSGBOX_NPC
	end

HoennVictoryRoad_1F_EventScript_H2::
	msgbox HoennVictoryRoad_1F_Text_H2, MSGBOX_NPC
	end

HoennVictoryRoad_1F_EventScript_H3::
	msgbox HoennVictoryRoad_1F_Text_H3, MSGBOX_NPC
	end

HoennVictoryRoad_1F_EventScript_H4::
	msgbox HoennVictoryRoad_1F_Text_H4, MSGBOX_NPC
	end

