HoennVictoryRoad_1F_Text_H0::
	.string "You've made it this far. Keep the\n"
	.string "momentum going and become the\l"
	.string "CHAMPION! If anyone can, it's you!$"

HoennVictoryRoad_1F_Text_H1::
	.string "You seem to have the potential for\n"
	.string "becoming the CHAMPION.$"

HoennVictoryRoad_1F_Text_H2::
	.string "I lost here…\p"
	.string "That means I lack the qualifications\n"
	.string "to become the CHAMPION…$"

HoennVictoryRoad_1F_Text_H3::
	.string "Humph, go right on ahead.\n"
	.string "See if I care.$"

HoennVictoryRoad_1F_Text_H4::
	.string "Getting through here safely--that's\n"
	.string "the final test for any TRAINER\l"
	.string "aiming to become the POKéMON\l"
	.string "CHAMPION.\p"
	.string "That's why it's called the VICTORY\n"
	.string "ROAD.$"

