PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "POKéMON TOWER was erected in the\n"
    .string "memory of POKéMON that died.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Did you come to pay respects?\p"
    .string "Bless your POKéMON-loving heart,\n"
    .string "son.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Did you come to pay respects?\p"
    .string "Bless your POKéMON-loving heart,\n"
    .string "girl.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "I came to pray for my dearly\n"
    .string "departed CLEFAIRY.\p"
    .string "Sniff!\n"
    .string "I'm awash in tears…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "My GROWLITHE…\n"
    .string "Why did you die?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "I am a CHANNELER.\p"
    .string "There are spirits up to mischief.\n"
    .string "I sense them high in the TOWER.$"


PokemonTower_1F_Text_ChannelerYouveBeenFollowed::
    .string "…!\n"
    .string "Restless spirits have followed you\l"
    .string "from the tower!\p"
    .string "Their song is clinging to this\n"
    .string "whole town… Hold still!$"

PokemonTower_1F_Text_ChannelerSpiritsAtRest::
    .string "There. The spirits are at rest.\p"
    .string "LAVENDER TOWN's music will sound\n"
    .string "as it always has.$"
