VerdanturfTown_MapScripts::
	.byte 0

VerdanturfTown_EventScript_H0::
	msgbox VerdanturfTown_Text_H0, MSGBOX_NPC
	end

VerdanturfTown_EventScript_H1::
	msgbox VerdanturfTown_Text_H1, MSGBOX_NPC
	end

VerdanturfTown_EventScript_H2::
	msgbox VerdanturfTown_Text_H2, MSGBOX_NPC
	end

VerdanturfTown_EventScript_H3::
	msgbox VerdanturfTown_Text_H3, MSGBOX_NPC
	end

VerdanturfTown_EventScript_H4::
	msgbox VerdanturfTown_Text_H4, MSGBOX_SIGN
	end

VerdanturfTown_EventScript_H5::
	msgbox VerdanturfTown_Text_H5, MSGBOX_SIGN
	end

VerdanturfTown_EventScript_H6::
	msgbox VerdanturfTown_Text_H6, MSGBOX_SIGN
	end

VerdanturfTown_EventScript_H7::
	msgbox VerdanturfTown_Text_H7, MSGBOX_SIGN
	end

