VerdanturfTown_Text_H0::
	.string "The way the winds blow, volcanic ash\n"
	.string "is never blown in this direction.\p"
	.string "The air is clean and delicious here.\n"
	.string "Living here should do wonders for\l"
	.string "even frail and sickly people.$"

VerdanturfTown_Text_H1::
	.string "My papa told me.\p"
	.string "He says this tunnel is full of\n"
	.string "timid POKéMON.\p"
	.string "They get all scared of loud noise\n"
	.string "and make a big uproar.\p"
	.string "So they had to stop the big tunnel\n"
	.string "project.\p"
	.string "But there's one man. He's trying to\n"
	.string "dig the tunnel by himself!$"

VerdanturfTown_Text_H2::
	.string "Did you see the cave next to the\n"
	.string "POKéMON MART?\p"
	.string "There's a guy in there who's trying\n"
	.string "to bust up boulders so he can bust\l"
	.string "out through to the other side.\p"
	.string "It'd be great if we could go\n"
	.string "through… It'll make it easy to visit\l"
	.string "RUSTBORO.$"

VerdanturfTown_Text_H3::
	.string "My POKéMON and I, we've been riding\n"
	.string "a hot winning streak.\p"
	.string "So I decided to make my BATTLE\n"
	.string "TENT debut in this town.$"

VerdanturfTown_Text_H4::
	.string "VERDANTURF TOWN\p"
	.string "“The windswept highlands with the\n"
	.string "sweet fragrance of grass.”$"

VerdanturfTown_Text_H5::
	.string "WANDA'S HOUSE$"

VerdanturfTown_Text_H6::
	.string "BATTLE TENT VERDANTURF SITE\n"
	.string "“Feast Your Eyes on Battles!”$"

VerdanturfTown_Text_H7::
	.string "RUSTURF TUNNEL\n"
	.string "“Linking RUSTBORO and VERDANTURF\p"
	.string "“The tunnel project has been\n"
	.string "canceled.”$"

