Route110_TrickHousePuzzle4_Text_H0_0::
	.string "It's too much bother to think this out.\n"
	.string "I only wanted to battle!$"

Route110_TrickHousePuzzle4_Text_H0_1::
	.string "Even though I lost, I still like battling\n"
	.string "the best!$"

Route110_TrickHousePuzzle4_Text_H0_2::
	.string "Wouldn't you agree? You would go\n"
	.string "anywhere if TRAINERS were there.$"

Route110_TrickHousePuzzle4_Text_H1_0::
	.string "The TRICK HOUSE is getting trickier,\n"
	.string "isn't it?$"

Route110_TrickHousePuzzle4_Text_H1_1::
	.string "Aaak!$"

Route110_TrickHousePuzzle4_Text_H1_2::
	.string "Has anyone made it to the end?$"

Route110_TrickHousePuzzle4_Text_H2_0::
	.string "Heh! Boulders like this, I can brush\n"
	.string "aside with one finger!$"

Route110_TrickHousePuzzle4_Text_H2_1::
	.string "I can push boulders, but I can't solve\n"
	.string "the puzzle…$"

Route110_TrickHousePuzzle4_Text_H2_2::
	.string "It's not good enough to be brawny…\n"
	.string "You have to use your head. Be brainy!$"

