Route104_PrettyPetalFlowerShop_Text_H0::
	.string "Hello!\p"
	.string "This is the PRETTY PETAL flower shop.\n"
	.string "Spreading flowers all over the world!$"

Route104_PrettyPetalFlowerShop_Text_H1::
	.string "While BERRY plants are growing,\n"
	.string "water them with the WAILMER PAIL.\p"
	.string "Oh, another thing.\p"
	.string "If you don't pick BERRIES for a while,\n"
	.string "they'll drop off onto the ground.\l"
	.string "But they'll sprout again.\p"
	.string "Isn't that awesome?\n"
	.string "It's like they have the will to live.$"

Route104_PrettyPetalFlowerShop_Text_H2::
	.string "I'm trying to be like my big sisters.\n"
	.string "I'm growing flowers, too!\p"
	.string "Here you go!\n"
	.string "It's for you!$"

