Route110_TrickHousePuzzle1_Text_H0_0::
	.string "I'll hack and slash my way to\n"
	.string "victory with the CUT we just\l"
	.string "learned!$"

Route110_TrickHousePuzzle1_Text_H0_1::
	.string "Why are you so serious?$"

Route110_TrickHousePuzzle1_Text_H0_2::
	.string "I never get tired of hacking\n"
	.string "and slashing!$"

Route110_TrickHousePuzzle1_Text_H1_0::
	.string "I wandered into this weird house\n"
	.string "by accident…$"

Route110_TrickHousePuzzle1_Text_H1_1::
	.string "And now I've lost…$"

Route110_TrickHousePuzzle1_Text_H1_2::
	.string "I lost my way, I lost a battle, and\n"
	.string "I'm now even more lost… I can't get\l"
	.string "out…$"

Route110_TrickHousePuzzle1_Text_H2_0::
	.string "Just who is the TRICK MASTER?$"

Route110_TrickHousePuzzle1_Text_H2_1::
	.string "I lost while I was lost in thought!$"

Route110_TrickHousePuzzle1_Text_H2_2::
	.string "You're strong!\n"
	.string "Just who are you?$"

