MossdeepCity_StevensHouse_MapScripts::
	.byte 0

MossdeepCity_StevensHouse_EventScript_H0::
	msgbox MossdeepCity_StevensHouse_Text_H0, MSGBOX_SIGN
	end

MossdeepCity_StevensHouse_EventScript_H1::
	msgbox MossdeepCity_StevensHouse_Text_H1, MSGBOX_SIGN
	end

MossdeepCity_StevensHouse_EventScript_H2::
	msgbox MossdeepCity_StevensHouse_Text_H2, MSGBOX_SIGN
	end

MossdeepCity_StevensHouse_EventScript_H3::
	msgbox MossdeepCity_StevensHouse_Text_H3, MSGBOX_SIGN
	end

