MossdeepCity_StevensHouse_Text_H0::
	.string "It's a collection of rare rocks and\n"
	.string "stones assembled by STEVEN.$"

MossdeepCity_StevensHouse_Text_H1::
	.string "It's a collection of rare rocks and\n"
	.string "stones assembled by STEVEN.$"

MossdeepCity_StevensHouse_Text_H2::
	.string "It's a collection of rare rocks and\n"
	.string "stones assembled by STEVEN.$"

MossdeepCity_StevensHouse_Text_H3::
	.string "It's a collection of rare rocks and\n"
	.string "stones assembled by STEVEN.$"

