CeruleanCity_House3_Text_PleaseTradeWithMyHusband::
    .string "My husband likes trading POKéMON.\p"
    .string "You're collecting POKéMON for your\n"
    .string "POKéDEX, aren't you?\p"
    .string "Would you please trade with him?$"


CeruleanCity_House3_Text_NursedBulbasaurBackToHealth::
    .string "I take care of injured POKéMON.\p"
    .string "I nursed this BULBASAUR back to\n"
    .string "health.\p"
    .string "It needs a good TRAINER to take\n"
    .string "care of it now.$"

CeruleanCity_House3_Text_WouldYouTakeCareOfBulbasaur::
    .string "Your PIKACHU looks so happy with\n"
    .string "you!\p"
    .string "I know! Would you take care of\n"
    .string "this BULBASAUR?$"

CeruleanCity_House3_Text_ReceivedBulbasaur::
    .string "{PLAYER} received a BULBASAUR\n"
    .string "from the girl!$"

CeruleanCity_House3_Text_PleaseTakeCareOfBulbasaur::
    .string "Please take care of BULBASAUR!$"

CeruleanCity_House3_Text_ThatsTooBad::
    .string "Oh…\n"
    .string "That's too bad…$"

CeruleanCity_House3_Text_IsBulbasaurDoingWell::
    .string "Is BULBASAUR doing well?$"
