FortreeCity_Gym_MapScripts::
	.byte 0

FortreeCity_Gym_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_WINONA_1, FortreeCity_Gym_Text_H0_0, FortreeCity_Gym_Text_H0_1
	msgbox FortreeCity_Gym_Text_H0_2, MSGBOX_AUTOCLOSE
	end

FortreeCity_Gym_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_JARED, FortreeCity_Gym_Text_H1_0, FortreeCity_Gym_Text_H1_1
	msgbox FortreeCity_Gym_Text_H1_2, MSGBOX_AUTOCLOSE
	end

FortreeCity_Gym_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_FLINT, FortreeCity_Gym_Text_H2_0, FortreeCity_Gym_Text_H2_1
	msgbox FortreeCity_Gym_Text_H2_2, MSGBOX_AUTOCLOSE
	end

FortreeCity_Gym_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_ASHLEY, FortreeCity_Gym_Text_H3_0, FortreeCity_Gym_Text_H3_1
	msgbox FortreeCity_Gym_Text_H3_2, MSGBOX_AUTOCLOSE
	end

FortreeCity_Gym_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_EDWARDO, FortreeCity_Gym_Text_H4_0, FortreeCity_Gym_Text_H4_1
	msgbox FortreeCity_Gym_Text_H4_2, MSGBOX_AUTOCLOSE
	end

FortreeCity_Gym_EventScript_H5::
	msgbox FortreeCity_Gym_Text_H5, MSGBOX_NPC
	end

FortreeCity_Gym_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_HUMBERTO, FortreeCity_Gym_Text_H6_0, FortreeCity_Gym_Text_H6_1
	msgbox FortreeCity_Gym_Text_H6_2, MSGBOX_AUTOCLOSE
	end

FortreeCity_Gym_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_DARIUS, FortreeCity_Gym_Text_H7_0, FortreeCity_Gym_Text_H7_1
	msgbox FortreeCity_Gym_Text_H7_2, MSGBOX_AUTOCLOSE
	end

