MauvilleCity_House1_Text_H0::
	.string "Woohoo!\p"
	.string "I hear people call me the ROCK\n"
	.string "SMASH GUY, but I find that sort of\l"
	.string "degrading.\p"
	.string "I think I deserve a bit more\n"
	.string "respect, like maybe the ROCK SMASH\l"
	.string "DUDE.\p"
	.string "Woohoo!\p"
	.string "Anyways, your POKéMON look pretty\n"
	.string "strong.\p"
	.string "I like that!\n"
	.string "Here, take this HIDDEN MACHINE!$"

