Route113_Text_H0::
	.string "It's fun walking through the\n"
	.string "volcano's ashes on the ground and\l"
	.string "grass.\p"
	.string "You can see where you walked--it's\n"
	.string "really neat!$"

Route113_Text_H1::
	.string "Wahahaha! Today's technology is a\n"
	.string "wondrous thing!\p"
	.string "Take this volcanic ash here.\n"
	.string "It can be fashioned into glass.$"

Route113_Text_H2_0::
	.string "Can you guess why it's so cool\n"
	.string "around here?$"

Route113_Text_H2_1::
	.string "Peeuuw!\n"
	.string "That stinks!$"

Route113_Text_H2_2::
	.string "The volcanic ash blocks the sun,\n"
	.string "so it doesn't get very warm.\p"
	.string "That's good for me--I can't stand\n"
	.string "heat!$"

Route113_Text_H3_0::
	.string "The volcano's eruption is proof that\n"
	.string "the earth is alive.$"

Route113_Text_H3_1::
	.string "You're some kind of strong!$"

Route113_Text_H3_2::
	.string "Ouch! Owww! I can't see!\n"
	.string "I got ashes in my eyelashes!\p"
	.string "Get it? Ashes and eyelashes?\p"
	.string "Okay, that was bad, sorry…$"

Route113_Text_H4_0::
	.string "I use this parasol to ward off this\n"
	.string "filthy, yucky volcanic ash from\l"
	.string "my dear NUMEL.$"

Route113_Text_H4_1::
	.string "Huff, huff…\n"
	.string "I am exhausted…$"

Route113_Text_H4_2::
	.string "You're very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_H5_0::
	.string "From out of the ashes I leap!\n"
	.string "Hiyah! I challenge thee!$"

Route113_Text_H5_1::
	.string "With honor I admit defeat!$"

Route113_Text_H5_2::
	.string "I must refine the art of\n"
	.string "concealment. I bid thee farewell.$"

Route113_Text_H6_0::
	.string "Thanks for finding me!\n"
	.string "But we still have to battle!$"

Route113_Text_H6_1::
	.string "I'll use my ninjutsu on you…\n"
	.string "“VOLCANIC ASH SWIRL CLOAK”!\p"
	.string "…What?\n"
	.string "It's already over?$"

Route113_Text_H6_2::
	.string "You know what's crummy about hiding?\n"
	.string "It's lonely if no one comes along.$"

Route113_Text_H7_0::
	.string "TORI: Both of us, we collect ashes.\n"
	.string "We battle POKéMON, too.$"

Route113_Text_H7_1::
	.string "TORI: We lost… It's boring, so I'm\n"
	.string "going to get some more ashes.$"

Route113_Text_H7_2::
	.string "TORI: How much ash do we have?\n"
	.string "Enough for a WHITE FLUTE, I hope.$"

Route113_Text_H8_0::
	.string "TIA: Both of us, we collect ashes.\n"
	.string "We battle POKéMON, too.$"

Route113_Text_H8_1::
	.string "TIA: We couldn't win… It's boring,\n"
	.string "so I'm getting some more ashes.$"

Route113_Text_H8_2::
	.string "TIA: We have a lot of ashes!\n"
	.string "I think enough for a WHITE FLUTE!$"

Route113_Text_H9_0::
	.string "Y-you want to battle with me? Even\n"
	.string "though I just caught my POKéMON?$"

Route113_Text_H9_1::
	.string "Y-you're all happy to win?\n"
	.string "Even though it's only me?$"

Route113_Text_H9_2::
	.string "Oh, so now you want to say a word\n"
	.string "to the loser?\p"
	.string "Aren't you just the coolest?\n"
	.string "Humph!$"

Route113_Text_H10_0::
	.string "Were you maybe in the middle\n"
	.string "of gathering volcanic ashes?$"

Route113_Text_H10_1::
	.string "Ehehe.\n"
	.string "We got beaten cleanly.$"

Route113_Text_H10_2::
	.string "I ought to hide under the ashes,\n"
	.string "too.$"

Route113_Text_H11_0::
	.string "The warmth here is making me drowsy.\n"
	.string "Battle with me so I can stay awake.$"

Route113_Text_H11_1::
	.string "This is a dream.\n"
	.string "I'm sure of it…$"

Route113_Text_H11_2::
	.string "Losing burns me up…\n"
	.string "I'm just going to sleep right here!\l"
	.string "Zzz!$"

Route113_Text_H12_0::
	.string "Pfft, with these wings I can\n"
	.string "flick you away!$"

Route113_Text_H12_1::
	.string "A… What?$"

Route113_Text_H12_2::
	.string "I don't know what to say when I get\n"
	.string "beaten so easily…$"

Route113_Text_H13::
	.string "ROUTE 113\n"
	.string "{RIGHT_ARROW} ROUTE 111$"

Route113_Text_H14::
	.string "ROUTE 113\n"
	.string "{LEFT_ARROW} FALLARBOR TOWN$"

Route113_Text_H15::
	.string "TRAINER TIPS\p"
	.string "You may register one of the KEY\n"
	.string "ITEMS in your BAG as SELECT.\p"
	.string "Simply press SELECT to use\n"
	.string "the registered item conveniently.$"

Route113_Text_H16::
	.string "GLASS WORKSHOP “Turning Volcanic\n"
	.string "Ash into Glass Items”$"

