Route113_Text_H0::
	.string "It's fun walking through the volcano's\n"
	.string "ashes on the ground and grass.\p"
	.string "You can see where you walked--it's\n"
	.string "really neat!$"

Route113_Text_H1::
	.string "Wahahaha! Today's technology is a\n"
	.string "wondrous thing!\p"
	.string "Take this volcanic ash here.\n"
	.string "It can be fashioned into glass.$"

Route113_Text_H2::
	.string "The volcanic ash blocks the sun,\n"
	.string "so it doesn't get very warm.\p"
	.string "That's good for me--I can't stand heat!$"

Route113_Text_H3::
	.string "Ouch! Owww! I can't see!\n"
	.string "I got ashes in my eyelashes!\p"
	.string "Get it? Ashes and eyelashes?\p"
	.string "Okay, that was bad, sorry…$"

Route113_Text_H4::
	.string "You're very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_H5::
	.string "I must refine the art of concealment.\n"
	.string "I bid thee farewell.$"

Route113_Text_H6::
	.string "You know what's crummy about hiding?\n"
	.string "It's lonely if no one comes along.$"

Route113_Text_H7::
	.string "TORI: How much ash do we have?\n"
	.string "Enough for a WHITE FLUTE, I hope.$"

Route113_Text_H8::
	.string "TIA: We have a lot of ashes!\n"
	.string "I think enough for a WHITE FLUTE!$"

Route113_Text_H9::
	.string "Oh, so now you want to say a word to\n"
	.string "the loser?\p"
	.string "Aren't you just the coolest?\n"
	.string "Humph!$"

Route113_Text_H10::
	.string "I ought to hide under the ashes, too.$"

Route113_Text_H11::
	.string "Losing burns me up…\n"
	.string "I'm just going to sleep right here!\l"
	.string "Zzz!$"

Route113_Text_H12::
	.string "I don't know what to say when I get\n"
	.string "beaten so easily…$"

Route113_Text_H13::
	.string "ROUTE 113\n"
	.string "{RIGHT_ARROW} ROUTE 111$"

Route113_Text_H14::
	.string "ROUTE 113\n"
	.string "{LEFT_ARROW} FALLARBOR TOWN$"

Route113_Text_H15::
	.string "TRAINER TIPS\p"
	.string "You may register one of the KEY ITEMS\n"
	.string "in your BAG as SELECT.\p"
	.string "Simply press SELECT to use\n"
	.string "the registered item conveniently.$"

Route113_Text_H16::
	.string "GLASS WORKSHOP\n"
	.string "“Turning Volcanic Ash into Glass Items”$"

