Route129_MapScripts::
	.byte 0

Route129_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_CHASE, Route129_Text_H0_0, Route129_Text_H0_1
	msgbox Route129_Text_H0_2, MSGBOX_AUTOCLOSE
	end

Route129_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_ALLISON, Route129_Text_H1_0, Route129_Text_H1_1
	msgbox Route129_Text_H1_2, MSGBOX_AUTOCLOSE
	end

Route129_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_TISHA, Route129_Text_H2_0, Route129_Text_H2_1
	msgbox Route129_Text_H2_2, MSGBOX_AUTOCLOSE
	end

Route129_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_REED, Route129_Text_H3_0, Route129_Text_H3_1
	msgbox Route129_Text_H3_2, MSGBOX_AUTOCLOSE
	end

Route129_EventScript_H4::
	trainerbattle_single TRAINER_HOENN_CLARENCE, Route129_Text_H4_0, Route129_Text_H4_1
	msgbox Route129_Text_H4_2, MSGBOX_AUTOCLOSE
	end

