Route129_Text_H0_0::
	.string "This is my first triathlon.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_H0_1::
	.string "Wroooaaar!\n"
	.string "I failed to win!$"

Route129_Text_H0_2::
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_H1_0::
	.string "I'm in the middle of a triathlon,\n"
	.string "but, sure, why don't we battle?$"

Route129_Text_H1_1::
	.string "I was sure I'd win!$"

Route129_Text_H1_2::
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_H2_0::
	.string "What's the hurry?\n"
	.string "Let's take it slow and easy.$"

Route129_Text_H2_1::
	.string "Oh, my.\n"
	.string "I wanted to relax a little more…$"

Route129_Text_H2_2::
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"

Route129_Text_H3_0::
	.string "Say hey, hey!\n"
	.string "Let's get on with it!$"

Route129_Text_H3_1::
	.string "Beat, I'm beaten.\n"
	.string "That's it, done!$"

Route129_Text_H3_2::
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_H4_0::
	.string "Surfing isn't as easy as it seems,\n"
	.string "isn't that right?$"

Route129_Text_H4_1::
	.string "Winning sure isn't easy.$"

Route129_Text_H4_2::
	.string "You have your sights on the POKéMON\n"
	.string "LEAGUE? Keep at it!$"

