Route129_Text_H0::
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_H1::
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_H2::
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"

Route129_Text_H3::
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_H4::
	.string "You have your sights on the POKéMON\n"
	.string "LEAGUE? Keep at it!$"

