FallarborTown_BattleTentLobby_MapScripts::
	.byte 0

FallarborTown_BattleTentLobby_EventScript_H0::
	msgbox FallarborTown_BattleTentLobby_Text_H0, MSGBOX_NPC
	end

FallarborTown_BattleTentLobby_EventScript_H1::
	msgbox FallarborTown_BattleTentLobby_Text_H1, MSGBOX_NPC
	end

FallarborTown_BattleTentLobby_EventScript_H2::
	msgbox FallarborTown_BattleTentLobby_Text_H2, MSGBOX_NPC
	end

FallarborTown_BattleTentLobby_EventScript_H3::
	msgbox FallarborTown_BattleTentLobby_Text_H3, MSGBOX_NPC
	end

FallarborTown_BattleTentLobby_EventScript_H4::
	msgbox FallarborTown_BattleTentLobby_Text_H4, MSGBOX_SIGN
	end

