LavaridgeTown_Gym_1F_MapScripts::
	.byte 0

LavaridgeTown_Gym_1F_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_FLANNERY_1, LavaridgeTown_Gym_1F_Text_H0_0, LavaridgeTown_Gym_1F_Text_H0_1
	msgbox LavaridgeTown_Gym_1F_Text_H0_2, MSGBOX_AUTOCLOSE
	end

LavaridgeTown_Gym_1F_EventScript_H1::
	msgbox LavaridgeTown_Gym_1F_Text_H1, MSGBOX_NPC
	end

LavaridgeTown_Gym_1F_EventScript_H2::
	msgbox LavaridgeTown_Gym_1F_Text_H2, MSGBOX_NPC
	end

LavaridgeTown_Gym_1F_EventScript_H3::
	msgbox LavaridgeTown_Gym_1F_Text_H3, MSGBOX_NPC
	end

LavaridgeTown_Gym_1F_EventScript_H4::
	msgbox LavaridgeTown_Gym_1F_Text_H4, MSGBOX_NPC
	end

LavaridgeTown_Gym_1F_EventScript_H5::
	msgbox LavaridgeTown_Gym_1F_Text_H5, MSGBOX_NPC
	end

