Route2_Text_RouteSign::
    .string "ROUTE 2\n"
    .string "VIRIDIAN CITY - PEWTER CITY$"

Route2_Text_DiglettsCave::
    .string "DIGLETT'S CAVE$"


Route2_Text_RandyTakeThisMonToMyFriend::
    .string "Excuse me, kid! Can you do a guy\n"
    .string "a favor?\p"
    .string "Can you take this POKéMON with\n"
    .string "MAIL to my friend?\p"
    .string "He's on ROUTE 22.$"

Route2_Text_RandyThanks::
    .string "You will? Perfect!\n"
    .string "Thanks, kid!\p"
    .string "My pal's a chubby guy who snoozes\n"
    .string "all the time.\p"
    .string "You'll recognize him right away!$"

Route2_Text_ReceivedMonWithMail::
    .string "{PLAYER} received a POKéMON\n"
    .string "with MAIL.$"

Route2_Text_RandyDontLoseIt::
    .string "You can read it, but don't lose it!\n"
    .string "ROUTE 22!\p"
    .string "He's probably napping by the\n"
    .string "POKéMON LEAGUE gate again.$"

Route2_Text_RandyCantCarryAnotherMon::
    .string "You can't carry another POKéMON…$"

Route2_Text_RandyNeverMind::
    .string "Oh… Never mind, then…$"

Route2_Text_RandySomethingForYourTrouble::
    .string "Thanks, kid! You made the delivery\n"
    .string "for me!\p"
    .string "Here's something for your trouble!$"

Route2_Text_RandyMyPalWasSnoozing::
    .string "My pal was snoozing, right?\n"
    .string "Heh, what'd I say?$"
