CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "I'm getting a present for my\n"
    .string "girlfriend.\p"
    .string "I guess a POKé DOLL will be it.\n"
    .string "It's the popular thing.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "I heard something useful.\p"
    .string "If a wild POKéMON appears, you can\n"
    .string "distract it with a POKé DOLL.\p"
    .string "You can run away while the wild\n"
    .string "POKéMON is distracted.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Express yourself with gifts!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "Evolution Special!\n"
    .string "Element STONES on sale now!$"

CeladonCity_DepartmentStore_4F_Text_Evolution0::
    .string "I study how POKéMON evolve. No\n"
    .string "need for a LINK CABLE these days!$"

CeladonCity_DepartmentStore_4F_Text_Evolution1::
    .string "KADABRA, MACHOKE, GRAVELER and\n"
    .string "HAUNTER evolve on their own at\l"
    .string "Lv37.$"

CeladonCity_DepartmentStore_4F_Text_Evolution2::
    .string "Some POKéMON evolve when they\n"
    .string "level up while holding an item.\l"
    .string "The item is used up.\p"
    .string "KING'S ROCK: POLIWHIRL at Lv30,\n"
    .string "SLOWPOKE at Lv37. METAL COAT: ONIX\l"
    .string "and SCYTHER at Lv30.\p"
    .string "DRAGON SCALE: SEADRA at Lv40. UP-\n"
    .string "GRADE: PORYGON at Lv30.\l"
    .string "DEEPSEATOOTH or DEEPSEASCALE:\l"
    .string "CLAMPERL at Lv30.\p"
    .string "You can buy all of those items\n"
    .string "right here!$"

CeladonCity_DepartmentStore_4F_Text_Evolution3::
    .string "A very friendly EEVEE becomes\n"
    .string "ESPEON if it levels up between 4\l"
    .string "in the morning and 8 at night, and\l"
    .string "UMBREON at night.\p"
    .string "Check the time on your POKéWATCH!$"

CeladonCity_DepartmentStore_4F_Text_Evolution4::
    .string "FEEBAS evolves when it's beautiful\n"
    .string "enough. Let DAISY in PALLET TOWN\l"
    .string "groom it, then level it up!$"

