LittlerootTown_Text_H0::
	.string "Um, um, um!\p"
	.string "If you go outside and go in the\n"
	.string "grass, wild POKéMON will jump out!$"

LittlerootTown_Text_H1::
	.string "PROF. BIRCH spends days in his LAB\n"
	.string "studying, then he'll suddenly go out\l"
	.string "in the wild to do more research…\p"
	.string "When does PROF. BIRCH spend time\n"
	.string "at home?$"

LittlerootTown_Text_H2::
	.string "LITTLEROOT TOWN “A town that can't\n"
	.string "be shaded any hue.”$"

LittlerootTown_Text_H3::
	.string "PROF. BIRCH'S POKéMON LAB$"

