DewfordTown_Gym_MapScripts::
	.byte 0

DewfordTown_Gym_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_BRAWLY_1, DewfordTown_Gym_Text_H0_0, DewfordTown_Gym_Text_H0_1
	msgbox DewfordTown_Gym_Text_H0_2, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_TAKAO, DewfordTown_Gym_Text_H1_0, DewfordTown_Gym_Text_H1_1
	msgbox DewfordTown_Gym_Text_H1_2, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_JOCELYN, DewfordTown_Gym_Text_H2_0, DewfordTown_Gym_Text_H2_1
	msgbox DewfordTown_Gym_Text_H2_2, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_H3::
	trainerbattle_single TRAINER_HOENN_LAURA, DewfordTown_Gym_Text_H3_0, DewfordTown_Gym_Text_H3_1
	msgbox DewfordTown_Gym_Text_H3_2, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_H4::
	msgbox DewfordTown_Gym_Text_H4, MSGBOX_NPC
	end

DewfordTown_Gym_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_CRISTIAN, DewfordTown_Gym_Text_H5_0, DewfordTown_Gym_Text_H5_1
	msgbox DewfordTown_Gym_Text_H5_2, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_LILITH, DewfordTown_Gym_Text_H6_0, DewfordTown_Gym_Text_H6_1
	msgbox DewfordTown_Gym_Text_H6_2, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_H7::
	trainerbattle_single TRAINER_HOENN_BRENDEN, DewfordTown_Gym_Text_H7_0, DewfordTown_Gym_Text_H7_1
	msgbox DewfordTown_Gym_Text_H7_2, MSGBOX_AUTOCLOSE
	end

