DewfordTown_Gym_MapScripts::
	.byte 0

DewfordTown_Gym_EventScript_H0::
	msgbox DewfordTown_Gym_Text_H0, MSGBOX_NPC
	end

DewfordTown_Gym_EventScript_H1::
	msgbox DewfordTown_Gym_Text_H1, MSGBOX_NPC
	end

DewfordTown_Gym_EventScript_H2::
	msgbox DewfordTown_Gym_Text_H2, MSGBOX_NPC
	end

DewfordTown_Gym_EventScript_H3::
	msgbox DewfordTown_Gym_Text_H3, MSGBOX_NPC
	end

DewfordTown_Gym_EventScript_H4::
	msgbox DewfordTown_Gym_Text_H4, MSGBOX_NPC
	end

DewfordTown_Gym_EventScript_H5::
	msgbox DewfordTown_Gym_Text_H5, MSGBOX_NPC
	end

DewfordTown_Gym_EventScript_H6::
	msgbox DewfordTown_Gym_Text_H6, MSGBOX_NPC
	end

DewfordTown_Gym_EventScript_H7::
	msgbox DewfordTown_Gym_Text_H7, MSGBOX_NPC
	end

