DewfordTown_Gym_Text_H0_0::
	.string "I'm BRAWLY!\n"
	.string "DEWFORD's GYM LEADER!\p"
	.string "I've been churned in the rough waves\n"
	.string "of these parts, and I've grown tough\l"
	.string "in the pitch-black cave!\p"
	.string "So you wanted to challenge me?\n"
	.string "Let me see what you're made of!$"

DewfordTown_Gym_Text_H0_1::
	.string "Whoah, wow! You made a much bigger\n"
	.string "splash than I expected!\p"
	.string "You swamped me!\p"
	.string "Okay, you've got me.\n"
	.string "Take this GYM BADGE!$"

DewfordTown_Gym_Text_H0_2::
	.string "I can see your talent becoming a\n"
	.string "giant wave to cause a storm of\l"
	.string "astonishment among TRAINERS one\l"
	.string "day!$"

DewfordTown_Gym_Text_H1_0::
	.string "Might is right!\n"
	.string "Come on!$"

DewfordTown_Gym_Text_H1_1::
	.string "Not enough power…$"

DewfordTown_Gym_Text_H1_2::
	.string "Your skill overcame my strength!\n"
	.string "Your technique is commendable!$"

DewfordTown_Gym_Text_H2_0::
	.string "There's no need for BRAWLY to be\n"
	.string "involved!\p"
	.string "I'll crush you!$"

DewfordTown_Gym_Text_H2_1::
	.string "But… How?\n"
	.string "How could I lose so easily?$"

DewfordTown_Gym_Text_H2_2::
	.string "I'm not going to waste this loss.\n"
	.string "I'll use it to motivate me to train!\p"
	.string "One day I'll become a GYM LEADER…\p"
	.string "No, I'll become the POKéMON LEAGUE\n"
	.string "CHAMPION!$"

DewfordTown_Gym_Text_H3_0::
	.string "Don't you dare brush me off!\n"
	.string "It's not my fault if you cry!$"

DewfordTown_Gym_Text_H3_1::
	.string "Waaaaaaah!\n"
	.string "I lost!$"

DewfordTown_Gym_Text_H3_2::
	.string "I battle in the dark to make my\n"
	.string "heart stronger.\p"
	.string "But because it's so dark, I can\n"
	.string "never see BRAWLY's face…$"

DewfordTown_Gym_Text_H4::
	.string "Hey, how's it going, CHAMPION-\n"
	.string "bound {PLAYER}?\p"
	.string "DEWFORD's GYM LEADER BRAWLY\n"
	.string "commands FIGHTING-type POKéMON.\p"
	.string "Going against him with NORMAL-type\n"
	.string "POKéMON is asking for trouble.\p"
	.string "FIGHTING POKéMON will lay a serious\n"
	.string "smack down on NORMAL POKéMON,\l"
	.string "so be careful!\p"
	.string "What's worse, the GYM is as dark as\n"
	.string "the ocean floor.\p"
	.string "But it will get brighter after\n"
	.string "defeating the TRAINERS in your way.\p"
	.string "Hey, okay, go for it!$"

DewfordTown_Gym_Text_H5_0::
	.string "If you mean to pass, it has to be\n"
	.string "through me!$"

DewfordTown_Gym_Text_H5_1::
	.string "Grrrrr!\n"
	.string "Vastly overpowered!$"

DewfordTown_Gym_Text_H5_2::
	.string "You win!\n"
	.string "Go after that BADGE!$"

DewfordTown_Gym_Text_H6_0::
	.string "Ufufu… Are you stumbling around in\n"
	.string "the dark?$"

DewfordTown_Gym_Text_H6_1::
	.string "Oh, you…\n"
	.string "I don't want to know you!$"

DewfordTown_Gym_Text_H6_2::
	.string "You deserve to stay lost and end up\n"
	.string "back at the entrance again!$"

DewfordTown_Gym_Text_H7_0::
	.string "I'll show you the gumption of\n"
	.string "a sailing man!$"

DewfordTown_Gym_Text_H7_1::
	.string "How'd this happen?\n"
	.string "It's not like me to lose this way!$"

DewfordTown_Gym_Text_H7_2::
	.string "Oh, aye! You're worthy of seeing\n"
	.string "our GYM LEADER.$"

