SSTidalRooms_MapScripts::
	.byte 0

SSTidalRooms_EventScript_H0::
	msgbox SSTidalRooms_Text_H0, MSGBOX_NPC
	end

SSTidalRooms_EventScript_H1::
	msgbox SSTidalRooms_Text_H1, MSGBOX_NPC
	end

SSTidalRooms_EventScript_H2::
	msgbox SSTidalRooms_Text_H2, MSGBOX_NPC
	end

SSTidalRooms_EventScript_H3::
	msgbox SSTidalRooms_Text_H3, MSGBOX_NPC
	end

SSTidalRooms_EventScript_H4::
	msgbox SSTidalRooms_Text_H4, MSGBOX_NPC
	end

SSTidalRooms_EventScript_H5::
	msgbox SSTidalRooms_Text_H5, MSGBOX_NPC
	end

SSTidalRooms_EventScript_H6::
	msgbox SSTidalRooms_Text_H6, MSGBOX_NPC
	end

SSTidalRooms_EventScript_H7::
	msgbox SSTidalRooms_Text_H7, MSGBOX_SIGN
	end

SSTidalRooms_EventScript_H8::
	msgbox SSTidalRooms_Text_H8, MSGBOX_SIGN
	end

