SSTidalRooms_MapScripts::
	.byte 0

SSTidalRooms_EventScript_H0::
	trainerbattle_single TRAINER_HOENN_COLTON, SSTidalRooms_Text_H0_0, SSTidalRooms_Text_H0_1
	msgbox SSTidalRooms_Text_H0_2, MSGBOX_AUTOCLOSE
	end

SSTidalRooms_EventScript_H1::
	trainerbattle_single TRAINER_HOENN_MICAH, SSTidalRooms_Text_H1_0, SSTidalRooms_Text_H1_1
	msgbox SSTidalRooms_Text_H1_2, MSGBOX_AUTOCLOSE
	end

SSTidalRooms_EventScript_H2::
	trainerbattle_single TRAINER_HOENN_THOMAS, SSTidalRooms_Text_H2_0, SSTidalRooms_Text_H2_1
	msgbox SSTidalRooms_Text_H2_2, MSGBOX_AUTOCLOSE
	end

SSTidalRooms_EventScript_H3::
	trainerbattle_double TRAINER_HOENN_LEA_AND_JED, SSTidalRooms_Text_H3_0, SSTidalRooms_Text_H3_1, SSTidalRooms_Text_H3_1
	msgbox SSTidalRooms_Text_H3_2, MSGBOX_AUTOCLOSE
	end

SSTidalRooms_EventScript_H4::
	trainerbattle_double TRAINER_HOENN_LEA_AND_JED, SSTidalRooms_Text_H4_0, SSTidalRooms_Text_H4_1, SSTidalRooms_Text_H4_1
	msgbox SSTidalRooms_Text_H4_2, MSGBOX_AUTOCLOSE
	end

SSTidalRooms_EventScript_H5::
	trainerbattle_single TRAINER_HOENN_GARRET, SSTidalRooms_Text_H5_0, SSTidalRooms_Text_H5_1
	msgbox SSTidalRooms_Text_H5_2, MSGBOX_AUTOCLOSE
	end

SSTidalRooms_EventScript_H6::
	trainerbattle_single TRAINER_HOENN_NAOMI, SSTidalRooms_Text_H6_0, SSTidalRooms_Text_H6_1
	msgbox SSTidalRooms_Text_H6_2, MSGBOX_AUTOCLOSE
	end

SSTidalRooms_EventScript_H7::
	msgbox SSTidalRooms_Text_H7, MSGBOX_SIGN
	end

SSTidalRooms_EventScript_H8::
	msgbox SSTidalRooms_Text_H8, MSGBOX_SIGN
	end

