SSTidalRooms_Text_H0_0::
	.string "I often sail to LILYCOVE CITY.\p"
	.string "I enjoy attending CONTESTS,\n"
	.string "you see.$"

SSTidalRooms_Text_H0_1::
	.string "That was an enjoyable match!$"

SSTidalRooms_Text_H0_2::
	.string "I get so excited imagining what kinds\n"
	.string "of POKéMON I'll get to see in the next\l"
	.string "CONTEST. The anticipation of it thrills!$"

SSTidalRooms_Text_H1_0::
	.string "Are your friends strong?$"

SSTidalRooms_Text_H1_1::
	.string "Your friends are, indeed, strong.$"

SSTidalRooms_Text_H1_2::
	.string "Friends need not be human.\n"
	.string "For me, POKéMON are treasured friends!$"

SSTidalRooms_Text_H2_0::
	.string "Child…\n"
	.string "Did you knock on the door?$"

SSTidalRooms_Text_H2_1::
	.string "A loss is to be accepted without haste\n"
	.string "or panic.$"

SSTidalRooms_Text_H2_2::
	.string "To be never ruffled in any situation is\n"
	.string "the GENTLEMAN's code of conduct.$"

SSTidalRooms_Text_H3_0::
	.string "JED: I feel a little shy about this, but…\n"
	.string "We'll show you our lovey-dovey power!$"

SSTidalRooms_Text_H3_1::
	.string "JED: Sigh…$"

SSTidalRooms_Text_H3_2::
	.string "JED: It's the first time that our lovey-\n"
	.string "dovey power couldn't prevail!\l"
	.string "You must be an awesome TRAINER!$"

SSTidalRooms_Text_H4_0::
	.string "LEA: I feel a little silly, but…\n"
	.string "We'll show you our lovey-dovey power!$"

SSTidalRooms_Text_H4_1::
	.string "LEA: Oh, boo!$"

SSTidalRooms_Text_H4_2::
	.string "LEA: I can't believe it!\n"
	.string "Our lovey-dovey power failed…\l"
	.string "You must be an awesome TRAINER!$"

SSTidalRooms_Text_H5_0::
	.string "Ah, you've come just in time.\p"
	.string "I'm bored, you see.\n"
	.string "You may entertain me.$"

SSTidalRooms_Text_H5_1::
	.string "…That will do.$"

SSTidalRooms_Text_H5_2::
	.string "Perhaps I shall get Father to acquire\n"
	.string "a yacht for me.\l"
	.string "A yacht for me and POKéMON!$"

SSTidalRooms_Text_H6_0::
	.string "Oh, you're such an adorable TRAINER.\n"
	.string "Would you like to have tea?\l"
	.string "Or would you rather battle?$"

SSTidalRooms_Text_H6_1::
	.string "I see.\n"
	.string "You're the active sort.$"

SSTidalRooms_Text_H6_2::
	.string "A world cruise on a luxury liner has its\n"
	.string "charms, I must say…\p"
	.string "But, I will admit there is an appealing\n"
	.string "side to touring HOENN by ferry.$"

SSTidalRooms_Text_H7::
	.string "There's a bed…\n"
	.string "Let's take a rest.$"

SSTidalRooms_Text_H8::
	.string "There's a bed…\n"
	.string "Let's take a rest.$"

